// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::weapon::weapons::prelude::*;

pub struct ATeaspoonOfTranscendenceEffect {
    pub stack: f64,
}

impl<A: Attribute> WeaponEffect<A> for ATeaspoonOfTranscendenceEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        attribute.add_atk_percentage("超越之匙被动", 0.21 + 0.07 * refine);

        if self.stack > 0.0 {
            attribute.set_value_by_t(AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarConduct,
            )), "超越之匙被动", (0.12 + 0.04 * refine) * self.stack);
        }
    }
}

pub struct ATeaspoonOfTranscendence;

impl WeaponTrait for ATeaspoonOfTranscendence {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::ATeaspoonOfTranscendence,
        internal_name: "Claymore_CrystallineSword",
        weapon_type: WeaponType::Claymore,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalDamage96),
        weapon_base: WeaponBaseATKFamily::ATK674,
        star: 5,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "攻击力提升 <span style=\"color: #409EFF;\">28%-35%-42%-49%-56%</span> 。此外，装备者的重击每次命中敌人后，都会短暂达成「超越」：使装备者的星超导反应伤害提升 <span style=\"color: #409EFF;\">16%-20%-24%-28%-32%</span> ，持续5秒。该效果至多叠加3层，每0.2秒至多叠加一层。",
            en: "ATK is increased by <span style=\"color: #409EFF;\">28%-35%-42%-49%-56%</span>. Additionally, each time the equipping character hits an opponent with their Charged Attack, they attain \"Transcendence\" for a short time: their Stellar-Conduct DMG is increased by <span style=\"color: #409EFF;\">16%-20%-24%-28%-32%</span> for 5s. This effect can stack once every 0.2s, max 3 stacks."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "超越之匙",
            en: "A Teaspoon of Transcendence"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "stack",
            title: locale!(zh_cn: "「超越」等效层数", en: "Avg Transcendence Stacks"),
            config: ItemConfigType::Float { min: 0.0, max: 3.0, default: 3.0 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let stack = match *config {
            WeaponConfig::ATeaspoonOfTranscendence { stack } => stack,
            _ => 0.0,
        };

        Some(Box::new(ATeaspoonOfTranscendenceEffect {
            stack,
        }))
    }
}
