// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::weapon::weapons::prelude::*;

pub struct BladeOfAtonementEffect {
    pub element_reaction: bool,
    pub stellar_reaction: bool,
}

impl<A: Attribute> WeaponEffect<A> for BladeOfAtonementEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 触发元素反应的12秒内，装备者的元素精通提升。
        // 战斗过程中元素反应持续触发，该效果近乎常驻，故以布尔配置项表示是否触发。
        if self.element_reaction {
            attribute.set_value_to(AttributeName::ElementalMastery, "救赎之斩被动", 48.0 + 16.0 * refine);
        }

        // 触发星烁反应的12秒内，装备者的攻击力提升。
        if self.stellar_reaction {
            attribute.add_atk_percentage("救赎之斩被动", 0.12 + 0.04 * refine);
        }
    }
}

pub struct BladeOfAtonement;

impl WeaponTrait for BladeOfAtonement {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::BladeOfAtonement,
        internal_name: "Claymore_GlintstoneClaymore",
        weapon_type: WeaponType::Claymore,
        weapon_sub_stat: Some(WeaponSubStatFamily::ATK60),
        weapon_base: WeaponBaseATKFamily::ATK565,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "触发元素反应的12秒内，装备者的元素精通提升 <span style=\"color: #409EFF;\">64-80-96-112-128</span> 点；触发星烁反应的12秒内，装备者的攻击力提升 <span style=\"color: #409EFF;\">16%-20%-24%-28%-32%</span> 。装备者处于队伍后台时，依然能触发上述效果。",
            en: "Triggering an Elemental Reaction increases the equipping character's Elemental Mastery by <span style=\"color: #409EFF;\">64-80-96-112-128</span> for 12s, while triggering a Stellar Glimmer reaction increases their ATK by <span style=\"color: #409EFF;\">16%-20%-24%-28%-32%</span> for 12s. The aforementioned effects can trigger even when the character is not on the field."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "救赎之斩",
            en: "Blade of Atonement"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "element_reaction",
            title: locale!(zh_cn: "触发元素反应", en: "Trigger Elemental Reaction"),
            config: ItemConfigType::Bool { default: true },
        },
        ItemConfig {
            name: "stellar_reaction",
            title: locale!(zh_cn: "触发星烁反应", en: "Trigger Stellar Glimmer Reaction"),
            config: ItemConfigType::Bool { default: true },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (element_reaction, stellar_reaction) = match *config {
            WeaponConfig::BladeOfAtonement { element_reaction, stellar_reaction } => (element_reaction, stellar_reaction),
            _ => (false, false),
        };

        Some(Box::new(BladeOfAtonementEffect {
            element_reaction,
            stellar_reaction,
        }))
    }
}
