// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::weapon::weapons::prelude::*;

pub struct ForgedByTheGoldenMelodyEffect {
    pub rate1: f64,
    pub rate2: f64,
    pub rate3: f64,
}

impl<A: Attribute> WeaponEffect<A> for ForgedByTheGoldenMelodyEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 「谐律乐章」按顺序循环奏响三种效果：攻击力 / 元素精通 / 星烁反应伤害，
        // 每种持续10秒。触发星烁反应后还会额外获得持续12秒的「谐律乐章·复调」（与触发时
        // 演奏的乐章效果相同，可与原本乐章叠加）。此处以三个「应用比例」配置项分别近似
        // 三种乐章的平均覆盖率（含「复调」叠加部分）。
        if self.rate1 > 0.0 {
            attribute.add_atk_percentage("金律铸影被动", (0.135 + 0.045 * refine) * self.rate1);
        }
        if self.rate2 > 0.0 {
            attribute.set_value_to(AttributeName::ElementalMastery, "金律铸影被动", (90.0 + 30.0 * refine) * self.rate2);
        }
        if self.rate3 > 0.0 {
            attribute.set_value_to_t(AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarConduct,
            )), "金律铸影被动", (0.21 + 0.07 * refine) * self.rate3);
            attribute.set_value_to_t(AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarSwirl,
            )), "金律铸影被动", (0.21 + 0.07 * refine) * self.rate3);
        }
    }
}

pub struct ForgedByTheGoldenMelody;

impl WeaponTrait for ForgedByTheGoldenMelody {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::ForgedByTheGoldenMelody,
        internal_name: "Claymore_EscapeWheel",
        weapon_type: WeaponType::Claymore,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalRate60),
        weapon_base: WeaponBaseATKFamily::ATK510,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "每10秒，装备者按照以下顺序，分别奏响对应效果的「谐律乐章」：攻击力提升 <span style=\"color: #409EFF;\">18%-22.5%-27%-31.5%-36%</span> /元素精通提升 <span style=\"color: #409EFF;\">120-150-180-210-240</span> 点/星烁反应伤害提升 <span style=\"color: #409EFF;\">28%-35%-42%-49%-56%</span> ，每种乐章效果持续10秒，装备者处于队伍后台时，依然能触发上述效果。触发星烁反应后，还会额外获得持续12秒的、与触发星烁反应时演奏乐章效果相同的「谐律乐章·复调」，该效果可以与原本的乐章效果叠加，每12秒至多触发一次。",
            en: "Every 10s, the equipping character plays a \"Harmonic Movement\" of the corresponding type for a boost in the following order: +<span style=\"color: #409EFF;\">18%-22.5%-27%-31.5%-36%</span> ATK > +<span style=\"color: #409EFF;\">120-150-180-210-240</span> Elemental Mastery > +<span style=\"color: #409EFF;\">28%-35%-42%-49%-56%</span> Stellar Glimmer reaction DMG. Each instance of Harmonic Movement lasts 10s. This effect can trigger even when the equipping character is not on the field. Triggering a Stellar Glimmer reaction will also grant an additional 12-second instance of \"Harmonic Movement: Contrapuntal\" with the same effects as the Harmonic Movement active when Stellar Glimmer is triggered. This effect stacks with the original Harmonic Movement effect, and can trigger once every 12s."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "金律铸影",
            en: "Forged by the Golden Melody"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "rate1",
            title: locale!(zh_cn: "攻击力乐章应用比例", en: "ATK Movement Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 0.0 },
        },
        ItemConfig {
            name: "rate2",
            title: locale!(zh_cn: "元素精通乐章应用比例", en: "Elemental Mastery Movement Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 0.0 },
        },
        ItemConfig {
            name: "rate3",
            title: locale!(zh_cn: "星烁反应乐章应用比例", en: "Stellar Glimmer Movement Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 0.0 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (rate1, rate2, rate3) = match *config {
            WeaponConfig::ForgedByTheGoldenMelody { rate1, rate2, rate3 } => (rate1, rate2, rate3),
            _ => (0.0, 0.0, 0.0),
        };

        Some(Box::new(ForgedByTheGoldenMelodyEffect {
            rate1,
            rate2,
            rate3,
        }))
    }
}
