// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::target_functions::target_functions::prelude::*;
use crate::character::characters::Vesna;

pub struct VesnaDefaultTargetFunction;

impl TargetFunctionMetaTrait for VesnaDefaultTargetFunction {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: TargetFunctionMeta = TargetFunctionMeta {
        name: TargetFunctionName::VesnaDefault,
        name_locale: locale!(
            zh_cn: "薇斯纳-「雪宴之锋」",
            en: "Vesna-Snowy Banquet's Sharp Blade"
        ),
        description: locale!(
            zh_cn: "薇斯纳一轮输出总伤害（元素战技×1、翔风剑一阶×1、翔风剑二阶及灵剑×1、翔风剑三阶及灵剑×3、风翎×10、元素爆发×1）",
            en: "Vesna Total Damage Output per Round (Skill ×1, Windborne Sword Lv. 1 ×1, Windborne Sword Lv. 2 + Spirit Blade ×1, Windborne Sword Lv. 3 + Spirit Blade ×3, Wind Pinion ×10, Burst ×1)"
        ),
        tags: "输出",
        four: TargetFunctionFor::SomeWho(CharacterName::Vesna),
        image: TargetFunctionMetaImage::Avatar
    };

    fn create(_character: &CharacterCommonData, _weapon: &WeaponCommonData, _config: &TargetFunctionConfig) -> Box<dyn TargetFunction> {
        Box::new(VesnaDefaultTargetFunction)
    }
}

impl TargetFunction for VesnaDefaultTargetFunction {
    fn get_target_function_opt_config(&self) -> TargetFunctionOptConfig {
        TargetFunctionOptConfig {
            atk_fixed: 0.2,
            atk_percentage: 0.6,
            hp_fixed: 0.0,
            hp_percentage: 0.0,
            def_fixed: 0.0,
            def_percentage: 0.0,
            recharge: 0.0,
            elemental_mastery: 0.2,
            critical: 1.0,
            critical_damage: 1.0,
            healing_bonus: 0.0,
            bonus_electro: 0.0,
            bonus_pyro: 0.0,
            bonus_hydro: 0.0,
            bonus_anemo: 0.0,
            bonus_cryo: 0.0,
            bonus_geo: 0.0,
            bonus_dendro: 0.0,
            bonus_physical: 0.0,
            sand_main_stats: vec![
                StatName::ATKPercentage,
            ],
            goblet_main_stats: vec![
                StatName::AnemoBonus,
                StatName::ATKPercentage,
            ],
            head_main_stats: vec![
                StatName::CriticalRate,
                StatName::CriticalDamage,
                StatName::ATKPercentage,
            ],
            set_names: Some(vec![
                ArtifactSetName::MarechausseeHunter,
                ArtifactSetName::GildedDreams,
            ]),
            very_critical_set_names: Some(vec![
                ArtifactSetName::ScarletProof,
                ArtifactSetName::ViridescentVenerer,
            ]),
            normal_threshold: TargetFunctionOptConfig::DEFAULT_NORMAL_THRESHOLD,
            critical_threshold: TargetFunctionOptConfig::DEFAULT_CRITICAL_THRESHOLD,
            very_critical_threshold: TargetFunctionOptConfig::DEFAULT_VERY_CRITICAL_THRESHOLD,
        }
    }

    fn get_default_artifact_config(&self, _team_config: &TeamQuantization) -> ArtifactEffectConfig {
        Default::default()
    }

    fn target(&self, attribute: &TargetFunctionAttributeType, character: &Character<TargetFunctionAttributeType>, _weapon: &Weapon<TargetFunctionAttributeType>, _artifacts: &[&Artifact], enemy: &Enemy) -> f64 {
        type Ty = <Vesna as CharacterTrait>::DamageEnumType;

        // 元素战技「操典·制胜有道」：施放时尚未进入「巡风列装」模式，且会清除已有「整肃」
        let config_e = CharacterSkillConfig::Vesna { in_armed_for_action: false, disciplinary_stacks: 0 };
        // 翔风剑一阶：处于「巡风列装」模式，此时「整肃」0 层
        // （风翎伤害不受「整肃」影响，故复用该配置）
        let config_sword1 = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: 0 };
        // 翔风剑二阶：施放本段前已因首次翔风剑获得 1 层「整肃」
        let config_sword2 = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: 1 };
        // 翔风剑三阶（第 1/2/3 次）：施放前分别已有 2/3/4 层「整肃」
        let config_sword3_1 = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: 2 };
        let config_sword3_2 = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: 3 };
        let config_sword3_3 = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: 4 };
        // 元素爆发「致礼·献予女皇陛下」：施放三次最高境界翔风剑后已退出「巡风列装」模式，
        // 此时已累积 5 层「整肃」
        let config_q = CharacterSkillConfig::Vesna { in_armed_for_action: false, disciplinary_stacks: 5 };

        let mut attribute_e = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_e, &character.common_data, &config_e);
        let solved_e = attribute_e.solve();
        let context_e = DamageContext { character_common_data: &character.common_data, attribute: &solved_e, enemy };

        let mut attribute_sword1 = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_sword1, &character.common_data, &config_sword1);
        let solved_sword1 = attribute_sword1.solve();
        let context_sword1 = DamageContext { character_common_data: &character.common_data, attribute: &solved_sword1, enemy };

        let mut attribute_sword2 = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_sword2, &character.common_data, &config_sword2);
        let solved_sword2 = attribute_sword2.solve();
        let context_sword2 = DamageContext { character_common_data: &character.common_data, attribute: &solved_sword2, enemy };

        let mut attribute_sword3_1 = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_sword3_1, &character.common_data, &config_sword3_1);
        let solved_sword3_1 = attribute_sword3_1.solve();
        let context_sword3_1 = DamageContext { character_common_data: &character.common_data, attribute: &solved_sword3_1, enemy };

        let mut attribute_sword3_2 = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_sword3_2, &character.common_data, &config_sword3_2);
        let solved_sword3_2 = attribute_sword3_2.solve();
        let context_sword3_2 = DamageContext { character_common_data: &character.common_data, attribute: &solved_sword3_2, enemy };

        let mut attribute_sword3_3 = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_sword3_3, &character.common_data, &config_sword3_3);
        let solved_sword3_3 = attribute_sword3_3.solve();
        let context_sword3_3 = DamageContext { character_common_data: &character.common_data, attribute: &solved_sword3_3, enemy };

        let mut attribute_q = (*attribute).clone();
        Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_q, &character.common_data, &config_q);
        let solved_q = attribute_q.solve();
        let context_q = DamageContext { character_common_data: &character.common_data, attribute: &solved_q, enemy };

        // 单个技能的期望伤害
        let dmg = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, skill: Ty, config: &CharacterSkillConfig| -> f64 {
            Vesna::damage::<SimpleDamageBuilder>(context, skill, config, None).normal.expectation
        };

        // 三阶翔风剑的灵剑：4 次灵剑伤害 + 最终段伤害
        let sword3_dmg = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            dmg(context, Ty::E_SPIRIT3_TOTAL, config) + dmg(context, Ty::E_SPIRIT3_FINAL, config)
        };

        // 一轮输出：
        // 普通元素战技×1 + 翔风剑一阶×1 + (翔风剑二阶 + 二阶灵剑)×1 + (翔风剑三阶 + 三阶灵剑)×3
        // + 风翎×10 + 元素爆发×1
        dmg(&context_e, Ty::E, &config_e)
            + dmg(&context_sword1, Ty::E_SWORD1, &config_sword1)
            + dmg(&context_sword2, Ty::E_SWORD2, &config_sword2)
            + dmg(&context_sword2, Ty::E_SPIRIT2, &config_sword2)
            + sword3_dmg(&context_sword3_1, &config_sword3_1)
            + sword3_dmg(&context_sword3_2, &config_sword3_2)
            + sword3_dmg(&context_sword3_3, &config_sword3_3)
            + dmg(&context_sword1, Ty::E_PLUME, &config_sword1) * 10.0
            + dmg(&context_q, Ty::Q_SPIRIT, &config_q)
    }
}
