// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::target_functions::target_functions::prelude::*;
use crate::character::characters::vesna::VESNA_SKILL;
use crate::character::characters::Vesna;

pub struct VesnaDefaultTargetFunction;

impl TargetFunctionMetaTrait for VesnaDefaultTargetFunction {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: TargetFunctionMeta = TargetFunctionMeta {
        name: TargetFunctionName::VesnaDefault,
        name_locale: locale!(
            zh_cn: "薇斯纳-「雪宴之锋」",
            en: "Vesna-Snowy Banquet's Sharp Blade"
        ),
        description: locale!(
            zh_cn: "薇斯纳一轮输出总伤害（元素战技×1、翔风剑一阶×1、风翎×10、翔风剑二阶及灵剑×1、元素爆发×1、翔风剑三阶及灵剑×3）",
            en: "Vesna Total Damage Output per Round (Skill ×1, Windborne Sword Lv. 1 ×1, Wind Pinion ×10, Windborne Sword Lv. 2 + Spirit Blade ×1, Burst ×1, Windborne Sword Lv. 3 + Spirit Blade ×3)"
        ),
        tags: "输出",
        four: TargetFunctionFor::SomeWho(CharacterName::Vesna),
        image: TargetFunctionMetaImage::Avatar
    };

    fn create(_character: &CharacterCommonData, _weapon: &WeaponCommonData, _config: &TargetFunctionConfig) -> Box<dyn TargetFunction> {
        Box::new(VesnaDefaultTargetFunction)
    }
}

impl TargetFunction for VesnaDefaultTargetFunction {
    fn get_target_function_opt_config(&self) -> TargetFunctionOptConfig {
        TargetFunctionOptConfig {
            atk_fixed: 0.2,
            atk_percentage: 0.6,
            hp_fixed: 0.0,
            hp_percentage: 0.0,
            def_fixed: 0.0,
            def_percentage: 0.0,
            recharge: 0.0,
            elemental_mastery: 0.2,
            critical: 1.0,
            critical_damage: 1.0,
            healing_bonus: 0.0,
            bonus_electro: 0.0,
            bonus_pyro: 0.0,
            bonus_hydro: 0.0,
            bonus_anemo: 0.0,
            bonus_cryo: 0.0,
            bonus_geo: 0.0,
            bonus_dendro: 0.0,
            bonus_physical: 0.0,
            sand_main_stats: vec![
                StatName::ATKPercentage,
            ],
            goblet_main_stats: vec![
                StatName::ATKPercentage,
            ],
            head_main_stats: vec![
                StatName::CriticalRate,
                StatName::CriticalDamage,
                StatName::ATKPercentage,
            ],
            set_names: Some(vec![
                ArtifactSetName::MarechausseeHunter,
                ArtifactSetName::GildedDreams,
            ]),
            very_critical_set_names: Some(vec![
                ArtifactSetName::ScarletProof,
                ArtifactSetName::ViridescentVenerer,
            ]),
            normal_threshold: TargetFunctionOptConfig::DEFAULT_NORMAL_THRESHOLD,
            critical_threshold: TargetFunctionOptConfig::DEFAULT_CRITICAL_THRESHOLD,
            very_critical_threshold: TargetFunctionOptConfig::DEFAULT_VERY_CRITICAL_THRESHOLD,
        }
    }

    fn get_default_artifact_config(&self, _team_config: &TeamQuantization) -> ArtifactEffectConfig {
        Default::default()
    }

    fn target(&self, attribute: &TargetFunctionAttributeType, character: &Character<TargetFunctionAttributeType>, _weapon: &Weapon<TargetFunctionAttributeType>, _artifacts: &[&Artifact], enemy: &Enemy) -> f64 {
        type Ty = <Vesna as CharacterTrait>::DamageEnumType;

        let constellation = character.common_data.constellation;
        // 命座2·迎春的轮舞：进入「巡风列装」模式时直接获得最大层数的「整肃」（需要解锁天赋1）
        let full_stacks_on_enter = constellation >= 2 && character.common_data.has_talent1;
        let max_stacks = VESNA_SKILL.p1_max_stacks as usize;
        // 命座1·送冬的华宴：最高境界的翔风剑至多可施放四次（而非三次）
        let sword3_count = if constellation >= 1 { 4 } else { 3 };
        // 命座6·不移的赤忱：每次施放最高境界翔风剑后的 5 秒内，可以点按普通攻击或元素战技
        // 施放「翔风剑·变移」（150% 攻击力 + 灵剑 200% 攻击力）
        let has_c6 = constellation >= 6;

        // 施放某段技能前已有的「整肃」层数（= 此前施放翔风剑/元素爆发的次数，至多 6 层）
        let stacks_before = |before_cast_count: usize| -> usize {
            if full_stacks_on_enter {
                max_stacks
            } else {
                before_cast_count.min(max_stacks)
            }
        };
        // 翔风剑触发的灵剑在翔风剑获得层数后结算，因此使用触发后的层数。
        let stacks_after = |before_cast_count: usize| -> usize {
            stacks_before(before_cast_count + 1)
        };

        // 元素战技「操典·制胜有道」：施放时尚未进入「巡风列装」模式，且会清除已有「整肃」
        let config_e = CharacterSkillConfig::Vesna { in_armed_for_action: false, disciplinary_stacks: 0 };
        // 元素爆发「致礼·献予女皇陛下」：在「巡风列装」模式下、二阶翔风剑后、三阶翔风剑前施放；
        // 爆发灵剑使用施放爆发前已有的层数，爆发后获得的层数用于后续三阶翔风剑。
        let config_q = CharacterSkillConfig::Vesna {
            in_armed_for_action: true,
            disciplinary_stacks: stacks_before(2),
        };

        // 「巡风列装」模式内各技能所需的「整肃」层数：翔风剑一阶 0 层、二阶 1 层，
        // 二阶灵剑使用触发后的层数；元素爆发后，三阶第 i 次使用 i + 3 层，
        // 三阶灵剑以及命座6额外灵剑使用触发后的层数。
        // 风翎伤害不受「整肃」影响，复用一阶的层数。
        let mut stacks_list: Vec<usize> = vec![stacks_before(0), stacks_before(1), stacks_after(1)];
        for i in 0..sword3_count {
            stacks_list.push(stacks_before(3 + i));
            stacks_list.push(stacks_after(3 + i));
        }

        // 每种「整肃」层数都需要独立的 DamageContext
        let mut unique_stacks: Vec<usize> = Vec::new();
        for s in stacks_list.iter() {
            if !unique_stacks.contains(s) {
                unique_stacks.push(*s);
            }
        }
        let mut in_mode_configs: Vec<CharacterSkillConfig> = Vec::new();
        let mut in_mode_solved: Vec<TargetFunctionAttributeResultType> = Vec::new();
        for s in unique_stacks.iter() {
            let config = CharacterSkillConfig::Vesna { in_armed_for_action: true, disciplinary_stacks: *s };
            let mut attribute_temp = (*attribute).clone();
            Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config);
            in_mode_solved.push(attribute_temp.solve());
            in_mode_configs.push(config);
        }
        let index_of = |stacks: usize| -> usize { unique_stacks.iter().position(|x| *x == stacks).unwrap() };
        // 「巡风列装」模式内单个技能的期望伤害（按「整肃」层数选取对应上下文）
        let in_mode_dmg = |stacks: usize, skill: Ty| -> f64 {
            let i = index_of(stacks);
            let context = DamageContext {
                character_common_data: &character.common_data,
                attribute: &in_mode_solved[i],
                enemy,
            };
            Vesna::damage::<SimpleDamageBuilder>(&context, skill, &in_mode_configs[i], None).normal.expectation
        };

        let solved_e = {
            let mut attribute_temp = (*attribute).clone();
            Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config_e);
            attribute_temp.solve()
        };
        let context_e = DamageContext { character_common_data: &character.common_data, attribute: &solved_e, enemy };

        let solved_q = {
            let mut attribute_temp = (*attribute).clone();
            Vesna::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config_q);
            attribute_temp.solve()
        };
        let context_q = DamageContext { character_common_data: &character.common_data, attribute: &solved_q, enemy };

        // 一轮输出：
        // 普通元素战技×1 + 翔风剑一阶×1 + 风翎×10
        // + (翔风剑二阶 + 二阶灵剑)×1 + 元素爆发×1
        // + (翔风剑三阶 + 三阶灵剑)×3（命座1 及以上为×4）
        // 命座6 额外计入每次最高境界翔风剑后的「翔风剑·变移」。该伤害及其额外灵剑
        // 均视为元素战技伤害；变移在「巡风列装」模式下额外唤出的风翎不额外计入风翎次数。
        let mut total = Vesna::damage::<SimpleDamageBuilder>(&context_e, Ty::E, &config_e, None).normal.expectation;

        total += in_mode_dmg(stacks_before(0), Ty::E_SWORD1);
        total += in_mode_dmg(stacks_before(0), Ty::E_PLUME) * 10.0;
        total += in_mode_dmg(stacks_before(1), Ty::E_SWORD2)
            + in_mode_dmg(stacks_after(1), Ty::E_SPIRIT2);
        total += Vesna::damage::<SimpleDamageBuilder>(&context_q, Ty::Q_SPIRIT, &config_q, None).normal.expectation;
        for i in 0..sword3_count {
            let sword_stacks = stacks_before(3 + i);
            let spirit_stacks = stacks_after(3 + i);
            total += in_mode_dmg(spirit_stacks, Ty::E_SPIRIT3_TOTAL)
                + in_mode_dmg(spirit_stacks, Ty::E_SPIRIT3_FINAL);
            if has_c6 {
                total += in_mode_dmg(sword_stacks, Ty::C6)
                    + in_mode_dmg(spirit_stacks, Ty::C6_SPIRIT);
            }
        }

        total
    }
}
