// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::character::characters::prelude::*;

pub struct AlyoshaSkillType {
    // Normal Attack: 角枪驰弋 (Skirmishing Spear)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg31: [f64; 15],
    pub a_dmg32: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 伏袭霆击 (Thunderbolt Strike)
    pub e_press_dmg: [f64; 15],          // 点按伤害
    pub e_hold_dmg: [f64; 15],           // 长按伤害
    pub e_hunters_precision_atk: [f64; 15], // 猎者之准攻击力提升（每层）

    // Elemental Burst: 守猎进踞 (Hunter's Advance)
    pub q_field_dmg: [f64; 15],          // 轰霆猎场伤害
    pub q_dog_dmg: [f64; 15],            // 图加林伤害

    // P1: 惊醒沉睡的林线
    pub p1_heal: f64,                    // 治疗量：攻击力的120%

    // C4: 衔取猎品
    pub c4_heal: f64,                    // 治疗量：攻击力的60%
}

pub const ALYOSHA_SKILL: AlyoshaSkillType = AlyoshaSkillType {
    // Normal Attack: 角枪驰弋
    a_dmg1: [0.4782, 0.5171, 0.556, 0.6116, 0.6505, 0.695, 0.7562, 0.8173, 0.8785, 0.9452, 1.0119, 1.0786, 1.1454, 1.2121, 1.2788],
    a_dmg2: [0.4816, 0.5208, 0.56, 0.616, 0.6552, 0.7, 0.7616, 0.8232, 0.8848, 0.952, 1.0192, 1.0864, 1.1536, 1.2208, 1.288],
    a_dmg31: [0.3423, 0.3701, 0.398, 0.4378, 0.4657, 0.4975, 0.5413, 0.5851, 0.6288, 0.6766, 0.7244, 0.7721, 0.8199, 0.8676, 0.9154],
    a_dmg32: [0.3182, 0.3441, 0.37, 0.407, 0.4329, 0.4625, 0.5032, 0.5439, 0.5846, 0.629, 0.6734, 0.7178, 0.7622, 0.8066, 0.851],
    a_dmg4: [0.7585, 0.8203, 0.882, 0.9702, 1.0319, 1.1025, 1.1995, 1.2965, 1.3936, 1.4994, 1.6052, 1.7111, 1.8169, 1.9228, 2.0286],
    z_dmg: [1.1103, 1.2006, 1.291, 1.4201, 1.5105, 1.6137, 1.7558, 1.8978, 2.0398, 2.1947, 2.3496, 2.5045, 2.6595, 2.8144, 2.9693],
    x_dmg1: [0.6393, 0.6914, 0.7434, 0.8177, 0.8698, 0.9293, 1.011, 1.0928, 1.1746, 1.2638, 1.353, 1.4422, 1.5314, 1.6206, 1.7098],
    x_dmg2: [1.2784, 1.3824, 1.4865, 1.6351, 1.7392, 1.8581, 2.0216, 2.1851, 2.3486, 2.527, 2.7054, 2.8838, 3.0622, 3.2405, 3.4189],
    x_dmg3: [1.5968, 1.7267, 1.8567, 2.0424, 2.1723, 2.3209, 2.5251, 2.7293, 2.9336, 3.1564, 3.3792, 3.602, 3.8248, 4.0476, 4.2704],

    // Elemental Skill: 伏袭霆击
    e_press_dmg: [2.8672, 3.0822, 3.2973, 3.584, 3.799, 4.0141, 4.3008, 4.5875, 4.8742, 5.161, 5.4477, 5.7344, 6.0928, 6.4512, 6.8096],
    e_hold_dmg: [3.584, 3.8528, 4.1216, 4.48, 4.7488, 5.0176, 5.376, 5.7344, 6.0928, 6.4512, 6.8096, 7.168, 7.616, 8.064, 8.512],
    e_hunters_precision_atk: [0.1166, 0.1272, 0.1378, 0.1484, 0.159, 0.1696, 0.1802, 0.1908, 0.2014, 0.212, 0.2247, 0.2374, 0.2502, 0.2629, 0.2756],

    // Elemental Burst: 守猎进踞
    q_field_dmg: [0.7496, 0.8058, 0.862, 0.937, 0.9932, 1.0494, 1.1244, 1.1994, 1.2743, 1.3493, 1.4242, 1.4992, 1.5929, 1.6866, 1.7803],
    q_dog_dmg: [0.5022, 0.5399, 0.5776, 0.6278, 0.6655, 0.7031, 0.7533, 0.8036, 0.8538, 0.904, 0.9542, 1.0045, 1.0672, 1.13, 1.1928],

    // P1: 惊醒沉睡的林线 — 图加林攻击时，为场上角色恢复攻击力120%的生命值
    p1_heal: 1.2,

    // C4: 衔取猎品 — 图加林攻击时，为生命值百分比最低的角色恢复攻击力60%的生命值
    c4_heal: 0.6,
};

pub const ALYOSHA_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Alyosha,
    internal_name: "Alyosha",
    element: Element::Electro,
    hp: [1003, 2577, 3408, 4982, 5597, 6343, 7135, 7881, 8496, 9241, 9856, 10602, 11217, 11962, 12790],
    atk: [22, 57, 76, 111, 124, 141, 158, 175, 189, 205, 219, 235, 249, 265, 333],
    def: [59, 151, 200, 293, 329, 373, 419, 463, 499, 543, 579, 623, 659, 703, 752],
    sub_stat: CharacterSubStatFamily::Recharge267,
    weapon_type: WeaponType::Polearm,
    star: 4,
    skill_name1: locale!(
        zh_cn: "角枪驰弋",
        en: "Skirmishing Spear",
    ),
    skill_name2: locale!(
        zh_cn: "伏袭霆击",
        en: "Thunderbolt Strike",
    ),
    skill_name3: locale!(
        zh_cn: "守猎进踞",
        en: "Hunter's Advance",
    ),
    name_locale: locale!(
        zh_cn: "阿罗夏",
        en: "Alyosha",
    )
};

pub struct AlyoshaEffect {
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for AlyoshaEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋2：告别冬麦与残叶 — 基于元素充能效率提升元素战技与元素爆发造成的伤害：
        // 每1%元素充能效率使上述伤害提升0.35%，至多提升至70%
        if self.common_data.has_talent2 {
            let bonus = Arc::new(move |recharge: f64, _| (recharge * 0.35).min(0.70));
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::Recharge),
                AttributeType::Invisible(InvisibleAttributeType::new_skill(AttributeVariableType::Bonus, SkillType::ElementalSkill)),
                bonus.clone(),
                "阿罗夏天赋2",
                EdgePriority::Invisible,
            );
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::Recharge),
                AttributeType::Invisible(InvisibleAttributeType::new_skill(AttributeVariableType::Bonus, SkillType::ElementalBurst)),
                bonus,
                "阿罗夏天赋2",
                EdgePriority::Invisible,
            );
        }
    }
}

damage_enum!(
    AlyoshaDamageEnum
    A1
    A2
    A31
    A32
    A4
    Z
    X1
    X2
    X3
    E
    Q_FIELD
    Q_DOG
    P1_HEAL
    C4_HEAL
);

impl AlyoshaDamageEnum {
    pub fn get_element(&self) -> Element {
        use AlyoshaDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | Z | X1 | X2 | X3 => Element::Physical,
            E | Q_FIELD | Q_DOG => Element::Electro,
            P1_HEAL | C4_HEAL => Element::Physical,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use AlyoshaDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E => SkillType::ElementalSkill,
            Q_FIELD | Q_DOG => SkillType::ElementalBurst,
            P1_HEAL | C4_HEAL => SkillType::NoneType,
        }
    }
}

pub struct Alyosha;

impl CharacterTrait for Alyosha {
    const STATIC_DATA: CharacterStaticData = ALYOSHA_STATIC_DATA;
    type SkillType = AlyoshaSkillType;
    const SKILL: Self::SkillType = ALYOSHA_SKILL;
    type DamageEnumType = AlyoshaDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            AlyoshaDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A31 hit_n_dmg!(3, 1)
            A32 hit_n_dmg!(3, 2)
            A4 hit_n_dmg!(4)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            AlyoshaDamageEnum
            E locale!(zh_cn: "元素战技伤害", en: "Elemental Skill DMG")
        ),
        skill3: skill_map!(
            AlyoshaDamageEnum
            Q_FIELD locale!(zh_cn: "轰霆猎场伤害", en: "Fulgurite Hunting Field DMG")
            Q_DOG locale!(zh_cn: "图加林伤害", en: "Tugarin DMG")
            P1_HEAL locale!(zh_cn: "天赋1治疗量", en: "Talent 1 Heal Amount")
            C4_HEAL locale!(zh_cn: "命座4治疗量", en: "C4 Heal Amount")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        // 天赋3：处于极星辉域中时进入辉映·星超导状态
        ItemConfig::STELLAR_GLIMMER_STATE(1, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "e_hold",
            title: locale!(
                zh_cn: "长按施放元素战技",
                en: "Hold to Cast Elemental Skill"
            ),
            config: ItemConfigType::Bool { default: false }
        },
        ItemConfig {
            name: "hunters_precision_stacks",
            title: locale!(
                zh_cn: "猎者之准层数（激活弋猎印记后，命座6可叠至2层）",
                en: "Hunter's Precision Stacks (after activating Hunter's Mark, up to 2 with C6)"
            ),
            config: ItemConfigType::Int { min: 0, max: 2, default: 1 }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let stellar_glimmer_state = match &common_data.config {
            CharacterConfig::Alyosha { stellar_glimmer_state, .. } => *stellar_glimmer_state,
            _ => 0,
        };

        let (e_hold, hunters_precision_stacks) = match *skill_config {
            CharacterSkillConfig::Alyosha { e_hold, hunters_precision_stacks } => (e_hold, hunters_precision_stacks),
            _ => (false, 0),
        };
        let _ = e_hold;

        // 非 6 命角色无法叠加「猎者之准」，将层数钳制到命座允许的上限
        let max_stacks = if common_data.constellation >= 6 { 2 } else { 1 };
        let hunters_precision_stacks = hunters_precision_stacks.min(max_stacks);

        // 猎者之准效果（激活弋猎印记后，队伍中附近的所有角色获得）：
        // 处于场上时，攻击力提升（基于元素战技等级，命座6可叠加至2层）
        if hunters_precision_stacks > 0 {
            let (_, s2, _) = common_data.get_3_skill();
            attribute.add_atk_percentage_s(
                CharacterSelector::select_all_onfield(attribute),
                "阿罗夏技能E",
                ALYOSHA_SKILL.e_hunters_precision_atk[s2] * hunters_precision_stacks as f64,
            );
        }

        // 天赋3：星赴险域 — 辉映·星超导状态下，猎者之准效果使角色处于场上时
        // 造成的星超导反应伤害提升20%
        if stellar_glimmer_state == 1 && hunters_precision_stacks > 0 {
            attribute.set_value_to_s(
                CharacterSelector::select_all_onfield(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "阿罗夏天赋3",
                0.20,
            );
        }

        // 命座6：复夺旌幡 — 猎者之准叠至2层时，场上角色的元素精通提升100点
        if common_data.constellation >= 6 && hunters_precision_stacks >= 2 {
            attribute.set_value_to_s(
                CharacterSelector::select_all_onfield(attribute),
                AttributeType::Panel(AttributeName::ElementalMastery),
                "阿罗夏命座6",
                100.0,
            );
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: AlyoshaDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (e_hold, _hunters_precision_stacks) = match *config {
            CharacterSkillConfig::Alyosha { e_hold, hunters_precision_stacks } => (e_hold, hunters_precision_stacks),
            _ => (false, 0),
        };

        use AlyoshaDamageEnum::*;
        let mut builder = D::new();

        // 治疗量（天赋1 / 命座4，均由图加林攻击触发）
        if s == P1_HEAL || s == C4_HEAL {
            if s == P1_HEAL {
                if !context.character_common_data.has_talent1 {
                    return builder.none();
                }
                builder.add_atk_ratio("额外治疗量", ALYOSHA_SKILL.p1_heal);
            } else {
                if context.character_common_data.constellation < 4 {
                    return builder.none();
                }
                builder.add_atk_ratio("额外治疗量", ALYOSHA_SKILL.c4_heal);
            }
            return builder.heal(&context.attribute);
        }

        // 元素战技点按/长按伤害共用同一伤害类型，根据技能配置返回不同倍率
        let ratio = match s {
            A1 => ALYOSHA_SKILL.a_dmg1[s1],
            A2 => ALYOSHA_SKILL.a_dmg2[s1],
            A31 => ALYOSHA_SKILL.a_dmg31[s1],
            A32 => ALYOSHA_SKILL.a_dmg32[s1],
            A4 => ALYOSHA_SKILL.a_dmg4[s1],
            Z => ALYOSHA_SKILL.z_dmg[s1],
            X1 => ALYOSHA_SKILL.x_dmg1[s1],
            X2 => ALYOSHA_SKILL.x_dmg2[s1],
            X3 => ALYOSHA_SKILL.x_dmg3[s1],
            E => if e_hold {
                ALYOSHA_SKILL.e_hold_dmg[s2]
            } else {
                ALYOSHA_SKILL.e_press_dmg[s2]
            },
            Q_FIELD => ALYOSHA_SKILL.q_field_dmg[s3],
            Q_DOG => ALYOSHA_SKILL.q_dog_dmg[s3],
            _ => 0.0,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        builder.damage(
            &context.attribute,
            &context.enemy,
            s.get_element(),
            s.get_skill_type(),
            context.character_common_data.level,
            fumo,
        )
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, _config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        Some(Box::new(AlyoshaEffect {
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
