// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct BeidouSkillType {
    // Normal Attack: 征涛 (Oceanborne)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub z_dmg1: [f64; 15],       // Charged Attack loop DMG
    pub z_dmg2: [f64; 15],       // Charged Attack final DMG
    pub x_dmg1: [f64; 15],       // Plunging Attack DMG
    pub x_dmg2: [f64; 15],       // Low Plunge DMG
    pub x_dmg3: [f64; 15],       // High Plunge DMG

    // Elemental Skill: 捉浪 (Tidecaller)
    pub e_shield_hp: [f64; 15],          // Shield HP ratio
    pub e_shield_fixed: [f64; 15],       // Shield fixed value
    pub e_dmg_base: [f64; 15],           // Base DMG
    pub e_dmg_delta: [f64; 15],          // DMG per stack

    // Elemental Burst: 斫雷 (Stormbreaker)
    pub q_dmg_skill: [f64; 15],   // Skill DMG
    pub q_dmg_lightning: [f64; 15], // Lightning DMG
}

pub const BEIDOU_SKILL: BeidouSkillType = BeidouSkillType {
    // Normal Attack: 征涛
    a_dmg1: [0.7112, 0.7691, 0.827, 0.9097, 0.9676, 1.0338, 1.1247, 1.2157, 1.3067, 1.4059, 1.5196, 1.6533, 1.7871, 1.9208, 2.0667],
    a_dmg2: [0.7086, 0.7663, 0.824, 0.9064, 0.9641, 1.03, 1.1206, 1.2113, 1.3019, 1.4008, 1.5141, 1.6473, 1.7806, 1.9138, 2.0592],
    a_dmg3: [0.8832, 0.9551, 1.027, 1.1297, 1.2016, 1.2838, 1.3967, 1.5097, 1.6227, 1.7459, 1.8871, 2.0532, 2.2192, 2.3853, 2.5665],
    a_dmg4: [0.8652, 0.9356, 1.006, 1.1066, 1.177, 1.2575, 1.3682, 1.4788, 1.5895, 1.7102, 1.8485, 2.0112, 2.1739, 2.3365, 2.514],
    a_dmg5: [1.1214, 1.2127, 1.304, 1.4344, 1.5257, 1.63, 1.7734, 1.9169, 2.0603, 2.2168, 2.3961, 2.607, 2.8178, 3.0287, 3.2587],
    z_dmg1: [0.5624, 0.6082, 0.654, 0.7194, 0.7652, 0.8175, 0.8894, 0.9614, 1.0333, 1.1118, 1.2017, 1.3075, 1.4132, 1.519, 1.6343],
    z_dmg2: [1.0182, 1.1011, 1.184, 1.3024, 1.3853, 1.48, 1.6102, 1.7405, 1.8707, 2.0128, 2.1756, 2.3671, 2.5585, 2.75, 2.9588],
    x_dmg1: [0.7459, 0.8066, 0.8673, 0.954, 1.0147, 1.0841, 1.1795, 1.2749, 1.3703, 1.4744, 1.5785, 1.6826, 1.7866, 1.8907, 1.9948],
    x_dmg2: [1.4914, 1.6128, 1.7342, 1.9077, 2.0291, 2.1678, 2.3586, 2.5493, 2.7401, 2.9482, 3.1563, 3.3644, 3.5725, 3.7806, 3.9887],
    x_dmg3: [1.8629, 2.0145, 2.1662, 2.3828, 2.5344, 2.7077, 2.946, 3.1842, 3.4225, 3.6825, 3.9424, 4.2023, 4.4623, 4.7222, 4.9821],

    // Elemental Skill: 捉浪
    e_shield_hp: [0.144, 0.1548, 0.1656, 0.18, 0.1908, 0.2016, 0.216, 0.2304, 0.2448, 0.2592, 0.2736, 0.288, 0.306, 0.324, 0.342],
    e_shield_fixed: [1386.0, 1525.0, 1675.0, 1837.0, 2010.0, 2195.0, 2392.0, 2600.0, 2819.0, 3050.0, 3293.0, 3547.0, 3813.0, 4090.0, 4379.0],
    e_dmg_base: [1.216, 1.3072, 1.3984, 1.52, 1.6112, 1.7024, 1.824, 1.9456, 2.0672, 2.1888, 2.3104, 2.432, 2.584, 2.736, 2.888],
    e_dmg_delta: [1.6, 1.72, 1.84, 2., 2.12, 2.24, 2.4, 2.56, 2.72, 2.88, 3.04, 3.2, 3.4, 3.6, 3.8],

    // Elemental Burst: 斫雷
    q_dmg_skill: [1.216, 1.3072, 1.3984, 1.52, 1.6112, 1.7024, 1.824, 1.9456, 2.0672, 2.1888, 2.3104, 2.432, 2.584, 2.736, 2.888],
    q_dmg_lightning: [0.96, 1.032, 1.104, 1.2, 1.272, 1.344, 1.44, 1.536, 1.632, 1.728, 1.824, 1.92, 2.04, 2.16, 2.28],
};

pub const BEIDOU_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Beidou,
    internal_name: "Beidou",
    element: Element::Electro,
    hp: [1094, 2811, 3628, 5435, 6015, 6919, 7694, 8597, 9178, 10081, 10662, 11565, 12146, 13050, 13953],
    atk: [19, 48, 63, 94, 104, 119, 133, 148, 158, 174, 184, 200, 210, 225, 283],
    def: [54, 140, 180, 270, 299, 344, 382, 427, 456, 501, 530, 575, 603, 648, 693],
    sub_stat: CharacterSubStatFamily::Bonus240(StatName::ElectroBonus),
    weapon_type: WeaponType::Claymore,
    star: 4,
    skill_name1: locale!(
        zh_cn: "征涛",
        en: "Normal Attack: Oceanborne",
    ),
    skill_name2: locale!(
        zh_cn: "捉浪",
        en: "Tidecaller",
    ),
    skill_name3: locale!(
        zh_cn: "斫雷",
        en: "Stormbreaker",
    ),
    name_locale: locale!(
        zh_cn: "北斗",
        en: "Beidou",
    ),
};

pub struct BeidouEffect {
    pub stellar_glimmer_state: usize,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for BeidouEffect {
    fn change_attribute(&self, attribute: &mut A) {
    }
}

damage_enum!(
    BeidouDamageEnum
    A1
    A2
    A3
    A4
    A5
    Z1
    Z2
    X1
    X2
    X3
    E1
    E2
    E3
    Q1
    Q2
);

impl BeidouDamageEnum {
    pub fn get_element(&self) -> Element {
        use BeidouDamageEnum::*;
        match *self {
            E1 | E2 | E3 | Q1 | Q2 => Element::Electro,
            _ => Element::Physical,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use BeidouDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4 | A5 => SkillType::NormalAttack,
            Z1 | Z2 => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | E2 | E3 => SkillType::ElementalSkill,
            Q1 | Q2 => SkillType::ElementalBurst,
        }
    }
}

pub struct Beidou;

impl CharacterTrait for Beidou {
    const STATIC_DATA: CharacterStaticData = BEIDOU_STATIC_DATA;
    type SkillType = BeidouSkillType;
    const SKILL: Self::SkillType = BEIDOU_SKILL;
    type DamageEnumType = BeidouDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            BeidouDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            A4 hit_n_dmg!(4)
            A5 hit_n_dmg!(5)
            Z1 charged_dmg!("loop1")
            Z2 charged_dmg!("loop2")
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            BeidouDamageEnum
            E1 locale!(zh_cn: "基础伤害", en: "Base DMG")
            E2 locale!(zh_cn: "一层伤害", en: "1-Stack DMG")
            E3 locale!(zh_cn: "二层伤害", en: "2-Stack DMG")
        ),
        skill3: skill_map!(
            BeidouDamageEnum
            Q1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q2 locale!(zh_cn: "闪电伤害", en: "Lightning DMG")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(0, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "under_q",
            title: locale!(
                zh_cn: "处于斫雷状态下",
                en: "Under Stormbreaker Status"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "perfect_counter",
            title: locale!(
                zh_cn: "触发完美弹反（天赋2：霹雳连霄）",
                en: "Perfect Counter Triggered (P2: Lightning Storm)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let stellar_glimmer_state = match &common_data.config {
            CharacterConfig::Beidou { stellar_glimmer_state } => *stellar_glimmer_state,
            _ => 0,
        };

        let (under_q, perfect_counter) = match *skill_config {
            CharacterSkillConfig::Beidou { under_q, perfect_counter } => (under_q, perfect_counter),
            _ => (false, false),
        };

        // C6: 北斗祓幽孽 — during Q, Electro RES -15%
        // 辉映·星超导: also Cryo RES -15%, on-field EM +200
        if common_data.constellation >= 6 && under_q {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_element(
                    AttributeVariableType::ResMinus,
                    Element::Electro,
                )),
                "北斗命座6",
                0.15,
            );

            if stellar_glimmer_state == 1 {
                attribute.set_value_to_s(
                    CharacterSelector::select_all(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_element(
                        AttributeVariableType::ResMinus,
                        Element::Cryo,
                    )),
                    "北斗命座6",
                    0.15,
                );
                attribute.set_value_to_s(
                    CharacterSelector::select_onfield(attribute),
                    AttributeType::Panel(AttributeName::ElementalMastery),
                    "北斗命座6",
                    200.0,
                );
            }
        }

        // P2: 霹雳连霄 — after perfect counter, NA/CA DMG +15%, ATK SPD +15% (10s)
        if common_data.has_talent2 && perfect_counter {
            for skill in [SkillType::NormalAttack, SkillType::ChargedAttack].iter() {
                attribute.set_value_to_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_skill(
                        AttributeVariableType::Bonus,
                        *skill,
                    )),
                    "北斗天赋2",
                    0.15,
                );
            }
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: BeidouDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let _ = context.character_common_data.config; // unused but present for pattern consistency

        let (under_q, perfect_counter) = match *config {
            CharacterSkillConfig::Beidou { under_q, perfect_counter } => (under_q, perfect_counter),
            _ => (false, false),
        };

        let _ = (under_q, perfect_counter);

        use BeidouDamageEnum::*;
        let mut builder = D::new();

        let ratio = match s {
            A1 => BEIDOU_SKILL.a_dmg1[s1],
            A2 => BEIDOU_SKILL.a_dmg2[s1],
            A3 => BEIDOU_SKILL.a_dmg3[s1],
            A4 => BEIDOU_SKILL.a_dmg4[s1],
            A5 => BEIDOU_SKILL.a_dmg5[s1],
            Z1 => BEIDOU_SKILL.z_dmg1[s1],
            Z2 => BEIDOU_SKILL.z_dmg2[s1],
            X1 => BEIDOU_SKILL.x_dmg1[s1],
            X2 => BEIDOU_SKILL.x_dmg2[s1],
            X3 => BEIDOU_SKILL.x_dmg3[s1],
            E1 => BEIDOU_SKILL.e_dmg_base[s2],
            E2 => BEIDOU_SKILL.e_dmg_base[s2] + BEIDOU_SKILL.e_dmg_delta[s2],
            E3 => BEIDOU_SKILL.e_dmg_base[s2] + 2.0 * BEIDOU_SKILL.e_dmg_delta[s2],
            Q1 => BEIDOU_SKILL.q_dmg_skill[s3],
            Q2 => BEIDOU_SKILL.q_dmg_lightning[s3],
        };

        builder.add_atk_ratio("技能倍率", ratio);

        builder.damage(
            &context.attribute,
            &context.enemy,
            s.get_element(),
            s.get_skill_type(),
            context.character_common_data.level,
            fumo,
        )
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let stellar_glimmer_state = match *config {
            CharacterConfig::Beidou { stellar_glimmer_state } => stellar_glimmer_state,
            _ => 0,
        };
        Some(Box::new(BeidouEffect {
            stellar_glimmer_state,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
