// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct CynoSkillType {
    // Normal Attack: Invoker's Spear (七圣枪术)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg31: [f64; 15],
    pub a_dmg32: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: Secret Rite: Chasmic Soulfarer (秘仪·律渊渡魂)
    pub e_dmg: [f64; 15],
    pub e_mortuary: [f64; 15], // Mortuary Rite DMG (冥祭)

    // Elemental Burst: Sacred Rite: Wolf's Swiftness (圣仪·煟煌随狼行)
    pub q_dmg1: [f64; 15],
    pub q_dmg2: [f64; 15],
    pub q_dmg3: [f64; 15],
    pub q_dmg41: [f64; 15],
    pub q_dmg42: [f64; 15],
    pub q_dmg5: [f64; 15],
    pub q_z_dmg: [f64; 15],
    pub q_x_dmg1: [f64; 15],
    pub q_x_dmg2: [f64; 15],
    pub q_x_dmg3: [f64; 15],

    // P1: Featherfall Judgment (落羽的裁择)
    pub p1_bolt_atk_ratio: f64,      // Duststalker Bolt ATK ratio (100%)
    pub p1_starsame_atk_ratio: f64,  // Starsame ATK ratio (200%)
    pub p1_judication_bonus: f64,    // Judication DMG bonus (35%)

    // P2: Authority Over the Nine Bows (九弓的执命)
    pub p2_na_em_ratio: f64,         // NA EM scaling (150%)
    pub p2_bolt_em_ratio: f64,       // Duststalker Bolt EM scaling (250%)
    pub p2_starsame_em_ratio: f64,   // Starsame EM scaling (600%)

    // C1: Ordinance: Unceasing Vigil (立仪·俯览昼冥)
    pub c1_atk_spd: f64,    // ATK SPD bonus (20%)
    pub c1_em_bonus: f64,   // Together We Rise EM bonus (200)

    // C2: Ceremony: Homecoming of Spirits (令仪·引谒归灵)
    pub c2_electro_per_stack: f64,  // Electro DMG per stack (10%)
    pub c2_sc_per_stack: f64,       // Stellar-Conduct DMG per stack (16%)
}

pub const CYNO_SKILL: CynoSkillType = CynoSkillType {
    // Normal Attack: Invoker's Spear
    a_dmg1: [0.492574, 0.532667, 0.57276, 0.630036, 0.670129, 0.71595, 0.778954, 0.841957, 0.904961, 0.973692, 1.042423, 1.111154, 1.179886, 1.248617, 1.317348],
    a_dmg2: [0.479209, 0.518215, 0.55722, 0.612942, 0.651947, 0.696525, 0.757819, 0.819113, 0.880408, 0.947274, 1.01414, 1.081007, 1.147873, 1.21474, 1.281606],
    a_dmg31: [0.293062, 0.316916, 0.34077, 0.374847, 0.398701, 0.425963, 0.463447, 0.500932, 0.538417, 0.579309, 0.620201, 0.661094, 0.701986, 0.742879, 0.783771],
    a_dmg32: [0.293062, 0.316916, 0.34077, 0.374847, 0.398701, 0.425963, 0.463447, 0.500932, 0.538417, 0.579309, 0.620201, 0.661094, 0.701986, 0.742879, 0.783771],
    a_dmg4: [0.758907, 0.820679, 0.88245, 0.970695, 1.032466, 1.103063, 1.200132, 1.297202, 1.394271, 1.500165, 1.606059, 1.711953, 1.817847, 1.923741, 2.029635],
    z_dmg: [1.22378, 1.32339, 1.423, 1.5653, 1.66491, 1.77875, 1.93528, 2.09181, 2.24834, 2.4191, 2.58986, 2.76062, 2.93138, 3.10214, 3.2729],
    x_dmg1: [0.639324, 0.691362, 0.7434, 0.81774, 0.869778, 0.92925, 1.011024, 1.092798, 1.174572, 1.26378, 1.352988, 1.442196, 1.531404, 1.620612, 1.70982],
    x_dmg2: [1.278377, 1.382431, 1.486485, 1.635134, 1.739187, 1.858106, 2.02162, 2.185133, 2.348646, 2.527025, 2.705403, 2.883781, 3.062159, 3.240537, 3.418915],
    x_dmg3: [1.596762, 1.726731, 1.8567, 2.04237, 2.172339, 2.320875, 2.525112, 2.729349, 2.933586, 3.15639, 3.379194, 3.601998, 3.824802, 4.047606, 4.27041],

    // Elemental Skill: Secret Rite: Chasmic Soulfarer
    e_dmg: [1.304, 1.4018, 1.4996, 1.63, 1.7278, 1.8256, 1.956, 2.0864, 2.2168, 2.3472, 2.4776, 2.608, 2.771, 2.934, 3.097],
    e_mortuary: [1.568, 1.6856, 1.8032, 1.96, 2.0776, 2.1952, 2.352, 2.5088, 2.6656, 2.8224, 2.9792, 3.136, 3.332, 3.528, 3.724],

    // Elemental Burst: Sacred Rite: Wolf's Swiftness
    q_dmg1: [0.782832, 0.846551, 0.91027, 1.001297, 1.065016, 1.137838, 1.237967, 1.338097, 1.438227, 1.547459, 1.656691, 1.765924, 1.875156, 1.984389, 2.093621],
    q_dmg2: [0.824688, 0.891814, 0.95894, 1.054834, 1.12196, 1.198675, 1.304158, 1.409642, 1.515125, 1.630198, 1.745271, 1.860344, 1.975416, 2.090489, 2.205562],
    q_dmg3: [1.046336, 1.131503, 1.21667, 1.338337, 1.423504, 1.520837, 1.654671, 1.788505, 1.922339, 2.068339, 2.214339, 2.36034, 2.50634, 2.652341, 2.798341],
    q_dmg41: [0.516942, 0.559018, 0.601095, 0.661205, 0.703281, 0.751369, 0.817489, 0.88361, 0.94973, 1.021861, 1.093993, 1.166124, 1.238256, 1.310387, 1.382518],
    q_dmg42: [0.516942, 0.559018, 0.601095, 0.661205, 0.703281, 0.751369, 0.817489, 0.88361, 0.94973, 1.021861, 1.093993, 1.166124, 1.238256, 1.310387, 1.382518],
    q_dmg5: [1.308447, 1.414948, 1.52145, 1.673595, 1.780096, 1.901812, 2.069172, 2.236531, 2.403891, 2.586465, 2.769039, 2.951613, 3.134187, 3.316761, 3.499335],
    q_z_dmg: [1.0105, 1.09275, 1.175, 1.2925, 1.37475, 1.46875, 1.598, 1.72725, 1.8565, 1.9975, 2.1385, 2.2795, 2.4205, 2.5615, 2.7025],
    q_x_dmg1: [0.639324, 0.691362, 0.7434, 0.81774, 0.869778, 0.92925, 1.011024, 1.092798, 1.174572, 1.26378, 1.352988, 1.442196, 1.531404, 1.620612, 1.70982],
    q_x_dmg2: [1.278377, 1.382431, 1.486485, 1.635134, 1.739187, 1.858106, 2.02162, 2.185133, 2.348646, 2.527025, 2.705403, 2.883781, 3.062159, 3.240537, 3.418915],
    q_x_dmg3: [1.596762, 1.726731, 1.8567, 2.04237, 2.172339, 2.320875, 2.525112, 2.729349, 2.933586, 3.15639, 3.379194, 3.601998, 3.824802, 4.047606, 4.27041],

    // P1: Featherfall Judgment
    p1_bolt_atk_ratio: 1.0,
    p1_starsame_atk_ratio: 2.0,
    p1_judication_bonus: 0.35,

    // P2: Authority Over the Nine Bows
    p2_na_em_ratio: 1.5,
    p2_bolt_em_ratio: 2.5,
    p2_starsame_em_ratio: 6.0,

    // C1: Ordinance: Unceasing Vigil
    c1_atk_spd: 0.2,
    c1_em_bonus: 200.0,

    // C2: Ceremony: Homecoming of Spirits
    c2_electro_per_stack: 0.1,
    c2_sc_per_stack: 0.16,
};

pub struct CynoEffect {
    pub in_polestar_field: bool,
    pub stellar_conduct_application_count: i32,
    pub after_q: bool,
    pub c2_stack: f64,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for CynoEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // Pactsworn Pathclearer: +100 EM
        if self.after_q {
            attribute.set_value_to(AttributeName::ElementalMastery, "赛诺启途誓使", 100.0);

            // C1 Together We Rise: +200 EM
            if self.common_data.constellation >= 1 {
                attribute.set_value_to(AttributeName::ElementalMastery, "赛诺命座1", CYNO_SKILL.c1_em_bonus);
            }
        }

        // C2: Electro DMG bonus per stack (from Cyno's own NAs)
        if self.common_data.constellation >= 2 {
            attribute.set_value_to(AttributeName::BonusElectro, "赛诺命座2", CYNO_SKILL.c2_electro_per_stack * self.c2_stack);
        }

        // Stellar-Conduct application count → ElevativeCoefficient
        let coefficient = ElevativeReaction::STELLAR_CONDUCT_EXTRA_COEFFICIENT[self.stellar_conduct_application_count as usize];
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeCoefficient,
                ReactionType::StellarConduct,
            )),
            "星超导附着次数",
            coefficient,
        );
    }
}

damage_enum!(
    CynoDamageEnum
    A1
    A2
    A31
    A32
    A4
    Z
    X1
    X2
    X3
    E1
    E2
    E3
    Q1
    Q2
    Q3
    Q41
    Q42
    Q5
    QZ
    QX1
    QX2
    QX3
    C6B
);

impl CynoDamageEnum {
    pub fn get_element(&self) -> Element {
        use CynoDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | Z | X1 | X2 | X3 => Element::Physical,
            E1 | E2 | E3 | Q1 | Q2 | Q3 | Q41 | Q42 | Q5 | QZ | QX1 | QX2 | QX3 | C6B => Element::Electro,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use CynoDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | Q1 | Q2 | Q3 | Q41 | Q42 | Q5 => SkillType::NormalAttack,
            Z | QZ => SkillType::ChargedAttack,
            X1 | QX1 => SkillType::PlungingAttackInAction,
            X2 | X3 | QX2 | QX3 => SkillType::PlungingAttackOnGround,
            E1 | E2 | E3 | C6B => SkillType::ElementalSkill,
        }
    }

    pub fn get_elevative_type(&self, in_polestar_field: bool) -> Option<ElevativeReaction> {
        use CynoDamageEnum::*;
        match *self {
            E3 | C6B if in_polestar_field => Some(ElevativeReaction::StellarConductElectro),
            _ => None,
        }
    }
}

pub struct Cyno;

impl CharacterTrait for Cyno {
    const STATIC_DATA: CharacterStaticData = CharacterStaticData {
        name: CharacterName::Cyno,
        internal_name: "Cyno",
        element: Element::Electro,
        hp: [972, 2522, 3356, 5022, 5614, 6459, 7249, 8103, 8695, 9557, 10149, 11020, 11613, 12491, 13379],
        atk: [25, 64, 85, 128, 143, 165, 185, 206, 221, 243, 258, 281, 296, 318, 390],
        def: [67, 174, 231, 345, 386, 444, 499, 557, 598, 657, 698, 758, 799, 859, 920],
        sub_stat: CharacterSubStatFamily::CriticalDamage384,
        weapon_type: WeaponType::Polearm,
        star: 5,
        skill_name1: locale!(
            zh_cn: "七圣枪术",
            en: "Invoker's Spear",
        ),
        skill_name2: locale!(
            zh_cn: "秘仪·律渊渡魂",
            en: "Secret Rite: Chasmic Soulfarer",
        ),
        skill_name3: locale!(
            zh_cn: "圣仪·煟煌随狼行",
            en: "Sacred Rite: Wolf's Swiftness",
        ),
        name_locale: locale!(
            zh_cn: "赛诺",
            en: "Cyno",
        )
    };
    type SkillType = CynoSkillType;
    const SKILL: Self::SkillType = CYNO_SKILL;
    type DamageEnumType = CynoDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            CynoDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A31 hit_n_dmg!(3, 1)
            A32 hit_n_dmg!(3, 2)
            A4 hit_n_dmg!(4)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            Q1 locale!(zh_cn: "启途誓使：一段伤害", en: "Pactsworn Pathclearer: 1-Hit DMG")
            Q2 locale!(zh_cn: "启途誓使：二段伤害", en: "Pactsworn Pathclearer: 2-Hit DMG")
            Q3 locale!(zh_cn: "启途誓使：三段伤害", en: "Pactsworn Pathclearer: 3-Hit DMG")
            Q41 locale!(zh_cn: "启途誓使：四段伤害1", en: "Pactsworn Pathclearer: 4-Hit DMG 1")
            Q42 locale!(zh_cn: "启途誓使：四段伤害2", en: "Pactsworn Pathclearer: 4-Hit DMG 2")
            Q5 locale!(zh_cn: "启途誓使：五段伤害", en: "Pactsworn Pathclearer: 5-Hit DMG")
            QZ locale!(zh_cn: "启途誓使：重击伤害", en: "Pactsworn Pathclearer: Charged Attack DMG")
            QX1 locale!(zh_cn: "启途誓使：下坠期间伤害", en: "Pactsworn Pathclearer: Plunge DMG")
            QX2 locale!(zh_cn: "启途誓使：低空坠地冲击伤害", en: "Pactsworn Pathclearer: Low Plunging DMG")
            QX3 locale!(zh_cn: "启途誓使：高空坠地冲击伤害", en: "Pactsworn Pathclearer: High Plunging DMG")
            C6B locale!(zh_cn: "命座6渡荒之雷", en: "C6 Duststalker Bolt")
        ),
        skill2: skill_map!(
            CynoDamageEnum
            E1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E2 locale!(zh_cn: "启途誓使：冥祭", en: "Pactsworn Pathclearer: Mortuary Rite DMG")
            E3 locale!(zh_cn: "启途誓使：渡荒之雷", en: "Pactsworn Pathclearer: Duststalker Bolt DMG")
        ),
        skill3: None,
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::IN_POLESTAR_FIELD(false, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "c2_stack",
            title: locale!(
                zh_cn: "命座2「令仪·引谒归灵」等效层数",
                en: "C2「Ceremony: Homecoming of Spirits」Stacks",
            ),
            config: ItemConfigType::Float { min: 0.0, max: 5.0, default: 4.0 },
        },
        ItemConfig {
            name: "after_q",
            title: locale!(
                zh_cn: "启途誓使",
                en: "Pactsworn Pathclearer",
            ),
            config: ItemConfigType::Bool { default: true },
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "under_judication",
            title: locale!(
                zh_cn: "触发「裁定」效果",
                en: "Enable \"Judication\"",
            ),
            config: ItemConfigType::Bool { default: true },
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (in_polestar_field, stellar_conduct_application_count, after_q, c2_stack) = match &common_data.config {
            CharacterConfig::Cyno { in_polestar_field, stellar_conduct_application_count, after_q, c2_stack, .. } =>
                (*in_polestar_field, *stellar_conduct_application_count, *after_q, *c2_stack),
            _ => (false, 0, false, 0.0),
        };

        let under_judication = match *skill_config {
            CharacterSkillConfig::Cyno { under_judication, .. } => under_judication,
            _ => false
        };

        let _ = (attribute, in_polestar_field, stellar_conduct_application_count, after_q, c2_stack, under_judication);
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: CynoDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_polestar_field, stellar_conduct_application_count, after_q, c2_stack) = match &context.character_common_data.config {
            CharacterConfig::Cyno { in_polestar_field, stellar_conduct_application_count, after_q, c2_stack, .. } =>
                (*in_polestar_field, *stellar_conduct_application_count, *after_q, *c2_stack),
            _ => (false, 0, false, 0.0),
        };

        let _ = stellar_conduct_application_count;

        let under_judication = match *config {
            CharacterSkillConfig::Cyno { under_judication, .. } => under_judication,
            _ => false
        };

        use CynoDamageEnum::*;

        // C6 bolts require constellation >= 6
        if s == C6B && context.character_common_data.constellation < 6 {
            return D::new().none();
        }

        // P1 bolts require talent1
        if s == E3 && !context.character_common_data.has_talent1 {
            return D::new().none();
        }

        // E3/C6B become Stellar-Conduct when in Polestar Field
        let is_stellar_conduct = matches!(s, E3 | C6B) && in_polestar_field;

        let mut builder = D::new();

        let ratio = match s {
            A1 => CYNO_SKILL.a_dmg1[s1],
            A2 => CYNO_SKILL.a_dmg2[s1],
            A31 => CYNO_SKILL.a_dmg31[s1],
            A32 => CYNO_SKILL.a_dmg32[s1],
            A4 => CYNO_SKILL.a_dmg4[s1],
            Z => CYNO_SKILL.z_dmg[s1],
            X1 => CYNO_SKILL.x_dmg1[s1],
            X2 => CYNO_SKILL.x_dmg2[s1],
            X3 => CYNO_SKILL.x_dmg3[s1],
            E1 => CYNO_SKILL.e_dmg[s2],
            E2 => CYNO_SKILL.e_mortuary[s2],
            E3 => if is_stellar_conduct { CYNO_SKILL.p1_starsame_atk_ratio } else { CYNO_SKILL.p1_bolt_atk_ratio },
            Q1 => CYNO_SKILL.q_dmg1[s3],
            Q2 => CYNO_SKILL.q_dmg2[s3],
            Q3 => CYNO_SKILL.q_dmg3[s3],
            Q41 => CYNO_SKILL.q_dmg41[s3],
            Q42 => CYNO_SKILL.q_dmg42[s3],
            Q5 => CYNO_SKILL.q_dmg5[s3],
            QZ => CYNO_SKILL.q_z_dmg[s3],
            QX1 => CYNO_SKILL.q_x_dmg1[s3],
            QX2 => CYNO_SKILL.q_x_dmg2[s3],
            QX3 => CYNO_SKILL.q_x_dmg3[s3],
            C6B => if is_stellar_conduct { CYNO_SKILL.p1_starsame_atk_ratio } else { CYNO_SKILL.p1_bolt_atk_ratio },
        };

        builder.add_atk_ratio("技能倍率", ratio);

        // P1 Judication: 35% bonus for Mortuary Rite and Duststalker Bolts
        if under_judication && context.character_common_data.has_talent1 {
            if matches!(s, E2 | E3) {
                builder.add_extra_bonus("赛诺天赋1", CYNO_SKILL.p1_judication_bonus);
            }
        }

        // P2: EM scaling (only during Pactsworn Pathclearer)
        if context.character_common_data.has_talent2 && after_q {
            let em = context.attribute.get_em_all();

            // Q Normal Attacks: 150% EM
            if matches!(s, Q1 | Q2 | Q3 | Q41 | Q42 | Q5) {
                builder.add_extra_damage("赛诺天赋2", em * CYNO_SKILL.p2_na_em_ratio);
            }

            // Duststalker Bolts / Starsame: different EM scaling based on mode
            if matches!(s, E3 | C6B) {
                builder.add_extra_damage("赛诺天赋2", em * if is_stellar_conduct { CYNO_SKILL.p2_starsame_em_ratio } else { CYNO_SKILL.p2_bolt_em_ratio });
            }
        }

        // C2 Stellar-Conduct DMG bonus when Together We Rise is active (C1 + after_q)
        if context.character_common_data.constellation >= 2
            && after_q
            && context.character_common_data.constellation >= 1
            && c2_stack > 0.0
            && is_stellar_conduct
        {
            builder.add_extra_reaction_enhance("赛诺命座2", CYNO_SKILL.c2_sc_per_stack * c2_stack);
        }

        // Determine if this is Stellar-Conduct (elevative) damage
        if let Some(elevative_type) = s.get_elevative_type(in_polestar_field) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (in_polestar_field, stellar_conduct_application_count, after_q, c2_stack) = match *config {
            CharacterConfig::Cyno { in_polestar_field, stellar_conduct_application_count, after_q, c2_stack, .. } =>
                (in_polestar_field, stellar_conduct_application_count, after_q, c2_stack),
            _ => (false, 0, false, 0.0),
        };
        Some(Box::new(CynoEffect {
            in_polestar_field,
            stellar_conduct_application_count,
            after_q,
            c2_stack,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}