// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct YaeMikoSkillType {
    // Normal Attack: 狐灵食罪式 (Spiritfox Sin-Eater)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 野干役咒·杀生樱 (Yakan Evocation: Sesshou Sakura)
    pub e_dmg1: [f64; 15], // Level 1
    pub e_dmg2: [f64; 15], // Level 2
    pub e_dmg3: [f64; 15], // Level 3
    pub e_dmg4: [f64; 15], // Level 4 (C2+)

    // Elemental Burst: 大密法·天狐显真 (Great Secret Art: Tenko Kenshin)
    pub q_dmg: [f64; 15],     // Initial skill DMG
    pub q_dmg_tk: [f64; 15],  // Tenko Thunderbolt DMG (per bolt)

    // P1: 神篱之御荫 (The Shrine's Sacred Shade) - extra lightning when 3+ Sakura
    pub p1_atk_ratio: f64,     // Regular: 40% ATK
    pub p1_sc_atk_ratio: f64,  // Stellar-Conduct: 50% ATK

    // P3: 祓所之讬宣 (Edict of Cleansing) - enhanced Sakura + extra Stellar-Conduct hit
    pub p3_enhance_atk_ratio: f64,  // Enhanced bonus: 80% ATK
    pub p3_sc_atk_ratio: f64,       // Stellar-Conduct extra hit: 200% ATK

    // C2: 望月吼哕声 (Fox's Mooncall) - EM bonus per Sakura level
    pub c2_em_bonus: [f64; 4],  // [60, 90, 120, 200] for levels 1-4
}

pub const YAE_MIKO_SKILL: YaeMikoSkillType = YaeMikoSkillType {
    // Normal Attack: 狐灵食罪式
    a_dmg1: [0.396584, 0.426328, 0.456072, 0.49573, 0.525474, 0.555218, 0.594876, 0.634534, 0.674193, 0.713851, 0.75351, 0.793168, 0.842741, 0.892314, 0.941887],
    a_dmg2: [0.385192, 0.414081, 0.442971, 0.48149, 0.510379, 0.539269, 0.577788, 0.616307, 0.654826, 0.693346, 0.731865, 0.770384, 0.818533, 0.866682, 0.914831],
    a_dmg3: [0.568888, 0.611555, 0.654221, 0.71111, 0.753777, 0.796443, 0.853332, 0.910221, 0.96711, 1.023998, 1.080887, 1.137776, 1.208887, 1.279998, 1.351109],
    z_dmg: [1.428948, 1.53612, 1.643291, 1.786185, 1.893357, 2.000528, 2.143423, 2.286317, 2.429212, 2.572107, 2.715002, 2.857897, 3.036515, 3.215134, 3.393752],
    x_dmg1: [0.568288, 0.614544, 0.6608, 0.72688, 0.773136, 0.826, 0.898688, 0.971376, 1.044064, 1.12336, 1.202656, 1.281952, 1.361248, 1.440544, 1.51984],
    x_dmg2: [1.136335, 1.228828, 1.32132, 1.453452, 1.545944, 1.65165, 1.796995, 1.94234, 2.087686, 2.246244, 2.404802, 2.563361, 2.721919, 2.880478, 3.039036],
    x_dmg3: [1.419344, 1.534872, 1.6504, 1.81544, 1.930968, 2.063, 2.244544, 2.426088, 2.607632, 2.80568, 3.003728, 3.201776, 3.399824, 3.597872, 3.79592],

    // Elemental Skill: 野干役咒·杀生樱
    e_dmg1: [0.60672, 0.652224, 0.697728, 0.7584, 0.803904, 0.849408, 0.91008, 0.970752, 1.031424, 1.092096, 1.152768, 1.21344, 1.28928, 1.36512, 1.44096],
    e_dmg2: [0.7584, 0.81528, 0.87216, 0.948, 1.00488, 1.06176, 1.1376, 1.21344, 1.28928, 1.36512, 1.44096, 1.5168, 1.6116, 1.7064, 1.8012],
    e_dmg3: [0.948, 1.0191, 1.0902, 1.185, 1.2561, 1.3272, 1.422, 1.5168, 1.6116, 1.7064, 1.8012, 1.896, 2.0145, 2.133, 2.2515],
    e_dmg4: [1.185, 1.273875, 1.36275, 1.48125, 1.570125, 1.659, 1.7775, 1.896, 2.0145, 2.133, 2.2515, 2.37, 2.518125, 2.66625, 2.814375],

    // Elemental Burst: 大密法·天狐显真
    q_dmg: [2.6, 2.795, 2.99, 3.25, 3.445, 3.64, 3.9, 4.16, 4.42, 4.68, 4.94, 5.2, 5.525, 5.85, 6.175],
    q_dmg_tk: [3.33816, 3.588522, 3.838884, 4.1727, 4.423062, 4.673424, 5.00724, 5.341056, 5.674872, 6.008688, 6.342504, 6.67632, 7.09359, 7.51086, 7.92813],

    // P1: 神篱之御荫
    p1_atk_ratio: 0.4,
    p1_sc_atk_ratio: 0.5,

    // P3: 祓所之讬宣
    p3_enhance_atk_ratio: 0.8,
    p3_sc_atk_ratio: 2.0,

    // C2: 望月吼哕声
    c2_em_bonus: [60.0, 90.0, 120.0, 200.0],
};

pub const YAE_MIKO_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::YaeMiko,
    internal_name: "Yae",
    element: Element::Electro,
    hp: [807, 2095, 2787, 4170, 4662, 5364, 6020, 6729, 7220, 7936, 8428, 9151, 9643, 10372, 11109],
    atk: [26, 69, 91, 137, 153, 176, 197, 220, 236, 260, 276, 300, 316, 340, 417],
    def: [44, 115, 153, 229, 256, 294, 330, 369, 396, 435, 462, 502, 529, 569, 609],
    sub_stat: CharacterSubStatFamily::CriticalRate192,
    weapon_type: WeaponType::Catalyst,
    star: 5,
    skill_name1: locale!(
        zh_cn: "狐灵食罪式",
        en: "Spiritfox Sin-Eater",
    ),
    skill_name2: locale!(
        zh_cn: "野干役咒·杀生樱",
        en: "Yakan Evocation: Sesshou Sakura",
    ),
    skill_name3: locale!(
        zh_cn: "大密法·天狐显真",
        en: "Great Secret Art: Tenko Kenshin",
    ),
    name_locale: locale!(
        zh_cn: "八重神子",
        en: "Yae Miko",
    ),
};

pub struct YaeMikoEffect {
    pub stellar_glimmer_state: usize,
    pub stellar_conduct_application_count: usize,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for YaeMikoEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P2: 启蜇之祝词 — EM → Sesshou Sakura DMG bonus (0.15% per EM)
        if self.common_data.has_talent2 {
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ElementalMastery),
                AttributeType::Invisible(InvisibleAttributeType::new(
                    AttributeVariableType::Bonus,
                    Some(Element::Electro),
                    Some(SkillType::ElementalSkill),
                    None,
                )),
                Arc::new(move |em: f64, _| em * 0.0015),
                "八重神子天赋2",
                EdgePriority::Invisible,
            );
        }

        // C1: 野狐供真篇 — 触发超导/星超导后，队伍角色获得50%雷伤+50%星超导伤害加成
        if self.common_data.constellation >= 1 {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::BonusElectro),
                "八重神子命座1",
                0.5,
            );
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "八重神子命座1",
                0.5,
            );
        }

        // C4: 绯樱引雷章 — 杀生樱命中后队伍角色获20%雷伤，且元素爆发伤害+100%
        if self.common_data.constellation >= 4 {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::BonusElectro),
                "八重神子命座4",
                0.2,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(
                    AttributeVariableType::Bonus,
                    SkillType::ElementalBurst,
                )),
                "八重神子命座4",
                1.0,
            );
        }

        // C6: 大杀生咒禁 — 杀生樱无视60%防御，星超导暴伤+200%
        if self.common_data.constellation >= 6 {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(
                    AttributeVariableType::DefPenetration,
                    SkillType::ElementalSkill,
                )),
                "八重神子命座6",
                0.6,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::CriticalDamage,
                    ReactionType::StellarConduct,
                )),
                "八重神子命座6",
                2.0,
            );
        }

        // 星超导附着次数 → ElevativeCoefficient
        ElevativeReaction::apply_stellar_conduct_extra_coefficient(attribute, self.stellar_conduct_application_count);
    }
}

damage_enum!(
    YaeMikoDamageEnum
    A1
    A2
    A3
    Z
    X1
    X2
    X3
    E1
    E2
    E3
    E4
    Q
    Q_TK
    Q_TK_TOTAL
    P1
    P3_SC
);

impl YaeMikoDamageEnum {
    pub fn get_element(&self) -> Element {
        use YaeMikoDamageEnum::*;
        match *self {
            _ => Element::Electro,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use YaeMikoDamageEnum::*;
        match *self {
            A1 | A2 | A3 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | E2 | E3 | E4 | P1 => SkillType::ElementalSkill,
            Q | Q_TK | Q_TK_TOTAL => SkillType::ElementalBurst,
            P3_SC => SkillType::Elevative,
        }
    }

    pub fn get_elevative_type(&self, stellar_glimmer_state: usize) -> Option<ElevativeReaction> {
        use YaeMikoDamageEnum::*;
        match *self {
            P1 if stellar_glimmer_state == 1 => Some(ElevativeReaction::StellarConductElectro),
            P3_SC => Some(ElevativeReaction::StellarConductElectro),
            _ => None,
        }
    }
}

pub struct YaeMiko;

impl CharacterTrait for YaeMiko {
    const STATIC_DATA: CharacterStaticData = YAE_MIKO_STATIC_DATA;
    type SkillType = YaeMikoSkillType;
    const SKILL: Self::SkillType = YAE_MIKO_SKILL;
    type DamageEnumType = YaeMikoDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            YaeMikoDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            YaeMikoDamageEnum
            E1 locale!(zh_cn: "杀生樱伤害·壹阶", en: "Sesshou Sakura DMG: Level 1")
            E2 locale!(zh_cn: "杀生樱伤害·贰阶", en: "Sesshou Sakura DMG: Level 2")
            E3 locale!(zh_cn: "杀生樱伤害·叁阶", en: "Sesshou Sakura DMG: Level 3")
            E4 locale!(zh_cn: "杀生樱伤害·肆阶", en: "Sesshou Sakura DMG: Level 4")
            P1 locale!(zh_cn: "天赋1额外雷击", en: "P1 Extra Lightning Strike")
            P3_SC locale!(zh_cn: "天赋3额外星超导伤害", en: "P3 Extra Stellar-Conduct DMG")
        ),
        skill3: skill_map!(
            YaeMikoDamageEnum
            Q locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q_TK locale!(zh_cn: "天狐霆雷伤害（单道）", en: "Tenko Thunderbolt DMG (per bolt)")
            Q_TK_TOTAL locale!(zh_cn: "天狐霆雷总伤害", en: "Tenko Thunderbolt Total DMG")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::STELLAR_GLIMMER_STATE(0, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "sesshou_sakura_level",
            title: locale!(
                zh_cn: "杀生樱位阶",
                en: "Sesshou Sakura Level"
            ),
            config: ItemConfigType::Int { min: 1, max: 4, default: 3 }
        },
        ItemConfig {
            name: "sesshou_sakura_count",
            title: locale!(
                zh_cn: "杀生樱数量",
                en: "Sesshou Sakura Count"
            ),
            config: ItemConfigType::Int { min: 1, max: 3, default: 3 }
        },
        ItemConfig {
            name: "p3_enhanced",
            title: locale!(
                zh_cn: "天赋3强化落雷生效",
                en: "P3 Enhanced Lightning Active"
            ),
            config: ItemConfigType::Bool { default: false }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (stellar_glimmer_state, stellar_conduct_application_count) = match &common_data.config {
            CharacterConfig::YaeMiko { stellar_glimmer_state, stellar_conduct_application_count } =>
                (*stellar_glimmer_state, *stellar_conduct_application_count),
            _ => (0, 0),
        };

        let (sesshou_sakura_level, sesshou_sakura_count, p3_enhanced) = match *skill_config {
            CharacterSkillConfig::YaeMiko { sesshou_sakura_level, sesshou_sakura_count, p3_enhanced } =>
                (sesshou_sakura_level, sesshou_sakura_count, p3_enhanced),
            _ => (3, 3, false),
        };

        // C2: 望月吼哕声 — 根据杀生樱位阶，提升八重神子与当前场上角色的元素精通
        if common_data.constellation >= 2 && sesshou_sakura_level >= 1 && sesshou_sakura_level <= 4 {
            let c2_em = YAE_MIKO_SKILL.c2_em_bonus[sesshou_sakura_level - 1];
            attribute.set_value_to(AttributeName::ElementalMastery, "八重神子命座2", c2_em);
            attribute.set_value_to_s(
                CharacterSelector::select_onfield(attribute),
                AttributeType::Panel(AttributeName::ElementalMastery),
                "八重神子命座2",
                c2_em,
            );
        }

        let _ = (stellar_glimmer_state, stellar_conduct_application_count, sesshou_sakura_count, p3_enhanced);
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: YaeMikoDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (stellar_glimmer_state, stellar_conduct_application_count) = match &context.character_common_data.config {
            CharacterConfig::YaeMiko { stellar_glimmer_state, stellar_conduct_application_count } =>
                (*stellar_glimmer_state, *stellar_conduct_application_count),
            _ => (0, 0),
        };

        let _ = stellar_conduct_application_count;

        let (sesshou_sakura_level, sesshou_sakura_count, p3_enhanced) = match *config {
            CharacterSkillConfig::YaeMiko { sesshou_sakura_level, sesshou_sakura_count, p3_enhanced } =>
                (sesshou_sakura_level, sesshou_sakura_count, p3_enhanced),
            _ => (3, 3, false),
        };

        use YaeMikoDamageEnum::*;

        // P1 extra lightning requires talent1 and 3+ Sakura
        if s == P1 && (!context.character_common_data.has_talent1 || sesshou_sakura_count < 3) {
            return D::new().none();
        }

        // P3_SC requires P3 enhanced active and in Stellar-Conduct state
        if s == P3_SC && (!p3_enhanced || stellar_glimmer_state != 1) {
            return D::new().none();
        }

        let mut builder = D::new();

        let ratio = match s {
            A1 => YAE_MIKO_SKILL.a_dmg1[s1],
            A2 => YAE_MIKO_SKILL.a_dmg2[s1],
            A3 => YAE_MIKO_SKILL.a_dmg3[s1],
            Z => YAE_MIKO_SKILL.z_dmg[s1],
            X1 => YAE_MIKO_SKILL.x_dmg1[s1],
            X2 => YAE_MIKO_SKILL.x_dmg2[s1],
            X3 => YAE_MIKO_SKILL.x_dmg3[s1],
            E1 => YAE_MIKO_SKILL.e_dmg1[s2],
            E2 => YAE_MIKO_SKILL.e_dmg2[s2],
            E3 => YAE_MIKO_SKILL.e_dmg3[s2],
            E4 => YAE_MIKO_SKILL.e_dmg4[s2],
            Q => YAE_MIKO_SKILL.q_dmg[s3],
            Q_TK => YAE_MIKO_SKILL.q_dmg_tk[s3],
            Q_TK_TOTAL => YAE_MIKO_SKILL.q_dmg_tk[s3] * sesshou_sakura_count as f64,
            P1 => if stellar_glimmer_state == 1 { YAE_MIKO_SKILL.p1_sc_atk_ratio } else { YAE_MIKO_SKILL.p1_atk_ratio },
            P3_SC => YAE_MIKO_SKILL.p3_sc_atk_ratio,
        };

        // P3 enhanced: add 80% ATK extra bonus for Sakura lightning under Superconduct/Stellar-Conduct
        if p3_enhanced && matches!(s, E1 | E2 | E3 | E4 | P3_SC) {
            if matches!(s, E1 | E2 | E3 | E4) {
                builder.add_atk_ratio("技能倍率", ratio);
                builder.add_atk_ratio("天赋3强化落雷", YAE_MIKO_SKILL.p3_enhance_atk_ratio);
            } else {
                builder.add_atk_ratio("技能倍率", ratio);
            }
        } else {
            builder.add_atk_ratio("技能倍率", ratio);
        }

        // Determine damage type — P1 becomes Stellar-Conduct when in Polestar Field
        if let Some(elevative_type) = s.get_elevative_type(stellar_glimmer_state) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (stellar_glimmer_state, stellar_conduct_application_count) = match *config {
            CharacterConfig::YaeMiko { stellar_glimmer_state, stellar_conduct_application_count } =>
                (stellar_glimmer_state, stellar_conduct_application_count),
            _ => (0, 0),
        };
        Some(Box::new(YaeMikoEffect {
            stellar_glimmer_state,
            stellar_conduct_application_count,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
