use serde::{Deserialize, Serialize};

use crate::attribute::Attribute;
use crate::buffs::Buff;
use crate::buffs::buffs::get_buff;
use crate::common::{Element, Moonsign};
use crate::common::item_config_type::ConfigElements8Multi;

#[derive(Serialize, Deserialize)]
pub enum BuffConfig {
    ATKPercentage { p: f64 },
    DEFPercentage { p: f64 },
    HPPercentage { p: f64 },
    ATKFixed { value: f64 },
    DEFFixed { value: f64 },
    HPFixed { value: f64 },
    Critical { p: f64 },
    CriticalDamage { p: f64 },
    CustomBonus { p: f64 },
    ElementalMastery { value: f64 },
    Recharge { p: f64 },
    DEFMinus { p: f64 },
    ResMinus { p: f64 },
    HealingBonus { p: f64 },
    BaseDmg { value: f64 },

    AetherAnemoC6 { has_elemental_absorption: bool, elemental_absorption: Element },
    LumineAnemoC6 { has_elemental_absorption: bool, elemental_absorption: Element },
    AetherDendroP1 { overflowing_lotuslight_count: usize },
    AetherDendroC6 { has_elemental_correspond: bool, elemental_correspond: Element },
    LumineDendroP1 { overflowing_lotuslight_count: usize },
    LumineDendroC6 { has_elemental_correspond: bool, elemental_correspond: Element },
    AetherPyroC1 { nightsouls_blessing: bool },
    AetherPyroC2 { stack: usize },
    LuminePyroC1 { nightsouls_blessing: bool },
    LuminePyroC2 { stack: usize },
    BennettQ { base_atk: f64, c1: bool, skill3: usize },
    SucroseTalent2 { em: f64 },
    SucroseC6 { element: Element },
    MonaQ { c4: bool, skill3: usize },
    VentiC2 { levitating: bool },
    VentiC6 { is_convert: bool, element: Element },
    RosariaTalent2 { crit: f64 },
    EulaE { skill2: usize },
    KaedeharaKazuhaTalent2 { element: Element, em: f64 },
    YoimiyaTalent2 { talent1_stack: usize },
    KujouSaraEOrQ { c6: bool, base_atk: f64, skill2: usize },
    RaidenShogunE { energy: usize, skill2: usize },
    ThomaTalent1 { stack: f64 },
    GorouE1 { skill2: usize },
    GorouC6 { level: usize },
    YunjinQ { talent2: bool, skill3: usize, def: f64, ele_count: usize },
    ShenheE { atk: f64, skill2: usize },
    ShenheQ { skill3: usize },
    ShenheTalent1 { c2: bool },
    ShenheTalent2 { t: usize },
    KamisatoAyatoQ { skill_level: usize },
    YelanTalent2 { secs: usize },
    YelanC4 { count: usize },
    TighnariC4 { after_reaction: bool },
    DoriC4 { hp_below50: bool, energy_below50: bool },
    CandaceTalent2 { hp: f64 },
    NilouTalent2 { hp: f64 },
    NahidaTalent1 { max_em: f64 },
    NahidaC2 { de_def: bool },
    LaylaC4 { hp: f64 },
    FaruzanQ { base_atk: usize, q_level: usize, rate_q1: f64, rate_q2: f64, rate_talent2: f64, enable_c6: bool },
    Mika { stack_talent2: f64, rate_c6: f64 },
    KavehQ { q_level: usize, rate: f64 },
    BaizhuTalent2 { hp: f64, rate: f64 },
    BaizhuC4 { rate: f64 },
    LynetteP1 { el_count: usize },
    FurinaQ { level_q: usize, fanfare: usize, rate: f64 },
    ChevreuseP2 { hp: f64 },
    ChevreuseC6 { stack: f64 },
    XianyunTalent1 { stack: f64 },
    XianyunTalent2 { rate: f64, c2: bool, atk: f64 },
    KachinaC4 { character_count: usize, rate: f64 },
    XilonenE { skill_level: usize, elements: ConfigElements8Multi },
    XilonenC2 { elements: ConfigElements8Multi },
    XilonenC4 { def: f64 },
    OroronC6 { stack: f64 },
    CitlaliTalent1 { has_c2: bool, rate: f64 },
    CitlaliC1 { em: f64 },
    CitlaliC6 { stack: f64 },
    YumemizukiMizukiC1 { em: f64 },
    YumemizukiMizukiC2 { em: f64 },
    IansanQ { nightsoul_point: usize, atk: f64, level_q: usize },
    EscoffierTalent2 { hydro_cryo_count: usize },
    EscoffierC2 { atk: f64 },
    Ifa { re_count: usize },
    Ineffa { atk: f64, has_c1: bool, has_p2: bool },
    AinoC6 { moonsign: Moonsign },
    LaumaE { em: f64, level_e: usize, has_p1: bool, moonsign: Moonsign },
    LaumaQ { em: f64, level_q: usize, has_c2: bool },
    LaumaP3 { em: f64 },
    FlinsP3 { atk: f64 },
    FlinsC6 { moonsign: Moonsign },
    NeferP3 { em: f64 },

    FreedomSworn { refine: usize },
    SongOfBrokenPines { refine: usize },
    WolfsGravestone { refine: usize },
    ThrillingTalesOfDragonSlayers { refine: usize },
    ElegyForTheEnd { refine: usize },
    HakushinRing { refine: usize, element: Element },
    SapwoodBlade { refine: usize, rate: f64 },
    Moonpiercer { refine: usize },
    XiphosMoonlight { refine: usize, em: f64 },
    MakhairaAquamarine { refine: usize, em: f64 },
    KeyOfKhajNisut { refine: usize, hp: f64 },
    AThousandFloatingDreams { refine: usize },
    CranesEchoingCall { refine: usize },
    PeakPatrolSong { refine: usize, rate: f64, def: f64 },
    StarcallersWatch { refine: usize },
    SymphonistOfScents { refine: usize },
    FracturedHalo { refine: usize },
    NightweaversLookingGlass { refine: usize },

    ResonanceCryo2 { rate: f64 },
    ResonanceGeo2 { rate1: f64, rate2: f64 },
    ResonanceDendro2 { rate1: f64, rate2: f64 },
    MoonsignPyro { atk: f64 },
    MoonsignHydro { hp: f64 },
    MoonsignAnemo { em: f64 },
    MoonsignElectro { atk: f64 },
    MoonsignDendro { em: f64 },
    MoonsignCryo { atk: f64 },
    MoonsignGeo { def: f64 },

    ArchaicPetra4 { element: Element },
    ViridescentVenerer4 { element: Element },
    DeepwoodMemories4 { rate: f64 },
    SongOfDaysPast4 { heal_amount: f64 },
    ScrollOfTheHeroOfCinderCity4 { elements: ConfigElements8Multi, nightsouls_blessing: bool },
    NightOfTheSkysUnveiling4 { gleaming_moon_effect_count: usize },
    SilkenMoonsSerenade4 { moonsign: Moonsign, gleaming_moon_effect_count: usize },

    NoConfig,
}
