use serde::{Deserialize, Serialize};

use crate::attribute::Attribute;
use crate::buffs::Buff;
use crate::buffs::buffs::get_buff;
use crate::common::{Element, Moonsign};
use crate::common::item_config_type::ConfigElements8Multi;

#[derive(Serialize, Deserialize)]
pub enum BuffConfig {
    ATKPercentage { p: f64 },
    DEFPercentage { p: f64 },
    HPPercentage { p: f64 },
    ATKFixed { value: f64 },
    DEFFixed { value: f64 },
    HPFixed { value: f64 },
    Critical { p: f64 },
    CriticalDamage { p: f64 },
    CustomBonus { p: f64 },
    ElementalMastery { value: f64 },
    Recharge { p: f64 },
    DEFMinus { p: f64 },
    ResMinus { p: f64 },
    HealingBonus { p: f64 },
    BaseDmg { value: f64 },

    AetherAnemoC6 { has_elemental_absorption: bool, elemental_absorption: Element },
    LumineAnemoC6 { has_elemental_absorption: bool, elemental_absorption: Element },
    AetherDendroP1 { overflowing_lotuslight_count: usize },
    AetherDendroC6 { has_elemental_correspond: bool, elemental_correspond: Element },
    LumineDendroP1 { overflowing_lotuslight_count: usize },
    LumineDendroC6 { has_elemental_correspond: bool, elemental_correspond: Element },
    AetherPyroC1 { nightsouls_blessing: bool },
    AetherPyroC2 { stack: usize },
    LuminePyroC1 { nightsouls_blessing: bool },
    LuminePyroC2 { stack: usize },
    AetherCryoP3 { aether_cryo_atk: f64 },
    AetherCryoC6 { frostglow_stacks: usize },
    LumineCryoP3 { lumine_cryo_atk: f64 },
    LumineCryoC6 { frostglow_stacks: usize },
    BeidouC6 { stellar_glimmer_state: usize },
    FischlP3 { overload: bool, charged: bool, has_c6: bool },
    BennettQ { base_atk: f64, c1: bool, skill3: usize },
    SucroseTalent2 { em: f64 },
    SucroseTalent3 { is_hexerei: bool },
    SucroseC6 { element: Element, is_hexerei: bool },
    QiqiP1 { stellar_glimmer_state: usize },
    QiqiP3 { stellar_glimmer_state: usize },
    QiqiC6 { qiqi_atk: f64 },
    MonaC1 { off_field: bool },
    MonaQ { c4: bool, skill3: usize, is_hexerei: bool },
    MonaTalent3 { hexerei_secret_rite: bool, stack: f64 },
    VentiC6 { elemental_absorption: Option<Element> },
    DionaC6 { hp_above_50: bool, stellar_glimmer_state: usize },
    AlbedoTalent3 { def: f64, is_hexerei: bool },
    AlbedoC4 { silver_isotoma: bool },
    RosariaTalent2 { crit: f64 },
    EulaE { skill2: usize },
    KaedeharaKazuhaTalent2 { element: Element, em: f64 },
    YoimiyaTalent2 { talent1_stack: usize },
    KujouSaraEOrQ { c6: bool, base_atk: f64, skill2: usize },
    RaidenShogunE { energy: usize, skill2: usize },
    ThomaTalent1 { stack: f64 },
    GorouE1 { skill2: usize },
    GorouC6 { level: usize },
    YunjinQ { talent2: bool, skill3: usize, def: f64, ele_count: usize },
    ShenheE { atk: f64, skill2: usize },
    ShenheQ { skill3: usize },
    ShenheTalent1 { c2: bool },
    ShenheTalent2 { t: usize },
    KamisatoAyatoQ { skill_level: usize },
    YelanTalent2 { secs: usize },
    YelanC4 { count: usize },
    TighnariC4 { after_reaction: bool },
    DoriC4 { hp_below50: bool, energy_below50: bool },
    CandaceTalent2 { hp: f64 },
    NilouTalent2 { hp: f64 },
    NahidaTalent1 { max_em: f64 },
    NahidaC2 { de_def: bool },
    LaylaC4 { hp: f64 },
    FaruzanQ { base_atk: usize, q_level: usize, rate_q1: f64, rate_q2: f64, rate_talent2: f64, enable_c6: bool },
    Mika { stack_talent2: f64, rate_c6: f64 },
    KavehQ { q_level: usize, rate: f64 },
    BaizhuTalent2 { hp: f64, rate: f64 },
    BaizhuC4 { rate: f64 },
    LynetteP1 { el_count: usize },
    FurinaQ { level_q: usize, fanfare: usize, rate: f64 },
    ChevreuseP2 { hp: f64 },
    ChevreuseC6 { stack: f64 },
    XianyunTalent1 { stack: f64 },
    XianyunTalent2 { rate: f64, c2: bool, atk: f64 },
    KachinaC4 { character_count: usize, rate: f64 },
    XilonenE { skill_level: usize, elements: ConfigElements8Multi },
    XilonenC2 { elements: ConfigElements8Multi },
    XilonenC4 { def: f64 },
    OroronC6 { stack: f64 },
    CitlaliTalent1 { has_c2: bool, rate: f64 },
    CitlaliC1 { em: f64 },
    CitlaliC6 { stack: f64 },
    YumemizukiMizukiC1 { em: f64 },
    YumemizukiMizukiC2 { em: f64 },
    YumemizukiMizukiP3 { em: f64 },
    IansanQ { nightsoul_point: usize, atk: f64, level_q: usize },
    Ifa { re_count: usize },
    EscoffierTalent2 { hydro_cryo_count: usize },
    EscoffierC2 { atk: f64 },
    Ineffa { atk: f64, has_c1: bool, has_p2: bool },
    LaumaE { level_e: usize },
    LaumaQ { em: f64, level_q: usize, has_c2: bool },
    LaumaP1 { moonsign: Moonsign },
    LaumaP3 { em: f64 },
    LaumaC6 { moonsign: Moonsign },
    AinoC6 { moonsign: Moonsign },
    FlinsP3 { atk: f64 },
    FlinsC6 { moonsign: Moonsign },
    NeferP3 { em: f64 },
    JahodaC6 { moonsign: Moonsign },
    DurinP1 { hexerei_secret_rite: bool, elements: ConfigElements8Multi },
    DurinC1 { atk: f64 },
    DurinC2 { elements: ConfigElements8Multi },
    IllugaQ { em: f64, level_q: usize, hydro_geo_count: usize },
    IllugaP1 { moonsign: Moonsign, has_c6: bool },
    ColumbinaQ { level_q: usize },
    ColumbinaP3 { hp: f64 },
    ColumbinaC2 { moonsign: Moonsign, main_element: Option<Element>, hp: f64 },
    ColumbinaC6 { reacted_element: ConfigElements8Multi },
    ColumbinaC { constellation: usize },
    ZibaiP3 { def: f64 },
    LinneaP1 { moonsign: Moonsign },
    LinneaP2 { def: f64 },
    LinneaP3 { def: f64 },
    LinneaC1 { def: f64, has_c6: bool },
    NicoleE { level_e: usize, atk: f64 },
    NicoleGuidance { has_guidance: bool },
    PruneP2 { atk: f64 },
    NicoleC2 { has_c2: bool, element: Element },
    NicoleC4 { atk: f64 },
    NicoleC6 { },
    LohenP2 { has_buff: bool },
    LohenC2 { has_buff: bool },
    SandroneP3 { sandrone_atk: f64 },
    AlyoshaE { hunters_precision_stacks: usize, skill_e_level: usize },
    AlyoshaP3 {},
    AlyoshaC6 {},
    OdetteP1 { marvelous_splendor_other: f64 },
    OdetteP3 { odette_atk: f64 },
    OdetteC2 { marvelous_splendor_other: f64 },
    OdetteC4 { level_q: usize },
    OdetteC6 {},

    FreedomSworn { refine: usize },
    SongOfBrokenPines { refine: usize },
    WolfsGravestone { refine: usize },
    ThrillingTalesOfDragonSlayers { refine: usize },
    ElegyForTheEnd { refine: usize },
    HakushinRing { refine: usize, element: Element },
    SapwoodBlade { refine: usize, rate: f64 },
    Moonpiercer { refine: usize },
    XiphosMoonlight { refine: usize, em: f64 },
    MakhairaAquamarine { refine: usize, em: f64 },
    KeyOfKhajNisut { refine: usize, hp: f64 },
    AThousandFloatingDreams { refine: usize },
    CranesEchoingCall { refine: usize },
    PeakPatrolSong { refine: usize, rate: f64, def: f64 },
    StarcallersWatch { refine: usize },
    SymphonistOfScents { refine: usize },
    FracturedHalo { refine: usize },
    NightweaversLookingGlass { refine: usize },
    AthameArtis { refine: usize, hexerei_secret_rite: bool },
    GoldenFrostboundOath { refine: usize, rate: f64 },
    AngelosHeptades { refine: usize, atk: f64, hexerei_secret_rite: bool, off_field_hexerei: bool },

    ResonancePyro2 { global: bool },
    ResonanceCryo2 { rate: f64, global: bool },
    ResonanceGeo2 { rate1: f64, rate2: f64, global: bool },
    ResonanceHydro2 { global: bool },
    ResonanceDendro2 { rate1: f64, rate2: f64, global: bool },
    MoonsignPyro { atk: f64, global: bool },
    MoonsignHydro { hp: f64, global: bool },
    MoonsignAnemo { em: f64, global: bool },
    MoonsignElectro { atk: f64, global: bool },
    MoonsignDendro { em: f64, global: bool },
    MoonsignCryo { atk: f64, global: bool },
    MoonsignGeo { def: f64, global: bool },

    ArchaicPetra4 { element: Element },
    ViridescentVenerer4 { element: Element },
    DeepwoodMemories4 { rate: f64 },
    SongOfDaysPast4 { heal_amount: f64 },
    ScrollOfTheHeroOfCinderCity4 { elements: ConfigElements8Multi, nightsouls_blessing: bool },
    NightOfTheSkysUnveiling4 { gleaming_moon_effect_count: usize },
    SilkenMoonsSerenade4 { moonsign: Moonsign, gleaming_moon_effect_count: usize },
    CelestialGift4 { hexerei_secret_rite: bool, equip_element: Element, active_element: Element },

    NoConfig,
}
