// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::buffs::buffs::prelude::*;

pub struct BuffAngelosHeptades {
    pub refine: usize,
    pub atk: f64,
    pub hexerei_secret_rite: bool,
    pub off_field_hexerei: bool,
}

impl<A: Attribute> Buff<A> for BuffAngelosHeptades {
    fn change_attribute(&self, attribute: &mut A) {
        let refine = self.refine as f64;

        // 先导之光：每1000点攻击力提升造成的伤害
        // ratio = 0.07 + refine * 0.03, cap = 0.18 + refine * 0.08
        let pathfinder_ratio = 0.07 + refine * 0.03;
        let pathfinder_cap = 0.18 + refine * 0.08;

        let mut bonus = ((self.atk / 1000.0) * pathfinder_ratio).min(pathfinder_cap);

        // 魔导·秘仪：后台魔导角色获得先导之光50%的伤害提升效果
        if self.hexerei_secret_rite && self.off_field_hexerei {
            bonus *= 0.5;
        }

        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_any(
                AttributeVariableType::Bonus,
            )),
            "尘光七谕被动",
            bonus,
        );
    }
}

impl BuffMeta for BuffAngelosHeptades {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::AngelosHeptades,
        name_locale: locale!(
            zh_cn: "尘光七谕-「末临者的华冠」",
            en: "Angelos' Heptades-Crown of the Final Scion"
        ),
        image: BuffImage::Weapon(WeaponName::AngelosHeptades),
        genre: BuffGenre::Weapon,
        description: Some(locale!(
            zh_cn: "装备者创造护盾后的20秒内，获得「先导之光」效果：依据装备者的攻击力，每1000点攻击力都会使队伍中自己的当前场上角色造成的伤害提升<span style=\"color: #409EFF;\">10%-13%-16%-19%-22%</span>，至多提升<span style=\"color: #409EFF;\">26%-34%-42%-50%-58%</span>。装备者处于队伍后台时依然能触发上述效果。<br>魔导·秘仪：队伍中自己的魔导角色位于队伍后台时，也能获得「先导之光」中50%的伤害提升效果。",
            en: "After the equipping character creates a Shield, they gain \"Pathfinder's Light\" for 20s: Increases your active party member's DMG by <span style=\"color: #409EFF;\">10%-13%-16%-19%-22%</span> for every 1,000 ATK, up to a maximum of <span style=\"color: #409EFF;\">26%-34%-42%-50%-58%</span>. The equipping character may trigger this effect even when off-field.<br>Hexerei: Secret Rite: When there are off-field Hexerei characters in your party, they will also gain 50% of the DMG increase from Pathfinder's Light."
        )),
        from: BuffFrom::Weapon(WeaponName::AngelosHeptades),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::REFINE,
        ItemConfig {
            name: "atk",
            title: locale!(
                zh_cn: "装备者攻击力",
                en: "Equipping Character's ATK"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
        ItemConfig {
            name: "hexerei_secret_rite",
            title: locale!(
                zh_cn: "魔导·秘仪",
                en: "Hexerei: Secret Rite"
            ),
            config: ItemConfigType::Bool { default: false }
        },
        ItemConfig {
            name: "off_field_hexerei",
            title: locale!(
                zh_cn: "当前角色为后台魔导角色",
                en: "Current character is off-field Hexerei"
            ),
            config: ItemConfigType::Bool { default: false }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (refine, atk, hexerei_secret_rite, off_field_hexerei) = match *b {
            BuffConfig::AngelosHeptades { refine, atk, hexerei_secret_rite, off_field_hexerei } => (refine, atk, hexerei_secret_rite, off_field_hexerei),
            _ => (1, 0.0, false, false)
        };
        Box::new(BuffAngelosHeptades { refine, atk, hexerei_secret_rite, off_field_hexerei })
    }
}
