use std::string::ToString;
use strum_macros::{Display, EnumIter};
use num_derive::FromPrimitive;
use serde::{Serialize, Deserialize};
use mona_derive::{WeaponData, EnumLen};
use crate::weapon::weapon_trait::WeaponTrait;
use crate::weapon::weapon_static_data::WeaponStaticData;
use crate::common::item_config_type::ItemConfig;

#[derive(Serialize, Deserialize)]
#[derive(Debug, Eq, PartialEq, Hash, Copy, Clone)]
#[derive(FromPrimitive, Display)]
#[derive(WeaponData, EnumLen, EnumIter)]
pub enum WeaponName {
    // sword
    // 1 star
    DullBlade,
    // 2 star
    SilverSword,
    // 3 star
    CoolSteel,
    HarbingerOfDawn,
    TravelersHandySword,
    DarkIronSword,
    FilletBlade,
    SkyriderSword,
    // 4 star
    FavoniusSword,
    TheFlute,
    SacrificialSword,
    RoyalLongsword,
    LionsRoar,
    PrototypeRancour,
    IronSting,
    BlackcliffLongsword,
    TheBlackSword,
    TheAlleyFlash,
    SwordOfDescension,
    FesteringDesire,
    AmenomaKageuchi,
    CinnabarSpindle,
    KagotsurubeIsshin,
    SapwoodBlade,
    XiphosMoonlight,
    ToukabouShigure,
    WolfFang,
    FinaleOfTheDeep,
    FleuveCendreFerryman,
    TheDockhandsAssistant,
    SwordOfNarzissenkreuz,
    SturdyBone,
    FluteOfEzpitzal,
    CalamityOfEshu,
    // 5 star
    AquilaFavonia,
    SkywardBlade,
    FreedomSworn,
    SummitShaper,
    PrimordialJadeCutter,
    MistsplitterReforged,
    HaranGeppakuFutsu,
    KeyOfKhajNisut,
    LightOfFoliarIncision,
    SplendorOfTranquilWaters,
    UrakuMisugiri,
    Absolution,
    PeakPatrolSong,
    Azurelight,

    // claymore
    // 1 star
    WasterGreatsword,
    // 2 star
    OldMercsPal,
    // 3 star
    FerrousShadow,
    BloodstainedGreatsword,
    WhiteIronGreatsword,
    DebateClub,
    SkyriderGreatsword,
    // 4 star
    FavoniusGreatsword,
    TheBell,
    SacrificialGreatsword,
    RoyalGreatsword,
    Rainslasher,
    PrototypeArchaic,
    Whiteblind,
    BlackcliffSlasher,
    SerpentSpine,
    LithicBlade,
    SnowTombedStarsilver,
    LuxuriousSeaLord,
    KatsuragikiriNagamasa,
    MakhairaAquamarine,
    Akuoumaru,
    ForestRegalia,
    MailedFlower,
    TalkingStick,
    TidalShadow,
    UltimateOverlordsMegaMagicSword,
    PortablePowerSaw,
    FruitfulHook,
    EarthShaker,
    // 5 star
    SkywardPride,
    WolfsGravestone,
    SongOfBrokenPines,
    TheUnforged,
    RedhornStonethresher,
    BeaconOfTheReedSea,
    Verdict,
    FangOfTheMountainKing,
    AThousandBlazingSuns,

    // polearm
    // 1 star
    BeginnersProtector,
    // 2 star
    IronPoint,
    // 3 star
    WhiteTassel,
    Halberd,
    BlackTassel,
    // 4 star
    DragonsBane,
    PrototypeStarglitter,
    CrescentPike,
    BlackcliffPole,
    Deathmatch,
    LithicSpear,
    FavoniusLance,
    RoyalSpear,
    DragonspineSpear,
    KitainCrossSpear,
    TheCatch,
    WavebreakersFin,
    Moonpiercer,
    MissiveWindspear,
    BalladOfTheFjords,
    RightfulReward,
    DialoguesOfTheDesertSages,
    ProspectorsDrill,
    MountainBracingBolt,
    FootprintOfTheRainbow,
    TamayurateiNoOhanashi,
    // 5 star
    StaffOfHoma,
    SkywardSpine,
    VortexVanquisher,
    PrimordialJadeWingedSpear,
    CalamityQueller,
    EngulfingLightning,
    StaffOfTheScarletSands,
    CrimsonMoonsSemblance,
    LumidouceElegy,
    SymphonistOfScents,

    // catalyst
    // 1 star
    ApprenticesNotes,
    // 2 star
    PocketGrimoire,
    // 3 star
    MagicGuide,
    ThrillingTalesOfDragonSlayers,
    OtherworldlyStory,
    EmeraldOrb,
    TwinNephrite,
    // 4 star
    FavoniusCodex,
    TheWidsith,
    SacrificialFragments,
    RoyalGrimoire,
    SolarPearl,
    PrototypeAmber,
    MappaMare,
    BlackcliffAgate,
    EyeOfPerception,
    WindAndSong,
    Frostbearer,
    DodocoTales,
    HakushinRing,
    OathswornEye,
    WanderingEvenstar,
    FruitOfFulfillment,
    SacrificialJade,
    FlowingPurity,
    BalladOfTheBoundlessBlue,
    AshGravenDrinkingHorn,
    WaveridingWhirl,
    RingOfYaxche,
    // 5 star
    SkywardAtlas,
    LostPrayerToTheSacredWinds,
    MemoryOfDust,
    JadefallsSplendor,
    EverlastingMoonglow,
    KagurasVerity,
    AThousandFloatingDreams,
    TulaytullahsRemembrance,
    CashflowSupervision,
    TomeOfTheEternalFlow,
    CranesEchoingCall,
    SurfsUp,
    StarcallersWatch,
    SunnyMorningSleepIn,
    VividNotions,

    // bows
    // 1 star
    HuntersBow,
    // 2 star
    SeasonedHuntersBow,
    // 3 star
    RavenBow,
    SharpshootersOath,
    RecurveBow,
    Slingshot,
    Messenger,
    // 4 star
    FavoniusWarbow,
    TheStringless,
    SacrificialBow,
    RoyalBow,
    Rust,
    PrototypeCrescent,
    CompoundBow,
    BlackcliffWarbow,
    TheViridescentHunt,
    AlleyHunter,
    FadingTwilight,
    MitternachtsWaltz,
    WindblumeOde,
    Hamayumi,
    Predator,
    MouunsMoon,
    KingsSquire,
    EndOfTheLine,
    IbisPiercer,
    ScionOfTheBlazingSun,
    SongOfStillness,
    Cloudforged,
    RangeGauge,
    FlowerWreathedFeathers,
    ChainBreaker,
    SequenceOfSolitude,
    // 5 star
    SkywardHarp,
    AmosBow,
    ElegyForTheEnd,
    PolarStar,
    AquaSimulacra,
    ThunderingPulse,
    HuntersPath,
    TheFirstGreatMagic,
    SilvershowerHeartstrings,
    AstralVulturesCrimsonPlumage,
}