// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::artifacts::effects::prelude::*;

pub struct CelestialGiftEffect {
    pub hexerei_secret_rite: bool,
}

impl<A: Attribute> ArtifactEffect<A> for CelestialGiftEffect {
    fn effect2(&self, attribute: &mut A) {
        attribute.set_value_by(AttributeName::Recharge, "天之美赐2", 0.2);
    }

    fn effect4(&self, attribute: &mut A) {
        // Check if equipping character has completed Witch's Homework (Hexerei tag)
        if !attribute.get_character().tags.contains(&CharacterTag::Hexerei) {
            return;
        }

        let equip_bonus = AttributeName::bonus_name_by_element(attribute.get_character().character_static_data.element);

        // Find active (on-field) character's element from the team
        let active_element = attribute.get_characters_by_selector(
            CharacterSelector::select_onfield(attribute)
        ).first().map(|c| c.character_static_data.element);

        if self.hexerei_secret_rite {
            // Mortal Hymn (凡世颂歌): 40% for equip element + 40% for active element
            attribute.set_value_by_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(equip_bonus),
                "天之美赐4",
                0.40,
            );

            if let Some(active_el) = active_element {
                if attribute.get_character().character_static_data.element != active_el {
                    let active_bonus = AttributeName::bonus_name_by_element(active_el);
                    attribute.set_value_by_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Panel(active_bonus),
                        "天之美赐4",
                        0.40,
                    );
                }
            }
        } else {
            // Light's Guidance (天光之引): 20% for equip element
            attribute.set_value_by_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(equip_bonus),
                "天之美赐4",
                0.20,
            );
        }
    }
}

pub struct CelestialGift;

impl ArtifactTrait for CelestialGift {
    fn create_effect<A: Attribute>(config: &ArtifactEffectConfig, character_common_data: &CharacterCommonData) -> Box<dyn ArtifactEffect<A>> {
        Box::new(CelestialGiftEffect {
            hexerei_secret_rite: config.config_celestial_gift.hexerei_secret_rite,
        })
    }

    #[cfg(not(target_family = "wasm"))]
    const META_DATA: ArtifactMetaData = ArtifactMetaData {
        name: ArtifactSetName::CelestialGift,
        name_mona: "CelestialGift",
        name_locale: locale!(zh_cn: "天之美赐", en: "Celestial Gift"),
        flower: Some(locale!(zh_cn: "天授之馨", en: "Heavensent Fragrance")),
        feather: Some(locale!(zh_cn: "天授之殁", en: "Heavensent Demise")),
        sand: Some(locale!(zh_cn: "天授之令", en: "Heavensent Decree")),
        goblet: Some(locale!(zh_cn: "天授之禄", en: "Heavensent Reward")),
        head: Some(locale!(zh_cn: "天授之冕", en: "Heavensent Crown")),
        star: (4, 5),
        effect1: None,
        effect2: Some(locale!(
            zh_cn: "元素充能效率提高20%。",
            en: "Energy Recharge +20%."
        )),
        effect3: None,
        effect4: Some(locale!(
            zh_cn: "若装备者已经完成了魔女的课业，则施放元素战技后，会获得「天光之引」效果：依据装备者的元素类型，使队伍中附近的所有角色获得20%对应元素伤害加成，持续20秒。装备者处于后台时也能触发上述效果，同名圣遗物套装产生的伤害加成效果无法叠加。\n·队伍拥有「魔导·秘仪」效果时，「天光之引」效果将会升级为「凡世颂歌」，除装备者的元素类型外，还会依据队伍中自己的当前场上角色的元素类型，使队伍中附近的所有角色获得对应元素伤害加成，且上述两种元素伤害加成提升至40%，同元素类型的元素伤害加成效果无法叠加。",
            en: "If the equipping character has completed Witch's Homework, after they use an Elemental Skill, they also gain \"Light's Guidance\" for 20s: All nearby party members gain a 20% Elemental DMG Bonus corresponding to the equipping character's Elemental Type. The equipping character can trigger this effect while off-field. DMG Bonuses provided by Artifact Sets with the same name do not stack.\n· When your party has the Hexerei: Secret Rite effect, Light's Guidance is upgraded to \"Mortal Hymn\": All nearby party members gain a 40% Elemental DMG Bonus corresponding to both the equipping character and the current active party member's Elemental Type instead. If both characters have the same Elemental Type, these bonuses will not stack."
        )),
        effect5: None,
        internal_id: 15045
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG4: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::HEXEREI_SECRET_RITE_GLOBAL(false, ItemConfig::PRIORITY_ARTIFACT),
    ]);
}
