// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::artifacts::effects::prelude::*;

pub struct DisenchantmentInDeepShadowEffect {}

impl<A: Attribute> ArtifactEffect<A> for DisenchantmentInDeepShadowEffect {
    fn effect2(&self, attribute: &mut A) {
        attribute.add_atk_percentage("影中沉凝的幻灭2", 0.18);
    }

    fn effect4(&self, attribute: &mut A) {
        // 超导反应造成的伤害提升80%
        attribute.set_value_by_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::Superconduct,
            )),
            "影中沉凝的幻灭4",
            0.8,
        );

        // 装备者攻击受到超导反应影响的敌人时，本次攻击的暴击率提高16%
        // 注：在超导队伍中该条件可视为常驻
        attribute.set_value_by_t(
            AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::CriticalRate)),
            "影中沉凝的幻灭4",
            0.16,
        );
    }
}

pub struct DisenchantmentInDeepShadow;

impl ArtifactTrait for DisenchantmentInDeepShadow {
    fn create_effect<A: Attribute>(
        config: &ArtifactEffectConfig,
        character_common_data: &CharacterCommonData,
    ) -> Box<dyn ArtifactEffect<A>> {
        let _ = character_common_data;
        let _ = config;

        Box::new(DisenchantmentInDeepShadowEffect {})
    }

    #[cfg(not(target_family = "wasm"))]
    const META_DATA: ArtifactMetaData = ArtifactMetaData {
        name: ArtifactSetName::DisenchantmentInDeepShadow,
        name_mona: "DisenchantmentInDeepShadow",
        name_locale: locale!(
            zh_cn: "影中沉凝的幻灭",
            en: "Disenchantment in Deep Shadow"
        ),
        flower: Some(locale!(
            zh_cn: "止于荣礼的缎彩",
            en: "Iridescence That Ceased Amidst Glory"
        )),
        feather: Some(locale!(
            zh_cn: "止于妙想成型的锋毫",
            en: "Sharpness That Ceased Upon Wondrous Creation"
        )),
        sand: Some(locale!(
            zh_cn: "止于宏伟梦醒的时刻",
            en: "Moment That Ceased Upon Waking From Grand Dreams"
        )),
        goblet: Some(locale!(
            zh_cn: "止于祝庆的喝礼",
            en: "Ovations That Ceased Upon Festivity"
        )),
        head: Some(locale!(
            zh_cn: "止于阔步跌坠的灵摆",
            en: "Pendulum That Ceased Amidst a Great Fall"
        )),
        star: (4, 5),
        effect1: None,
        effect2: Some(locale!(
            zh_cn: "攻击力提高18%。",
            en: "ATK +18%."
        )),
        effect3: None,
        effect4: Some(locale!(
            zh_cn: "超导反应造成的伤害提升80%；装备者攻击受到超导反应影响的敌人时，本次攻击的暴击率提高16%。前往至冬的途中，或许还会得到全新的祝赐…",
            en: "Increases Superconduct Reaction DMG by 80%. When the wielder attacks opponents affected by Superconduct, this attack's CRIT Rate is increased by 16%. An all-new blessing may be obtained as you make your way toward Snezhnaya…"
        )),
        effect5: None,
        internal_id: 15046,
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG4: Option<&'static [ItemConfig]> = None;
}
