// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::artifacts::effects::prelude::*;

pub struct HeartOfTheFurnaceEffect {
    pub set4_rate: f64,
}

impl<A: Attribute> ArtifactEffect<A> for HeartOfTheFurnaceEffect {
    fn effect2(&self, attribute: &mut A) {
        attribute.add_atk_percentage("炉火融炼之心2", 0.18);
    }

    fn effect4(&self, attribute: &mut A) {
        // 装备者触发星烁反应或造成星烁反应伤害后的12秒内，攻击力提升12%（后台也可触发）。
        // 该效果为限时触发型（12秒），此处以「四件套被动比例」set4_rate（0~1，默认1.0）近似覆盖率。
        attribute.add_atk_percentage("炉火融炼之心4", 0.12 * self.set4_rate);

        // 队伍中附近的所有角色造成的星烁反应伤害提升50%，同名圣遗物套装产生的伤害加成效果无法叠加。
        // 同样以 set4_rate 近似覆盖率。
        for reaction in [ReactionType::StellarConduct, ReactionType::StellarSwirl] {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    reaction,
                )),
                "炉火融炼之心4",
                0.50 * self.set4_rate,
            );
        }
    }
}

pub struct HeartOfTheFurnace;

impl ArtifactTrait for HeartOfTheFurnace {
    fn create_effect<A: Attribute>(config: &ArtifactEffectConfig, _character_common_data: &CharacterCommonData) -> Box<dyn ArtifactEffect<A>> {
        Box::new(HeartOfTheFurnaceEffect {
            set4_rate: config.config_heart_of_the_furnace.set4_rate,
        })
    }

    #[cfg(not(target_family = "wasm"))]
    const META_DATA: ArtifactMetaData = ArtifactMetaData {
        name: ArtifactSetName::HeartOfTheFurnace,
        name_mona: "HeartOfTheFurnace",
        name_locale: locale!(zh_cn: "炉火融炼之心", en: "Heart of the Furnace"),
        flower: Some(locale!(zh_cn: "熔铸者的揣度", en: "Foundryman's Conjecture")),
        feather: Some(locale!(zh_cn: "熔铸者的观测", en: "Foundryman's Observation")),
        sand: Some(locale!(zh_cn: "熔铸者的计算", en: "Foundryman's Calculus")),
        goblet: Some(locale!(zh_cn: "熔铸者的雅量", en: "Foundryman's Magnanimity")),
        head: Some(locale!(zh_cn: "熔铸者的继志", en: "Foundryman's Legacy")),
        star: (4, 5),
        effect1: None,
        effect2: Some(locale!(
            zh_cn: "攻击力提高18%。",
            en: "ATK +18%."
        )),
        effect3: None,
        effect4: Some(locale!(
            zh_cn: "装备者触发星烁反应或造成星烁反应伤害后的12秒内，攻击力提升12%，队伍中附近的所有角色造成的星烁反应伤害提升50%。装备者处于后台时也能触发上述效果。同名圣遗物套装产生的伤害加成效果无法叠加。",
            en: "Increases the equipping character's ATK by 12% for 12s when they trigger a Stellar Glimmer reaction or deal Stellar Glimmer reaction DMG. Also increases Stellar Glimmer reaction DMG dealt by all nearby party members by 50%. The above effects can trigger even when the equipping character is not on the field, and the DMG bonus from multiple Artifact Sets with the same name do not stack."
        )),
        effect5: None,
        internal_id: 15048,
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG4: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "set4_rate",
            title: locale!(
                zh_cn: "四件套被动比例",
                en: "4-Set Ratio",
            ),
            config: ItemConfigType::GlobalLinkFloat {
                min: 0.0,
                max: 1.0,
                default: 1.0,
                global_link: GlobalLinkConfig {
                    key: "[heart_of_the_furnace]set4_rate",
                    priority: ItemConfig::PRIORITY_ARTIFACT,
                    team_shared: false,
                },
            },
        },
    ]);
}
