// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::artifacts::effects::prelude::*;

pub struct ScarletProofEffect {
    pub set4_rate: f64,
}

impl<A: Attribute> ArtifactEffect<A> for ScarletProofEffect {
    fn effect2(&self, attribute: &mut A) {
        attribute.add_atk_percentage("血红之证2", 0.18);
    }

    fn effect4(&self, attribute: &mut A) {
        // 装备者触发星扩散反应后的10秒内，暴击率提升16%，星扩散反应伤害提升40%。
        // 该效果为限时触发型（10秒），此处以「四件套被动比例」set4_rate（0~1，默认1.0）近似覆盖率。
        attribute.set_value_to(AttributeName::CriticalBase, "血红之证4", 0.16 * self.set4_rate);
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarSwirl,
            )),
            "血红之证4",
            0.40 * self.set4_rate,
        );
    }
}

pub struct ScarletProof;

impl ArtifactTrait for ScarletProof {
    fn create_effect<A: Attribute>(config: &ArtifactEffectConfig, _character_common_data: &CharacterCommonData) -> Box<dyn ArtifactEffect<A>> {
        Box::new(ScarletProofEffect {
            set4_rate: config.config_scarlet_proof.set4_rate,
        })
    }

    #[cfg(not(target_family = "wasm"))]
    const META_DATA: ArtifactMetaData = ArtifactMetaData {
        name: ArtifactSetName::ScarletProof,
        name_mona: "ScarletProof",
        name_locale: locale!(zh_cn: "血红之证", en: "Scarlet Proof"),
        flower: Some(locale!(zh_cn: "感谢你的奉献", en: "Honor to Your Devotion")),
        feather: Some(locale!(zh_cn: "铭记你的功勋", en: "Glory to Your Legacy")),
        sand: Some(locale!(zh_cn: "授予你的年华", en: "Time Gifted Unto You")),
        goblet: Some(locale!(zh_cn: "饮尽你的血泪", en: "Chalice of Your Blood and Sorrow")),
        head: Some(locale!(zh_cn: "缅怀你的信仰", en: "Testament to Your Faith")),
        star: (4, 5),
        effect1: None,
        effect2: Some(locale!(
            zh_cn: "攻击力提高18%。",
            en: "ATK +18%."
        )),
        effect3: None,
        effect4: Some(locale!(
            zh_cn: "装备者触发星扩散反应后的10秒内，暴击率提升16%，星扩散反应伤害提升40%。",
            en: "Increases the equipping character's CRIT Rate by 16%, and their Stellar Swirl reaction dealt by 40%, for 10s after they trigger a Stellar Swirl reaction."
        )),
        effect5: None,
        internal_id: 15047,
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG4: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "set4_rate",
            title: locale!(
                zh_cn: "四件套被动比例",
                en: "4-Set Ratio",
            ),
            config: ItemConfigType::GlobalLinkFloat {
                min: 0.0,
                max: 1.0,
                default: 1.0,
                global_link: GlobalLinkConfig {
                    key: "[scarlet_proof]set4_rate",
                    priority: ItemConfig::PRIORITY_ARTIFACT,
                    team_shared: false,
                },
            },
        },
    ]);
}
