// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::character::characters::prelude::*;

pub struct VodyanitsaSkillType {
    // Normal Attack: 水色咏叹 (Psyshkhwe Arietta)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15], // 下坠期间伤害
    pub x_dmg2: [f64; 15], // 低空坠地冲击伤害
    pub x_dmg3: [f64; 15], // 高空坠地冲击伤害

    // Elemental Skill: 宣叙·晨声纷流 (Rechitativ: Sonorous Dawn)
    pub e_dmg: [f64; 15],        // 技能伤害（生命值上限倍率）
    pub e_horn_dmg: [f64; 15],   // 唤春角笛伤害（生命值上限倍率）
    pub e_heal: [f64; 15],       // 遥久之歌治疗量（生命值上限倍率）
    pub e_heal_fixed: [f64; 15], // 遥久之歌治疗量（固定值）
    pub e_res_minus: [f64; 15],  // 水元素/冰元素抗性降低

    // Elemental Burst: 终奏·伴尔沉沦 (Sink With Thee)
    pub q_dmg: [f64; 15],     // 技能伤害（生命值上限倍率）
    pub q_enhance: [f64; 15], // 遥久之歌状态下造成的伤害进一步提升

    // P1: 最后的塑诗者
    pub p1_res_minus: f64, // 创造/引爆「流荡风旋」时附近敌人的风元素抗性降低

    // P2: 十二弦的泪歌 — 「领唱」/「重唱」
    pub p2_hp_threshold: f64,        // 提升值计算的生命值上限基准
    pub p2_ss_per_1000: f64,         // 每 1000 点超出生命值上限提升星扩散反应伤害
    pub p2_hydro_cryo_per_1000: f64, // 每 1000 点超出生命值上限提升水/冰元素伤害
    pub p2_ss_max: f64,              // 星扩散反应伤害提升上限
    pub p2_hydro_cryo_max: f64,      // 水/冰元素伤害提升上限

    // C1: 聚光灯下的水华
    pub c1_atk_per_hp: f64, // 攻击力提升值相当于生命值上限的比例

    // C2: 穿彻风雪的余响
    pub c2_hydro_cryo_crit_dmg: f64, // 水/冰元素伤害暴击伤害提升
    pub c2_ss_crit_dmg: f64,         // 星扩散反应伤害暴击伤害提升

    // C4: 柔波摇漾的低诉
    pub c4_heal_bonus: f64,   // 受治疗角色生命值低于 40% 时本次治疗量提升
    pub c4_hp_per_stack: f64, // 每层生命值上限提升
    pub c4_max_stacks: f64,   // 生命值上限提升效果的最大层数

    // C6: 永不落幕的盛歌
    pub c6_elevate: f64,          // 星扩散反应伤害擢升
    pub c6_hydro_cryo_bonus: f64, // 水/冰元素伤害提升
}

pub const VODYANITSA_SKILL: VodyanitsaSkillType = VodyanitsaSkillType {
    // Normal Attack: 水色咏叹
    a_dmg1: [0.4338, 0.4664, 0.4989, 0.5423, 0.5748, 0.6074, 0.6508, 0.6942, 0.7375, 0.7809, 0.8243, 0.8677, 0.9219, 0.9762, 1.0304],
    a_dmg2: [0.4023, 0.4325, 0.4627, 0.5029, 0.5331, 0.5632, 0.6035, 0.6437, 0.6839, 0.7242, 0.7644, 0.8046, 0.8549, 0.9052, 0.9555],
    a_dmg3: [0.493, 0.53, 0.567, 0.6163, 0.6532, 0.6902, 0.7395, 0.7888, 0.8381, 0.8874, 0.9367, 0.986, 1.0477, 1.1093, 1.1709],
    a_dmg4: [0.6556, 0.7048, 0.754, 0.8195, 0.8687, 0.9179, 0.9834, 1.049, 1.1146, 1.1801, 1.2457, 1.3113, 1.3932, 1.4752, 1.5571],
    z_dmg: [1.2376, 1.3304, 1.4232, 1.547, 1.6398, 1.7326, 1.8564, 1.9802, 2.1039, 2.2277, 2.3514, 2.4752, 2.6299, 2.7846, 2.9393],
    x_dmg1: [0.5683, 0.6145, 0.6608, 0.7269, 0.7731, 0.826, 0.8987, 0.9714, 1.0441, 1.1234, 1.2027, 1.282, 1.3612, 1.4405, 1.5198],
    x_dmg2: [1.1363, 1.2288, 1.3213, 1.4535, 1.5459, 1.6516, 1.797, 1.9423, 2.0877, 2.2462, 2.4048, 2.5634, 2.7219, 2.8805, 3.039],
    x_dmg3: [1.4193, 1.5349, 1.6504, 1.8154, 1.931, 2.063, 2.2445, 2.4261, 2.6076, 2.8057, 3.0037, 3.2018, 3.3998, 3.5979, 3.7959],

    // Elemental Skill: 宣叙·晨声纷流
    e_dmg: [0.0327, 0.0352, 0.0376, 0.0409, 0.0434, 0.0458, 0.0491, 0.0524, 0.0556, 0.0589, 0.0622, 0.0654, 0.0695, 0.0736, 0.0777],
    e_horn_dmg: [0.0327, 0.0352, 0.0376, 0.0409, 0.0434, 0.0458, 0.0491, 0.0524, 0.0556, 0.0589, 0.0622, 0.0654, 0.0695, 0.0736, 0.0777],
    e_heal: [0.028, 0.0301, 0.0322, 0.035, 0.0371, 0.0392, 0.042, 0.0448, 0.0476, 0.0504, 0.0532, 0.056, 0.0595, 0.063, 0.0665],
    e_heal_fixed: [270.0, 297.0, 326.0, 357.0, 391.0, 427.0, 465.0, 506.0, 548.0, 593.0, 640.0, 690.0, 742.0, 795.0, 852.0],
    e_res_minus: [0.165, 0.18, 0.195, 0.21, 0.225, 0.24, 0.255, 0.27, 0.285, 0.30, 0.318, 0.336, 0.354, 0.372, 0.39],

    // Elemental Burst: 终奏·伴尔沉沦
    q_dmg: [0.4568, 0.491, 0.5253, 0.571, 0.6052, 0.6395, 0.6852, 0.7308, 0.7765, 0.8222, 0.8679, 0.9135, 0.9706, 1.0277, 1.0848],
    q_enhance: [0.48, 0.516, 0.552, 0.6, 0.636, 0.672, 0.72, 0.768, 0.816, 0.864, 0.912, 0.96, 1.02, 1.08, 1.14],

    // P1: 最后的塑诗者
    p1_res_minus: 0.35,

    // P2: 十二弦的泪歌
    p2_hp_threshold: 40000.0,
    p2_ss_per_1000: 260.0,
    p2_hydro_cryo_per_1000: 140.0,
    p2_ss_max: 6500.0,
    p2_hydro_cryo_max: 3500.0,

    // C1: 聚光灯下的水华
    c1_atk_per_hp: 0.008,

    // C2: 穿彻风雪的余响
    c2_hydro_cryo_crit_dmg: 0.5,
    c2_ss_crit_dmg: 0.6,

    // C4: 柔波摇漾的低诉
    c4_heal_bonus: 0.5,
    c4_hp_per_stack: 0.2,
    c4_max_stacks: 3.0,

    // C6: 永不落幕的盛歌
    c6_elevate: 0.25,
    c6_hydro_cryo_bonus: 0.6,
};

pub const VODYANITSA_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Vodyanitsa,
    internal_name: "Vodyanitsa",
    name_locale: locale!(
        zh_cn: "沃雅妮莎",
        en: "Vodyanitsa",
    ),
    element: Element::Hydro,
    hp: [1154, 2992, 3981, 5957, 6660, 7662, 8599, 9612, 10315, 11337, 12040, 13073, 13776, 14818, 15871],
    atk: [8, 22, 29, 43, 48, 56, 62, 70, 75, 82, 87, 95, 100, 108, 132],
    def: [38, 98, 130, 195, 218, 250, 281, 314, 337, 370, 393, 427, 450, 484, 519],
    sub_stat: CharacterSubStatFamily::HP288,
    weapon_type: WeaponType::Catalyst,
    star: 5,
    skill_name1: locale!(
        zh_cn: "水色咏叹",
        en: "Psyshkhwe Arietta",
    ),
    skill_name2: locale!(
        zh_cn: "宣叙·晨声纷流",
        en: "Rechitativ: Sonorous Dawn",
    ),
    skill_name3: locale!(
        zh_cn: "终奏·伴尔沉沦",
        en: "Sink With Thee",
    ),
};

pub struct VodyanitsaEffect {
    pub stellar_glimmer_state: StellarGlimmerState,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for VodyanitsaEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // 沃雅妮莎的战斗效果均依赖「遥久之歌」（元素战技）或「流荡风旋」等实时状态，
        // 且大部分效果作用于队伍中的其他角色，统一在 CharacterTrait::change_attribute
        // （CONFIG_SKILL）中根据 in_song_of_ages_past 等配置施加。
        let _ = self.stellar_glimmer_state;
    }
}

damage_enum!(
    VodyanitsaDamageEnum
    A1       // 一段伤害
    A2       // 二段伤害
    A3       // 三段伤害
    A4       // 四段伤害
    Z        // 重击伤害
    X1       // 下坠期间伤害
    X2       // 低空坠地冲击伤害
    X3       // 高空坠地冲击伤害
    E        // 元素战技伤害
    E_HORN   // 唤春角笛伤害
    E_HEAL   // 遥久之歌治疗量
    Q        // 元素爆发伤害
);

impl VodyanitsaDamageEnum {
    pub fn get_element(&self) -> Element {
        use VodyanitsaDamageEnum::*;
        match *self {
            // 治疗量无明确元素类型
            E_HEAL => Element::Physical,
            _ => Element::Hydro,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use VodyanitsaDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            // 唤春角笛为「遥久之歌」状态下由元素战技召唤的协同攻击，按元素战技伤害类型计算
            // （与七七「寒病鬼差协同攻击」、薇斯纳「风翎」的处理一致）
            E | E_HORN | E_HEAL => SkillType::ElementalSkill,
            Q => SkillType::ElementalBurst,
        }
    }
}

pub struct Vodyanitsa;

impl CharacterTrait for Vodyanitsa {
    const STATIC_DATA: CharacterStaticData = VODYANITSA_STATIC_DATA;
    type SkillType = VodyanitsaSkillType;
    const SKILL: Self::SkillType = VODYANITSA_SKILL;
    type DamageEnumType = VodyanitsaDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            VodyanitsaDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            A4 hit_n_dmg!(4)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            VodyanitsaDamageEnum
            E locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E_HORN locale!(zh_cn: "唤春角笛伤害", en: "Horn of Spring's Call DMG")
            E_HEAL locale!(zh_cn: "遥久之歌治疗量", en: "Song of Ages Past Healing")
        ),
        skill3: skill_map!(
            VodyanitsaDamageEnum
            Q locale!(zh_cn: "技能伤害", en: "Skill DMG")
        ),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "in_song_of_ages_past",
            title: locale!(
                zh_cn: "处于「遥久之歌」状态（施放元素战技后）",
                en: "In Song of Ages Past State (after Elemental Skill)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "c4_hp_stacks",
            title: locale!(
                zh_cn: "命座4「柔波摇漾的低诉」生命值上限提升层数（受治疗角色生命值不低于40%时获得，至多3层）",
                en: "C4 Max HP Increase Stacks (gained when the healed character's HP is 40% or above, max 3)"
            ),
            config: ItemConfigType::Int { min: 0, max: 3, default: 3 }
        },
        ItemConfig {
            name: "c4_low_hp",
            title: locale!(
                zh_cn: "命座4：受治疗角色生命值低于40%（本次治疗量提升50%）",
                en: "C4: Healed Character's HP below 40% (this instance of healing is increased by 50%)"
            ),
            config: ItemConfigType::Bool { default: false }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let stellar_glimmer_state = match &common_data.config {
            CharacterConfig::Vodyanitsa { stellar_glimmer_state } => *stellar_glimmer_state,
            _ => StellarGlimmerState::None,
        };

        let (in_song_of_ages_past, c4_hp_stacks, c4_low_hp) = match *skill_config {
            CharacterSkillConfig::Vodyanitsa { in_song_of_ages_past, c4_hp_stacks, c4_low_hp } =>
                (in_song_of_ages_past, c4_hp_stacks, c4_low_hp),
            _ => (false, 0, false),
        };

        let (_, s2, s3) = common_data.get_3_skill();

        // 「流荡风旋」为星扩散体系中的风旋，仅当队伍处于辉映·星扩散状态时才存在，
        // 因此此处以 stellar_glimmer_state.is_stellar_swirl() 近似「当前场上存在流荡风旋」。
        let has_wandering_vortex = stellar_glimmer_state.is_stellar_swirl();

        // 元素战技：宣叙·晨声纷流 — 技能伤害与唤春角笛伤害命中时，
        // 使敌人的水元素抗性与冰元素抗性降低。降抗效果施加于敌人，故总是使用 select_all。
        if in_song_of_ages_past {
            let res_minus = VODYANITSA_SKILL.e_res_minus[s2];
            for element in [Element::Hydro, Element::Cryo] {
                attribute.set_value_to_s(
                    CharacterSelector::select_all(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, element)),
                    "沃雅妮莎技能E",
                    res_minus,
                );
            }
        }

        // 元素爆发：终奏·伴尔沉沦 — 处于「遥久之歌」状态下时，造成的伤害进一步提升
        if in_song_of_ages_past {
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(AttributeVariableType::Bonus, SkillType::ElementalBurst)),
                "沃雅妮莎技能Q",
                VODYANITSA_SKILL.q_enhance[s3],
            );
        }

        // 天赋1：最后的塑诗者 — 施放元素战技时将场上的星辉风旋转化为「流荡风旋」，
        // 「遥久之歌」持续期间队伍中附近的角色触发星扩散反应时也会创造「流荡风旋」；
        // 创造或引爆「流荡风旋」时，使附近敌人的风元素抗性降低35%。
        // 注：描述中「辉映·星扩散状态持续时间延长4秒」不影响伤害计算，故不在此实现。
        if common_data.has_talent1 && has_wandering_vortex && in_song_of_ages_past {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Anemo)),
                "沃雅妮莎天赋1",
                VODYANITSA_SKILL.p1_res_minus,
            );
        }

        // 天赋2：十二弦的泪歌 — 施放元素战技时获得「领唱」与「重唱」，
        // 使队伍中当前场上角色（领唱）与其他角色（重唱）造成水元素伤害或冰元素伤害时，
        // 基于沃雅妮莎生命值上限超过40000的部分提升造成的伤害（每1000点提升140点，至多3500点）；
        // 若当前场上存在「流荡风旋」或处于其引爆后的5秒内，则改为造成星扩散反应伤害时触发
        // （每1000点提升260点，至多6500点）。
        // 注：「领唱」/「重唱」的层数只限制可被提升的伤害次数上限（25层/10层，且每次施放元素战技刷新），
        // 不改变单次伤害的提升值，故此处不额外设置层数配置项。
        if common_data.has_talent2 {
            let hp_bonus = Arc::new(move |hp: f64, _| {
                let excess = (hp - VODYANITSA_SKILL.p2_hp_threshold).max(0.0) / 1000.0;
                (excess * VODYANITSA_SKILL.p2_hydro_cryo_per_1000).min(VODYANITSA_SKILL.p2_hydro_cryo_max)
            });
            let ss_bonus = Arc::new(move |hp: f64, _| {
                let excess = (hp - VODYANITSA_SKILL.p2_hp_threshold).max(0.0) / 1000.0;
                (excess * VODYANITSA_SKILL.p2_ss_per_1000).min(VODYANITSA_SKILL.p2_ss_max)
            });

            if has_wandering_vortex {
                // 基于特定数值提升星扩散反应伤害，对应 ReactionExtra
                attribute.add_edge_s1to1(
                    CharacterSelector::select_all(attribute),
                    AttributeType::Panel(AttributeName::HP),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(AttributeVariableType::ReactionExtra, ReactionType::StellarSwirl)),
                    ss_bonus,
                    "沃雅妮莎天赋2",
                    EdgePriority::Invisible,
                );
            } else {
                // 基于特定数值提升水元素/冰元素伤害，对应 BaseDamage
                for element in [Element::Hydro, Element::Cryo] {
                    attribute.add_edge_s1to1(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Panel(AttributeName::HP),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::BaseDamage, element)),
                        hp_bonus.clone(),
                        "沃雅妮莎天赋2",
                        EdgePriority::Invisible,
                    );
                }
            }
        }

        // 命座1：聚光灯下的水华 — 触发「遥久之歌」的治疗效果时，
        // 使队伍中附近的所有角色攻击力提升，提升值相当于沃雅妮莎生命值上限的0.8%
        if common_data.constellation >= 1 && in_song_of_ages_past {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::HP),
                AttributeType::Panel(AttributeName::ATKFixed),
                Arc::new(|hp: f64, _| hp * VODYANITSA_SKILL.c1_atk_per_hp),
                "沃雅妮莎命座1",
                EdgePriority::Common,
            );
        }

        // 命座2：穿彻风雪的余响 — 「唤春角笛」攻击敌人时获得「黑与白的双音」，
        // 使队伍中当前场上角色造成的水元素伤害与冰元素伤害的暴击伤害提升50%；
        // 若当前场上存在「流荡风旋」或处于其引爆后的5秒内，则改为使星扩散反应伤害的暴击伤害提升60%。
        // 命座6使该效果改为对队伍中附近的所有角色生效。
        // 注：描述中「遥久之歌持续时间延长9秒」不影响单次伤害计算，故不在此实现。
        if common_data.constellation >= 2 && in_song_of_ages_past {
            let selector = if common_data.constellation >= 6 {
                CharacterSelector::select_all(attribute)
            } else {
                CharacterSelector::select_onfield(attribute)
            };

            if has_wandering_vortex {
                attribute.set_value_to_s(
                    selector,
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(AttributeVariableType::CriticalDamage, ReactionType::StellarSwirl)),
                    "沃雅妮莎命座2",
                    VODYANITSA_SKILL.c2_ss_crit_dmg,
                );
            } else {
                for element in [Element::Hydro, Element::Cryo] {
                    attribute.set_value_to_s(
                        selector.clone(),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::CriticalDamage, element)),
                        "沃雅妮莎命座2",
                        VODYANITSA_SKILL.c2_hydro_cryo_crit_dmg,
                    );
                }
            }
        }

        // 命座4：柔波摇漾的低诉 — 触发「遥久之歌」的治疗效果时，基于受治疗角色的生命值触发不同效果
        if common_data.constellation >= 4 {
            if c4_low_hp {
                // 受治疗角色生命值低于40%：本次治疗量提升50%
                attribute.set_value_to_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::HealingBonus)),
                    "沃雅妮莎命座4",
                    VODYANITSA_SKILL.c4_heal_bonus,
                );
            } else {
                // 受治疗角色生命值不低于40%：沃雅妮莎的生命值上限提升20%，至多叠加3层
                let stacks = (c4_hp_stacks as f64).min(VODYANITSA_SKILL.c4_max_stacks);
                if stacks > 0.0 {
                    attribute.add_hp_percentage("沃雅妮莎命座4", stacks * VODYANITSA_SKILL.c4_hp_per_stack);
                }
            }
        }

        // 命座6：永不落幕的盛歌 — 「遥久之歌」持续期间，
        // 队伍中附近的角色造成的星扩散反应伤害擢升25%，造成的水元素伤害与冰元素伤害提升60%
        if common_data.constellation >= 6 && in_song_of_ages_past {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(AttributeVariableType::ElevativeElevate, ReactionType::StellarSwirl)),
                "沃雅妮莎命座6",
                VODYANITSA_SKILL.c6_elevate,
            );
            for element in [Element::Hydro, Element::Cryo] {
                attribute.set_value_to_s(
                    CharacterSelector::select_all(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::Bonus, element)),
                    "沃雅妮莎命座6",
                    VODYANITSA_SKILL.c6_hydro_cryo_bonus,
                );
            }
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: VodyanitsaDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_song_of_ages_past, _c4_hp_stacks, _c4_low_hp) = match *config {
            CharacterSkillConfig::Vodyanitsa { in_song_of_ages_past, c4_hp_stacks, c4_low_hp } =>
                (in_song_of_ages_past, c4_hp_stacks, c4_low_hp),
            _ => (false, 0, false),
        };

        use VodyanitsaDamageEnum::*;
        let mut builder = D::new();

        // 条件检查：「遥久之歌」状态下方可召唤「唤春角笛」并获得其治疗
        if matches!(s, E_HORN | E_HEAL) && !in_song_of_ages_past {
            return builder.none();
        }

        let ratio = match s {
            A1 => VODYANITSA_SKILL.a_dmg1[s1],
            A2 => VODYANITSA_SKILL.a_dmg2[s1],
            A3 => VODYANITSA_SKILL.a_dmg3[s1],
            A4 => VODYANITSA_SKILL.a_dmg4[s1],
            Z => VODYANITSA_SKILL.z_dmg[s1],
            X1 => VODYANITSA_SKILL.x_dmg1[s1],
            X2 => VODYANITSA_SKILL.x_dmg2[s1],
            X3 => VODYANITSA_SKILL.x_dmg3[s1],
            E => VODYANITSA_SKILL.e_dmg[s2],
            E_HORN => VODYANITSA_SKILL.e_horn_dmg[s2],
            E_HEAL => VODYANITSA_SKILL.e_heal[s2],
            Q => VODYANITSA_SKILL.q_dmg[s3],
        };

        match s {
            A1 | A2 | A3 | A4 | Z | X1 | X2 | X3 => {
                builder.add_atk_ratio("技能倍率", ratio);
            }
            E | E_HORN | Q => {
                // 技能伤害基于沃雅妮莎的生命值上限
                builder.add_hp_ratio("技能倍率", ratio);
            }
            E_HEAL => {
                builder.add_hp_ratio("技能倍率", ratio);
                builder.add_base("技能倍率", VODYANITSA_SKILL.e_heal_fixed[s2]);
            }
        }

        // 命座4：受治疗角色生命值低于40%时，本次治疗量提升50%，
        // 由 change_attribute 中的 HealingBonus（「沃雅妮莎命座4」）统一处理。

        if s == E_HEAL {
            builder.heal(&context.attribute)
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let stellar_glimmer_state = match *config {
            CharacterConfig::Vodyanitsa { stellar_glimmer_state } => stellar_glimmer_state,
            _ => StellarGlimmerState::None,
        };
        Some(Box::new(VodyanitsaEffect {
            stellar_glimmer_state,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
