// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::buffs::buffs::prelude::*;
use crate::character::characters::vodyanitsa::VODYANITSA_SKILL;

// 元素战技：宣叙·晨声纷流
pub struct BuffVodyanitsaE {
    pub level_e: usize,
}

impl<A: Attribute> Buff<A> for BuffVodyanitsaE {
    fn change_attribute(&self, attribute: &mut A) {
        // 元素战技「宣叙·晨声纷流」的技能伤害与「唤春角笛」伤害命中时，
        // 将使敌人的水元素抗性与冰元素抗性降低。
        let res_minus = VODYANITSA_SKILL.e_res_minus[self.level_e - 1];
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Hydro)),
            "沃雅妮莎技能E",
            res_minus,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Cryo)),
            "沃雅妮莎技能E",
            res_minus,
        );
    }
}

impl BuffMeta for BuffVodyanitsaE {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaE,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「宣叙·晨声纷流」",
            en: "Vodyanitsa-Rechitativ: Sonorous Dawn"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎技能E：显现出水妖原本的姿态，造成水元素范围伤害，并获得「遥久之歌」效果。\
                <br>「遥久之歌」持续期间，沃雅妮莎将召唤出古老的「唤春角笛」，间歇性快速移动至一名敌人附近，对其进行攻击。\
                <br>上述两种攻击命中时，将会使敌人的水元素抗性与冰元素抗性降低。",
            en: "Vodyanitsa Skill E: Reveals her true Water Imp form, dealing AoE Hydro DMG and gaining the Song of Ages Past effect. \
                <br>While Song of Ages Past is active, Vodyanitsa summons the ancient Horn of Spring's Call, periodically moving closer to an opponent in a swift movement to attack them. \
                <br>Opponents that have taken the above two types of DMG will have their Hydro RES and Cryo RES lowered."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "level_e",
            title: locale!(
                zh_cn: "元素战技等级",
                en: "Elemental Skill Level"
            ),
            config: ItemConfigType::Int { min: 1, max: 15, default: 10 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let level_e = match *b {
            BuffConfig::VodyanitsaE { level_e } => level_e,
            _ => 10
        };
        Box::new(BuffVodyanitsaE {
            level_e,
        })
    }
}


// 天赋1：最后的塑诗者
pub struct BuffVodyanitsaP1;

impl<A: Attribute> Buff<A> for BuffVodyanitsaP1 {
    fn change_attribute(&self, attribute: &mut A) {
        // 创造或引爆「流荡风旋」时，使附近敌人的风元素抗性降低35%。
        // 应用该 buff 视为当前处于「流荡风旋」相关的条件成立状态。
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Anemo)),
            "沃雅妮莎天赋1",
            VODYANITSA_SKILL.p1_res_minus,
        );
    }
}

impl BuffMeta for BuffVodyanitsaP1 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaP1,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「最后的塑诗者」",
            en: "Vodyanitsa-The Last Djeguako Songstress"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎天赋1：创造或引爆「流荡风旋」时，还会使附近敌人的风元素抗性降低35%，持续6秒。",
            en: "Vodyanitsa Talent 1: Generating or detonating a Wandering Vortex will also reduce nearby opponents' Anemo RES by 35% for 6s."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    fn create<A: Attribute>(_b: &BuffConfig) -> Box<dyn Buff<A>> {
        Box::new(BuffVodyanitsaP1)
    }
}


// 天赋2：十二弦的泪歌
pub struct BuffVodyanitsaP2 {
    pub hp: f64,                                    // 沃雅妮莎的生命值上限
    pub stellar_glimmer_state: StellarGlimmerState, // 辉映·星烁状态（用于区分是否存在「流荡风旋」）
}

impl<A: Attribute> Buff<A> for BuffVodyanitsaP2 {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋2「十二弦的泪歌」：「领唱」/「重唱」的固定数值伤害提升，
        // 基于沃雅妮莎生命值上限超过40000的部分计算。
        // 注：「领唱」/「重唱」的层数只限制可被提升的伤害次数上限（25层/10层，且每次施放元素战技刷新），
        // 不改变单次伤害的提升值，故不设置层数配置项。
        // 注：「当前场上存在流荡风旋」以辉映·星扩散状态近似（与角色文件实现一致）。
        let excess = (self.hp - VODYANITSA_SKILL.p2_hp_threshold).max(0.0) / 1000.0;

        if self.stellar_glimmer_state.is_stellar_swirl() {
            // 当前场上存在「流荡风旋」（以辉映·星扩散近似）：
            // 改为角色造成星扩散反应伤害时触发，基于特定数值提升星扩散反应伤害
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionExtra,
                    ReactionType::StellarSwirl,
                )),
                "沃雅妮莎天赋2",
                (excess * VODYANITSA_SKILL.p2_ss_per_1000).min(VODYANITSA_SKILL.p2_ss_max),
            );
        } else {
            // 否则：角色造成水元素伤害或冰元素伤害时触发，基于特定数值提升水/冰元素伤害
            let bonus = (excess * VODYANITSA_SKILL.p2_hydro_cryo_per_1000).min(VODYANITSA_SKILL.p2_hydro_cryo_max);
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::BaseDamage, Element::Hydro)),
                "沃雅妮莎天赋2",
                bonus,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::BaseDamage, Element::Cryo)),
                "沃雅妮莎天赋2",
                bonus,
            );
        }
    }
}

impl BuffMeta for BuffVodyanitsaP2 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaP2,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「十二弦的泪歌」",
            en: "Vodyanitsa-Dirge of the Fandyr"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎天赋2：施放元素战技时，沃雅妮莎还会获得25层「领唱」与10层「重唱」，上述两种效果分别持续30秒，并会在施放元素战技时刷新层数。\
                <br>队伍中自己的当前角色的普通攻击、重击、下落攻击、元素战技或元素爆发造成水元素伤害或冰元素伤害时，将消耗一层「领唱」，提升造成的伤害；\
                由队伍中后台角色或队伍中附近的其他角色触发时消耗一层「重唱」，效果与「领唱」一致。\
                <br>基于沃雅妮莎生命值上限超过40000的部分，每1000点生命值上限都会使上述效果中的水元素伤害与冰元素伤害提升140点，至多提升3500点。\
                <br>若当前场上存在「流荡风旋」，或处于「流荡风旋」引爆后的5秒内，则改为角色造成星扩散反应伤害时才会触发上述效果，每1000点生命值上限使星扩散反应伤害提升260点，至多提升6500点。",
            en: "Vodyanitsa Talent 2: When the Elemental Skill is used, Vodyanitsa also gains 25 stacks of Lead Vocal and 10 stacks of Chorus. These two effects last 30s each, and the stack count is refreshed when the Elemental Skill is used. \
                <br>When the party's currently active character deals Hydro DMG or Cryo DMG with a Normal Attack, Charged Attack, Plunging Attack, Elemental Skill, or Elemental Burst, 1 stack of Lead Vocal is consumed to increase the DMG dealt; Chorus is triggered by off-field party members or other nearby party members, with the same effects as Lead Vocal. \
                <br>Every 1,000 Max HP Vodyanitsa has in excess of 40,000 will increase the Hydro DMG and Cryo DMG from the above effect by 140, up to a maximum of 3,500. \
                <br>If a Wandering Vortex is present on the field or within the 5s after a Wandering Vortex explosion, the effect will only trigger when the character deals Stellar Swirl reaction DMG instead, in which case every 1,000 Max HP increases Stellar Swirl reaction DMG by 260, up to a maximum of 6,500."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "hp",
            title: locale!(
                zh_cn: "沃雅妮莎的生命值上限",
                en: "Vodyanitsa's Max HP"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_BUFF),
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (hp, stellar_glimmer_state) = match *b {
            BuffConfig::VodyanitsaP2 { hp, stellar_glimmer_state } => (hp, stellar_glimmer_state),
            _ => (0.0, StellarGlimmerState::None)
        };
        Box::new(BuffVodyanitsaP2 {
            hp,
            stellar_glimmer_state,
        })
    }
}


// 命座1：聚光灯下的水华
pub struct BuffVodyanitsaC1 {
    pub hp: f64, // 沃雅妮莎的生命值上限
}

impl<A: Attribute> Buff<A> for BuffVodyanitsaC1 {
    fn change_attribute(&self, attribute: &mut A) {
        // 命座1：沃雅妮莎触发「遥久之歌」的治疗效果时，
        // 使队伍中附近的所有角色攻击力提升，提升值相当于沃雅妮莎生命值上限的0.8%。
        attribute.set_value_to(
            AttributeName::ATKFixed,
            "沃雅妮莎命座1",
            self.hp * VODYANITSA_SKILL.c1_atk_per_hp,
        );
    }
}

impl BuffMeta for BuffVodyanitsaC1 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaC1,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「聚光灯下的水华」",
            en: "Vodyanitsa-Waters in Full Splendor"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎命座1：沃雅妮莎触发「遥久之歌」的治疗效果时，还会使队伍中附近的所有角色攻击力提升，提升值相当于沃雅妮莎生命值上限的0.8%，持续5秒。",
            en: "Vodyanitsa Constellation 1: Each time Vodyanitsa triggers the healing effect of Song of Ages Past, it also increases the ATK of all nearby party members by 0.8% of her Max HP for 5s."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "hp",
            title: locale!(
                zh_cn: "沃雅妮莎的生命值上限",
                en: "Vodyanitsa's Max HP"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let hp = match *b {
            BuffConfig::VodyanitsaC1 { hp } => hp,
            _ => 0.0
        };
        Box::new(BuffVodyanitsaC1 {
            hp,
        })
    }
}


// 命座2：穿彻风雪的余响
pub struct BuffVodyanitsaC2 {
    pub stellar_glimmer_state: StellarGlimmerState, // 辉映·星烁状态（用于区分是否存在「流荡风旋」）
}

impl<A: Attribute> Buff<A> for BuffVodyanitsaC2 {
    fn change_attribute(&self, attribute: &mut A) {
        // 命座2：「唤春角笛」攻击敌人时获得「黑与白的双音」，
        // 使队伍中当前场上角色造成的水元素伤害与冰元素伤害的暴击伤害提升50%；
        // 若当前场上存在「流荡风旋」（以辉映·星扩散近似）或处于其引爆后的5秒内，
        // 则改为使星扩散反应伤害的暴击伤害提升60%。
        // 命座6使该效果改为对队伍中附近的所有角色生效，故直接作用于当前角色。
        if self.stellar_glimmer_state.is_stellar_swirl() {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::CriticalDamage,
                    ReactionType::StellarSwirl,
                )),
                "沃雅妮莎命座2",
                VODYANITSA_SKILL.c2_ss_crit_dmg,
            );
        } else {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_element(
                    AttributeVariableType::CriticalDamage,
                    Element::Hydro,
                )),
                "沃雅妮莎命座2",
                VODYANITSA_SKILL.c2_hydro_cryo_crit_dmg,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_element(
                    AttributeVariableType::CriticalDamage,
                    Element::Cryo,
                )),
                "沃雅妮莎命座2",
                VODYANITSA_SKILL.c2_hydro_cryo_crit_dmg,
            );
        }
    }
}

impl BuffMeta for BuffVodyanitsaC2 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaC2,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「穿彻风雪的余响」",
            en: "Vodyanitsa-Echoes That Pierce the Snow"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎命座2：元素战技「宣叙·晨声纷流」中的「唤春角笛」攻击敌人时，沃雅妮莎将获得「黑与白的双音」效果，\
                使队伍中当前场上角色造成的水元素伤害与冰元素伤害的暴击伤害提升50%，持续5秒。\
                <br>若当前场上存在「流荡风旋」，或处于「流荡风旋」引爆后的5秒内，则改为使队伍中当前场上角色造成的星扩散反应伤害的暴击伤害提升60%，持续5秒。\
                <br>命座6「永不落幕的盛歌」：「黑与白的双音」改为对队伍中附近的所有角色生效。",
            en: "Vodyanitsa Constellation 2: When the Horn of Spring's Call from the Elemental Skill Rechitativ: Sonorous Dawn attacks an opponent, Vodyanitsa gains the \"Two Voices in Black and White\" effect which increases the CRIT DMG from Hydro DMG and Cryo DMG dealt by the currently active party member by 50% for 5s. \
                <br>If there is a Wandering Vortex present on the field or in the 5s after a Wandering Vortex explodes, the effect changes to: increases the CRIT DMG from Stellar Swirl reaction DMG caused by the currently active party member by 60% for 5s. \
                <br>Constellation 6 \"Neverending Song of Revelry\": \"Two Voices in Black and White\" now applies to all nearby party members."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_BUFF),
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let stellar_glimmer_state = match *b {
            BuffConfig::VodyanitsaC2 { stellar_glimmer_state } => stellar_glimmer_state,
            _ => StellarGlimmerState::None
        };
        Box::new(BuffVodyanitsaC2 {
            stellar_glimmer_state,
        })
    }
}


// 命座6：永不落幕的盛歌
pub struct BuffVodyanitsaC6;

impl<A: Attribute> Buff<A> for BuffVodyanitsaC6 {
    fn change_attribute(&self, attribute: &mut A) {
        // 命座6：「遥久之歌」效果持续期间，队伍中附近的角色造成的星扩散反应伤害擢升25%，
        // 造成的水元素伤害与冰元素伤害提升60%。
        // 应用该 buff 视为当前处于「遥久之歌」持续期间。
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeElevate,
                ReactionType::StellarSwirl,
            )),
            "沃雅妮莎命座6",
            VODYANITSA_SKILL.c6_elevate,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::Bonus, Element::Hydro)),
            "沃雅妮莎命座6",
            VODYANITSA_SKILL.c6_hydro_cryo_bonus,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::Bonus, Element::Cryo)),
            "沃雅妮莎命座6",
            VODYANITSA_SKILL.c6_hydro_cryo_bonus,
        );
    }
}

impl BuffMeta for BuffVodyanitsaC6 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VodyanitsaC6,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「永不落幕的盛歌」",
            en: "Vodyanitsa-Neverending Song of Revelry"
        ),
        image: BuffImage::Avatar(CharacterName::Vodyanitsa),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "沃雅妮莎命座6：命之座「穿彻风雪的余响」的效果获得强化：「黑与白的双音」改为对队伍中附近的所有角色生效。\
                <br>此外，「遥久之歌」效果持续期间，队伍中附近的角色造成的星扩散反应伤害擢升25%，造成的水元素伤害与冰元素伤害提升60%。",
            en: "Vodyanitsa Constellation 6: The Constellation \"Echoes That Pierce the Snow\" is enhanced as follows: \"Two Voices in Black and White\" now applies to all nearby party members. \
                <br>Additionally, while the Song of Ages Past effect is active, Stellar Swirl reaction DMG dealt by nearby party members is elevated by 25% while Hydro DMG and Cryo DMG dealt are increased by 60%."
        )),
        from: BuffFrom::Character(CharacterName::Vodyanitsa),
    };

    fn create<A: Attribute>(_b: &BuffConfig) -> Box<dyn Buff<A>> {
        Box::new(BuffVodyanitsaC6)
    }
}
