// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::weapon::weapons::prelude::*;

pub struct AngelosHeptadesEffect {
    pub hexerei_secret_rite: bool,
}

impl<A: Attribute> WeaponEffect<A> for AngelosHeptadesEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 攻击力提升
        attribute.add_atk_percentage("尘光七谕被动", 0.09 + 0.03 * refine);

        // 先导之光：基于装备者攻击力，每1000点提升当前场上角色伤害
        // 从装备者 ATK 引属性边到自身通用伤害加成
        attribute.add_edge_s1to1(
            CharacterSelector::select_onfield(attribute),
            AttributeType::Panel(AttributeName::ATK),
            AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::Bonus)),
            Arc::new(move |atk: f64, _| {
                let per_1k = 0.07 + 0.03 * refine;
                let max_bonus = 0.18 + 0.08 * refine;
                ((atk / 1000.0) * per_1k).min(max_bonus)
            }),
            "尘光七谕被动",
            EdgePriority::Invisible,
        );

        // 魔导·秘仪：队伍中自己的魔导角色位于队伍后台时，获得先导之光50%的伤害提升效果
        if self.hexerei_secret_rite {
            attribute.add_edge_s1to1(
                CharacterSelector::new({
                    let team_id = attribute.get_character().team_id;
                    move |status: &CharacterStatus| {
                        !status.on_field
                            && status.tags.contains(&CharacterTag::Hexerei)
                            && status.team_id == team_id
                    }
                }),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::Bonus)),
                Arc::new(move |atk: f64, _| {
                    let per_1k = 0.07 + 0.03 * refine;
                    let max_bonus = 0.18 + 0.08 * refine;
                    ((atk / 1000.0) * per_1k).min(max_bonus) * 0.5
                }),
                "尘光七谕被动",
                EdgePriority::Invisible,
            );
        }
    }
}

pub struct AngelosHeptades;

impl WeaponTrait for AngelosHeptades {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::AngelosHeptades,
        internal_name: "Catalyst_AngelosHeptades",
        weapon_type: WeaponType::Catalyst,
        weapon_sub_stat: Some(WeaponSubStatFamily::ATK36),
        weapon_base: WeaponBaseATKFamily::ATK741,
        star: 5,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "攻击力提升 <span style=\"color: #409EFF;\">12%-15%-18%-21%-24%</span> 。装备者创造护盾后的20秒内，获得「先导之光」效果：依据装备者的攻击力，每1000点攻击力都会使队伍中自己的当前场上角色造成的伤害提升 <span style=\"color: #409EFF;\">10%-13%-16%-19%-22%</span> ，至多提升 <span style=\"color: #409EFF;\">26%-34%-42%-50%-58%</span> 。此外，装备者创造护盾时，还会获得「指引者的餍足」效果，使装备者恢复 <span style=\"color: #409EFF;\">14-15-16-17-18</span> 点元素能量，该效果每14秒至多触发一次；在不处于战斗状态下开启各类宝箱时，也会获得该效果。装备者处于队伍后台时，依然能触发上述效果。<br>魔导·秘仪：队伍中自己的魔导角色位于队伍后台时，也能获得「先导之光」中50%的伤害提升效果。",
            en: "ATK is increased by <span style=\"color: #409EFF;\">12%-15%-18%-21%-24%</span> . After the equipping character creates a Shield, they gain \"Pathfinder's Light\" for 20s: Increases your active party member's DMG by <span style=\"color: #409EFF;\">10%-13%-16%-19%-22%</span> for every 1,000 ATK the equipping character has, up to a maximum of <span style=\"color: #409EFF;\">26%-34%-42%-50%-58%</span> . Additionally, when the equipping character creates a Shield, they will also gain \"Guide's Contentment\": Restores <span style=\"color: #409EFF;\">14-15-16-17-18</span> Elemental Energy to the equipping character. The aforementioned effect can trigger once every 14s, and can also be triggered when all types of chests are opened outside of combat. The equipping character may trigger this effect even when they are an off-field.<br>Hexerei: Secret Rite: When there are off-field Hexerei characters in your party, they will also gain 50% of the DMG increase from Pathfinder's Light."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "尘光七谕",
            en: "Angelos' Heptades"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::HEXEREI_SECRET_RITE_GLOBAL(false, ItemConfig::PRIORITY_WEAPON),
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let hexerei_secret_rite = match *config {
            WeaponConfig::AngelosHeptades { hexerei_secret_rite } => hexerei_secret_rite,
            _ => false,
        };

        Some(Box::new(AngelosHeptadesEffect {
            hexerei_secret_rite,
        }))
    }
}
