// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::weapon::weapons::prelude::*;

pub struct HymnOfTheMaelstromEffect {
    pub stack: f64,
    pub reaction: bool,
}

impl<A: Attribute> WeaponEffect<A> for HymnOfTheMaelstromEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 治疗加成提升。
        attribute.set_value_to(AttributeName::HealingBonus, "漩流颂歌被动", 0.03 + 0.01 * refine);

        // 队伍中附近的角色触发冻结反应或星扩散反应后的 5 秒内，「告真的蜜酿」的生命值上限
        // 与攻击力提升效果额外提高 75%，以配置项「冻结/星扩散反应」近似该状态的覆盖。
        let multiplier = if self.reaction { 1.75 } else { 1.0 };

        // 「告真的蜜酿」：生命值上限提升，至多叠加 3 层。
        let hp_per_stack = (0.03 + 0.01 * refine) * multiplier;
        attribute.add_hp_percentage("漩流颂歌被动", hp_per_stack * self.stack);

        // 「告真的蜜酿」：基于装备者生命值上限超过 40000 的部分，每 1000 点生命值上限都会
        // 使队伍中自己的当前场上角色的攻击力提升，通过这种方式至多提升一定数值。
        // 该加成随装备者最终生命值上限变化，故从装备者的生命值上限连边到当前场上角色的
        // 攻击力百分比；每层单独计算上限，再乘以等效层数。
        let per_1000 = (0.003 + 0.001 * refine) * multiplier;
        let max_per_stack = (0.06 + 0.02 * refine) * multiplier;
        let stack = self.stack;
        attribute.add_edge_s1to1(
            CharacterSelector::select_onfield(attribute),
            AttributeType::Panel(AttributeName::HP),
            AttributeType::Panel(AttributeName::ATKPercentage),
            Arc::new(move |hp: f64, _| {
                let count = ((hp - 40000.0) / 1000.0).max(0.0);
                (count * per_1000).min(max_per_stack) * stack
            }),
            "漩流颂歌被动",
            EdgePriority::Common,
        );
    }
}

pub struct HymnOfTheMaelstrom;

impl WeaponTrait for HymnOfTheMaelstrom {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::HymnOfTheMaelstrom,
        internal_name: "Catalyst_Bludnye",
        weapon_type: WeaponType::Catalyst,
        weapon_sub_stat: Some(WeaponSubStatFamily::HP144),
        weapon_base: WeaponBaseATKFamily::ATK542,
        star: 5,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "治疗加成提升 <span style=\"color: #409EFF;\">4%-5%-6%-7%-8%</span> ；<br>进行治疗时，装备者获得「告真的蜜酿」效果：生命值上限提升 <span style=\"color: #409EFF;\">4%-5%-6%-7%-8%</span> ，且基于装备者生命值上限超过40000的部分，每1000点生命值上限都会使队伍中自己的当前场上角色的攻击力提升 <span style=\"color: #409EFF;\">0.4%-0.5%-0.6%-0.7%-0.8%</span> ，通过这种方式至多提升 <span style=\"color: #409EFF;\">8%-10%-12%-14%-16%</span> 。该效果持续10秒，至多叠加3层。<br>队伍中附近的角色触发冻结反应或星扩散反应后的5秒内，上述效果中生命值上限与攻击力提升的效果额外提高75%。<br>装备者处于队伍后台时，依然能触发上述效果。",
            en: "Increases Healing Bonus by <span style=\"color: #409EFF;\">4%-5%-6%-7%-8%</span> .<br>When performing healing, the equipping character gains the \"Tipple of Truth\" effect, which increases Max HP by <span style=\"color: #409EFF;\">4%-5%-6%-7%-8%</span> as well as increases the currently active party member's ATK by <span style=\"color: #409EFF;\">0.4%-0.5%-0.6%-0.7%-0.8%</span> for every 1,000 Max HP the equipping character has over 40,000. A maximum of <span style=\"color: #409EFF;\">8%-10%-12%-14%-16%</span> ATK can be gained in this way. This effect lasts 10s, max 3 stacks.<br>When a nearby party member triggers a Frozen or Stellar Swirl reaction, the aforementioned Max HP and ATK boosts will be further increased by 75% for the next 5s.<br>The aforementioned effects can still trigger even when the equipping character is not on the field."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "漩流颂歌",
            en: "Hymn of the Maelstrom"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "stack",
            title: ItemConfig::DEFAULT_STACK_TITLE,
            config: ItemConfigType::Float { min: 0.0, max: 3.0, default: 3.0 },
        },
        ItemConfig {
            name: "reaction",
            title: locale!(zh_cn: "触发冻结/星扩散反应", en: "Trigger Frozen/Stellar Swirl Reaction"),
            config: ItemConfigType::Bool { default: true },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (stack, reaction) = match *config {
            WeaponConfig::HymnOfTheMaelstrom { stack, reaction } => (stack, reaction),
            _ => (0.0, false),
        };

        Some(Box::new(HymnOfTheMaelstromEffect {
            stack,
            reaction,
        }))
    }
}
