// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::weapon::weapons::prelude::*;
use crate::common::StellarGlimmerState;

pub struct WintersHeavyHeartEffect {
    pub cryo_count: usize,
    pub electro_count: usize,
    pub stellar_glimmer_state: StellarGlimmerState,
}

impl<A: Attribute> WeaponEffect<A> for WintersHeavyHeartEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 「银染的血契」：至多 4 位冰元素类型或雷元素类型的角色可以提供效果，
        // 超出部分按比例缩减。
        let total = (self.cryo_count + self.electro_count) as f64;
        let factor = if total > 4.0 { 4.0 / total } else { 1.0 };
        let cryo_count = self.cryo_count as f64 * factor;
        let electro_count = self.electro_count as f64 * factor;

        if self.stellar_glimmer_state.is_stellar_glimmer() {
            // 辉映·星烁：「银染的血契」效果改为队伍中每存在一位冰元素类型或雷元素类型的角色，
            // 装备者的元素精通提升，且造成的星烁反应伤害提升（星烁反应包含星超导与星扩散）。
            let count = cryo_count + electro_count;
            attribute.set_value_to(AttributeName::ElementalMastery, "凝雪沉心被动", (15.0 + 5.0 * refine) * count);

            let bonus = (0.045 + 0.015 * refine) * count;
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "凝雪沉心被动",
                bonus,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "凝雪沉心被动",
                bonus,
            );
        } else {
            // 「银染的血契」：队伍中每存在一位冰元素类型的角色，装备者的元素精通提升；
            // 队伍中每存在一位雷元素类型的角色，装备者的攻击力提升。
            if cryo_count > 0.0 {
                attribute.set_value_to(AttributeName::ElementalMastery, "凝雪沉心被动", (18.0 + 6.0 * refine) * cryo_count);
            }
            if electro_count > 0.0 {
                attribute.add_atk_percentage("凝雪沉心被动", (0.036 + 0.012 * refine) * electro_count);
            }
        }
    }
}

pub struct WintersHeavyHeart;

impl WeaponTrait for WintersHeavyHeart {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::WintersHeavyHeart,
        internal_name: "Catalyst_FrostScepter",
        weapon_type: WeaponType::Catalyst,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalDamage120),
        weapon_base: WeaponBaseATKFamily::ATK510,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "装备者获得「银染的血契」：队伍中每存在一位冰元素类型的角色，装备者的元素精通提升 <span style=\"color: #409EFF;\">24-30-36-42-48</span> 点；队伍中每存在一位雷元素类型的角色，装备者的攻击力提升 <span style=\"color: #409EFF;\">4.8%-6%-7.2%-8.4%-9.6%</span> 。至多4位冰元素类型或雷元素类型的角色可以提供上述效果。<br>辉映·星烁：「银染的血契」效果改为：队伍中每存在一位冰元素类型或雷元素类型的角色，装备者的元素精通提升 <span style=\"color: #409EFF;\">20-25-30-35-40</span> 点，造成的星烁反应伤害提升 <span style=\"color: #409EFF;\">6%-7.5%-9%-10.5%-12%</span> 。",
            en: "The equipping character gains \"Silver-Tinged Blood Pact\": The equipping character's Elemental Mastery is increased by <span style=\"color: #409EFF;\">24-30-36-42-48</span> for every Cryo character present in the party. For every Electro character present in the party, the equipping character's ATK is increased by <span style=\"color: #409EFF;\">4.8%-6%-7.2%-8.4%-9.6%</span>. The equipping character can gain the above buffs for 4 characters max.<br>Radiance: Stellar Glimmer: The effect of \"Silver-Tinged Blood Pact\" is changed to: For every Cryo or Electro character present in the party, the equipping character gains a <span style=\"color: #409EFF;\">20-25-30-35-40</span>-point Elemental Mastery boost and deals <span style=\"color: #409EFF;\">6%-7.5%-9%-10.5%-12%</span> increased Stellar Glimmer reaction DMG."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "凝雪沉心",
            en: "Winter's Heavy Heart"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "cryo_count",
            title: locale!(zh_cn: "队伍冰元素数量", en: "# Cryo Member"),
            config: ItemConfigType::Int { min: 0, max: 4, default: 0 },
        },
        ItemConfig {
            name: "electro_count",
            title: locale!(zh_cn: "队伍雷元素数量", en: "# Electro Member"),
            config: ItemConfigType::Int { min: 0, max: 4, default: 0 },
        },
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_WEAPON),
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (cryo_count, electro_count, stellar_glimmer_state) = match *config {
            WeaponConfig::WintersHeavyHeart { cryo_count, electro_count, stellar_glimmer_state } => (cryo_count, electro_count, stellar_glimmer_state),
            _ => (0, 0, StellarGlimmerState::None),
        };

        Some(Box::new(WintersHeavyHeartEffect {
            cryo_count,
            electro_count,
            stellar_glimmer_state,
        }))
    }
}
