// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct DionaSkillType {
    // Normal Attack: 猎人射术 / Kätzlein Style
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub z_dmg1: [f64; 15],  // Aimed Shot
    pub z_dmg2: [f64; 15],  // Fully-Charged Aimed Shot (Cryo)
    pub x_dmg1: [f64; 15],  // Plunge DMG
    pub x_dmg2: [f64; 15],  // Low Plunge DMG
    pub x_dmg3: [f64; 15],  // High Plunge DMG

    // Elemental Skill: 猫爪冻冻 / Icy Paws
    pub e_dmg: [f64; 15],           // Icy Paw DMG (per paw)
    pub e_shield_ratio: [f64; 15],  // Shield HP ratio
    pub e_shield_fixed: [f64; 15],  // Shield flat value

    // Elemental Burst: 最烈特调 / Signature Mix
    pub q_dmg1: [f64; 15],          // Skill DMG (initial)
    pub q_dmg2: [f64; 15],          // Continuous Field DMG
    pub q_heal_ratio: [f64; 15],    // HP Regeneration HP ratio
    pub q_heal_fixed: [f64; 15],    // HP Regeneration flat value

    // C2: 猫爪冰摇 / Shaken, Not Purred
    pub c2_dmg_bonus: f64,     // 0.15
    pub c2_shield_bonus: f64,  // 0.15

    // C6: 猫尾打烊之时 / Cat's Tail Closing Time
    pub c6_hp_bonus: f64,      // 0.25 (self only)
}

pub const DIONA_SKILL: DionaSkillType = DionaSkillType {
    // Normal Attack: 猎人射术
    a_dmg1: [0.3612, 0.3906, 0.42, 0.462, 0.4914, 0.525, 0.5712, 0.6174, 0.6636, 0.714, 0.7718, 0.8397, 0.9076, 0.9755, 1.0496],
    a_dmg2: [0.3354, 0.3627, 0.39, 0.429, 0.4563, 0.4875, 0.5304, 0.5733, 0.6162, 0.663, 0.7166, 0.7797, 0.8428, 0.9058, 0.9746],
    a_dmg3: [0.4558, 0.4929, 0.53, 0.583, 0.6201, 0.6625, 0.7208, 0.7791, 0.8374, 0.901, 0.9739, 1.0596, 1.1453, 1.231, 1.3245],
    a_dmg4: [0.43, 0.465, 0.5, 0.55, 0.585, 0.625, 0.68, 0.735, 0.79, 0.85, 0.9188, 0.9996, 1.0805, 1.1613, 1.2495],
    a_dmg5: [0.5375, 0.5813, 0.625, 0.6875, 0.7313, 0.7813, 0.85, 0.9188, 0.9875, 1.0625, 1.1484, 1.2495, 1.3506, 1.4516, 1.5619],
    z_dmg1: [0.4386, 0.4743, 0.51, 0.561, 0.5967, 0.6375, 0.6936, 0.7497, 0.8058, 0.867, 0.9371, 1.0196, 1.1021, 1.1845, 1.2745],
    z_dmg2: [1.24, 1.333, 1.426, 1.55, 1.643, 1.736, 1.86, 1.984, 2.108, 2.232, 2.361, 2.5296, 2.6982, 2.8669, 3.0355],
    x_dmg1: [0.5683, 0.6145, 0.6608, 0.7269, 0.7731, 0.826, 0.8987, 0.9714, 1.0441, 1.1234, 1.2027, 1.282, 1.3612, 1.4405, 1.5198],
    x_dmg2: [1.1363, 1.2288, 1.3213, 1.4535, 1.5459, 1.6517, 1.797, 1.9423, 2.0877, 2.2462, 2.4048, 2.5634, 2.7219, 2.8805, 3.039],
    x_dmg3: [1.4193, 1.5349, 1.6504, 1.8154, 1.931, 2.063, 2.2445, 2.4261, 2.6076, 2.8057, 3.0037, 3.2018, 3.3998, 3.5979, 3.7959],

    // Elemental Skill: 猫爪冻冻
    e_dmg: [0.4192, 0.4506, 0.4821, 0.524, 0.5554, 0.5869, 0.6288, 0.6707, 0.7126, 0.7546, 0.7965, 0.8384, 0.8908, 0.9432, 0.9956],
    e_shield_ratio: [0.072, 0.0774, 0.0828, 0.09, 0.0954, 0.1008, 0.108, 0.1152, 0.1224, 0.1296, 0.1368, 0.144, 0.153, 0.162, 0.171],
    e_shield_fixed: [693.0, 762.0, 837.0, 918.0, 1005.0, 1097.0, 1195.0, 1299.0, 1409.0, 1524.0, 1646.0, 1773.0, 1905.0, 2044.0, 2188.0],

    // Elemental Burst: 最烈特调
    q_dmg1: [0.8, 0.86, 0.92, 1.0, 1.06, 1.12, 1.2, 1.28, 1.36, 1.44, 1.52, 1.6, 1.7, 1.8, 1.9],
    q_dmg2: [0.5264, 0.5659, 0.6054, 0.658, 0.6975, 0.737, 0.7896, 0.8422, 0.8949, 0.9475, 1.0002, 1.0528, 1.1186, 1.1844, 1.2502],
    q_heal_ratio: [0.0534, 0.0574, 0.0614, 0.0667, 0.0707, 0.0747, 0.08, 0.0854, 0.0907, 0.096, 0.1014, 0.1067, 0.1134, 0.1201, 0.1267],
    q_heal_fixed: [513.0, 565.0, 620.0, 680.0, 744.0, 813.0, 885.0, 962.0, 1044.0, 1129.0, 1219.0, 1313.0, 1411.0, 1514.0, 1621.0],

    // C2: 猫爪冰摇
    c2_dmg_bonus: 0.15,
    c2_shield_bonus: 0.15,

    // C6: 猫尾打烊之时
    c6_hp_bonus: 0.25,
};

pub const DIONA_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Diona,
    internal_name: "Diona",
    element: Element::Cryo,
    hp: [802, 2061, 2661, 3985, 4411, 5074, 5642, 6305, 6731, 7393, 7818, 8481, 8907, 9570, 10232],
    atk: [18, 46, 59, 88, 98, 113, 125, 140, 149, 164, 174, 188, 198, 212, 266],
    def: [50, 129, 167, 250, 277, 318, 354, 396, 422, 464, 491, 532, 559, 601, 642],
    sub_stat: CharacterSubStatFamily::Bonus240(StatName::CryoBonus),
    weapon_type: WeaponType::Bow,
    star: 4,
    skill_name1: locale!(
        zh_cn: "猎人射术",
        en: "Normal Attack: Kätzlein Style",
    ),
    skill_name2: locale!(
        zh_cn: "猫爪冻冻",
        en: "Icy Paws",
    ),
    skill_name3: locale!(
        zh_cn: "最烈特调",
        en: "Signature Mix",
    ),
    name_locale: locale!(
        zh_cn: "迪奥娜",
        en: "Diona",
    ),
};

pub struct DionaEffect {
    pub in_polestar_field: bool,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for DionaEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // C2: 猫爪冻冻造成的伤害提高15%
        if self.common_data.constellation >= 2 {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(
                    AttributeVariableType::Bonus,
                    SkillType::ElementalSkill,
                )),
                "迪奥娜命座2",
                DIONA_SKILL.c2_dmg_bonus,
            );
        }

        // C6: 迪奥娜的生命值上限提升25%
        if self.common_data.constellation >= 6 {
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::HPPercentage),
                "迪奥娜命座6",
                DIONA_SKILL.c6_hp_bonus,
            );

            // 辉映·星超导：处于极星辉域中时，超导、星超导反应伤害提升40%
            if self.in_polestar_field {
                attribute.set_value_to_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::Superconduct,
                    )),
                    "迪奥娜命座6",
                    0.4,
                );
                attribute.set_value_to_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarConduct,
                    )),
                    "迪奥娜命座6",
                    0.4,
                );
            }
        }
    }
}

damage_enum!(
    DionaDamageEnum
    A1
    A2
    A3
    A4
    A5
    Z1
    Z2
    X1
    X2
    X3
    E1
    ESHIELD
    Q1
    Q2
    QHEAL
);

impl DionaDamageEnum {
    pub fn get_element(&self) -> Element {
        use DionaDamageEnum::*;
        match *self {
            Z2 | E1 | Q1 | Q2 => Element::Cryo,
            ESHIELD => Element::Cryo,
            _ => Element::Physical,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use DionaDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4 | A5 => SkillType::NormalAttack,
            Z1 | Z2 => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | ESHIELD => SkillType::ElementalSkill,
            Q1 | Q2 | QHEAL => SkillType::ElementalBurst,
        }
    }

    pub fn is_heal(&self) -> bool {
        *self == DionaDamageEnum::QHEAL
    }

    pub fn is_shield(&self) -> bool {
        *self == DionaDamageEnum::ESHIELD
    }
}

pub struct Diona;

impl CharacterTrait for Diona {
    const STATIC_DATA: CharacterStaticData = DIONA_STATIC_DATA;
    type SkillType = DionaSkillType;
    const SKILL: Self::SkillType = DIONA_SKILL;
    type DamageEnumType = DionaDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            DionaDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            A4 hit_n_dmg!(4)
            A5 hit_n_dmg!(5)
            Z1 charged_dmg!("shoot1")
            Z2 charged_dmg!("shoot2")
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            DionaDamageEnum
            E1 locale!(zh_cn: "猫爪伤害", en: "Icy Paw DMG")
            ESHIELD locale!(zh_cn: "护盾吸收量", en: "Shield DMG Absorption")
        ),
        skill3: skill_map!(
            DionaDamageEnum
            Q1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q2 locale!(zh_cn: "领域持续伤害", en: "Continuous Field DMG")
            QHEAL locale!(zh_cn: "持续治疗量", en: "HP Regeneration Over Time")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::IN_POLESTAR_FIELD(false, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "in_signature_mix",
            title: locale!(
                zh_cn: "处于最烈特调领域内",
                en: "Within Signature Mix field"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "hp_above_50",
            title: locale!(
                zh_cn: "当前场上角色生命值高于50%",
                en: "Current on-field character HP above 50%"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (in_signature_mix, hp_above_50) = match *skill_config {
            CharacterSkillConfig::Diona { in_signature_mix, hp_above_50 } => (in_signature_mix, hp_above_50),
            _ => (false, true),
        };

        // C6: 处在最烈特调领域内的角色，依据生命值获得效果
        if in_signature_mix && common_data.constellation >= 6 {
            let selector = CharacterSelector::select_all_onfield(attribute);
            if hp_above_50 {
                // 生命值高于50%时，元素精通提升200
                attribute.set_value_to_s(
                    selector,
                    AttributeType::Panel(AttributeName::ElementalMastery),
                    "迪奥娜命座6",
                    200.0,
                );
            } else {
                // 生命值低于或等于50%时，受治疗加成提升30%
                attribute.set_value_to_s(
                    selector,
                    AttributeType::Panel(AttributeName::IncomingHealingBonus),
                    "迪奥娜命座6",
                    0.3,
                );
            }
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: DionaDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let _ = config; // Config effects handled in change_attribute

        use DionaDamageEnum::*;
        let mut builder = D::new();

        if s.is_heal() {
            // Q healing: HP ratio + fixed
            let ratio = match s {
                QHEAL => DIONA_SKILL.q_heal_ratio[s3],
                _ => 0.0,
            };
            let fixed = match s {
                QHEAL => DIONA_SKILL.q_heal_fixed[s3],
                _ => 0.0,
            };
            builder.add_hp_ratio("技能倍率", ratio);
            builder.add_extra_damage("技能倍率", fixed);
            builder.heal(&context.attribute)
        } else if s.is_shield() {
            // E shield: HP ratio + fixed, C2 absorption bonus applied separately
            let ratio = match s {
                ESHIELD => DIONA_SKILL.e_shield_ratio[s2],
                _ => 0.0,
            };
            let fixed = match s {
                ESHIELD => DIONA_SKILL.e_shield_fixed[s2],
                _ => 0.0,
            };
            builder.add_hp_ratio("技能倍率", ratio);
            builder.add_extra_damage("技能倍率", fixed);
            if context.character_common_data.constellation >= 2 {
                builder.add_hp_ratio("迪奥娜命座2", ratio * DIONA_SKILL.c2_shield_bonus);
                builder.add_extra_damage("迪奥娜命座2", fixed * DIONA_SKILL.c2_shield_bonus);
            }
            builder.shield(&context.attribute, s.get_element())
        } else {
            let ratio = match s {
                A1 => DIONA_SKILL.a_dmg1[s1],
                A2 => DIONA_SKILL.a_dmg2[s1],
                A3 => DIONA_SKILL.a_dmg3[s1],
                A4 => DIONA_SKILL.a_dmg4[s1],
                A5 => DIONA_SKILL.a_dmg5[s1],
                Z1 => DIONA_SKILL.z_dmg1[s1],
                Z2 => DIONA_SKILL.z_dmg2[s1],
                X1 => DIONA_SKILL.x_dmg1[s1],
                X2 => DIONA_SKILL.x_dmg2[s1],
                X3 => DIONA_SKILL.x_dmg3[s1],
                E1 => DIONA_SKILL.e_dmg[s2],
                Q1 => DIONA_SKILL.q_dmg1[s3],
                Q2 => DIONA_SKILL.q_dmg2[s3],
                _ => 0.0,
            };
            builder.add_atk_ratio("技能倍率", ratio);

            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let in_polestar_field = match *config {
            CharacterConfig::Diona { in_polestar_field } => in_polestar_field,
            _ => false,
        };
        Some(Box::new(DionaEffect {
            in_polestar_field,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}

