// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct LohenSkillType {
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub a_dmg51: [f64; 15],
    pub a_dmg52: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    pub e_dmg1: [f64; 15],
    pub e_dmg2: [f64; 15],
    pub e_dmg3: [f64; 15],
    pub e_dmg4: [f64; 15],
    pub e_dmg51: [f64; 15],
    pub e_dmg52: [f64; 15],
    pub e_z_dmg: [f64; 15],

    pub eg_dmg: [f64; 15], // 镂骨彻心伤害
    pub will_bonus: f64,    // 每点争胜提升伤害比例

    pub q_dmg: [f64; 15], // 裁罚遂成伤害

    pub c2_dmg: f64, // 命座2破邪之刃伤害
}

pub const LOHEN_SKILL: LohenSkillType = LohenSkillType {
    // Normal Attack: 西风枪术·破誓
    a_dmg1: [0.5399, 0.5839, 0.6278, 0.6906, 0.7345, 0.7848, 0.8538, 0.9229, 0.9919, 1.0673, 1.1426, 1.218, 1.2933, 1.3686, 1.444],
    a_dmg2: [0.5644, 0.6104, 0.6563, 0.7219, 0.7679, 0.8204, 0.8926, 0.9648, 1.037, 1.1157, 1.1945, 1.2732, 1.352, 1.4308, 1.5095],
    a_dmg3: [0.2542, 0.2749, 0.2956, 0.3251, 0.3458, 0.3695, 0.402, 0.4345, 0.467, 0.5025, 0.538, 0.5734, 0.6089, 0.6444, 0.6798],
    a_dmg4: [0.7523, 0.8135, 0.8747, 0.9622, 1.0234, 1.0934, 1.1896, 1.2858, 1.3821, 1.487, 1.592, 1.697, 1.8019, 1.9069, 2.0119],
    a_dmg51: [0.3686, 0.3986, 0.4286, 0.4714, 0.5014, 0.5357, 0.5829, 0.63, 0.6772, 0.7286, 0.78, 0.8314, 0.8829, 0.9343, 0.9857],
    a_dmg52: [0.5529, 0.5979, 0.6429, 0.7072, 0.7522, 0.8036, 0.8743, 0.945, 1.0157, 1.0929, 1.17, 1.2472, 1.3243, 1.4015, 1.4786],
    z_dmg: [0.6588, 0.7124, 0.766, 0.8426, 0.8962, 0.9575, 1.0418, 1.126, 1.2103, 1.3022, 1.3941, 1.486, 1.578, 1.6699, 1.7618],
    x_dmg1: [0.6393, 0.6914, 0.7434, 0.8177, 0.8698, 0.9293, 1.011, 1.0928, 1.1746, 1.2638, 1.353, 1.4422, 1.5314, 1.6206, 1.7098],
    x_dmg2: [1.2784, 1.3824, 1.4865, 1.6351, 1.7392, 1.8581, 2.0216, 2.1851, 2.3486, 2.527, 2.7054, 2.8838, 3.0622, 3.2405, 3.4189],
    x_dmg3: [1.5968, 1.7267, 1.8567, 2.0424, 2.1723, 2.3209, 2.5251, 2.7293, 2.9336, 3.1564, 3.3792, 3.602, 3.8248, 4.0476, 4.2704],

    // Elemental Skill: 奇兵诡出（奇谋状态下的强化普攻/重击）
    e_dmg1: [0.8099, 0.8758, 0.9417, 1.0359, 1.1018, 1.1771, 1.2807, 1.3843, 1.4879, 1.6009, 1.7139, 1.8269, 1.9399, 2.0529, 2.1659],
    e_dmg2: [0.8466, 0.9156, 0.9845, 1.0829, 1.1518, 1.2306, 1.3389, 1.4472, 1.5555, 1.6736, 1.7917, 1.9099, 2.028, 2.1461, 2.2643],
    e_dmg3: [0.3813, 0.4123, 0.4434, 0.4877, 0.5187, 0.5542, 0.603, 0.6518, 0.7005, 0.7537, 0.8069, 0.8601, 0.9133, 0.9665, 1.0198],
    e_dmg4: [1.1284, 1.2202, 1.3121, 1.4433, 1.5351, 1.6401, 1.7844, 1.9288, 2.0731, 2.2305, 2.388, 2.5454, 2.7029, 2.8603, 3.0178],
    e_dmg51: [0.5529, 0.5979, 0.6429, 0.7072, 0.7522, 0.8036, 0.8743, 0.945, 1.0157, 1.0929, 1.17, 1.2472, 1.3243, 1.4015, 1.4786],
    e_dmg52: [0.8293, 0.8968, 0.9643, 1.0607, 1.1282, 1.2054, 1.3115, 1.4175, 1.5236, 1.6393, 1.755, 1.8708, 1.9865, 2.1022, 2.2179],
    e_z_dmg: [0.9881, 1.0686, 1.149, 1.2639, 1.3443, 1.4362, 1.5626, 1.689, 1.8154, 1.9533, 2.0912, 2.2291, 2.3669, 2.5048, 2.6427],

    // 镂骨彻心（特殊元素战技）
    eg_dmg: [0.6, 0.645, 0.69, 0.75, 0.795, 0.84, 0.9, 0.96, 1.02, 1.08, 1.14, 1.2, 1.275, 1.35, 1.425],
    will_bonus: 0.004,

    // Elemental Burst: 裁罚遂成
    q_dmg: [1.188, 1.2771, 1.3662, 1.485, 1.5741, 1.6632, 1.782, 1.9008, 2.0196, 2.1384, 2.2572, 2.376, 2.5245, 2.673, 2.8215],

    // 命座2 破邪之刃
    c2_dmg: 5.0,
};

pub const LOHEN_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Lohen,
    internal_name: "Lohen",
    element: Element::Cryo,
    hp: [1001, 2597, 3540, 5170, 5865, 6649, 7549, 8341, 9039, 9838, 10537, 11345, 12044, 12858, 13772],
    atk: [27, 70, 95, 138, 157, 178, 202, 223, 242, 264, 282, 304, 323, 344, 422],
    def: [61, 158, 216, 315, 358, 405, 460, 509, 551, 600, 642, 692, 734, 784, 840],
    sub_stat: CharacterSubStatFamily::CriticalDamage384,
    weapon_type: WeaponType::Polearm,
    star: 5,
    skill_name1: locale!(
        zh_cn: "西风枪术·破誓",
        en: "Spear of Favonius — Broken Oath",
    ),
    skill_name2: locale!(
        zh_cn: "奇兵诡出",
        en: "Unforeseen Strike",
    ),
    skill_name3: locale!(
        zh_cn: "裁罚遂成",
        en: "Manifest Judgment",
    ),
    name_locale: locale!(
        zh_cn: "洛恩",
        en: "Lohen",
    ),
};

pub struct LohenEffect {
    pub hexerei_secret_rite: bool,
    pub avg_will_to_win: f64, // 施放镂骨彻心时的平均争胜层数（应用一命效果前）
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for LohenEffect {
    fn change_attribute(&self, _attribute: &mut A) {
    }
}

damage_enum!(
    LohenDamageEnum
    A1
    A2
    A3
    A3T
    A4
    A51
    A52
    Z
    ZT
    X1
    X2
    X3
    E1
    E2
    E3
    E3T
    E4
    E51
    E52
    EZ
    EZT
    EG
    EGT
    Q
    QT
    C2A
    C2Z
);

impl LohenDamageEnum {
    pub fn get_element(&self, in_masterstroke: bool) -> Element {
        use LohenDamageEnum::*;
        match *self {
            // 非奇谋状态下普攻/重击/下落为物理，奇谋状态下转为冰元素
            A1 | A2 | A3 | A3T | A4 | A51 | A52 | Z | ZT | X1 | X2 | X3 => {
                if in_masterstroke { Element::Cryo } else { Element::Physical }
            }
            // 奇谋状态下强化普攻/重击始终为冰元素
            E1 | E2 | E3 | E3T | E4 | E51 | E52 | EZ | EZT | EG | EGT | Q | QT | C2A | C2Z => Element::Cryo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use LohenDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A3T | A4 | A51 | A52 => SkillType::NormalAttack,
            Z | ZT => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | E2 | E3 | E3T | E4 | E51 | E52 => SkillType::NormalAttack,
            EZ | EZT => SkillType::ChargedAttack,
            EG | EGT => SkillType::ElementalSkill,
            Q | QT => SkillType::ElementalBurst,
            C2A => SkillType::NormalAttack,
            C2Z => SkillType::ChargedAttack,
        }
    }
}

pub struct Lohen;

impl CharacterTrait for Lohen {
    const STATIC_DATA: CharacterStaticData = LOHEN_STATIC_DATA;
    type SkillType = LohenSkillType;
    const SKILL: Self::SkillType = LOHEN_SKILL;
    type DamageEnumType = LohenDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = Some(
        &[CharacterTag::Hexerei]
    );

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            LohenDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3, 1)
            A3T locale!(zh_cn: "三段总伤害", en: "3-Hit Total DMG")
            A4 hit_n_dmg!(4)
            A51 hit_n_dmg!(5, 1)
            A52 hit_n_dmg!(5, 2)
            Z charged_dmg!("shoot1")
            ZT locale!(zh_cn: "重击总伤害", en: "Charged Attack Total DMG")
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            C2A locale!(zh_cn: "破邪之刃伤害-普通攻击触发", en: "Evilsbane Blade DMG-Normal Attack")
        ),
        skill2: skill_map!(
            LohenDamageEnum
            E1 locale!(zh_cn: "奇谋·一段伤害", en: "Masterstroke 1-Hit DMG")
            E2 locale!(zh_cn: "奇谋·二段伤害", en: "Masterstroke 2-Hit DMG")
            E3 locale!(zh_cn: "奇谋·三段伤害", en: "Masterstroke 3-Hit DMG")
            E3T locale!(zh_cn: "奇谋·三段总伤害", en: "Masterstroke 3-Hit Total DMG")
            E4 locale!(zh_cn: "奇谋·四段伤害", en: "Masterstroke 4-Hit DMG")
            E51 locale!(zh_cn: "奇谋·五段伤害-1", en: "Masterstroke 5-Hit DMG-1")
            E52 locale!(zh_cn: "奇谋·五段伤害-2", en: "Masterstroke 5-Hit DMG-2")
            EZ locale!(zh_cn: "奇谋·重击伤害", en: "Masterstroke Charged Attack DMG")
            EZT locale!(zh_cn: "奇谋·重击总伤害", en: "Masterstroke Charged Attack Total DMG")
            EG locale!(zh_cn: "镂骨彻心伤害", en: "Etched Into Bone and Soul DMG")
            EGT locale!(zh_cn: "镂骨彻心总伤害", en: "Etched Into Bone and Soul Total DMG")
            C2Z locale!(zh_cn: "破邪之刃伤害-重击触发", en: "Evilsbane Blade DMG-Charged Attack")
        ),
        skill3: skill_map!(
            LohenDamageEnum
            Q locale!(zh_cn: "裁罚遂成伤害", en: "Manifest Judgment DMG")
            QT locale!(zh_cn: "裁罚遂成总伤害", en: "Manifest Judgment Total DMG")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::HEXEREI_SECRET_RITE_GLOBAL(false, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "avg_will_to_win",
            title: locale!(
                zh_cn: "平均争胜层数（应用一命效果前）",
                en: "Average Will to Win stacks (before C1 effect)"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 100.0, default: 80.0 }
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "in_masterstroke",
            title: locale!(
                zh_cn: "处于奇谋状态",
                en: "In Masterstroke state"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "activated_cryo_reaction",
            title: locale!(
                zh_cn: "触发冰元素相关反应（天赋2）",
                en: "Activated Cryo reaction (Talent 2)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "evilsbane_blade",
            title: locale!(
                zh_cn: "「破邪之刃」效果（命座2）",
                en: "\"Evilsbane Blade\" effect (C2)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (hexerei_secret_rite, avg_will_to_win) = match &common_data.config {
            CharacterConfig::Lohen { hexerei_secret_rite, avg_will_to_win } => (*hexerei_secret_rite, *avg_will_to_win),
            _ => (false, 0.0),
        };

        let (in_masterstroke, activated_cryo_reaction, evilsbane_blade) = match *skill_config {
            CharacterSkillConfig::Lohen { in_masterstroke, activated_cryo_reaction, evilsbane_blade } =>
                (in_masterstroke, activated_cryo_reaction, evilsbane_blade),
            _ => (false, false, false),
        };

        // P2: 戏言的杰作 —— 奇谋状态下触发冰元素相关反应后8秒内，触发者与洛恩攻击力+15%
        if common_data.has_talent2 && in_masterstroke && activated_cryo_reaction {
            attribute.set_value_by_t(
                AttributeType::Panel(AttributeName::ATKPercentage),
                "洛恩天赋2",
                0.15,
            );
        }

        // P3: 魔女的前夜礼·不愈之刺 —— 魔导秘仪：争胜≥50%时 NA/CA 增伤40%
        // 通过 avg_will_to_win 判断：未解锁C1时上限100，解锁C1时乘以5倍（上限300）
        let will_max = if common_data.constellation >= 1 { 300.0 } else { 100.0 };
        let effective_will = if common_data.constellation >= 1 {
            (avg_will_to_win * 5.0).min(will_max)
        } else {
            avg_will_to_win.min(will_max)
        };
        if hexerei_secret_rite && effective_will >= will_max * 0.5 {
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(AttributeVariableType::Bonus, SkillType::NormalAttack)),
                "洛恩天赋3",
                0.4,
            );
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(AttributeVariableType::Bonus, SkillType::ChargedAttack)),
                "洛恩天赋3",
                0.4,
            );
        }

        // C2: 破邪之刃 —— 触发后附近角色元素精通+200
        if common_data.constellation >= 2 && evilsbane_blade {
            attribute.set_value_by_s(
                CharacterSelector::select_all_except_self(attribute),
                AttributeType::Panel(AttributeName::ElementalMastery),
                "洛恩命座2",
                200.0,
            );
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: LohenDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (hexerei_secret_rite, avg_will_to_win) = match &context.character_common_data.config {
            CharacterConfig::Lohen { hexerei_secret_rite, avg_will_to_win } => (*hexerei_secret_rite, *avg_will_to_win),
            _ => (false, 0.0),
        };

        let (in_masterstroke, activated_cryo_reaction, evilsbane_blade) = match *config {
            CharacterSkillConfig::Lohen { in_masterstroke, activated_cryo_reaction, evilsbane_blade } =>
                (in_masterstroke, activated_cryo_reaction, evilsbane_blade),
            _ => (false, false, false),
        };

        // 计算有效争胜层数：
        // C1: 争胜上限变为300%，积累速度变为500%
        // 用户输入 avg_will_to_win 为应用一命效果前的平均层数
        // C4: 奇谋状态下施放Q时争胜积攒至上限
        let effective_will = if (s == Q || s == QT) && context.character_common_data.constellation >= 4 {
            // C4: Q时争胜填满至上限
            if context.character_common_data.constellation >= 1 { 300.0 } else { 100.0 }
        } else if context.character_common_data.constellation >= 1 {
            (avg_will_to_win * 5.0).min(300.0)
        } else {
            avg_will_to_win.min(100.0)
        };

        // C1 仅在奇谋状态下生效
        let will_bonus = if in_masterstroke {
            effective_will * LOHEN_SKILL.will_bonus
        } else {
            0.0
        };

        use LohenDamageEnum::*;
        let mut builder = D::new();

        // 需要奇谋状态才能触发的伤害
        if (s == E1 || s == E2 || s == E3 || s == E3T || s == E4 || s == E51 || s == E52 || s == EZ || s == EZT || s == EG || s == EGT) && !in_masterstroke {
            return builder.none();
        }

        // 需要命座才能触发的伤害
        if (s == C2A || s == C2Z) && context.character_common_data.constellation < 2 {
            return builder.none();
        }

        let ratio = match s {
            A1 => LOHEN_SKILL.a_dmg1[s1],
            A2 => LOHEN_SKILL.a_dmg2[s1],
            A3 => LOHEN_SKILL.a_dmg3[s1],
            A3T => LOHEN_SKILL.a_dmg3[s1] * 3.0,
            A4 => LOHEN_SKILL.a_dmg4[s1],
            A51 => LOHEN_SKILL.a_dmg51[s1],
            A52 => LOHEN_SKILL.a_dmg52[s1],
            Z => LOHEN_SKILL.z_dmg[s1],
            ZT => LOHEN_SKILL.z_dmg[s1] * 2.0,
            X1 => LOHEN_SKILL.x_dmg1[s1],
            X2 => LOHEN_SKILL.x_dmg2[s1],
            X3 => LOHEN_SKILL.x_dmg3[s1],
            E1 => LOHEN_SKILL.e_dmg1[s2],
            E2 => LOHEN_SKILL.e_dmg2[s2],
            E3 => LOHEN_SKILL.e_dmg3[s2],
            E3T => LOHEN_SKILL.e_dmg3[s2] * 3.0,
            E4 => LOHEN_SKILL.e_dmg4[s2],
            E51 => LOHEN_SKILL.e_dmg51[s2],
            E52 => LOHEN_SKILL.e_dmg52[s2],
            EZ => LOHEN_SKILL.e_z_dmg[s2],
            EZT => LOHEN_SKILL.e_z_dmg[s2] * 2.0,
            EG => LOHEN_SKILL.eg_dmg[s2],
            EGT => LOHEN_SKILL.eg_dmg[s2] * 4.0,
            Q => LOHEN_SKILL.q_dmg[s3],
            QT => LOHEN_SKILL.q_dmg[s3] * 6.0,
            C2A | C2Z => LOHEN_SKILL.c2_dmg,
        };

        // 镂骨彻心与元素爆发享受争胜加成
        let will_extra_ratio = match s {
            EG | EGT | Q | QT => will_bonus * ratio,
            _ => 0.0,
        };

        builder.add_atk_ratio("技能倍率", ratio);
        if will_extra_ratio > 0.0 {
            builder.add_atk_ratio("争胜加成", will_extra_ratio);
        }

        // C6: 暴击伤害+175%
        if context.character_common_data.constellation >= 6 {
            match s {
                EG | EGT | Q | QT => {
                    builder.add_extra_critical_damage("洛恩命座6", 1.75);
                }
                _ => {}
            }
        }

        builder.damage(
            &context.attribute,
            &context.enemy,
            s.get_element(in_masterstroke),
            s.get_skill_type(),
            context.character_common_data.level,
            fumo,
        )
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (hexerei_secret_rite, avg_will_to_win) = match *config {
            CharacterConfig::Lohen { hexerei_secret_rite, avg_will_to_win } => (hexerei_secret_rite, avg_will_to_win),
            _ => (false, 0.0),
        };
        Some(Box::new(LohenEffect {
            hexerei_secret_rite,
            avg_will_to_win,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
