// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::character::characters::prelude::*;

pub struct OdetteSkillType {
    // Normal Attack: 雪鹄变奏
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg31: [f64; 15],
    pub a_dmg32: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 柔板·幻灵夜舞
    pub e_dmg: [f64; 15],              // 技能伤害
    pub e_coda_dot: [f64; 15],         // 破晓终奏持续伤害
    pub e_coda_sc: [f64; 15],          // 破晓终奏星超导伤害（视为星超导反应伤害）
    pub e_coda_ss: [f64; 15],          // 破晓终奏星扩散伤害（视为星扩散反应伤害）
    pub e_plume_dmg: [f64; 15],        // 拂羽舞步伤害
    pub e_plume_sc: [f64; 15],         // 拂羽舞步星超导伤害（视为星超导反应伤害）
    pub e_plume_ss: [f64; 15],         // 拂羽舞步星扩散伤害（视为星扩散反应伤害）
    pub e_wing_dmg: [f64; 15],         // 旋翼舞步伤害
    pub e_wing_sc: [f64; 15],          // 旋翼舞步星超导伤害（视为星超导反应伤害）
    pub e_wing_ss: [f64; 15],          // 旋翼舞步星扩散伤害（视为星扩散反应伤害）

    // Elemental Burst: 疾板·苍羽一梦
    pub q_slash: [f64; 15],            // 斩击伤害（单段，共3段）
    pub q_final: [f64; 15],            // 斩击最终段伤害
    pub q_swan_dream_bonus: [f64; 15], // 雪鹄之梦星烁反应伤害提升

    // P1: 获选者的春祭
    pub p1_stellar_bonus_per_stack: f64, // 每层「华彩」星烁反应伤害提升 (0.15)
    pub p1_stacks: f64,                  // 召唤独舞倒影时获得的「华彩」层数 (4.0)

    // P2: 赤忱者的悲歌
    pub p2_base_atk: f64,         // 基准攻击力 (1000)
    pub p2_bonus_per_100_atk: f64, // 每100点攻击力额外提升 (0.015)
    pub p2_bonus_max: f64,         // 最大额外提升 (0.30)

    // P3: 星耀祝礼·银晓之舞
    pub p3_base_per_100_atk: f64, // 每100点攻击力提升基础伤害 (0.007)
    pub p3_base_max: f64,         // 最大基础伤害提升 (0.14)

    // C1: 不曾起舞的清晨，她望向倒影
    pub c1_sc_atk: f64, // 星超导额外伤害攻击力倍率 (3.0)
    pub c1_ss_atk: f64, // 星扩散额外伤害攻击力倍率 (4.5)

    // C2: 她想，我要见证雪鹄未见之梦
    pub c2_atk_per_stack: f64, // 每层「华彩」攻击力提升 (0.07)
    pub c2_res_minus: f64,     // 独舞倒影附近敌人对应元素抗性降低 (0.20)

    // C4: 向上，坠往恍惚、燃烧的蓝空
    pub c4_sc_atk: f64, // 星超导协同攻击攻击力倍率 (0.66)
    pub c4_ss_atk: f64, // 星扩散协同攻击攻击力倍率 (0.99)

    // C6: 伸出手，触及苍穹永恒的面容
    pub c6_elevate_all: f64,  // 受「华彩」影响角色星烁反应伤害擢升 (0.25)
    pub c6_elevate_self: f64, // 奥黛塔自身额外擢升 (0.20)
}

pub const ODETTE_SKILL: OdetteSkillType = OdetteSkillType {
    // Normal Attack: 雪鹄变奏
    a_dmg1: [0.5186, 0.5608, 0.603, 0.6633, 0.7055, 0.7537, 0.8201, 0.8864, 0.9527, 1.0251, 1.0974, 1.1698, 1.2422, 1.3145, 1.3869],
    a_dmg2: [0.5151, 0.557, 0.599, 0.6589, 0.7008, 0.7487, 0.8146, 0.8805, 0.9464, 1.0182, 1.0901, 1.162, 1.2339, 1.3057, 1.3776],
    a_dmg31: [0.3261, 0.3527, 0.3792, 0.4171, 0.4437, 0.474, 0.5157, 0.5574, 0.5991, 0.6446, 0.6901, 0.7356, 0.7812, 0.8267, 0.8722],
    a_dmg32: [0.3828, 0.4139, 0.4451, 0.4896, 0.5208, 0.5564, 0.6053, 0.6543, 0.7033, 0.7567, 0.8101, 0.8635, 0.9169, 0.9703, 1.0237],
    a_dmg4: [0.7457, 0.8064, 0.8671, 0.9538, 1.0145, 1.0839, 1.1793, 1.2747, 1.3701, 1.4741, 1.5782, 1.6822, 1.7863, 1.8903, 1.9944],
    a_dmg5: [0.9021, 0.9756, 1.049, 1.1539, 1.2273, 1.3112, 1.4266, 1.542, 1.6574, 1.7833, 1.9091, 2.035, 2.1609, 2.2868, 2.4127],
    z_dmg: [1.0741, 1.1616, 1.249, 1.3739, 1.4613, 1.5612, 1.6986, 1.836, 1.9734, 2.1233, 2.2732, 2.4231, 2.5729, 2.7228, 2.8727],
    x_dmg1: [0.6393, 0.6914, 0.7434, 0.8177, 0.8698, 0.9293, 1.011, 1.0928, 1.1746, 1.2638, 1.353, 1.4422, 1.5314, 1.6206, 1.7098],
    x_dmg2: [1.2784, 1.3824, 1.4865, 1.6351, 1.7392, 1.8581, 2.0216, 2.1851, 2.3486, 2.527, 2.7054, 2.8838, 3.0622, 3.2405, 3.4189],
    x_dmg3: [1.5968, 1.7267, 1.8567, 2.0424, 2.1723, 2.3209, 2.5251, 2.7293, 2.9336, 3.1564, 3.3792, 3.602, 3.8248, 4.0476, 4.2704],

    // Elemental Skill: 柔板·幻灵夜舞
    e_dmg: [1.0808, 1.1619, 1.2429, 1.351, 1.4321, 1.5131, 1.6212, 1.7293, 1.8374, 1.9454, 2.0535, 2.1616, 2.2967, 2.4318, 2.5669],
    e_coda_dot: [0.9584, 1.0303, 1.1022, 1.198, 1.2699, 1.3418, 1.4376, 1.5334, 1.6293, 1.7251, 1.821, 1.9168, 2.0366, 2.1564, 2.2762],
    e_coda_sc: [3.0576, 3.2869, 3.5162, 3.822, 4.0513, 4.2806, 4.5864, 4.8922, 5.1979, 5.5037, 5.8094, 6.1152, 6.4974, 6.8796, 7.2618],
    e_coda_ss: [4.5864, 4.9304, 5.2744, 5.733, 6.077, 6.421, 6.8796, 7.3382, 7.7969, 8.2555, 8.7142, 9.1728, 9.7461, 10.3194, 10.8927],
    e_plume_dmg: [0.4304, 0.4627, 0.495, 0.538, 0.5703, 0.6026, 0.6456, 0.6886, 0.7317, 0.7747, 0.8178, 0.8608, 0.9146, 0.9684, 1.0222],
    e_plume_sc: [0.2702, 0.2905, 0.3108, 0.3378, 0.3581, 0.3783, 0.4054, 0.4324, 0.4594, 0.4864, 0.5135, 0.5405, 0.5743, 0.608, 0.6418],
    e_plume_ss: [0.4053, 0.4357, 0.4661, 0.5066, 0.537, 0.5674, 0.6079, 0.6484, 0.689, 0.7295, 0.77, 0.8106, 0.8612, 0.9119, 0.9625],
    e_wing_dmg: [0.5146, 0.5532, 0.5918, 0.6433, 0.6819, 0.7205, 0.772, 0.8234, 0.8749, 0.9264, 0.9778, 1.0293, 1.0936, 1.1579, 1.2223],
    e_wing_sc: [0.3231, 0.3474, 0.3716, 0.4039, 0.4281, 0.4524, 0.4847, 0.517, 0.5493, 0.5816, 0.6139, 0.6462, 0.6866, 0.727, 0.7674],
    e_wing_ss: [0.4846, 0.521, 0.5573, 0.6058, 0.6421, 0.6785, 0.727, 0.7754, 0.8239, 0.8724, 0.9208, 0.9693, 1.0299, 1.0904, 1.151],

    // Elemental Burst: 疾板·苍羽一梦
    q_slash: [1.1018, 1.1844, 1.267, 1.3772, 1.4598, 1.5425, 1.6526, 1.7628, 1.873, 1.9832, 2.0933, 2.2035, 2.3412, 2.479, 2.6167],
    q_final: [1.7027, 1.8304, 1.9581, 2.1284, 2.2561, 2.3838, 2.5541, 2.7244, 2.8946, 3.0649, 3.2352, 3.4054, 3.6183, 3.8311, 4.044],
    q_swan_dream_bonus: [0.14, 0.18, 0.22, 0.26, 0.30, 0.34, 0.38, 0.42, 0.46, 0.50, 0.54, 0.58, 0.62, 0.66, 0.70],

    // P1: 获选者的春祭 — 召唤独舞倒影时获得4层华彩，每层使星烁反应伤害提升15%
    p1_stellar_bonus_per_stack: 0.15,
    p1_stacks: 4.0,

    // P2: 赤忱者的悲歌 — 攻击力超过1000的部分，每100点使星烁反应伤害额外造成原本1.5%的伤害，至多30%
    p2_base_atk: 1000.0,
    p2_bonus_per_100_atk: 0.015,
    p2_bonus_max: 0.30,

    // P3: 星耀祝礼·银晓之舞 — 每100点攻击力提升队伍星超导/星扩散基础伤害0.7%，至多14%
    p3_base_per_100_atk: 0.007,
    p3_base_max: 0.14,

    // C1: 额外一次视为星超导（300%）/星扩散（450%）反应伤害
    c1_sc_atk: 3.0,
    c1_ss_atk: 4.5,

    // C2: 每层华彩提升7%攻击力；独舞倒影在场且辉映状态下敌人对应元素抗性降低20%
    c2_atk_per_stack: 0.07,
    c2_res_minus: 0.20,

    // C4: 协同攻击，视为星超导（66%）/星扩散（99%）反应伤害
    c4_sc_atk: 0.66,
    c4_ss_atk: 0.99,

    // C6: 受华彩影响角色星烁反应伤害擢升25%，奥黛塔额外擢升20%
    c6_elevate_all: 0.25,
    c6_elevate_self: 0.20,
};

pub const ODETTE_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Odette,
    internal_name: "Odette",
    element: Element::Cryo,
    hp: [1011, 2621, 3574, 5219, 5921, 6712, 7621, 8421, 9125, 9932, 10637, 11453, 12159, 12981, 13903],
    atk: [26, 68, 92, 135, 153, 173, 197, 217, 235, 256, 274, 295, 314, 335, 410],
    def: [61, 159, 217, 316, 359, 407, 462, 511, 553, 602, 645, 694, 737, 787, 843],
    sub_stat: CharacterSubStatFamily::CriticalDamage384,
    weapon_type: WeaponType::Sword,
    star: 5,
    skill_name1: locale!(
        zh_cn: "雪鹄变奏",
        en: "Snow Swan Variation",
    ),
    skill_name2: locale!(
        zh_cn: "柔板·幻灵夜舞",
        en: "Adagio: Phantom Night Dancers",
    ),
    skill_name3: locale!(
        zh_cn: "疾板·苍羽一梦",
        en: "Presto: Bluebird Finale",
    ),
    name_locale: locale!(
        zh_cn: "奥黛塔",
        en: "Odette",
    ),
};

pub struct OdetteEffect {
    pub stellar_glimmer_state: usize,
    pub stellar_conduct_application_count: usize,
    pub marvelous_splendor_self: f64,  // 「华彩」自身平均层数（由用户在角色配置中给出）
    pub marvelous_splendor_other: f64, // 「华彩」其他角色平均层数（奥黛塔后台时转移给队友）
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for OdetteEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋1：获选者的春祭 — 每层「华彩」使角色星烁反应伤害提升15%
        // 注：华彩层数在召唤后随时间（奥黛塔处于后台时每秒减少并转移给队友）动态变化，
        // 此处分别以「自身平均层数」与「其他角色平均层数」近似计算。
        if self.common_data.has_talent1 {
            // 奥黛塔自身持有的「华彩」
            let self_bonus = self.marvelous_splendor_self * ODETTE_SKILL.p1_stellar_bonus_per_stack;
            if self_bonus > 0.0 {
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔天赋1",
                    self_bonus,
                );
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔天赋1",
                    self_bonus,
                );
            }
            // 队伍中其他角色持有的「华彩」（奥黛塔处于后台时转移）
            let other_bonus = self.marvelous_splendor_other * ODETTE_SKILL.p1_stellar_bonus_per_stack;
            if other_bonus > 0.0 {
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔天赋1·队友",
                    other_bonus,
                );
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔天赋1·队友",
                    other_bonus,
                );
            }
        }

        // 天赋2：赤忱者的悲歌 — 攻击力超过1000的部分，每100点使星烁反应伤害额外造成原本1.5%的伤害，至多30%
        if self.common_data.has_talent2 {
            let bonus = Arc::new(move |atk: f64, _| {
                if atk > ODETTE_SKILL.p2_base_atk {
                    ((atk - ODETTE_SKILL.p2_base_atk) / 100.0 * ODETTE_SKILL.p2_bonus_per_100_atk)
                        .min(ODETTE_SKILL.p2_bonus_max)
                } else {
                    0.0
                }
            });
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                bonus.clone(),
                "奥黛塔天赋2",
                EdgePriority::Invisible,
            );
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                bonus,
                "奥黛塔天赋2",
                EdgePriority::Invisible,
            );
        }

        // 天赋3：星耀祝礼·银晓之舞 — 处于辉映·星超导/星扩散状态时，队伍角色触发超导/冰扩散
        // 转为星超导/星扩散，并基于奥黛塔攻击力提升该反应的基础伤害（每100点攻击力+0.7%，至多14%）
        // 仅增强与当前辉映状态对应的反应（无辉映状态不提供增益）
        let base_bonus = Arc::new(move |atk: f64, _| {
            (atk / 100.0 * ODETTE_SKILL.p3_base_per_100_atk).min(ODETTE_SKILL.p3_base_max)
        });
        if self.stellar_glimmer_state == 1 {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeBase,
                    ReactionType::StellarConduct,
                )),
                base_bonus.clone(),
                "奥黛塔天赋3",
                EdgePriority::Invisible,
            );
        }
        if self.stellar_glimmer_state == 2 {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeBase,
                    ReactionType::StellarSwirl,
                )),
                base_bonus,
                "奥黛塔天赋3",
                EdgePriority::Invisible,
            );
        }

        // 命座2：她想，我要见证雪鹄未见之梦 — 每层「华彩」使角色攻击力提升7%
        if self.common_data.constellation >= 2 {
            // 奥黛塔自身持有的「华彩」
            let self_atk_bonus = self.marvelous_splendor_self * ODETTE_SKILL.c2_atk_per_stack;
            if self_atk_bonus > 0.0 {
                attribute.add_atk_percentage("奥黛塔命座2", self_atk_bonus);
            }
            // 队伍中其他角色持有的「华彩」
            let other_atk_bonus = self.marvelous_splendor_other * ODETTE_SKILL.c2_atk_per_stack;
            if other_atk_bonus > 0.0 {
                attribute.add_atk_percentage_s(
                    CharacterSelector::select_all_except_self(attribute),
                    "奥黛塔命座2·队友",
                    other_atk_bonus,
                );
            }
        }

        // 命座6：伸出手，触及苍穹永恒的面容 — 受「华彩」影响的角色星烁反应伤害擢升25%，
        // 奥黛塔对敌人造成的星烁反应伤害额外擢升20%
        if self.common_data.constellation >= 6 {
            // 奥黛塔自身持有「华彩」：擢升25%，且额外擢升20%
            if self.marvelous_splendor_self > 0.0 {
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔命座6",
                    ODETTE_SKILL.c6_elevate_all,
                );
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔命座6",
                    ODETTE_SKILL.c6_elevate_all,
                );
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔命座6·自身",
                    ODETTE_SKILL.c6_elevate_self,
                );
                attribute.set_value_by_t(
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔命座6·自身",
                    ODETTE_SKILL.c6_elevate_self,
                );
            }
            // 队伍中其他角色持有「华彩」：擢升25%
            if self.marvelous_splendor_other > 0.0 {
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔命座6·队友",
                    ODETTE_SKILL.c6_elevate_all,
                );
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ElevativeElevate,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔命座6·队友",
                    ODETTE_SKILL.c6_elevate_all,
                );
            }
        }

        // 星超导附着次数 → ElevativeCoefficient
        ElevativeReaction::apply_stellar_conduct_extra_coefficient(attribute, self.stellar_conduct_application_count);
    }
}

damage_enum!(
    OdetteDamageEnum
    A1          // 一段伤害
    A2          // 二段伤害
    A31         // 三段伤害（第一击）
    A32         // 三段伤害（第二击）
    A4          // 四段伤害
    A5          // 五段伤害
    Z           // 重击伤害
    X1          // 下坠期间伤害
    X2          // 低空坠地冲击伤害
    X3          // 高空坠地冲击伤害
    E           // 元素战技伤害（召唤独舞倒影）
    EC_DOT      // 破晓终奏持续伤害
    EC          // 破晓终奏共舞结束伤害（视为星超导/星扩散反应伤害）
    EP          // 拂羽舞步伤害（独舞倒影）
    EP_STELLAR  // 拂羽舞步星超导/星扩散伤害（视为星超导/星扩散反应伤害）
    EW          // 旋翼舞步伤害（独舞倒影）
    EW_STELLAR  // 旋翼舞步星超导/星扩散伤害（视为星超导/星扩散反应伤害）
    Q           // 元素爆发斩击伤害（单段）
    Q_TOTAL     // 元素爆发斩击总伤害（×3）
    QF          // 斩击最终段伤害
    C1          // 命座1额外伤害（视为星超导/星扩散反应伤害）
    C4          // 命座4协同攻击（视为星超导/星扩散反应伤害）
);

impl OdetteDamageEnum {
    pub fn get_element(&self) -> Element {
        use OdetteDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | A5 | Z | X1 | X2 | X3 => Element::Physical,
            E | EC_DOT | EC | EP | EP_STELLAR | EW | EW_STELLAR | Q | Q_TOTAL | QF | C1 | C4 => Element::Cryo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use OdetteDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | A5 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E | EC_DOT | EP | EW => SkillType::ElementalSkill,
            // 所有视为星超导/星扩散反应伤害的技能类型均为擢升反应
            EC | EP_STELLAR | EW_STELLAR | C1 | C4 => SkillType::Elevative,
            Q | Q_TOTAL | QF => SkillType::ElementalBurst,
        }
    }

    pub fn get_elevative_type(&self, stellar_glimmer_state: usize) -> Option<ElevativeReaction> {
        use OdetteDamageEnum::*;
        match *self {
            // 破晓终奏共舞结束伤害与命座伤害：
            // 无辉映状态或辉映·星超导时视为星超导，辉映·星扩散时视为星扩散
            EC | C1 | C4 => {
                if stellar_glimmer_state == 2 {
                    Some(ElevativeReaction::StellarSwirlCryo)
                } else {
                    Some(ElevativeReaction::StellarConductCryo)
                }
            }
            // 独舞倒影舞步的星烁额外伤害：仅辉映状态下触发
            EP_STELLAR | EW_STELLAR => match stellar_glimmer_state {
                1 => Some(ElevativeReaction::StellarConductCryo),
                2 => Some(ElevativeReaction::StellarSwirlCryo),
                _ => None,
            },
            _ => None,
        }
    }
}

pub struct Odette;

impl CharacterTrait for Odette {
    const STATIC_DATA: CharacterStaticData = ODETTE_STATIC_DATA;
    type SkillType = OdetteSkillType;
    const SKILL: Self::SkillType = ODETTE_SKILL;
    type DamageEnumType = OdetteDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            OdetteDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A31 hit_n_dmg!(3, 1)
            A32 hit_n_dmg!(3, 2)
            A4 hit_n_dmg!(4)
            A5 hit_n_dmg!(5)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            OdetteDamageEnum
            E locale!(zh_cn: "技能伤害", en: "Skill DMG")
            EC_DOT locale!(zh_cn: "破晓终奏持续伤害", en: "Coda at Dawn's Tolling DoT")
            EC locale!(zh_cn: "破晓终奏星超导/星扩散伤害", en: "Coda at Dawn's Tolling Stellar-Conduct/Stellar Swirl DMG")
            EP locale!(zh_cn: "拂羽舞步伤害", en: "\"Plume\" Dance Move DMG")
            EP_STELLAR locale!(zh_cn: "拂羽舞步星超导/星扩散伤害", en: "\"Plume\" Dance Move Stellar-Conduct/Stellar Swirl DMG")
            EW locale!(zh_cn: "旋翼舞步伤害", en: "\"Wing\" Dance Move DMG")
            EW_STELLAR locale!(zh_cn: "旋翼舞步星超导/星扩散伤害", en: "\"Wing\" Dance Move Stellar-Conduct/Stellar Swirl DMG")
            C1 locale!(zh_cn: "命座1额外伤害", en: "C1 Additional DMG")
        ),
        skill3: skill_map!(
            OdetteDamageEnum
            Q locale!(zh_cn: "斩击伤害（单段）", en: "Slash DMG (per hit)")
            Q_TOTAL locale!(zh_cn: "斩击总伤害", en: "Slash Total DMG")
            QF locale!(zh_cn: "斩击最终段伤害", en: "Final Slash DMG")
            C4 locale!(zh_cn: "命座4协同攻击", en: "C4 Coordinated Attack")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "marvelous_splendor_self",
            title: locale!(
                zh_cn: "自身「华彩」平均层数（召唤独舞倒影时4层，命座1为6层；后台每秒减少）",
                en: "Self Marvelous Splendor Avg. Stacks (4 on summon, 6 with C1; decays off-field)"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 6.0, default: 4.0 }
        },
        ItemConfig {
            name: "marvelous_splendor_other",
            title: locale!(
                zh_cn: "其他角色「华彩」平均层数（奥黛塔处于后台时转移给队友）",
                en: "Other Characters Marvelous Splendor Avg. Stacks (transferred to teammates when Odette off-field)"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 6.0, default: 0.0 }
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "activated_coda",
            title: locale!(
                zh_cn: "施放「柔板·破晓终奏」（元素战技施放后6秒内可用）",
                en: "Cast Adagio: Coda at Dawn's Tolling (available 6s after Elemental Skill)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "has_dance_double",
            title: locale!(
                zh_cn: "「独舞倒影」在场",
                en: "Solo Dance Double on Field"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "snow_swans_dream_active",
            title: locale!(
                zh_cn: "「雪鹄之梦」生效",
                en: "Snow Swan's Dream Active"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (stellar_glimmer_state, _, _) = match &common_data.config {
            CharacterConfig::Odette { stellar_glimmer_state, .. } => (*stellar_glimmer_state, 0, 0.0),
            _ => (0, 0, 0.0),
        };

        let (activated_coda, has_dance_double, snow_swans_dream_active) = match *skill_config {
            CharacterSkillConfig::Odette { activated_coda, has_dance_double, snow_swans_dream_active } =>
                (activated_coda, has_dance_double, snow_swans_dream_active),
            _ => (false, false, false),
        };
        let _ = activated_coda;

        let (_, _, s3) = common_data.get_3_skill();

        // 命座2：独舞倒影在场且奥黛塔处于辉映·星烁状态时，独舞倒影附近敌人的对应元素抗性降低20%
        // - 辉映·星超导：冰、雷元素抗性降低20%
        // - 辉映·星扩散：冰、风元素抗性降低20%
        if common_data.constellation >= 2 && has_dance_double {
            match stellar_glimmer_state {
                1 => {
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Cryo)),
                        "奥黛塔命座2",
                        ODETTE_SKILL.c2_res_minus,
                    );
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Electro)),
                        "奥黛塔命座2",
                        ODETTE_SKILL.c2_res_minus,
                    );
                }
                2 => {
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Cryo)),
                        "奥黛塔命座2",
                        ODETTE_SKILL.c2_res_minus,
                    );
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, Element::Anemo)),
                        "奥黛塔命座2",
                        ODETTE_SKILL.c2_res_minus,
                    );
                }
                _ => {}
            }
        }

        // 元素爆发：雪鹄之梦 — 提升奥黛塔造成的星烁反应伤害（基于元素爆发等级）
        if snow_swans_dream_active {
            let bonus = ODETTE_SKILL.q_swan_dream_bonus[s3];
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "奥黛塔技能Q",
                bonus,
            );
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "奥黛塔技能Q",
                bonus,
            );

            // 命座4：奥黛塔获得雪鹄之梦时，队伍中附近的其他角色造成的星烁反应伤害提升，
            // 提升值相当于雪鹄之梦效果的50%
            if common_data.constellation >= 4 {
                let team_bonus = bonus * 0.5;
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarConduct,
                    )),
                    "奥黛塔命座4",
                    team_bonus,
                );
                attribute.set_value_to_s(
                    CharacterSelector::select_all_except_self(attribute),
                    AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                        AttributeVariableType::ReactionEnhance,
                        ReactionType::StellarSwirl,
                    )),
                    "奥黛塔命座4",
                    team_bonus,
                );
            }
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: OdetteDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (stellar_glimmer_state, stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other) = match &context.character_common_data.config {
            CharacterConfig::Odette { stellar_glimmer_state, stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other } =>
                (*stellar_glimmer_state, *stellar_conduct_application_count, *marvelous_splendor_self, *marvelous_splendor_other),
            _ => (0, 0, 0.0, 0.0),
        };
        let _ = (stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other);

        let (activated_coda, has_dance_double, snow_swans_dream_active) = match *config {
            CharacterSkillConfig::Odette { activated_coda, has_dance_double, snow_swans_dream_active } =>
                (activated_coda, has_dance_double, snow_swans_dream_active),
            _ => (false, false, false),
        };
        let _ = snow_swans_dream_active;

        use OdetteDamageEnum::*;
        let mut builder = D::new();

        // 条件检查
        // 破晓终奏相关伤害：需施放特殊元素战技「柔板·破晓终奏」
        if matches!(s, EC_DOT | EC | C1) && !activated_coda {
            return builder.none();
        }
        // 独舞倒影舞步伤害：需独舞倒影在场
        if matches!(s, EP | EW | EP_STELLAR | EW_STELLAR) && !has_dance_double {
            return builder.none();
        }
        // 舞步的星烁额外伤害：需施放特殊元素战技「柔板·破晓终奏」，且处于辉映·星烁状态
        if matches!(s, EP_STELLAR | EW_STELLAR) && (!activated_coda || stellar_glimmer_state == 0) {
            return builder.none();
        }
        // 命座伤害条件
        if s == C1 && context.character_common_data.constellation < 1 {
            return builder.none();
        }
        if s == C4 && context.character_common_data.constellation < 4 {
            return builder.none();
        }

        // 星反应类型判定：辉映·星扩散（state 2）为星扩散，其余（无辉映/辉映·星超导）为星超导
        let is_stellar_swirl = stellar_glimmer_state == 2;

        let ratio = match s {
            A1 => ODETTE_SKILL.a_dmg1[s1],
            A2 => ODETTE_SKILL.a_dmg2[s1],
            A31 => ODETTE_SKILL.a_dmg31[s1],
            A32 => ODETTE_SKILL.a_dmg32[s1],
            A4 => ODETTE_SKILL.a_dmg4[s1],
            A5 => ODETTE_SKILL.a_dmg5[s1],
            Z => ODETTE_SKILL.z_dmg[s1],
            X1 => ODETTE_SKILL.x_dmg1[s1],
            X2 => ODETTE_SKILL.x_dmg2[s1],
            X3 => ODETTE_SKILL.x_dmg3[s1],
            E => ODETTE_SKILL.e_dmg[s2],
            EC_DOT => ODETTE_SKILL.e_coda_dot[s2],
            EC => if is_stellar_swirl {
                ODETTE_SKILL.e_coda_ss[s2]
            } else {
                ODETTE_SKILL.e_coda_sc[s2]
            },
            EP => ODETTE_SKILL.e_plume_dmg[s2],
            EP_STELLAR => if stellar_glimmer_state == 1 {
                ODETTE_SKILL.e_plume_sc[s2]
            } else {
                ODETTE_SKILL.e_plume_ss[s2]
            },
            EW => ODETTE_SKILL.e_wing_dmg[s2],
            EW_STELLAR => if stellar_glimmer_state == 1 {
                ODETTE_SKILL.e_wing_sc[s2]
            } else {
                ODETTE_SKILL.e_wing_ss[s2]
            },
            Q => ODETTE_SKILL.q_slash[s3],
            Q_TOTAL => ODETTE_SKILL.q_slash[s3] * 3.0,
            QF => ODETTE_SKILL.q_final[s3],
            C1 => if is_stellar_swirl {
                ODETTE_SKILL.c1_ss_atk
            } else {
                ODETTE_SKILL.c1_sc_atk
            },
            C4 => if is_stellar_swirl {
                ODETTE_SKILL.c4_ss_atk
            } else {
                ODETTE_SKILL.c4_sc_atk
            },
        };

        builder.add_atk_ratio("技能倍率", ratio);

        if let Some(elevative_type) = s.get_elevative_type(stellar_glimmer_state) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (stellar_glimmer_state, stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other) = match *config {
            CharacterConfig::Odette { stellar_glimmer_state, stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other } =>
                (stellar_glimmer_state, stellar_conduct_application_count, marvelous_splendor_self, marvelous_splendor_other),
            _ => (0, 0, 0.0, 0.0),
        };
        // 「华彩」层数上限：基础召唤为4层，命座1额外获得2层（共6层），非1命角色钳制为4层
        let max_stacks = if common_data.constellation >= 1 { 6.0 } else { 4.0 };
        let marvelous_splendor_self = marvelous_splendor_self.min(max_stacks);
        let marvelous_splendor_other = marvelous_splendor_other.min(max_stacks);
        Some(Box::new(OdetteEffect {
            stellar_glimmer_state,
            stellar_conduct_application_count,
            marvelous_splendor_self,
            marvelous_splendor_other,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
