// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct QiqiSkillType {
    // Normal Attack: 云来古剑法
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg31: [f64; 15],
    pub a_dmg32: [f64; 15],
    pub a_dmg41: [f64; 15],
    pub a_dmg42: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub z_dmg1: [f64; 15],
    pub z_dmg2: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 仙法·寒病鬼差
    pub e_dmg: [f64; 15],               // 技能伤害 (param8)
    pub e_dot: [f64; 15],               // 寒病鬼差伤害 (param5)
    pub e_coord: [f64; 15],             // 寒病鬼差协同攻击伤害 (param9)
    pub e_heal_hit_ratio: [f64; 15],    // 命中治疗量 攻击力比例 (param1)
    pub e_heal_hit_fixed: [f64; 15],    // 命中治疗量 固定值 (param2)
    pub e_heal_cont_ratio: [f64; 15],   // 持续治疗量 攻击力比例 (param3)
    pub e_heal_cont_fixed: [f64; 15],   // 持续治疗量 固定值 (param4)

    // Elemental Burst: 仙法·救苦度厄
    pub q_dmg: [f64; 15],               // 技能伤害 (param3)
    pub q_sc_dmg: [f64; 15],            // 星超导伤害 (param7)
    pub q_heal_ratio: [f64; 15],        // 治疗量 攻击力比例 (param1)
    pub q_heal_fixed: [f64; 15],        // 治疗量 固定值 (param2)

    // P3: 七宝奉真
    pub p3_sc_bonus: f64,               // 超导/星超导反应伤害提升 (0.5)

    // C2: 冰寒蚀骨 (辉映·星超导)
    pub c2_atk_bonus: f64,              // 攻击力提升 (0.5)
    pub c2_cryo_bonus: f64,             // 对冰附着普攻重击伤害提升 (0.15)

    // C4: 天威压众
    pub c4_atk_reduce: f64,             // 标记目标攻击力下降 (0.2)
    pub c4_extra_heal_ratio: f64,       // 额外治疗攻击力比例 (1.8)

    // C6: 起死回骸
    pub c6_bonus_per_stack: f64,        // 每层洞玄提升攻击力比例 (6.0)
}

pub const QIQI_SKILL: QiqiSkillType = QiqiSkillType {
    // Normal Attack: 云来古剑法
    a_dmg1: [0.37754, 0.40827, 0.439, 0.4829, 0.51363, 0.54875, 0.59704, 0.64533, 0.69362, 0.7463, 0.79898, 0.85166, 0.90434, 0.95702, 1.0097],
    a_dmg2: [0.38872, 0.42036, 0.452, 0.4972, 0.52884, 0.565, 0.61472, 0.66444, 0.71416, 0.7684, 0.82264, 0.87688, 0.93112, 0.98536, 1.0396],
    a_dmg31: [0.24166, 0.26133, 0.281, 0.3091, 0.32877, 0.35125, 0.38216, 0.41307, 0.44398, 0.4777, 0.51142, 0.54514, 0.57886, 0.61258, 0.6463],
    a_dmg32: [0.24166, 0.26133, 0.281, 0.3091, 0.32877, 0.35125, 0.38216, 0.41307, 0.44398, 0.4777, 0.51142, 0.54514, 0.57886, 0.61258, 0.6463],
    a_dmg41: [0.24682, 0.26691, 0.287, 0.3157, 0.33579, 0.35875, 0.39032, 0.42189, 0.45346, 0.4879, 0.52234, 0.55678, 0.59122, 0.62566, 0.6601],
    a_dmg42: [0.24682, 0.26691, 0.287, 0.3157, 0.33579, 0.35875, 0.39032, 0.42189, 0.45346, 0.4879, 0.52234, 0.55678, 0.59122, 0.62566, 0.6601],
    a_dmg5: [0.63038, 0.68169, 0.733, 0.8063, 0.85761, 0.91625, 0.99688, 1.07751, 1.15814, 1.2461, 1.33406, 1.42202, 1.50998, 1.59794, 1.6859],
    z_dmg1: [0.64328, 0.69564, 0.748, 0.8228, 0.87516, 0.935, 1.01728, 1.09956, 1.18184, 1.2716, 1.36136, 1.45112, 1.54088, 1.63064, 1.7204],
    z_dmg2: [0.64328, 0.69564, 0.748, 0.8228, 0.87516, 0.935, 1.01728, 1.09956, 1.18184, 1.2716, 1.36136, 1.45112, 1.54088, 1.63064, 1.7204],
    x_dmg1: [0.639324, 0.691362, 0.7434, 0.81774, 0.869778, 0.92925, 1.011024, 1.092798, 1.174572, 1.26378, 1.352988, 1.442196, 1.531404, 1.620612, 1.70982],
    x_dmg2: [1.278377, 1.382431, 1.486485, 1.635134, 1.739187, 1.858106, 2.02162, 2.185133, 2.348646, 2.527025, 2.705403, 2.883781, 3.062159, 3.240537, 3.418915],
    x_dmg3: [1.596762, 1.726731, 1.8567, 2.04237, 2.172339, 2.320875, 2.525112, 2.729349, 2.933586, 3.15639, 3.379194, 3.601998, 3.824802, 4.047606, 4.27041],

    // Elemental Skill: 仙法·寒病鬼差
    e_dmg: [0.96, 1.032, 1.104, 1.2, 1.272, 1.344, 1.44, 1.536, 1.632, 1.728, 1.824, 1.92, 2.04, 2.16, 2.28],
    e_dot: [0.36, 0.387, 0.414, 0.45, 0.477, 0.504, 0.54, 0.576, 0.612, 0.648, 0.684, 0.72, 0.765, 0.81, 0.855],
    e_coord: [0.24, 0.258, 0.276, 0.3, 0.318, 0.336, 0.36, 0.384, 0.408, 0.432, 0.456, 0.48, 0.51, 0.54, 0.57],
    e_heal_hit_ratio: [0.1056, 0.11352, 0.12144, 0.132, 0.13992, 0.14784, 0.1584, 0.16896, 0.17952, 0.19008, 0.20064, 0.2112, 0.2244, 0.2376, 0.2508],
    e_heal_hit_fixed: [67.0, 74.0, 81.0, 89.0, 98.0, 107.0, 116.0, 126.0, 137.0, 148.0, 160.0, 172.0, 185.0, 199.0, 213.0],
    e_heal_cont_ratio: [0.696, 0.7482, 0.8004, 0.87, 0.9222, 0.9744, 1.044, 1.1136, 1.1832, 1.2528, 1.3224, 1.392, 1.479, 1.566, 1.653],
    e_heal_cont_fixed: [451.0, 496.0, 544.0, 597.0, 653.0, 713.0, 777.0, 845.0, 916.0, 991.0, 1070.0, 1153.0, 1239.0, 1329.0, 1423.0],

    // Elemental Burst: 仙法·救苦度厄
    q_dmg: [2.848, 3.0616, 3.2752, 3.56, 3.7736, 3.9872, 4.272, 4.5568, 4.8416, 5.1264, 5.4112, 5.696, 6.052, 6.408, 6.764],
    q_sc_dmg: [2.973336, 3.196336, 3.419336, 3.71667, 3.93967, 4.16267, 4.460004, 4.757338, 5.054671, 5.352005, 5.649338, 5.946672, 6.318339, 6.690006, 7.061673],
    q_heal_ratio: [0.9, 0.9675, 1.035, 1.125, 1.1925, 1.26, 1.35, 1.44, 1.53, 1.62, 1.71, 1.8, 1.9125, 2.025, 2.1375],
    q_heal_fixed: [577.0, 635.0, 698.0, 765.0, 837.0, 914.0, 996.0, 1083.0, 1174.0, 1270.0, 1371.0, 1477.0, 1588.0, 1703.0, 1824.0],

    // P3: 七宝奉真
    p3_sc_bonus: 0.5,

    // C2: 冰寒蚀骨
    c2_atk_bonus: 0.5,
    c2_cryo_bonus: 0.15,

    // C4: 天威压众
    c4_atk_reduce: 0.2,
    c4_extra_heal_ratio: 1.8,

    // C6: 起死回骸
    c6_bonus_per_stack: 6.0,
};

pub const QIQI_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Qiqi,
    internal_name: "Qiqi",
    element: Element::Cryo,
    hp: [963, 2498, 3323, 4973, 5559, 6396, 7178, 8023, 8610, 9463, 10050, 10912, 11499, 12368, 13247],
    atk: [22, 58, 77, 115, 129, 148, 167, 186, 200, 220, 233, 253, 267, 287, 352],
    def: [72, 186, 248, 371, 415, 477, 535, 598, 642, 706, 749, 814, 857, 922, 988],
    sub_stat: CharacterSubStatFamily::HealingBonus222,
    weapon_type: WeaponType::Sword,
    star: 5,
    skill_name1: locale!(
        zh_cn: "云来古剑法",
        en: "Normal Attack: Ancient Sword Art",
    ),
    skill_name2: locale!(
        zh_cn: "仙法·寒病鬼差",
        en: "Adeptus Art: Herald of Frost",
    ),
    skill_name3: locale!(
        zh_cn: "仙法·救苦度厄",
        en: "Adeptus Art: Preserver of Fortune",
    ),
    name_locale: locale!(
        zh_cn: "七七",
        en: "Qiqi",
    )
};

pub struct QiqiEffect {
    pub in_pole_star_field: bool,
    pub stellar_conduct_application_count: i32,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for QiqiEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P1: 延命妙法 — E状态下角色触发元素反应时受治疗加成+20%
        // E技能跟随当前场上角色，近似100%覆盖
        if self.in_pole_star_field && self.common_data.has_talent1 {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::IncomingHealingBonus)),
                "七七天赋1",
                0.2,
            );
        }

        // P3: 辉映·星超导 — 寒病鬼差持续期间，队伍中超导/星超导反应伤害+50%
        // E技能15s持续/15s冷却，近似100%覆盖
        if self.in_pole_star_field {
            attribute.set_value_to_s(
                CharacterSelector::select_team(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "七七天赋3",
                QIQI_SKILL.p3_sc_bonus,
            );
            attribute.set_value_to_s(
                CharacterSelector::select_team(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::Superconduct,
                )),
                "七七天赋3",
                QIQI_SKILL.p3_sc_bonus,
            );
        }

        // C2: 辉映·星超导 — 攻击力+50%
        if self.in_pole_star_field && self.common_data.constellation >= 2 {
            attribute.set_value_by_t(
                AttributeType::Panel(AttributeName::ATKPercentage),
                "七七命座2",
                QIQI_SKILL.c2_atk_bonus,
            );
        }

        // C4: 天威压众 — 度厄真符标记目标攻击力下降20%（敌方减益，不在本系统中建模）
        // C4 额外治疗在 damage_internal 中处理

        // 星超导附着次数 → ElevativeCoefficient
        let coefficient = ElevativeReaction::STELLAR_CONDUCT_EXTRA_COEFFICIENT[self.stellar_conduct_application_count as usize];
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeCoefficient,
                ReactionType::StellarConduct,
            )),
            "星超导附着次数",
            coefficient,
        );
    }
}

damage_enum!(
    QiqiDamageEnum
    A1          // 一段伤害
    A2          // 二段伤害
    A31         // 三段伤害-1
    A32         // 三段伤害-2
    A41         // 四段伤害-1
    A42         // 四段伤害-2
    A5          // 五段伤害
    Z1          // 重击伤害-1
    Z2          // 重击伤害-2
    X1          // 下坠期间伤害
    X2          // 低空坠地冲击伤害
    X3          // 高空坠地冲击伤害
    E_DMG       // 技能伤害（初击）
    E_DOT       // 寒病鬼差伤害
    E_COORD     // 寒病鬼差协同攻击伤害
    E_HEAL_HIT  // 命中治疗量
    E_HEAL_CONT // 持续治疗量（原EHeal2，target function引用）
    Q_DMG       // 技能伤害
    Q_SC        // 星超导伤害
    Q_HEAL      // 治疗量
    C4_HEAL     // 命座4额外治疗
);

impl QiqiDamageEnum {
    pub fn get_element(&self) -> Element {
        use QiqiDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A41 | A42 | A5 | Z1 | Z2 | X1 | X2 | X3 => Element::Physical,
            E_DMG | E_DOT | E_COORD | Q_DMG => Element::Cryo,
            Q_SC => Element::Cryo,
            E_HEAL_HIT | E_HEAL_CONT | Q_HEAL | C4_HEAL => Element::Physical,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use QiqiDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A41 | A42 | A5 => SkillType::NormalAttack,
            Z1 | Z2 => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E_DMG | E_DOT | E_COORD | E_HEAL_HIT | E_HEAL_CONT => SkillType::ElementalSkill,
            Q_DMG | Q_HEAL => SkillType::ElementalBurst,
            Q_SC => SkillType::Elevative,
            C4_HEAL => SkillType::ElementalBurst,
        }
    }

    pub fn get_elevative_type(&self, in_pole_star_field: bool) -> Option<ElevativeReaction> {
        use QiqiDamageEnum::*;
        if !in_pole_star_field {
            return None;
        }
        match *self {
            Q_SC => Some(ElevativeReaction::StellarConductCryo),
            _ => None,
        }
    }
}

pub struct Qiqi;

impl CharacterTrait for Qiqi {
    const STATIC_DATA: CharacterStaticData = QIQI_STATIC_DATA;
    type SkillType = QiqiSkillType;
    const SKILL: Self::SkillType = QIQI_SKILL;
    type DamageEnumType = QiqiDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            QiqiDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A31 hit_n_dmg!(3, 1)
            A32 hit_n_dmg!(3, 2)
            A41 hit_n_dmg!(4, 1)
            A42 hit_n_dmg!(4, 2)
            A5 hit_n_dmg!(5)
            Z1 charged_dmg!(1)
            Z2 charged_dmg!(2)
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            QiqiDamageEnum
            E_DMG locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E_DOT locale!(zh_cn: "寒病鬼差伤害", en: "Herald of Frost DMG")
            E_COORD locale!(zh_cn: "寒病鬼差协同攻击伤害", en: "Herald of Frost Coordinated Attack DMG")
            E_HEAL_HIT locale!(zh_cn: "命中治疗量", en: "Regeneration on Hit")
            E_HEAL_CONT locale!(zh_cn: "持续治疗量", en: "Continuous Regeneration")
        ),
        skill3: skill_map!(
            QiqiDamageEnum
            Q_DMG locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q_SC locale!(zh_cn: "星超导伤害", en: "Stellar-Conduct DMG")
            Q_HEAL locale!(zh_cn: "治疗量", en: "Healing")
            C4_HEAL locale!(zh_cn: "命座4额外治疗", en: "C4 Extra Healing")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::IN_POLESTAR_FIELD(true, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "cryo_affected",
            title: locale!(
                zh_cn: "敌人受冰元素影响（命座2普攻重击增伤）",
                en: "Opponent Affected by Cryo (C2 NA/CA Bonus)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "c6_stacks",
            title: locale!(
                zh_cn: "洞玄效果激活（命座6，每次触发消耗1层，提升600%攻击力的伤害）",
                en: "Glimpse of Mystery Active (C6, 1 stack consumed per trigger, +600% ATK DMG)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (cryo_affected, c6_stacks) = match *skill_config {
            CharacterSkillConfig::Qiqi { cryo_affected, c6_stacks } => (cryo_affected, c6_stacks),
            _ => (false, false),
        };
        let _ = cryo_affected;

        // C6: 洞玄 — 除七七外的当前场上角色造成星超导伤害时消耗1层，提升伤害
        // 每次触发消耗1层，提升值相当于七七攻击力的600%
        if common_data.constellation >= 6 && c6_stacks {
            attribute.add_edge_s1to1(
                CharacterSelector::select_onfield_except_self(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionExtra,
                    ReactionType::StellarConduct,
                )),
                Arc::new(move |atk: f64, _| atk * QIQI_SKILL.c6_bonus_per_stack),
                "七七命座6",
                EdgePriority::Invisible,
            );
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: QiqiDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_pole_star_field, stellar_conduct_application_count) = match &context.character_common_data.config {
            CharacterConfig::Qiqi { in_pole_star_field, stellar_conduct_application_count } =>
                (*in_pole_star_field, *stellar_conduct_application_count),
            _ => (false, 0),
        };
        let _ = stellar_conduct_application_count;

        let (cryo_affected, _c6_active) = match *config {
            CharacterSkillConfig::Qiqi { cryo_affected, c6_stacks } => (cryo_affected, c6_stacks),
            _ => (false, false),
        };

        use QiqiDamageEnum::*;
        let mut builder = D::new();

        // C4 额外治疗需要命座4
        if s == C4_HEAL && context.character_common_data.constellation < 4 {
            return builder.none();
        }

        // 处理治疗类技能
        match s {
            E_HEAL_HIT => {
                let ratio = QIQI_SKILL.e_heal_hit_ratio[s2];
                let fixed = QIQI_SKILL.e_heal_hit_fixed[s2];
                builder.add_atk_ratio("技能倍率", ratio);
                builder.add_extra_damage("技能倍率", fixed);
                return builder.heal(&context.attribute);
            }
            E_HEAL_CONT => {
                let ratio = QIQI_SKILL.e_heal_cont_ratio[s2];
                let fixed = QIQI_SKILL.e_heal_cont_fixed[s2];
                builder.add_atk_ratio("技能倍率", ratio);
                builder.add_extra_damage("技能倍率", fixed);
                return builder.heal(&context.attribute);
            }
            Q_HEAL => {
                let ratio = QIQI_SKILL.q_heal_ratio[s3];
                let fixed = QIQI_SKILL.q_heal_fixed[s3];
                builder.add_atk_ratio("技能倍率", ratio);
                builder.add_extra_damage("技能倍率", fixed);
                return builder.heal(&context.attribute);
            }
            C4_HEAL => {
                builder.add_atk_ratio("七七命座4", QIQI_SKILL.c4_extra_heal_ratio);
                return builder.heal(&context.attribute);
            }
            _ => {}
        }

        // 处理伤害类技能
        let mut ratio = match s {
            A1 => QIQI_SKILL.a_dmg1[s1],
            A2 => QIQI_SKILL.a_dmg2[s1],
            A31 => QIQI_SKILL.a_dmg31[s1],
            A32 => QIQI_SKILL.a_dmg32[s1],
            A41 => QIQI_SKILL.a_dmg41[s1],
            A42 => QIQI_SKILL.a_dmg42[s1],
            A5 => QIQI_SKILL.a_dmg5[s1],
            Z1 => QIQI_SKILL.z_dmg1[s1],
            Z2 => QIQI_SKILL.z_dmg2[s1],
            X1 => QIQI_SKILL.x_dmg1[s1],
            X2 => QIQI_SKILL.x_dmg2[s1],
            X3 => QIQI_SKILL.x_dmg3[s1],
            E_DMG => QIQI_SKILL.e_dmg[s2],
            E_DOT => QIQI_SKILL.e_dot[s2],
            E_COORD => QIQI_SKILL.e_coord[s2],
            Q_DMG => QIQI_SKILL.q_dmg[s3],
            Q_SC => QIQI_SKILL.q_sc_dmg[s3],
            _ => 0.0,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        // C2: 对冰附着敌人普攻重击+15%
        if context.character_common_data.constellation >= 2 && cryo_affected {
            if matches!(s, A1 | A2 | A31 | A32 | A41 | A42 | A5 | Z1 | Z2) {
                builder.add_extra_bonus("七七命座2", QIQI_SKILL.c2_cryo_bonus);
            }
        }

        // 判断是否为星超导擢升伤害
        if s.get_elevative_type(in_pole_star_field).is_some() {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                ElevativeReaction::StellarConductCryo,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (in_pole_star_field, stellar_conduct_application_count) = match *config {
            CharacterConfig::Qiqi { in_pole_star_field, stellar_conduct_application_count } =>
                (in_pole_star_field, stellar_conduct_application_count),
            _ => (false, 0),
        };
        Some(Box::new(QiqiEffect {
            in_pole_star_field,
            stellar_conduct_application_count,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        use crate::target_functions::target_functions::QiqiDefaultTargetFunction;
        let _ = role_index;
        Box::new(QiqiDefaultTargetFunction {
            recharge_demand: 1.6
        })
    }
}

