// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct SandroneSkillType {
    // Normal Attack: 事象数式·自明演绎
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_z_dmg_sweep: [f64; 15],      // Charged Attack Sweeping Fire DMG
    pub a_z_dmg_beam: [f64; 15],       // Charged Attack Condensed Beam DMG
    pub a_z_dmg_beam_sc: [f64; 15],    // Charged Attack Condensed Beam Stellar-Conduct DMG
    pub a_z_dmg_overdrive: [f64; 15],  // DMG When in Power Overdrive
    pub x_dmg1: [f64; 15],             // Plunge DMG
    pub x_dmg2: [f64; 15],             // Low Plunge DMG
    pub x_dmg3: [f64; 15],             // High Plunge DMG

    // Elemental Skill: 事象数式·游衍解析
    pub e_dmg: [f64; 15],       // Prism Shot DMG
    pub e_dmg_sc: [f64; 15],    // Prism Shot Stellar-Conduct DMG

    // Elemental Burst: 事象数式·万理证毕
    pub q_dmg_bomb: [f64; 15],      // Bombardment DMG (per hit, ×3 total)
    pub q_dmg_ray: [f64; 15],       // Convective Inhibition Ray DMG
    pub q_dmg_ray_sc: [f64; 15],    // Convective Inhibition Ray Stellar-Conduct DMG

    // P1: 悠久的演算机关
    pub p1_second_shot_multiplier: f64, // P1 second Prism Shot multiplier when DP > 50 (4.0)
    pub p1_tactics_per_stack: f64,      // P1 Refined Tactics bonus per stack (0.1 = 10%)

    // P2: 淑女的行事准则
    pub p2_em_per_100_atk: f64, // P2 EM per 100 ATK (8.0)
    pub p2_em_max: f64,         // P2 max EM (160.0)

    // P3: 星耀祝礼·唯理为光
    pub p3_base_per_100_atk: f64, // P3 Base Stellar-Conduct DMG per 100 ATK (0.007 = 0.7%)
    pub p3_base_max: f64,         // P3 Base Stellar-Conduct DMG max (0.14 = 14%)

    // C4: 世事皆数，昼来夜往
    pub c4_atk_ratio: f64, // C4 coordinated attack ATK ratio (1.25 = 125%)

    // C6: 水仙梦醒，且望晨光
    pub c6_beam_extra_count: f64,  // C6 extra hits count (4.0)
    pub c6_beam_extra_atk: f64,    // C6 extra hits ATK ratio for regular (1.0 = 100%)
    pub c6_beam_extra_sc_atk: f64, // C6 extra hits ATK ratio for Stellar-Conduct (0.8 = 80%)
    pub c6_elevate: f64,           // C6 elevation (0.2 = 20%)
}

pub const SANDRONE_SKILL: SandroneSkillType = SandroneSkillType {
    // Normal Attack: 事象数式·自明演绎
    a_dmg1: [0.7629, 0.825, 0.887, 0.9758, 1.0378, 1.1088, 1.2064, 1.304, 1.4015, 1.508, 1.6144, 1.7209, 1.8273, 1.9338, 2.0402],
    a_dmg2: [0.672, 0.7267, 0.7814, 0.8595, 0.9142, 0.9767, 1.0626, 1.1486, 1.2345, 1.3283, 1.4221, 1.5158, 1.6096, 1.7034, 1.7971],
    a_dmg3: [1.028, 1.1117, 1.1954, 1.3149, 1.3986, 1.4942, 1.6257, 1.7572, 1.8887, 2.0322, 2.1756, 2.3191, 2.4625, 2.606, 2.7494],
    a_z_dmg_sweep: [0.43, 0.465, 0.5, 0.55, 0.585, 0.625, 0.68, 0.735, 0.79, 0.85, 0.91, 0.97, 1.03, 1.09, 1.15],
    a_z_dmg_beam: [1.2255, 1.3253, 1.425, 1.5675, 1.6673, 1.7812, 1.938, 2.0947, 2.2515, 2.4225, 2.5935, 2.7645, 2.9355, 3.1065, 3.2775],
    a_z_dmg_beam_sc: [0.817, 0.8835, 0.95, 1.045, 1.1115, 1.1875, 1.292, 1.3965, 1.501, 1.615, 1.729, 1.843, 1.957, 2.071, 2.185],
    a_z_dmg_overdrive: [0.43, 0.465, 0.5, 0.55, 0.585, 0.625, 0.68, 0.735, 0.79, 0.85, 0.91, 0.97, 1.03, 1.09, 1.15],
    x_dmg1: [0.7459, 0.8066, 0.8673, 0.954, 1.0147, 1.0841, 1.1795, 1.2749, 1.3703, 1.4744, 1.5785, 1.6826, 1.7866, 1.8907, 1.9948],
    x_dmg2: [1.4914, 1.6128, 1.7342, 1.9077, 2.0291, 2.1678, 2.3586, 2.5493, 2.7401, 2.9482, 3.1563, 3.3644, 3.5725, 3.7806, 3.9887],
    x_dmg3: [1.8629, 2.0145, 2.1662, 2.3828, 2.5344, 2.7077, 2.946, 3.1842, 3.4225, 3.6825, 3.9424, 4.2023, 4.4623, 4.7222, 4.9821],

    // Elemental Skill: 事象数式·游衍解析
    e_dmg: [0.324, 0.3483, 0.3726, 0.405, 0.4293, 0.4536, 0.486, 0.5184, 0.5508, 0.5832, 0.6156, 0.648, 0.6885, 0.729, 0.7695],
    e_dmg_sc: [0.216, 0.2322, 0.2484, 0.27, 0.2862, 0.3024, 0.324, 0.3456, 0.3672, 0.3888, 0.4104, 0.432, 0.459, 0.486, 0.513],

    // Elemental Burst: 事象数式·万理证毕
    q_dmg_bomb: [0.8822, 0.9483, 1.0145, 1.1027, 1.1689, 1.235, 1.3232, 1.4115, 1.4997, 1.5879, 1.6761, 1.7643, 1.8746, 1.9849, 2.0951],
    q_dmg_ray: [3.308, 3.5561, 3.8042, 4.135, 4.3831, 4.6312, 4.962, 5.2928, 5.6236, 5.9544, 6.2852, 6.616, 7.0295, 7.443, 7.8565],
    q_dmg_ray_sc: [2.2053, 2.3707, 2.5361, 2.7567, 2.9221, 3.0875, 3.308, 3.5285, 3.7491, 3.9696, 4.1901, 4.4107, 4.6863, 4.962, 5.2377],

    // P1: 悠久的演算机关
    p1_second_shot_multiplier: 4.0,
    p1_tactics_per_stack: 0.1,

    // P2: 淑女的行事准则
    p2_em_per_100_atk: 8.0,
    p2_em_max: 160.0,

    // P3: 星耀祝礼·唯理为光
    p3_base_per_100_atk: 0.007,
    p3_base_max: 0.14,

    // C4: 世事皆数，昼来夜往
    c4_atk_ratio: 1.25,

    // C6: 水仙梦醒，且望晨光
    c6_beam_extra_count: 4.0,
    c6_beam_extra_atk: 1.0,
    c6_beam_extra_sc_atk: 0.8,
    c6_elevate: 0.2,
};

pub const SANDRONE_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Sandrone,
    internal_name: "Sandrone",
    element: Element::Cryo,
    hp: [1030, 2671, 3641, 5317, 6033, 6839, 7765, 8579, 9297, 10119, 10838, 11669, 12389, 13226, 14166],
    atk: [27, 69, 94, 138, 156, 177, 201, 222, 240, 262, 280, 302, 320, 342, 419],
    def: [59, 152, 207, 302, 343, 389, 442, 488, 529, 576, 617, 664, 705, 752, 806],
    sub_stat: CharacterSubStatFamily::CriticalRate192,
    weapon_type: WeaponType::Claymore,
    star: 5,
    skill_name1: locale!(
        zh_cn: "事象数式·自明演绎",
        en: "Formule Phenomenale: Self-Evident Proposition",
    ),
    skill_name2: locale!(
        zh_cn: "事象数式·游衍解析",
        en: "Formule Phenomenale: Differential Analysis",
    ),
    skill_name3: locale!(
        zh_cn: "事象数式·万理证毕",
        en: "Formule Phenomenale: Q.E.D.",
    ),
    name_locale: locale!(
        zh_cn: "桑多涅",
        en: "Sandrone",
    ),
};

pub struct SandroneEffect {
    pub in_polestar_field: bool,
    pub stellar_conduct_application_count: usize,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for SandroneEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P2: 淑女的行事准则 — 基于攻击力提升元素精通
        if self.common_data.has_talent2 {
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Panel(AttributeName::ElementalMastery),
                Arc::new(move |atk: f64, _| (atk / 100.0 * SANDRONE_SKILL.p2_em_per_100_atk).min(SANDRONE_SKILL.p2_em_max)),
                "桑多涅天赋2",
                EdgePriority::Common,
            );
        }

        // P3: 星耀祝礼·唯理为光 — 基于攻击力提升星超导基础伤害
        if self.common_data.has_talent2 {
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeBase,
                    ReactionType::StellarConduct,
                )),
                Arc::new(move |atk: f64, _| (atk / 100.0 * SANDRONE_SKILL.p3_base_per_100_atk).min(SANDRONE_SKILL.p3_base_max)),
                "桑多涅天赋3",
                EdgePriority::Invisible,
            );
        }

        // C1: 鎏金未凋，夕暮已远 — 队伍星超导反应伤害+30%
        if self.common_data.constellation >= 1 {
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "桑多涅命座1",
                0.3,
            );
        }

        // C6: 水仙梦醒，且望晨光 — 星超导反应伤害擢升20%
        if self.common_data.constellation >= 6 {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeElevate,
                    ReactionType::StellarConduct,
                )),
                "桑多涅命座6",
                SANDRONE_SKILL.c6_elevate,
            );
        }

        // 星超导附着次数 → ElevativeCoefficient
        ElevativeReaction::apply_stellar_conduct_extra_coefficient(attribute, self.stellar_conduct_application_count);
    }
}

damage_enum!(
    SandroneDamageEnum
    A1
    A2
    A3
    ZS
    ZB
    ZO
    X1
    X2
    X3
    E1
    E2
    Q_BOMB
    Q_BOMB_TOTAL
    Q_RAY
    C4
    C6B
    C6B_TOTAL
);

impl SandroneDamageEnum {
    pub fn get_element(&self) -> Element {
        use SandroneDamageEnum::*;
        match *self {
            A1 | A2 | A3 | X1 | X2 | X3 => Element::Physical,
            _ => Element::Cryo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use SandroneDamageEnum::*;
        match *self {
            A1 | A2 | A3 => SkillType::NormalAttack,
            ZS | ZB | ZO | C6B | C6B_TOTAL => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | E2 => SkillType::ElementalSkill,
            Q_BOMB | Q_BOMB_TOTAL | Q_RAY => SkillType::ElementalBurst,
            C4 => SkillType::Elevative,
        }
    }

    pub fn get_elevative_type(&self) -> Option<ElevativeReaction> {
        use SandroneDamageEnum::*;
        match *self {
            ZB | E2 | Q_RAY | C6B | C6B_TOTAL | C4 => Some(ElevativeReaction::StellarConductCryo),
            _ => None,
        }
    }
}

pub struct Sandrone;

impl CharacterTrait for Sandrone {
    const STATIC_DATA: CharacterStaticData = SANDRONE_STATIC_DATA;
    type SkillType = SandroneSkillType;
    const SKILL: Self::SkillType = SANDRONE_SKILL;
    type DamageEnumType = SandroneDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            SandroneDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            ZS locale!(zh_cn: "重击扫射伤害", en: "Charged Attack Sweeping Fire DMG")
            ZB locale!(zh_cn: "重击冷凝射线伤害", en: "Charged Attack Condensed Beam DMG")
            ZO locale!(zh_cn: "功率过载时伤害", en: "DMG When in Power Overdrive")
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            C4 locale!(zh_cn: "命座4协同攻击", en: "C4 Coordinated Attack")
            C6B locale!(zh_cn: "命座6集束射线（单段）", en: "C6 Condensed Cluster Beam (per hit)")
            C6B_TOTAL locale!(zh_cn: "命座6集束射线总伤害", en: "C6 Condensed Cluster Beam Total DMG")
        ),
        skill2: skill_map!(
            SandroneDamageEnum
            E1 locale!(zh_cn: "棱晶弹第一发伤害", en: "Prism Shot 1st Hit DMG")
            E2 locale!(zh_cn: "棱晶弹第二发伤害", en: "Prism Shot 2nd Hit DMG")
        ),
        skill3: skill_map!(
            SandroneDamageEnum
            Q_BOMB locale!(zh_cn: "轰炸伤害（单段）", en: "Bombardment DMG (per hit)")
            Q_BOMB_TOTAL locale!(zh_cn: "轰炸总伤害", en: "Bombardment Total DMG")
            Q_RAY locale!(zh_cn: "聚能光束伤害", en: "Convective Inhibition Ray DMG")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::IN_POLESTAR_FIELD(true, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "decoding_power",
            title: locale!(
                zh_cn: "解算功率（施放元素战技时）",
                en: "Decoding Power (when casting Elemental Skill)"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 100.0, default: 100.0 }
        },
        ItemConfig {
            name: "refined_tactics_stacks",
            title: locale!(
                zh_cn: "改进战术层数（天赋1，施放元素爆发时清除）",
                en: "Refined Tactics Stacks (Talent 1, cleared upon Elemental Burst)"
            ),
            config: ItemConfigType::Int { min: 0, max: 10, default: 10 }
        },
        ItemConfig {
            name: "c2_beam_stack",
            title: locale!(
                zh_cn: "冷凝射线暴伤层数（命座2）",
                en: "Condensed Beam CRIT DMG Stack (C2)"
            ),
            config: ItemConfigType::Int { min: 0, max: 3, default: 3 }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (in_polestar_field, stellar_conduct_application_count) = match &common_data.config {
            CharacterConfig::Sandrone { in_polestar_field, stellar_conduct_application_count, .. } =>
                (*in_polestar_field, *stellar_conduct_application_count),
            _ => (false, 0),
        };

        let (decoding_power, refined_tactics_stacks, c2_beam_stack) = match *skill_config {
            CharacterSkillConfig::Sandrone { decoding_power, refined_tactics_stacks, c2_beam_stack, .. } =>
                (decoding_power, refined_tactics_stacks, c2_beam_stack),
            _ => (0.0, 0, 0),
        };

        let _ = (attribute, in_polestar_field, decoding_power, stellar_conduct_application_count, refined_tactics_stacks, c2_beam_stack);
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: SandroneDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_polestar_field, stellar_conduct_application_count) = match &context.character_common_data.config {
            CharacterConfig::Sandrone { in_polestar_field, stellar_conduct_application_count, .. } =>
                (*in_polestar_field, *stellar_conduct_application_count),
            _ => (false, 0),
        };

        let _ = stellar_conduct_application_count;

        let (decoding_power, refined_tactics_stacks, c2_beam_stack) = match *config {
            CharacterSkillConfig::Sandrone { decoding_power, refined_tactics_stacks, c2_beam_stack, .. } =>
                (decoding_power, refined_tactics_stacks, c2_beam_stack),
            _ => (0.0, 0, 0),
        };

        use SandroneDamageEnum::*;
        let mut builder = D::new();

        // 需要命座才能触发的伤害
        if s == C4 && context.character_common_data.constellation < 4 {
            return builder.none();
        }
        if (s == C6B || s == C6B_TOTAL) && context.character_common_data.constellation < 6 {
            return builder.none();
        }

        // 当前技能是否由 in_polestar_field 决定为星超导伤害（C4 始终为星超导）
        let is_stellar_conduct = matches!(s, C4)
            || (in_polestar_field && matches!(s, ZB | E2 | Q_RAY | C6B | C6B_TOTAL));

        let ratio = match s {
            A1 => SANDRONE_SKILL.a_dmg1[s1],
            A2 => SANDRONE_SKILL.a_dmg2[s1],
            A3 => SANDRONE_SKILL.a_dmg3[s1],
            ZS => SANDRONE_SKILL.a_z_dmg_sweep[s1],
            ZB => if is_stellar_conduct {
                SANDRONE_SKILL.a_z_dmg_beam_sc[s1]
            } else {
                SANDRONE_SKILL.a_z_dmg_beam[s1]
            },
            ZO => SANDRONE_SKILL.a_z_dmg_overdrive[s1],
            X1 => SANDRONE_SKILL.x_dmg1[s1],
            X2 => SANDRONE_SKILL.x_dmg2[s1],
            X3 => SANDRONE_SKILL.x_dmg3[s1],
            E1 => SANDRONE_SKILL.e_dmg[s2],
            E2 => {
                let base = if is_stellar_conduct {
                    SANDRONE_SKILL.e_dmg_sc[s2]
                } else {
                    SANDRONE_SKILL.e_dmg[s2]
                };
                // P1: 解算功率>50时第二发棱晶弹造成400%伤害
                if context.character_common_data.has_talent1 && decoding_power > 50.0 {
                    base * SANDRONE_SKILL.p1_second_shot_multiplier
                } else {
                    base
                }
            },
            Q_BOMB => SANDRONE_SKILL.q_dmg_bomb[s3],
            Q_BOMB_TOTAL => SANDRONE_SKILL.q_dmg_bomb[s3] * 3.0,
            Q_RAY => {
                let base = if is_stellar_conduct {
                    SANDRONE_SKILL.q_dmg_ray_sc[s3]
                } else {
                    SANDRONE_SKILL.q_dmg_ray[s3]
                };
                // P1: 改进战术层数 → 聚能光束造成 100% + 层数×10% 伤害（需星超导状态）
                if context.character_common_data.has_talent1 && is_stellar_conduct && refined_tactics_stacks > 0 {
                    base * (1.0 + refined_tactics_stacks as f64 * SANDRONE_SKILL.p1_tactics_per_stack)
                } else {
                    base
                }
            },
            C4 => SANDRONE_SKILL.c4_atk_ratio,
            C6B => if is_stellar_conduct {
                SANDRONE_SKILL.c6_beam_extra_sc_atk
            } else {
                SANDRONE_SKILL.c6_beam_extra_atk
            },
            C6B_TOTAL => (if is_stellar_conduct {
                SANDRONE_SKILL.c6_beam_extra_sc_atk
            } else {
                SANDRONE_SKILL.c6_beam_extra_atk
            }) * SANDRONE_SKILL.c6_beam_extra_count,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        // C2: 冷凝射线暴伤+40%，每层再+20%
        if context.character_common_data.constellation >= 2 && c2_beam_stack > 0 {
            if s == ZB {
                builder.add_extra_critical_damage("桑多涅命座2", 0.4 + c2_beam_stack as f64 * 0.2);
            }
        }

        // 判断是否为星超导擢升伤害
        if is_stellar_conduct {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                ElevativeReaction::StellarConductCryo,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (in_polestar_field, stellar_conduct_application_count) = match *config {
            CharacterConfig::Sandrone { in_polestar_field, stellar_conduct_application_count, .. } =>
                (in_polestar_field, stellar_conduct_application_count),
            _ => (false, 0),
        };
        Some(Box::new(SandroneEffect {
            in_polestar_field,
            stellar_conduct_application_count,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
