// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct WriothesleySkillType {
    pub normal_dmg1: [f64; 15],
    pub normal_dmg2: [f64; 15],
    pub normal_dmg3: [f64; 15],
    pub normal_dmg4: [f64; 15],
    pub normal_dmg5: [f64; 15],
    pub charged_dmg: [f64; 15],
    pub plunging_dmg1: [f64; 15],
    pub plunging_dmg2: [f64; 15],
    pub plunging_dmg3: [f64; 15],

    pub e_bonus: [f64; 15],

    pub q_dmg1: [f64; 15],
    pub q_dmg2: [f64; 15],
}

pub const WRIOTHESLEY_SKILL: WriothesleySkillType = WriothesleySkillType {
    normal_dmg1: [0.533596, 0.577028, 0.62046, 0.682506, 0.725938, 0.775575, 0.843826, 0.912076, 0.980327, 1.054782, 1.129237, 1.203692, 1.278148, 1.352603, 1.427058],
    normal_dmg2: [0.517987, 0.560148, 0.60231, 0.662541, 0.704703, 0.752888, 0.819142, 0.885396, 0.95165, 1.023927, 1.096204, 1.168481, 1.240759, 1.313036, 1.385313],
    normal_dmg3: [0.672228, 0.726944, 0.78166, 0.859826, 0.914542, 0.977075, 1.063058, 1.14904, 1.235023, 1.328822, 1.422621, 1.51642, 1.61022, 1.704019, 1.797818],
    normal_dmg4: [0.379041, 0.409893, 0.440745, 0.48482, 0.515672, 0.550931, 0.599413, 0.647895, 0.696377, 0.749266, 0.802156, 0.855045, 0.907935, 0.960824, 1.013713],
    normal_dmg5: [0.90742, 0.98128, 1.05514, 1.160654, 1.234514, 1.318925, 1.43499, 1.551056, 1.667121, 1.793738, 1.920355, 2.046972, 2.173588, 2.300205, 2.426822],
    charged_dmg: [1.5296, 1.64432, 1.75904, 1.912, 2.02672, 2.14144, 2.2944, 2.44736, 2.60032, 2.75328, 2.90624, 3.0592, 3.2504, 3.4416, 3.6328],
    plunging_dmg1: [0.568288, 0.614544, 0.6608, 0.72688, 0.773136, 0.826, 0.898688, 0.971376, 1.044064, 1.12336, 1.202656, 1.281952, 1.361248, 1.440544, 1.51984],
    plunging_dmg2: [1.136335, 1.228828, 1.32132, 1.453452, 1.545944, 1.65165, 1.796995, 1.94234, 2.087686, 2.246244, 2.404802, 2.563361, 2.721919, 2.880478, 3.039036],
    plunging_dmg3: [1.419344, 1.534872, 1.6504, 1.81544, 1.930968, 2.063, 2.244544, 2.426088, 2.607632, 2.80568, 3.003728, 3.201776, 3.399824, 3.597872, 3.79592],
    e_bonus: [1.431695, 1.457545, 1.483395, 1.517, 1.54285, 1.5687, 1.602305, 1.63591, 1.669515, 1.70312, 1.736725, 1.77033, 1.803935, 1.83754, 1.871145],
    q_dmg1: [1.272, 1.3674, 1.4628, 1.59, 1.6854, 1.7808, 1.908, 2.0352, 2.1624, 2.2896, 2.4168, 2.544, 2.703, 2.862, 3.021],
    q_dmg2: [0.424, 0.4558, 0.4876, 0.53, 0.5618, 0.5936, 0.636, 0.6784, 0.7208, 0.7632, 0.8056, 0.848, 0.901, 0.954, 1.007],
};

pub const WRIOTHESLEY_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Wriothesley,
    internal_name: "Wriothesley",
    name_locale: locale!(
        zh_cn: "莱欧斯利",
        en: "Wriothesley"
    ),
    element: Element::Cryo,
    hp: [1058, 2745, 3652, 5465, 6110, 7029, 7889, 8818, 9462, 10400, 11045, 11993, 12637, 13593, 14559],
    atk: [24, 63, 84, 125, 140, 161, 180, 202, 216, 238, 253, 274, 289, 311, 381],
    def: [59, 154, 205, 307, 343, 395, 443, 495, 531, 584, 620, 673, 710, 763, 817],
    sub_stat: CharacterSubStatFamily::CriticalDamage384,
    weapon_type: WeaponType::Catalyst,
    star: 5,
    skill_name1: locale!(
        zh_cn: "迅烈倾霜拳",
        en: "Normal Attack: Forceful Fists of Frost"
    ),
    skill_name2: locale!(
        zh_cn: "冰牙突驰",
        en: "Icefang Rush"
    ),
    skill_name3: locale!(
        zh_cn: "黑金狼噬",
        en: "Darkgold Wolfbite"
    ),
};

pub struct WriothesleyEffect {
    pub in_pole_star_field: bool,
    pub stellar_conduct_application_count: i32,
    pub talent2_stack: f64,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for WriothesleyEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P2: 罪业终有报偿之时 — 每层检偿之敕提升6%攻击力
        if self.common_data.has_talent2 {
            let value = 0.06 * self.talent2_stack;
            attribute.set_value_by_t(
                AttributeType::Panel(AttributeName::ATKPercentage),
                "莱欧斯利天赋2",
                value,
            );
            // 存储层数供 damage_internal 使用
            attribute.set_value_to(AttributeName::USER1, "检偿之敕层数", self.talent2_stack);
        }

        // 特殊被动「冤苦终有显明之期」：星超导反应伤害+30%（极星辉域中生效）
        if self.in_pole_star_field {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "莱欧斯利特殊天赋",
                0.3,
            );
        }

        // 星超导附着次数 → ElevativeCoefficient
        let coefficient = ElevativeReaction::STELLAR_CONDUCT_EXTRA_COEFFICIENT[self.stellar_conduct_application_count as usize];
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeCoefficient,
                ReactionType::StellarConduct,
            )),
            "星超导附着次数",
            coefficient,
        );
    }
}

damage_enum!(
    WriothesleyDamageEnum
    A1          // 一段伤害
    A2          // 二段伤害
    A3          // 三段伤害（极星辉域中视为星超导）
    A4Div2      // 四段伤害/2
    A5          // 五段伤害（极星辉域中视为星超导）
    Z           // 重击（恩典之诫状态下强化为惩戒·凌跃拳/天辉·凌跃拳）
    X1          // 下坠期间伤害
    X2          // 低空坠地冲击伤害
    X3          // 高空坠地冲击伤害
    Q1          // 元素爆发技能伤害（×5）
    Q2          // 流涌之刃伤害
    C6_A5       // 命座6冰锥伤害（五段触发，极星辉域中视为星超导）
    C6_Z        // 命座6冰锥伤害（重击触发，极星辉域中视为星超导）
);

impl WriothesleyDamageEnum {
    pub fn get_element(&self) -> Element {
        use WriothesleyDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4Div2 | A5 | Z | X1 | X2 | X3 | Q1 | Q2 | C6_A5 | C6_Z => Element::Cryo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use WriothesleyDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4Div2 | A5 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            Q1 | Q2 => SkillType::ElementalBurst,
            C6_A5 => SkillType::NormalAttack,
            C6_Z => SkillType::ChargedAttack,
        }
    }

    pub fn get_elevative_type(&self, in_pole_star_field: bool) -> Option<ElevativeReaction> {
        use WriothesleyDamageEnum::*;
        if !in_pole_star_field {
            return None;
        }
        match *self {
            A3 | A5 | Z | C6_A5 | C6_Z => Some(ElevativeReaction::StellarConductCryo),
            _ => None,
        }
    }
}

pub struct Wriothesley;

impl CharacterTrait for Wriothesley {
    const STATIC_DATA: CharacterStaticData = WRIOTHESLEY_STATIC_DATA;
    type SkillType = WriothesleySkillType;
    const SKILL: Self::SkillType = WRIOTHESLEY_SKILL;
    type DamageEnumType = WriothesleyDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            WriothesleyDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            A4Div2 locale!(
                zh_cn: "四段伤害/2",
                en: "4-Hit DMG/2"
            )
            A5 hit_n_dmg!(5)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            C6_A5 locale!(
                zh_cn: "命座6冰锥伤害（五段）",
                en: "C6 Icicle DMG (5-Hit)"
            )
            C6_Z locale!(
                zh_cn: "命座6冰锥伤害（重击）",
                en: "C6 Icicle DMG (Charged)"
            )
        ),
        skill2: None,
        skill3: skill_map!(
            WriothesleyDamageEnum
            Q1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q2 locale!(zh_cn: "流涌之刃伤害", en: "Surging Blade DMG")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::IN_POLESTAR_FIELD(true, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "talent2_stack",
            title: locale!(
                zh_cn: "「检偿之敕」层数",
                en: "「Prosecution Edict」Stack"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 5.0, default: 4.0 }
        }
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "under_chilling_penalty",
            title: locale!(
                zh_cn: "「寒烈的惩裁」状态",
                en: "Enable 「Chilling Penalty」"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "gracious_rebuke",
            title: locale!(
                zh_cn: "「恩典之诫」状态",
                en: "Enable 「Gracious Rebuke」"
            ),
            config: ItemConfigType::Bool { default: true }
        }
    ]);

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: WriothesleyDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_pole_star_field, stellar_conduct_application_count, talent2_stack) = match &context.character_common_data.config {
            CharacterConfig::Wriothesley { in_pole_star_field, stellar_conduct_application_count, talent2_stack } =>
                (*in_pole_star_field, *stellar_conduct_application_count, *talent2_stack),
            _ => (false, 0, 0.0),
        };
        let _ = stellar_conduct_application_count;

        let (under_chilling_penalty, gracious_rebuke) = match *config {
            CharacterSkillConfig::Wriothesley { under_chilling_penalty, gracious_rebuke } => (under_chilling_penalty, gracious_rebuke),
            _ => (true, true),
        };

        use WriothesleyDamageEnum::*;
        let mut builder = D::new();

        // 天赋1「公理终有辩诉之日」
        let has_p1 = context.character_common_data.has_talent1;
        // 恩典之诫是否生效
        let use_gracious_rebuke = has_p1 && gracious_rebuke;

        // C6 冰锥需要解锁命座6
        if (s == C6_A5 || s == C6_Z) && context.character_common_data.constellation < 6 {
            return builder.none();
        }

        // 判断当前伤害是否视为星超导伤害
        // 在极星辉域中，特殊被动将三段、五段、重击转化为星超导伤害
        let is_stellar_conduct = s.get_elevative_type(in_pole_star_field).is_some();

        // 基础倍率
        let mut ratio = match s {
            A1 => WRIOTHESLEY_SKILL.normal_dmg1[s1],
            A2 => WRIOTHESLEY_SKILL.normal_dmg2[s1],
            A3 => WRIOTHESLEY_SKILL.normal_dmg3[s1],
            A4Div2 => WRIOTHESLEY_SKILL.normal_dmg4[s1],
            A5 => WRIOTHESLEY_SKILL.normal_dmg5[s1],
            Z => WRIOTHESLEY_SKILL.charged_dmg[s1],
            X1 => WRIOTHESLEY_SKILL.plunging_dmg1[s1],
            X2 => WRIOTHESLEY_SKILL.plunging_dmg2[s1],
            X3 => WRIOTHESLEY_SKILL.plunging_dmg3[s1],
            Q1 => WRIOTHESLEY_SKILL.q_dmg1[s3],
            Q2 => WRIOTHESLEY_SKILL.q_dmg2[s3],
            C6_A5 => WRIOTHESLEY_SKILL.normal_dmg5[s1],
            C6_Z => WRIOTHESLEY_SKILL.charged_dmg[s1],
        };

        // 寒烈的惩裁状态下普通攻击倍率强化
        if matches!(s, A1 | A2 | A3 | A4Div2 | A5) && under_chilling_penalty {
            ratio *= WRIOTHESLEY_SKILL.e_bonus[s2];
        }

        // 星超导状态下的倍率调整（特殊被动「冤苦终有显明之期」）
        if is_stellar_conduct {
            if context.character_common_data.constellation >= 2 && talent2_stack >= 5.0 {
                // C2 + 5层检偿之敕：三段90%、五段120%、重击150%
                match s {
                    A3 => ratio *= 0.9,
                    A5 => ratio *= 1.2,
                    Z => ratio *= 1.5,
                    C6_A5 => ratio *= 1.2,
                    C6_Z => ratio *= 1.5,
                    _ => {}
                }
            } else {
                // 默认星超导倍率：三段60%、五段80%、重击100%
                match s {
                    A3 => ratio *= 0.6,
                    A5 => ratio *= 0.8,
                    Z => ratio *= 1.0,
                    C6_A5 => ratio *= 0.8,
                    C6_Z => ratio *= 1.0,
                    _ => {}
                }
            }

            // C1 星超导交替加成：天辉·凌跃拳与五段斥逐拳互相+50%
            // 由于交替触发，取平均覆盖，两者均获得加成（合理近似）
            if context.character_common_data.constellation >= 1 && use_gracious_rebuke {
                if matches!(s, A5 | Z) {
                    builder.add_extra_bonus("莱欧斯利命座1", 0.5);
                }
            }
        } else {
            // 非星超导状态下的恩典之诫加成
            if s == Z && use_gracious_rebuke {
                let punch_bonus = if context.character_common_data.constellation >= 1 {
                    2.0  // C1: 200%
                } else {
                    0.5  // P1: 50%
                };
                builder.add_extra_bonus("莱欧斯利天赋1", punch_bonus);
            }

            // C2 非星超导：5层检偿之敕时普攻125%、重击130%
            if context.character_common_data.constellation >= 2 && talent2_stack >= 5.0 {
                match s {
                    A1 | A2 | A3 | A4Div2 | A5 => ratio *= 1.25,
                    Z => ratio *= 1.3,
                    _ => {}
                }
            }
        }

        builder.add_atk_ratio("技能倍率", ratio);

        // C2：施放元素爆发时，每层检偿之敕+40%伤害
        if matches!(s, Q1) && context.character_common_data.constellation >= 2 {
            let q_bonus = talent2_stack * 0.4;
            if q_bonus > 0.0 {
                builder.add_extra_bonus("莱欧斯利命座2", q_bonus);
            }
        }

        // C6：暴击率/暴击伤害加成
        if context.character_common_data.constellation >= 6 {
            if is_stellar_conduct {
                // 星超导C6：被强化的斥逐拳与天辉·凌跃拳 +10%暴击率 +80%暴击伤害
                if matches!(s, A3 | A5) || (s == Z && use_gracious_rebuke) {
                    builder.add_extra_critical("莱欧斯利命座6", 0.1);
                    builder.add_extra_critical_damage("莱欧斯利命座6", 0.8);
                }
            } else {
                // 非星超导C6：惩戒·凌跃拳 +10%暴击率 +80%暴击伤害
                if s == Z && use_gracious_rebuke {
                    builder.add_extra_critical("莱欧斯利命座6", 0.1);
                    builder.add_extra_critical_damage("莱欧斯利命座6", 0.8);
                }
                // 非星超导下五段不触发冰锥
                if s == C6_A5 {
                    return builder.none();
                }
            }
        }

        if let Some(elevative_type) = s.get_elevative_type(in_pole_star_field) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (in_pole_star_field, stellar_conduct_application_count, talent2_stack) = match *config {
            CharacterConfig::Wriothesley { in_pole_star_field, stellar_conduct_application_count, talent2_stack } =>
                (in_pole_star_field, stellar_conduct_application_count, talent2_stack),
            _ => (false, 0, 0.0),
        };
        Some(Box::new(WriothesleyEffect {
            in_pole_star_field,
            stellar_conduct_application_count,
            talent2_stack,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
