// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::character::characters::prelude::*;

pub struct LumineCryoSkillType {
    // Normal Attack: Foreign Frostglint (异邦寒芒)
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub a_dmg4: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub z_dmg1: [f64; 15],
    pub z_dmg2: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: Ice Fog Piercer (冰雾剑)
    pub e_dmg: [f64; 15],            // Skill DMG
    pub e_ice_crystal_dmg: [f64; 15], // Ice Crystal DMG

    // Elemental Burst: Frostbound Javelin (聚冰成锋)
    pub q_javelin_dmg: [f64; 15],        // Ice Javelin DMG per strike
    pub q_frostglow_bonus: [f64; 15],    // Frostglow DMG Bonus per stack
    pub q_sc_javelin_dmg: [f64; 15],     // Stellar-Conduct Ice Javelin Single Strike DMG
    pub q_sc_frostglow_bonus: [f64; 15], // Stellar-Conduct Frostglow DMG Bonus per stack
    pub q_strikes: usize,                // No. of Strikes in Attack
    pub q_extra_strikes_at_max: usize,   // Additional Frostglow Attack Strikes at Stack Max

    // P1: Ever-Keen Frost (自锐的凛冰)
    pub p1_bonus: f64, // DMG +80% of ATK

    // P2: Lucent Ice (通明的冽冰)
    pub p2_em_ratio: f64, // EM +8% of ATK
    pub p2_em_max: f64,   // max 160 EM

    // P3: Stellar Jubilee: Illusory Frostmirror (星耀祝礼·幻变冰镜)
    pub p3_base_per_100_atk: f64, // Base DMG +0.35% per 100 ATK
    pub p3_base_max: f64,         // max 7%

    // P4: Foreign Permafrost (异邦的层冰)
    pub p4_bonus: f64, // Charged Attack: Freezing Ice DMG +140% of ATK

    // C6: Brumal Grimfrost (肃杀的熙冰)
    pub c6_bonus_per_stack: f64, // Stellar Glimmer reaction DMG +5% per stack
    pub c6_bonus_max: f64,       // max 40%
}

pub const LUMINECRYO_SKILL: LumineCryoSkillType = LumineCryoSkillType {
    // Normal Attack: Foreign Frostglint
    a_dmg1: [0.44462, 0.48081, 0.517, 0.5687, 0.60489, 0.64625, 0.70312, 0.76, 0.81686, 0.8789, 0.94094, 1.00298, 1.06502, 1.12706, 1.1891],
    a_dmg2: [0.4343, 0.46965, 0.505, 0.5555, 0.59085, 0.63125, 0.6868, 0.74235, 0.7979, 0.8585, 0.9191, 0.9797, 1.0403, 1.1009, 1.1615],
    a_dmg3: [0.52976, 0.57288, 0.616, 0.6776, 0.72072, 0.77, 0.83776, 0.90552, 0.97328, 1.0472, 1.12112, 1.19504, 1.26896, 1.34288, 1.4168],
    a_dmg4: [0.58308, 0.63054, 0.678, 0.7458, 0.79326, 0.8475, 0.92208, 0.99666, 1.07124, 1.1526, 1.23396, 1.31532, 1.39668, 1.47804, 1.5594],
    a_dmg5: [0.70778, 0.76539, 0.823, 0.9053, 0.96291, 1.02875, 1.11928, 1.20981, 1.30034, 1.3991, 1.49786, 1.59662, 1.69538, 1.79414, 1.8929],
    z_dmg1: [0.559, 0.6045, 0.65, 0.715, 0.7605, 0.8125, 0.884, 0.9555, 1.027, 1.105, 1.183, 1.261, 1.339, 1.417, 1.495],
    z_dmg2: [0.7224, 0.7812, 0.84, 0.924, 0.9828, 1.05, 1.1424, 1.2348, 1.3272, 1.428, 1.5288, 1.6296, 1.7304, 1.8312, 1.932],
    x_dmg1: [0.639324, 0.691362, 0.7434, 0.81774, 0.869778, 0.92925, 1.011024, 1.092798, 1.174572, 1.26378, 1.352988, 1.442196, 1.531404, 1.620612, 1.70982],
    x_dmg2: [1.278377, 1.382431, 1.486485, 1.635134, 1.739187, 1.858106, 2.02162, 2.185133, 2.348646, 2.527025, 2.705403, 2.883781, 3.062159, 3.240537, 3.418915],
    x_dmg3: [1.596762, 1.726731, 1.8567, 2.04237, 2.172339, 2.320875, 2.525112, 2.729349, 2.933586, 3.15639, 3.379194, 3.601998, 3.824802, 4.047606, 4.27041],

    // Elemental Skill: Ice Fog Piercer
    e_dmg: [0.9168, 0.9856, 1.0543, 1.146, 1.2148, 1.2835, 1.3752, 1.4669, 1.5586, 1.6502, 1.7419, 1.8336, 1.9482, 2.0628, 2.1774],
    e_ice_crystal_dmg: [0.2139, 0.23, 0.246, 0.2674, 0.2834, 0.2995, 0.3209, 0.3423, 0.3637, 0.3851, 0.4064, 0.4278, 0.4546, 0.4813, 0.5081],

    // Elemental Burst: Frostbound Javelin
    q_javelin_dmg: [0.5513, 0.5927, 0.634, 0.6891, 0.7305, 0.7718, 0.827, 0.8821, 0.9372, 0.9924, 1.0475, 1.1026, 1.1715, 1.2404, 1.3094],
    q_frostglow_bonus: [0.0276, 0.0296, 0.0317, 0.0345, 0.0365, 0.0386, 0.0413, 0.0441, 0.0469, 0.0496, 0.0524, 0.0551, 0.0586, 0.062, 0.0655],
    q_sc_javelin_dmg: [0.3675, 0.3951, 0.4227, 0.4594, 0.487, 0.5146, 0.5513, 0.5881, 0.6248, 0.6616, 0.6983, 0.7351, 0.781, 0.827, 0.8729],
    q_sc_frostglow_bonus: [0.0184, 0.0198, 0.0211, 0.023, 0.0244, 0.0257, 0.0276, 0.0294, 0.0312, 0.0331, 0.0349, 0.0368, 0.0391, 0.0413, 0.0436],
    q_strikes: 3,
    q_extra_strikes_at_max: 2,

    // P1: Ever-Keen Frost
    p1_bonus: 0.8,

    // P2: Lucent Ice
    p2_em_ratio: 0.08,
    p2_em_max: 160.0,

    // P3: Stellar Jubilee: Illusory Frostmirror
    p3_base_per_100_atk: 0.0035,
    p3_base_max: 0.07,

    // P4: Foreign Permafrost
    p4_bonus: 1.4,

    // C6: Brumal Grimfrost
    c6_bonus_per_stack: 0.05,
    c6_bonus_max: 0.4,
};

pub const LUMINECRYO_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::LumineCryo,
    internal_name: "LumineCryo",
    element: Element::Cryo,
    hp: [912, 2342, 3024, 4529, 5031, 5766, 6411, 7164, 7648, 8401, 8885, 9638, 10122, 10875, 11627],
    atk: [18, 46, 59, 88, 98, 113, 125, 140, 149, 164, 174, 188, 198, 212, 266],
    def: [57, 147, 190, 284, 315, 362, 402, 450, 480, 527, 558, 605, 635, 683, 730],
    sub_stat: CharacterSubStatFamily::ATK240,
    weapon_type: WeaponType::Sword,
    star: 5,
    skill_name1: locale!(
        zh_cn: "异邦寒芒",
        en: "Foreign Frostglint",
    ),
    skill_name2: locale!(
        zh_cn: "冰雾剑",
        en: "Ice Fog Piercer",
    ),
    skill_name3: locale!(
        zh_cn: "聚冰成锋",
        en: "Frostbound Javelin",
    ),
    name_locale: locale!(
        zh_cn: "荧-冰",
        en: "Lumine-Cryo",
    )
};

pub struct LumineCryoEffect {
    pub elements: ConfigElements8Multi,
    pub stellar_conduct_application_count: usize,
    pub stellar_glimmer_state: usize,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for LumineCryoEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋2：通明的冽冰 — 基于攻击力提升元素精通，至多160点
        if self.common_data.has_talent2 {
            attribute.add_edge_t1(
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Panel(AttributeName::ElementalMastery),
                Arc::new(move |atk: f64, _| (atk * LUMINECRYO_SKILL.p2_em_ratio).min(LUMINECRYO_SKILL.p2_em_max)),
                "旅行者天赋2",
                EdgePriority::Common,
            );
        }

        // 天赋3：星耀祝礼·幻变冰镜 — 辉映·星超导/星扩散状态下，队伍角色触发超导/冰扩散
        // 转为星超导/星扩散，并基于旅行者攻击力提升该反应的基础伤害（每100点攻击力+0.35%，至多7%）
        let p3_elevative_base = Arc::new(move |atk: f64, _| (atk / 100.0 * LUMINECRYO_SKILL.p3_base_per_100_atk).min(LUMINECRYO_SKILL.p3_base_max));
        if self.stellar_glimmer_state == 1 {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeBase,
                    ReactionType::StellarConduct,
                )),
                p3_elevative_base.clone(),
                "旅行者天赋3",
                EdgePriority::Invisible,
            );
        }
        if self.stellar_glimmer_state == 2 {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeBase,
                    ReactionType::StellarSwirl,
                )),
                p3_elevative_base.clone(),
                "旅行者天赋3",
                EdgePriority::Invisible,
            );
        }

        // 天赋4：异邦的层冰 — 每种共鸣过的元素提供额外的强化效果
        if self.elements.anemo {
            attribute.set_value_by(AttributeName::CriticalBase, "旅行者天赋4", 0.10);
        }
        if self.elements.geo {
            attribute.add_def_percentage("旅行者天赋4", 0.20);
        }
        if self.elements.electro {
            attribute.set_value_by(AttributeName::Recharge, "旅行者天赋4", 0.20);
        }
        if self.elements.dendro {
            attribute.set_value_by(AttributeName::ElementalMastery, "旅行者天赋4", 60.0);
        }
        if self.elements.hydro {
            attribute.add_hp_percentage("旅行者天赋4", 0.20);
        }
        if self.elements.pyro {
            attribute.add_atk_percentage("旅行者天赋4", 0.20);
        }
        if self.elements.cryo {
            attribute.set_value_by(AttributeName::CriticalDamageBase, "旅行者天赋4", 0.20);
        }

        // 星超导附着次数 → ElevativeCoefficient
        ElevativeReaction::apply_stellar_conduct_extra_coefficient(attribute, self.stellar_conduct_application_count);
    }
}

damage_enum!(
    LumineCryoDamageEnum
    A1
    A2
    A3
    A4
    A5
    Z1
    Z2
    X1
    X2
    X3
    P4A         // 重击·冰凝一段（天赋4）
    P4B         // 重击·冰凝二段（天赋4）
    P4T         // 重击·冰凝总伤害（天赋4）
    E           // 冰雾剑技能伤害
    E_CRYSTAL   // 冰晶伤害
    Q           // 元素爆发单段伤害
    Q_TOTAL     // 元素爆发总伤害（段数随寒辉层数变化）
);

impl LumineCryoDamageEnum {
    pub fn get_element(&self, infused: bool) -> Element {
        use LumineCryoDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4 | A5 | Z1 | Z2 | X1 | X2 | X3 => {
                if infused {
                    Element::Cryo
                } else {
                    Element::Physical
                }
            }
            _ => Element::Cryo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use LumineCryoDamageEnum::*;
        match *self {
            A1 | A2 | A3 | A4 | A5 => SkillType::NormalAttack,
            Z1 | Z2 | P4A | P4B | P4T => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E | E_CRYSTAL => SkillType::ElementalSkill,
            Q | Q_TOTAL => SkillType::ElementalBurst,
        }
    }

    pub fn get_elevative_type(&self, stellar_glimmer_state: usize) -> Option<ElevativeReaction> {
        use LumineCryoDamageEnum::*;
        match *self {
            // 辉映·星烁状态下，元素爆发与重击·冰凝改为造成视为对应星烁反应伤害的冰元素伤害
            Q | Q_TOTAL | P4A | P4B | P4T => match stellar_glimmer_state {
                1 => Some(ElevativeReaction::StellarConductCryo),
                2 => Some(ElevativeReaction::StellarSwirlCryo),
                _ => None,
            },
            _ => None,
        }
    }
}

pub struct LumineCryo;

impl CharacterTrait for LumineCryo {
    const STATIC_DATA: CharacterStaticData = LUMINECRYO_STATIC_DATA;
    type SkillType = LumineCryoSkillType;
    const SKILL: Self::SkillType = LUMINECRYO_SKILL;
    type DamageEnumType = LumineCryoDamageEnum;
    type RoleEnum = ();

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            LumineCryoDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            A4 hit_n_dmg!(4)
            A5 hit_n_dmg!(5)
            Z1 charged_dmg!(1)
            Z2 charged_dmg!(2)
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            P4A locale!(zh_cn: "重击·冰凝一段", en: "Charged Attack: Freezing Ice (1st Segment)")
            P4B locale!(zh_cn: "重击·冰凝二段", en: "Charged Attack: Freezing Ice (2nd Segment)")
            P4T locale!(zh_cn: "重击·冰凝总伤害", en: "Charged Attack: Freezing Ice (Total)")
        ),
        skill2: skill_map!(
            LumineCryoDamageEnum
            E locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E_CRYSTAL locale!(zh_cn: "冰晶伤害", en: "Ice Crystal DMG")
        ),
        skill3: skill_map!(
            LumineCryoDamageEnum
            Q locale!(zh_cn: "冰矛单段伤害", en: "Ice Javelin DMG (per strike)")
            Q_TOTAL locale!(zh_cn: "冰矛总伤害（3段，满层5段）", en: "Ice Javelin Total DMG (3 strikes, 5 at max stacks)")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_CONDUCT_APPLICATION_COUNT(0, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig::STELLAR_GLIMMER_STATE(1, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "elements",
            title: locale!(
                zh_cn: "共鸣过的元素（天赋4额外强化效果）",
                en: "Resonated Elements (Talent 4 Additional Buff Effects)"
            ),
            config: ItemConfigType::ElementMulti {
                elements: &[Element::Pyro, Element::Hydro, Element::Anemo, Element::Electro, Element::Dendro, Element::Cryo, Element::Geo],
                default: ConfigElements8Multi {
                    pyro: true,
                    hydro: true,
                    anemo: true,
                    electro: true,
                    dendro: true,
                    cryo: true,
                    geo: true,
                    physical: false,
                }
            }
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "frostglow_stacks",
            title: locale!(
                zh_cn: "元素爆发消耗的「寒辉」层数",
                en: "Frostglow Stacks Consumed by Elemental Burst"
            ),
            config: ItemConfigType::Int { min: 0, max: 8, default: 8 }
        },
        ItemConfig {
            name: "frostpierce_star_on_field",
            title: locale!(
                zh_cn: "栗烈寒星在场（天赋1）",
                en: "Frostpierce Star On Field (Talent 1)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let stellar_glimmer_state = match &common_data.config {
            CharacterConfig::LumineCryo { stellar_glimmer_state, .. } => *stellar_glimmer_state,
            _ => 0,
        };
        let (frostglow_stacks, _frostpierce_star_on_field) = match *skill_config {
            CharacterSkillConfig::LumineCryo { frostglow_stacks, frostpierce_star_on_field } =>
                (frostglow_stacks, frostpierce_star_on_field),
            _ => (0, false),
        };

        // 命座6：肃杀的熙冰 — 施放元素爆发时，每消耗1层寒辉，
        // 队伍中其他角色造成的星烁反应（星超导/星扩散）伤害提升5%，至多40%，持续15秒
        if common_data.constellation >= 6 && frostglow_stacks > 0 {
            let bonus = (frostglow_stacks as f64 * LUMINECRYO_SKILL.c6_bonus_per_stack).min(LUMINECRYO_SKILL.c6_bonus_max);
            attribute.set_value_to_s(
                CharacterSelector::select_team_except_self(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "旅行者命座6",
                bonus,
            );
            attribute.set_value_to_s(
                CharacterSelector::select_team_except_self(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "旅行者命座6",
                bonus,
            );
        }

        let _ = stellar_glimmer_state;
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: LumineCryoDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (_elements, _stellar_conduct_application_count, stellar_glimmer_state) = match &context.character_common_data.config {
            CharacterConfig::LumineCryo { elements, stellar_conduct_application_count, stellar_glimmer_state } =>
                (*elements, *stellar_conduct_application_count, *stellar_glimmer_state),
            _ => (ConfigElements8Multi::default(), 0, 0),
        };

        let (frostglow_stacks, frostpierce_star_on_field) = match *config {
            CharacterSkillConfig::LumineCryo { frostglow_stacks, frostpierce_star_on_field } =>
                (frostglow_stacks, frostpierce_star_on_field),
            _ => (0, false),
        };

        use LumineCryoDamageEnum::*;
        let mut builder = D::new();

        // 天赋1：自锐的凛冰 — 辉映·星超导且栗烈寒星在场时，
        // 普通攻击/重击/下落攻击转为冰伤并提升相当于攻击力80%的伤害。
        // 该加成对「重击·冰凝」（P4A/P4B/P4T）无效。
        let p1_active = context.character_common_data.has_talent1
            && stellar_glimmer_state == 1
            && frostpierce_star_on_field;
        if p1_active && !matches!(s, P4A | P4B | P4T)
            && matches!(s.get_skill_type(), SkillType::NormalAttack | SkillType::ChargedAttack | SkillType::PlungingAttackInAction | SkillType::PlungingAttackOnGround)
        {
            builder.add_extra_bonus("旅行者天赋1", LUMINECRYO_SKILL.p1_bonus);
        }

        // 元素爆发：消耗的每层寒辉提升本次元素爆发造成的伤害
        if matches!(s, Q | Q_TOTAL) && frostglow_stacks > 0 {
            let frostglow_bonus = if stellar_glimmer_state == 1 {
                LUMINECRYO_SKILL.q_sc_frostglow_bonus[s3]
            } else {
                LUMINECRYO_SKILL.q_frostglow_bonus[s3]
            };
            builder.add_extra_bonus("寒辉", frostglow_bonus * frostglow_stacks as f64);
        }

        // 辉映·星超导状态下的冰矛单段倍率（星扩散与无状态时使用基础倍率）
        let q_base = if stellar_glimmer_state == 1 {
            LUMINECRYO_SKILL.q_sc_javelin_dmg[s3]
        } else {
            LUMINECRYO_SKILL.q_javelin_dmg[s3]
        };

        // 元素爆发总段数：满层（≥8 层寒辉）时为基础3段 + 额外2段
        let q_strikes_total = if frostglow_stacks >= 8 {
            LUMINECRYO_SKILL.q_strikes + LUMINECRYO_SKILL.q_extra_strikes_at_max
        } else {
            LUMINECRYO_SKILL.q_strikes
        };

        let ratio = match s {
            A1 => LUMINECRYO_SKILL.a_dmg1[s1],
            A2 => LUMINECRYO_SKILL.a_dmg2[s1],
            A3 => LUMINECRYO_SKILL.a_dmg3[s1],
            A4 => LUMINECRYO_SKILL.a_dmg4[s1],
            A5 => LUMINECRYO_SKILL.a_dmg5[s1],
            Z1 => LUMINECRYO_SKILL.z_dmg1[s1],
            Z2 => LUMINECRYO_SKILL.z_dmg2[s1],
            X1 => LUMINECRYO_SKILL.x_dmg1[s1],
            X2 => LUMINECRYO_SKILL.x_dmg2[s1],
            X3 => LUMINECRYO_SKILL.x_dmg3[s1],
            P4A => LUMINECRYO_SKILL.z_dmg1[s1] + LUMINECRYO_SKILL.p4_bonus, // 重击·冰凝一段：重击一段伤害 + 140%攻击力
            P4B => LUMINECRYO_SKILL.z_dmg2[s1] + LUMINECRYO_SKILL.p4_bonus, // 重击·冰凝二段：重击二段伤害 + 140%攻击力
            P4T => LUMINECRYO_SKILL.z_dmg1[s1] + LUMINECRYO_SKILL.z_dmg2[s1] + 2.0 * LUMINECRYO_SKILL.p4_bonus, // 重击·冰凝总伤害
            E => LUMINECRYO_SKILL.e_dmg[s2],
            E_CRYSTAL => LUMINECRYO_SKILL.e_ice_crystal_dmg[s2],
            Q => q_base,
            Q_TOTAL => q_base * q_strikes_total as f64,
            _ => 0.0,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        // 辉映·星烁状态下视为星超导/星扩散擢升伤害，否则为普通伤害
        if let Some(elevative_type) = s.get_elevative_type(stellar_glimmer_state) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(p1_active),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(p1_active),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (elements, stellar_conduct_application_count, stellar_glimmer_state) = match *config {
            CharacterConfig::LumineCryo { elements, stellar_conduct_application_count, stellar_glimmer_state, .. } =>
                (elements, stellar_conduct_application_count, stellar_glimmer_state),
            _ => (ConfigElements8Multi::default(), 0, 0),
        };
        Some(Box::new(LumineCryoEffect {
            elements,
            stellar_conduct_application_count,
            stellar_glimmer_state,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
