// Generated by GitHub Copilot (GPT-5.2-Codex)
use crate::character::characters::prelude::*;

pub struct NicoleSkillType {
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    pub e_dmg: [f64; 15],
    pub e_shield: [f64; 15],
    pub e_shield_fixed: [f64; 15],
    pub e_grace_ratio: [f64; 15],
    pub e_grace_max: [f64; 15],

    pub q_dmg: [f64; 15],
    pub q_projection: [f64; 15],
}

pub const NICOLE_SKILL: NicoleSkillType = NicoleSkillType {
    // Normal Attack: Allegoria
    a_dmg1: [0.3518, 0.3782, 0.4046, 0.4397, 0.4661, 0.4925, 0.5277, 0.5629, 0.5980, 0.6332, 0.6684, 0.7036, 0.7476, 0.7915, 0.8355],
    a_dmg2: [0.2963, 0.3186, 0.3408, 0.3704, 0.3926, 0.4149, 0.4445, 0.4741, 0.5038, 0.5334, 0.5630, 0.5927, 0.6297, 0.6668, 0.7038],
    a_dmg3: [0.4619, 0.4965, 0.5312, 0.5774, 0.6120, 0.6466, 0.6928, 0.7390, 0.7852, 0.8314, 0.8776, 0.9238, 0.9815, 1.0392, 1.0970],
    z_dmg: [1.1232, 1.2074, 1.2917, 1.4040, 1.4882, 1.5725, 1.6848, 1.7971, 1.9094, 2.0218, 2.1341, 2.2464, 2.3868, 2.5272, 2.6676],
    x_dmg1: [0.5683, 0.6145, 0.6608, 0.7269, 0.7731, 0.8260, 0.8987, 0.9714, 1.0441, 1.1234, 1.2027, 1.2820, 1.3612, 1.4405, 1.5198],
    x_dmg2: [1.1363, 1.2288, 1.3213, 1.4535, 1.5459, 1.6516, 1.7970, 1.9423, 2.0877, 2.2462, 2.4048, 2.5634, 2.7219, 2.8805, 3.0390],
    x_dmg3: [1.4193, 1.5349, 1.6504, 1.8154, 1.9310, 2.0630, 2.2445, 2.4261, 2.6076, 2.8057, 3.0037, 3.2018, 3.3998, 3.5979, 3.7959],

    // Elemental Skill: Revelation: Uncreated Light
    e_dmg: [1.3840, 1.4878, 1.5916, 1.7300, 1.8338, 1.9376, 2.0760, 2.2144, 2.3528, 2.4912, 2.6296, 2.7680, 2.9410, 3.1140, 3.2870],
    e_shield: [2.2118, 2.3777, 2.5436, 2.7648, 2.9307, 3.0966, 3.3178, 3.5389, 3.7601, 3.9813, 4.2025, 4.4237, 4.7002, 4.9766, 5.2531],
    e_shield_fixed: [1387.0, 1525.0, 1676.0, 1837.0, 2011.0, 2196.0, 2392.0, 2600.0, 2820.0, 3051.0, 3294.0, 3548.0, 3814.0, 4091.0, 4380.0],
    e_grace_ratio: [0.0825, 0.0900, 0.0975, 0.1050, 0.1125, 0.1200, 0.1275, 0.1350, 0.1425, 0.1500, 0.1590, 0.1680, 0.1770, 0.1860, 0.1950],
    e_grace_max: [330.0, 360.0, 390.0, 420.0, 450.0, 480.0, 510.0, 540.0, 570.0, 600.0, 636.0, 672.0, 708.0, 744.0, 780.0],

    // Elemental Burst: Revelation: Ladder of Divine Ascent
    q_dmg: [3.1680, 3.4056, 3.6432, 3.9600, 4.1976, 4.4352, 4.7520, 5.0688, 5.3856, 5.7024, 6.0192, 6.3360, 6.7320, 7.1280, 7.5240],
    q_projection: [0.9900, 1.0800, 1.1700, 1.2600, 1.3500, 1.4400, 1.5300, 1.6200, 1.7100, 1.8000, 1.9080, 2.0160, 2.1240, 2.2320, 2.3400],
};

pub const NICOLE_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Nicole,
    internal_name: "Nicole",
    element: Element::Pyro,
    hp: [810, 2102, 2797, 4185, 4678, 5383, 6041, 6752, 7246, 7964, 8458, 9184, 9677, 10409, 11149],
    atk: [27, 69, 92, 138, 154, 177, 198, 222, 238, 262, 278, 302, 318, 342, 419],
    def: [44, 114, 151, 226, 253, 291, 326, 365, 392, 430, 457, 496, 523, 563, 603],
    sub_stat: CharacterSubStatFamily::ATK288,
    weapon_type: WeaponType::Catalyst,
    star: 5,
    skill_name1: locale!(
        zh_cn: "托喻",
        en: "Allegoria",
    ),
    skill_name2: locale!(
        zh_cn: "圣言默示·未现之光",
        en: "Revelation: Uncreated Light",
    ),
    skill_name3: locale!(
        zh_cn: "圣言默示·天路历程",
        en: "Revelation: Ladder of Divine Ascent",
    ),
    name_locale: locale!(
        zh_cn: "尼可",
        en: "Nicole",
    ),
};

pub struct NicoleEffect {
    pub hexerei_secret_rite: bool,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for NicoleEffect {
    fn change_attribute(&self, _attribute: &mut A) {
    }
}

damage_enum!(
    NicoleDamageEnum
    A1
    A2
    A3
    Z
    X1
    X2
    X3
    E
    EShield
    Q
    QArc
    C1
);

impl NicoleDamageEnum {
    pub fn get_element(&self, arcane_element: Option<Element>) -> Element {
        use NicoleDamageEnum::*;
        match *self {
            A1 | A2 | A3 | Z | X1 | X2 | X3 | E | EShield | Q => Element::Pyro,
            QArc | C1 => arcane_element.unwrap_or(Element::Pyro),
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use NicoleDamageEnum::*;
        match *self {
            A1 | A2 | A3 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E | EShield => SkillType::ElementalSkill,
            Q | QArc | C1 => SkillType::ElementalBurst,
        }
    }
}

pub struct Nicole;

impl CharacterTrait for Nicole {
    const STATIC_DATA: CharacterStaticData = NICOLE_STATIC_DATA;
    type SkillType = NicoleSkillType;
    const SKILL: Self::SkillType = NICOLE_SKILL;
    type DamageEnumType = NicoleDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = Some(
        &[CharacterTag::Hexerei]
    );

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            NicoleDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            NicoleDamageEnum
            E locale!(zh_cn: "技能伤害", en: "Skill DMG")
            EShield locale!(zh_cn: "护盾吸收量", en: "Shield DMG Absorption")
        ),
        skill3: skill_map!(
            NicoleDamageEnum
            Q locale!(zh_cn: "技能伤害", en: "Skill DMG")
            QArc locale!(zh_cn: "奥迹造影伤害", en: "Arcane Projection DMG")
            C1 locale!(zh_cn: "奥迹造影·合一伤害", en: "Arcane Projection: Unity DMG")
        ),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::HEXEREI_SECRET_RITE_GLOBAL(false, ItemConfig::PRIORITY_CHARACTER),
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "on_field_over_3s",
            title: locale!(
                zh_cn: "场上角色处于场上超过3秒",
                en: "On-field character has been on the field for over 3 seconds",
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (_, s2, _) = common_data.get_3_skill();
        let on_field_over_3s = match skill_config {
            CharacterSkillConfig::Nicole { on_field_over_3s, .. } => *on_field_over_3s,
            _ => false,
        };

        // 第一步：E 基础提升（含 C2），对全部角色生效
        let ratio = NICOLE_SKILL.e_grace_ratio[s2];
        let max = NICOLE_SKILL.e_grace_max[s2];
        let c2_extra = if common_data.constellation >= 2 {
            300.0
        } else {
            0.0
        };

        attribute.add_edge_s1to1(
            CharacterSelector::select_all(attribute),
            AttributeType::Panel(AttributeName::ATK),
            AttributeType::Panel(AttributeName::ATKFixed),
            Arc::new(move |atk: f64, _| (atk * ratio).min(max) + c2_extra),
            "尼可元素战技",
            EdgePriority::Common,
        );

        // 预计算拥有圣祝之引的角色 ID 列表
        let self_id = *attribute.get_character_id();
        let guidance_selector = if common_data.constellation >= 6 && common_data.has_talent2 {
            // C6 + 天赋2：尼可升变时全体一同升变
            CharacterSelector::select_all(attribute)
        } else if common_data.has_talent2 {
            CharacterSelector::new(move |c| {
                // 天赋1「分有」+ 天赋2「慕善」：魔导角色（总是）或场上角色（停留3秒），包括尼可自身
                if c.character_id == self_id || c.tags.contains(&CharacterTag::Hexerei) || (c.on_field && on_field_over_3s){
                    return true;
                }
                false
            })
        } else if common_data.has_talent1 {
            CharacterSelector::new(move |c| {
                // 天赋1「分有」：魔导角色（总是）或场上角色（停留3秒），尼可除外
                if c.character_id != self_id && (c.tags.contains(&CharacterTag::Hexerei) || (c.on_field && on_field_over_3s)) {
                    return true;
                }
                false
            })
        } else {
            CharacterSelector::new(move |c| { false })
        };

        // 第二步：为拥有圣祝之引的角色应用 +300
        attribute.set_value_to_s(
            guidance_selector.clone(),
            AttributeType::Panel(AttributeName::ATKFixed),
            "尼可圣祝之引",
            300.0,
        );

        // C2：依据拥有圣祝之引的角色元素类型降低对应抗性
        if common_data.constellation >= 2 {
            let characters = attribute.get_characters().clone();
            for status in characters.iter() {
                if guidance_selector.clone().check(&status) {
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(
                            AttributeVariableType::ResMinus,
                            status.character_static_data.element,
                        )),
                        "尼可命座2",
                        0.25,
                    );
                }
            }
        }

        // C4：先导之佑 — 其他角色攻击力×70% 作为基础伤害提升
        if common_data.constellation >= 4 {
            for skill in [
                SkillType::NormalAttack,
                SkillType::ChargedAttack,
                SkillType::PlungingAttackInAction,
                SkillType::PlungingAttackOnGround,
                SkillType::ElementalSkill,
                SkillType::ElementalBurst,
            ]
            .into_iter()
            {
                attribute.add_edge_s1to1(
                    guidance_selector.clone(),
                    AttributeType::Panel(AttributeName::ATK),
                    AttributeType::Invisible(InvisibleAttributeType::new_skill(
                        AttributeVariableType::BaseDamage,
                        skill,
                    )),
                    Arc::new(move |atk: f64, _| atk * 0.7),
                    "尼可命座4",
                    EdgePriority::Invisible,
                );
            }
        }

        // C6：圣祝之引角色无视40%防御
        if common_data.constellation >= 6 {
            attribute.set_value_to_s(
                guidance_selector.clone(),
                AttributeType::Invisible(InvisibleAttributeType::new_any(
                    AttributeVariableType::DefPenetration,
                )),
                "尼可命座6",
                0.4,
            );
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: NicoleDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let hexerei_secret_rite = match &context.character_common_data.config {
            CharacterConfig::Nicole {
                hexerei_secret_rite,
            } => *hexerei_secret_rite,
            _ => false,
        };

        let _ = config; // 当前 config 中已无 damage_internal 需要的配置项

        use NicoleDamageEnum::*;
        let mut builder = D::new();

        if s == EShield {
            let ratio = NICOLE_SKILL.e_shield[s2];
            let fixed = NICOLE_SKILL.e_shield_fixed[s2];

            builder.add_atk_ratio("技能倍率", ratio);
            builder.add_extra_damage("技能倍率", fixed);

            builder.shield(&context.attribute, Element::Pyro)
        } else if s == QArc || s == C1 {
            // 获取当前场上角色：奥迹造影视为由该角色造成的伤害，受益于该角色的攻击力与元素类型
            let onfield_characters = context
                .attribute
                .get_characters_by_selector(CharacterSelector::select_onfield(context.attribute));
            let onfield_status = match onfield_characters.first().copied() {
                Some(status) => status,
                None => return builder.none(),
            };

            let onfield_attribute = context
                .attribute
                .get_change_active_character(onfield_status.character_id);
            let element = onfield_status.character_static_data.element;

            if s == C1 {
                if context.character_common_data.constellation < 1 {
                    return builder.none();
                }
                builder.add_atk_ratio("技能倍率", 6.0);
            } else {
                builder.add_atk_ratio("技能倍率", NICOLE_SKILL.q_projection[s3]);
            }

            if hexerei_secret_rite && onfield_status.tags.contains(&CharacterTag::Hexerei) {
                builder.add_extra_damage("尼可天赋3", context.attribute.get_atk() * 3.0);
            }

            builder.damage(
                &onfield_attribute,
                &context.enemy,
                s.get_element(Some(element)),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        } else {
            let ratio = match s {
                A1 => NICOLE_SKILL.a_dmg1[s1],
                A2 => NICOLE_SKILL.a_dmg2[s1],
                A3 => NICOLE_SKILL.a_dmg3[s1],
                Z => NICOLE_SKILL.z_dmg[s1],
                X1 => NICOLE_SKILL.x_dmg1[s1],
                X2 => NICOLE_SKILL.x_dmg2[s1],
                X3 => NICOLE_SKILL.x_dmg3[s1],
                E => NICOLE_SKILL.e_dmg[s2],
                Q => NICOLE_SKILL.q_dmg[s3],
                _ => 0.0,
            };

            builder.add_atk_ratio("技能倍率", ratio);

            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(None),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let hexerei_secret_rite = match *config {
            CharacterConfig::Nicole { hexerei_secret_rite } => hexerei_secret_rite,
            _ => false,
        };
        Some(Box::new(NicoleEffect {
            hexerei_secret_rite,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(_role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
