use serde::{Deserialize, Serialize};
use crate::common::{Element, Moonsign};

fn default_true() -> bool {
    true
}

fn default_false() -> bool {
    false
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum CharacterSkillConfig {
    AetherAnemo { elemental_absorption: Element },
    LumineAnemo { elemental_absorption: Element },
    AetherDendro { overflowing_lotuslight_count: usize },
    LumineDendro { overflowing_lotuslight_count: usize },
    AetherHydro { hp_above_half: bool, consumed_hp_times: usize },
    LumineHydro { hp_above_half: bool, consumed_hp_times: usize },
    AetherPyro { gosoythoth: bool, nightsouls_blessing: bool, active: bool, activated_q: bool },
    LuminePyro { gosoythoth: bool, nightsouls_blessing: bool, active: bool, activated_q: bool },
    Beidou { under_q: bool, perfect_counter: bool },
    Xingqiu { c4: bool },
    Noelle { after_q: bool },
    Sucrose { talent1_coverage: f64, talent2_coverage: f64, c6_coverage: f64, small_wind_spirit_coverage: f64, large_wind_spirit_coverage: f64 },
    Diluc { pyro: bool },
    Qiqi { cryo_affected: bool, c6_stacks: bool },
    Mona { omen: bool, astral_glow_of_mercury: f64, after_z: bool, bonus_z: usize },
    Keqing { after_e: bool },
    Venti { activated_q: bool, breeze_blow: bool },
    Klee { boom_badge: usize, active: bool, activated_q: bool, activated_c1: bool },
    Diona { in_signature_mix: bool, hp_above_50: bool },
    Xinyan { shield_rate: f64 },
    Albedo { lower50: bool, activated_q: bool, fatal_count: usize, crystallize_shield: bool },
    Ganyu { talent1_rate: f64 },
    Xiao { after_q: bool, talent1_stack: f64, talent2_stack: f64 },
    HuTao { after_e: bool },
    Yanfei { after_q: bool },
    Eula { lightfall_stack: usize },
    KaedeharaKazuha { after_e_or_q: bool },
    KamisatoAyaka { #[serde(default = "default_true")] after_dash: bool, #[serde(default = "default_false")] use_c6: bool },
    Yoimiya { after_e: bool },
    Aloy { coil_count: usize },
    RaidenShogun { under_e: bool, resolve_stack: usize },
    SangonomiyaKokomi { after_q: bool },
    AratakiItto { after_q: bool },
    YaeMiko { sesshou_sakura_level: usize, sesshou_sakura_count: usize, p3_enhanced: bool },
    KamisatoAyato { e_stack: usize, in_q: bool },
    Dori { c6: bool },
    Candace { crown: bool },
    Cyno { under_judication: bool },
    Nahida { q_bonus: bool, q_bonus_count: usize },
    Faruzan { talent2_ratio: f64 },
    Wanderer { e_enabled: bool, e_hydro: bool, sdpoints: f64 },
    Alhaitham { under_e: bool },
    Dehya { c2_rate: f64, c6_stack: f64 },
    Kaveh { after_q: bool },
    Lyney { prop_stack: f64, under_pyro: bool, pyro_count: usize, },
    Freminet { talent2_rate: f64 },
    Neuvillette { talent1_stack: usize },
    Wriothesley { under_chilling_penalty: bool, gracious_rebuke: bool },
    Furina { hp_above50_count: usize, #[serde(default = "default_false")] c6_after_e: bool, #[serde(default = "default_false")] c6_pneuma: bool },
    Navia { shard_count: usize, strike11: bool, after_e: bool },
    Gaming { pyro: bool },
    Arlecchino { bond_of_life: f64 },
    Clorinde { bond_of_life: f64 },
    Emilie { enemy_burn: bool, use_c6: bool },
    Kinich { hunters_exp: f64 },
    Xilonen { nightsoul: bool },
    Chasca { element_count: usize, c6_rate: f64 },
    Mavuika { after_q: bool },
    YumemizukiMizuki { in_dreamdrifter: bool, p3_boost_active: bool },
    Skirk { cunning_stacks: i32, seven_phase_mode: bool, havoc_extinction: bool, death_crossing_stacks: i32, void_rift_count: i32 },
    Nefer { veil_of_falsehood: usize, shadow_dance: bool },
    Jahoda { elemental_absorption: Element, activated_p2: bool },
    Durin { activated_res: bool, primordial_fusion: bool, cycle_of_enlightenment: bool, activated_reaction: bool },
    Illuga { nightingales_song: bool },
    Columbina { activated_q: bool, stack_p1: usize, activated_c4: bool },
    Zibai { lunar_phase_shift: bool, activated_c1: bool, activated_c4: bool, stack_c6: usize },
    Varka { azure_fang_oath: usize, c1_bonus: bool },
    Linnea { field_catalog: usize },
    Prune { tolling_rally: bool, swirl_trigger: bool, hunt_the_witch_stacks: usize, c6_atk: bool },
    Nicole { on_field_over_3s: bool },
    Lohen { in_masterstroke: bool, evilsbane_blade: bool },
    Sandrone { decoding_power: f64, refined_tactics_stacks: usize, c2_beam_stack: usize },
    NoConfig,
}
