// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::target_functions::target_functions::prelude::*;
use crate::character::characters::Vodyanitsa;

pub struct VodyanitsaDefaultTargetFunction {
    pub hp_demand: f64,
}

impl TargetFunctionMetaTrait for VodyanitsaDefaultTargetFunction {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: TargetFunctionMeta = TargetFunctionMeta {
        name: TargetFunctionName::VodyanitsaDefault,
        name_locale: locale!(
            zh_cn: "沃雅妮莎-「幽歌萦渊」",
            en: "Vodyanitsa-Lingering Siren-Song"
        ),
        description: locale!(
            zh_cn: "沃雅妮莎一轮输出总伤害（元素战技×1、唤春角笛×6、元素爆发×1）",
            en: "Vodyanitsa Total Damage Output per Round (Skill ×1, Horn of Spring's Call ×6, Burst ×1)"
        ),
        tags: "输出",
        four: TargetFunctionFor::SomeWho(CharacterName::Vodyanitsa),
        image: TargetFunctionMetaImage::Avatar
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "hp_demand",
            title: locale!(
                zh_cn: "生命值上限需求",
                en: "Max HP Demand",
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create(_character: &CharacterCommonData, _weapon: &WeaponCommonData, config: &TargetFunctionConfig) -> Box<dyn TargetFunction> {
        let hp_demand = match *config {
            TargetFunctionConfig::VodyanitsaDefault { hp_demand } => hp_demand,
            _ => 0.0,
        };
        Box::new(VodyanitsaDefaultTargetFunction {
            hp_demand,
        })
    }
}

impl TargetFunction for VodyanitsaDefaultTargetFunction {
    fn get_target_function_opt_config(&self) -> TargetFunctionOptConfig {
        TargetFunctionOptConfig {
            atk_fixed: 0.0,
            atk_percentage: 0.0,
            hp_fixed: 0.2,
            hp_percentage: 0.6,
            def_fixed: 0.0,
            def_percentage: 0.0,
            recharge: 0.0,
            elemental_mastery: 0.2,
            critical: 1.0,
            critical_damage: 1.0,
            healing_bonus: 0.0,
            bonus_electro: 0.0,
            bonus_pyro: 0.0,
            bonus_hydro: 1.0,
            bonus_anemo: 0.0,
            bonus_cryo: 0.0,
            bonus_geo: 0.0,
            bonus_dendro: 0.0,
            bonus_physical: 0.0,
            sand_main_stats: vec![
                StatName::HPPercentage,
            ],
            goblet_main_stats: vec![
                StatName::HydroBonus,
                StatName::HPPercentage,
            ],
            head_main_stats: vec![
                StatName::CriticalRate,
                StatName::CriticalDamage,
                StatName::HPPercentage,
            ],
            set_names: Some(vec![
                ArtifactSetName::MarechausseeHunter,
                ArtifactSetName::HeartOfTheFurnace,
            ]),
            very_critical_set_names: Some(vec![
                ArtifactSetName::VourukashasGlow,
                ArtifactSetName::GoldenTroupe,
            ]),
            normal_threshold: TargetFunctionOptConfig::DEFAULT_NORMAL_THRESHOLD,
            critical_threshold: TargetFunctionOptConfig::DEFAULT_CRITICAL_THRESHOLD,
            very_critical_threshold: TargetFunctionOptConfig::DEFAULT_VERY_CRITICAL_THRESHOLD,
        }
    }

    fn get_default_artifact_config(&self, _team_config: &TeamQuantization) -> ArtifactEffectConfig {
        Default::default()
    }

    fn target(&self, attribute: &TargetFunctionAttributeType, character: &Character<TargetFunctionAttributeType>, _weapon: &Weapon<TargetFunctionAttributeType>, _artifacts: &[&Artifact], enemy: &Enemy) -> f64 {
        // 一轮输出期间「遥久之歌」持续生效（元素战技召唤「唤春角笛」并提供治疗），
        // 施放元素战技后同时获得「领唱」与「重唱」（持续30秒），
        // 命座4 按受治疗角色生命值不低于40%的分支、至多3层生命值上限提升计
        let config = CharacterSkillConfig::Vodyanitsa {
            in_song_of_ages_past: true,
            has_lead_vocal: true,
            has_chorus: true,
            c4_hp_stacks: 3,
            c4_low_hp: false,
        };

        let context = {
            let mut attribute_temp = (*attribute).clone();
            Vodyanitsa::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config);
            DamageContext { character_common_data: &character.common_data, attribute: &attribute_temp.solve(), enemy }
        };

        // 生命值上限需求：低于该值时直接返回 0
        if context.attribute.get_hp() < self.hp_demand {
            return 0.0;
        }

        type Ty = <Vodyanitsa as CharacterTrait>::DamageEnumType;

        let dmg = |s: Ty| -> f64 {
            Vodyanitsa::damage::<SimpleDamageBuilder>(&context, s, &config, None).normal.expectation
        };

        // 一轮输出：元素战技伤害×1 + 「唤春角笛」伤害×6 + 元素爆发伤害×1
        // （「唤春角笛」攻击间隔3秒、「遥久之歌」持续16秒，取6次）
        dmg(Ty::E)
            + dmg(Ty::E_HORN) * 6.0
            + dmg(Ty::Q)
    }
}
