// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::buffs::buffs::prelude::*;

pub struct BuffDionaC6 {
    pub hp_above_50: bool,
    pub stellar_glimmer_state: StellarGlimmerState,
}

impl<A: Attribute> Buff<A> for BuffDionaC6 {
    fn change_attribute(&self, attribute: &mut A) {
        if self.hp_above_50 {
            // 生命值高于50%时，元素精通提升200
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::ElementalMastery),
                "迪奥娜命座6",
                200.0,
            );
        } else {
            // 生命值低于或等于50%时，受治疗加成提升30%
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::IncomingHealingBonus),
                "迪奥娜命座6",
                0.3,
            );
        }

        if self.stellar_glimmer_state.is_stellar_conduct() {
            // 辉映·星超导：处在最烈特调领域内的角色造成的超导、星超导反应伤害提升40%
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::Superconduct,
                )),
                "迪奥娜命座6",
                0.4,
            );
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "迪奥娜命座6",
                0.4,
            );
        }
    }
}

impl BuffMeta for BuffDionaC6 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::DionaC6,
        name_locale: locale!(
            zh_cn: "迪奥娜-「猫尾打烊之时」",
            en: "Diona-Cat's Tail Closing Time"
        ),
        image: BuffImage::Avatar(CharacterName::Diona),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "迪奥娜命座6：处在最烈特调领域内的角色，依据生命值获得如下效果：\
                <br>·生命值低于或等于50%时，受治疗加成提升30%；\
                <br>·生命值高于50%时，元素精通提升200。\
                <br>辉映·星超导：处在最烈特调领域内的角色造成的超导、星超导反应伤害提升40%。",
            en: "Diona C6: Characters within Signature Mix's radius gain the following effects based on their HP levels:\
                <br>· The Incoming Healing Bonus is increased by 30% when HP is at, or lower than, 50%.\
                <br>· Elemental Mastery is increased by 200 when HP is above 50%.\
                <br>Radiance: Stellar-Conduct: Characters within Signature Mix's radius deal 40% increased Superconduct and Stellar-Conduct Reaction DMG."
        )),
        from: BuffFrom::Character(CharacterName::Diona),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_BUFF),
        ItemConfig {
            name: "hp_above_50",
            title: locale!(
                zh_cn: "当前场上角色生命值高于50%",
                en: "Current on-field character HP above 50%"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (hp_above_50, stellar_glimmer_state) = match *b {
            BuffConfig::DionaC6 { hp_above_50, stellar_glimmer_state } => (hp_above_50, stellar_glimmer_state),
            _ => (true, StellarGlimmerState::None)
        };
        Box::new(BuffDionaC6 {
            hp_above_50,
            stellar_glimmer_state,
        })
    }
}

