// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::buffs::buffs::prelude::*;

pub struct BuffLohenP2 {
    pub has_buff: bool,
}

impl<A: Attribute> Buff<A> for BuffLohenP2 {
    fn change_attribute(&self, attribute: &mut A) {
        if self.has_buff {
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::ATKPercentage),
                "洛恩天赋2",
                0.15,
            );
        }
    }
}

impl BuffMeta for BuffLohenP2 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::LohenP2,
        name_locale: locale!(
            zh_cn: "洛恩-「戏言的杰作」",
            en: "Lohen-Flippant Masterpiece"
        ),
        image: BuffImage::Avatar(CharacterName::Lohen),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "洛恩天赋2：在奇谋状态下，队伍中附近的其他角色对敌人触发冰元素相关反应后的8秒内，该角色的攻击力提升15%。",
            en: "Lohen Talent 2: While in Masterstroke mode, for 8s after another nearby party member triggers a Cryo Reaction, that character's ATK is increased by 15%."
        )),
        from: BuffFrom::Character(CharacterName::Lohen),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "has_buff",
            title: locale!(
                zh_cn: "触发冰元素相关反应",
                en: "Triggered Cryo Reaction"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let has_buff = match *b {
            BuffConfig::LohenP2 { has_buff } => has_buff,
            _ => false
        };
        Box::new(BuffLohenP2 { has_buff })
    }
}


pub struct BuffLohenC2 {
    pub has_buff: bool,
}

impl<A: Attribute> Buff<A> for BuffLohenC2 {
    fn change_attribute(&self, attribute: &mut A) {
        if self.has_buff {
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::ElementalMastery),
                "洛恩命座2",
                200.0,
            );
        }
    }
}

impl BuffMeta for BuffLohenC2 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::LohenC2,
        name_locale: locale!(
            zh_cn: "洛恩-「凡飞翔者，皆为靶标」",
            en: "Lohen-\"In Flight, I Strike Whatever Flies\""
        ),
        image: BuffImage::Avatar(CharacterName::Lohen),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "洛恩命座2：破邪之刃命中敌人后，使队伍中附近的其他角色的元素精通提升200点，持续8秒。",
            en: "Lohen C2: After Evilsbane Blade hits an opponent, increase the Elemental Mastery of other nearby party members by 200 for 8s."
        )),
        from: BuffFrom::Character(CharacterName::Lohen),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "has_buff",
            title: locale!(
                zh_cn: "拥有破邪之刃精通加成",
                en: "Has Evilsbane Blade EM Bonus"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let has_buff = match *b {
            BuffConfig::LohenC2 { has_buff } => has_buff,
            _ => false
        };
        Box::new(BuffLohenC2 { has_buff })
    }
}



