// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::buffs::buffs::prelude::*;
use crate::character::characters::traveller::lumine_cryo::LUMINECRYO_SKILL;

pub struct BuffLumineCryoP3 {
    pub lumine_cryo_atk: f64, // 荧-冰的攻击力
}

impl<A: Attribute> Buff<A> for BuffLumineCryoP3 {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋3：基于旅行者攻击力提升队伍角色星超导/星扩散反应的基础伤害（每100攻击力0.35%，至多7%）
        let value = (self.lumine_cryo_atk / 100.0 * LUMINECRYO_SKILL.p3_base_per_100_atk).min(LUMINECRYO_SKILL.p3_base_max);
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeBase,
                ReactionType::StellarConduct,
            )),
            "旅行者天赋3",
            value,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeBase,
                ReactionType::StellarSwirl,
            )),
            "旅行者天赋3",
            value,
        );
    }
}

impl BuffMeta for BuffLumineCryoP3 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::LumineCryoP3,
        name_locale: locale!(
            zh_cn: "荧-冰-「星耀祝礼·幻变冰镜」",
            en: "Lumine-Cryo-Stellar Jubilee: Illusory Frostmirror"
        ),
        image: BuffImage::Avatar(CharacterName::LumineCryo),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "荧-冰天赋3：处于极星辉域中时/队伍中的角色在附近触发星扩散反应后的8秒内，旅行者将分别进入辉映·星超导/辉映·星扩散状态。队伍中的角色触发超导/冰元素扩散反应时，将转为触发星超导/星扩散反应，且基于旅行者的攻击力，提升队伍中角色造成的上述反应的基础伤害：每100点攻击力都将提升0.35%上述反应的基础伤害，至多通过这种方式提升7%伤害。",
            en: "Lumine-Cryo Talent 3: When inside the Polestar Field / within 8 seconds after a nearby party member triggers a Stellar Swirl reaction, the Traveller enters the Radiance: Stellar-Conduct / Radiance: Stellar Swirl state respectively. When a party member triggers Superconduct or Cryo Swirl, it becomes a Stellar-Conduct or Stellar Swirl reaction instead, and the Base DMG of said reaction is increased based on the Traveller's ATK: every 100 points of ATK increase the Base DMG by 0.35%, up to 7%."
        )),
        from: BuffFrom::Character(CharacterName::LumineCryo),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "lumine_cryo_atk",
            title: locale!(
                zh_cn: "荧-冰的攻击力",
                en: "Lumine-Cryo's ATK"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 10000.0, default: 2000.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let lumine_cryo_atk = match *b {
            BuffConfig::LumineCryoP3 { lumine_cryo_atk } => lumine_cryo_atk,
            _ => 2000.0,
        };
        Box::new(BuffLumineCryoP3 { lumine_cryo_atk })
    }
}


pub struct BuffLumineCryoC6 {
    pub frostglow_stacks: usize, // 元素爆发消耗的「寒辉」层数
}

impl<A: Attribute> Buff<A> for BuffLumineCryoC6 {
    fn change_attribute(&self, attribute: &mut A) {
        // 命座6：施放元素爆发时，每消耗1层寒辉，队伍中其他角色星烁反应伤害提升5%（至多40%，持续15秒）
        let bonus = (self.frostglow_stacks as f64 * LUMINECRYO_SKILL.c6_bonus_per_stack).min(LUMINECRYO_SKILL.c6_bonus_max);
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarConduct,
            )),
            "旅行者命座6",
            bonus,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarSwirl,
            )),
            "旅行者命座6",
            bonus,
        );
    }
}

impl BuffMeta for BuffLumineCryoC6 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::LumineCryoC6,
        name_locale: locale!(
            zh_cn: "荧-冰-「肃杀的熙冰」",
            en: "Lumine-Cryo-Brumal Grimfrost"
        ),
        image: BuffImage::Avatar(CharacterName::LumineCryo),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "荧-冰命座6：施放元素爆发聚冰成锋时，每消耗1层寒辉，队伍中其他角色造成的星烁反应伤害提升5%，至多通过这种方式提升40%，持续15秒。",
            en: "Lumine-Cryo Constellation 6: When casting Elemental Burst Frostbound Javelin, for every stack of Frostglow consumed, Stellar Glimmer reaction DMG dealt by other party members is increased by 5%, up to a maximum increase of 40% for 15 seconds."
        )),
        from: BuffFrom::Character(CharacterName::LumineCryo),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "frostglow_stacks",
            title: locale!(
                zh_cn: "元素爆发消耗的「寒辉」层数",
                en: "Frostglow Stacks Consumed by Elemental Burst"
            ),
            config: ItemConfigType::Int { min: 0, max: 8, default: 8 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let frostglow_stacks = match *b {
            BuffConfig::LumineCryoC6 { frostglow_stacks } => frostglow_stacks,
            _ => 8,
        };
        Box::new(BuffLumineCryoC6 { frostglow_stacks })
    }
}
