// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::buffs::buffs::prelude::*;
use crate::character::characters::cryo::qiqi::QIQI_SKILL;

pub struct BuffQiqiP3 {}

impl<A: Attribute> Buff<A> for BuffQiqiP3 {
    fn change_attribute(&self, attribute: &mut A) {
        // P3: 辉映·星超导 — 队伍中超导/星超导反应伤害+50%
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarConduct,
            )),
            "七七天赋3",
            QIQI_SKILL.p3_sc_bonus,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::Superconduct,
            )),
            "七七天赋3",
            QIQI_SKILL.p3_sc_bonus,
        );
    }
}

impl BuffMeta for BuffQiqiP3 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::QiqiP3,
        name_locale: locale!(
            zh_cn: "七七-「七宝奉真」",
            en: "Qiqi-Seven Sacred Treasures"
        ),
        image: BuffImage::Avatar(CharacterName::Qiqi),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "七七天赋3：辉映·星超导——寒病鬼差持续期间，队伍中自己的角色造成的超导、星超导反应伤害提升50%。<br>处于极星辉域中时，七七将会进入辉映·星超导状态。",
            en: "Qiqi Talent 3: Radiance: Stellar-Conduct — While the Herald of Frost is on the field, party members' Superconduct and Stellar-Conduct Reaction DMG is increased by 50%.<br>When inside a Polestar Field, Qiqi will enter the Radiance: Stellar-Conduct state."
        )),
        from: BuffFrom::Character(CharacterName::Qiqi),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        Box::new(BuffQiqiP3 {})
    }
}


pub struct BuffQiqiP1 {}

impl<A: Attribute> Buff<A> for BuffQiqiP1 {
    fn change_attribute(&self, attribute: &mut A) {
        // P1: 延命妙法 — 受治疗加成+20%
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::IncomingHealingBonus)),
            "七七天赋1",
            0.2,
        );
    }
}

impl BuffMeta for BuffQiqiP1 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::QiqiP1,
        name_locale: locale!(
            zh_cn: "七七-「延命妙法」",
            en: "Qiqi-Life-Prolonging Methods"
        ),
        image: BuffImage::Avatar(CharacterName::Qiqi),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "七七天赋1：处于仙法·寒病鬼差状态下的角色触发元素反应时，受治疗加成提升20%，持续8秒。",
            en: "Qiqi Talent 1: When a character under the effects of Adeptus Art: Herald of Frost triggers an Elemental Reaction, their Incoming Healing Bonus is increased by 20% for 8s."
        )),
        from: BuffFrom::Character(CharacterName::Qiqi),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        Box::new(BuffQiqiP1 {})
    }
}


pub struct BuffQiqiC6 {
    pub qiqi_atk: f64,
}

impl<A: Attribute> Buff<A> for BuffQiqiC6 {
    fn change_attribute(&self, attribute: &mut A) {
        // C6: 洞玄 — 每次触发消耗1层，提升星超导伤害，提升值相当于七七攻击力的600%
        let bonus = self.qiqi_atk * QIQI_SKILL.c6_bonus_per_stack;
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionExtra,
                ReactionType::StellarConduct,
            )),
            "七七命座6",
            bonus,
        );
    }
}

impl BuffMeta for BuffQiqiC6 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::QiqiC6,
        name_locale: locale!(
            zh_cn: "七七-「起死回骸」",
            en: "Qiqi-Rite of Resurrection"
        ),
        image: BuffImage::Avatar(CharacterName::Qiqi),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "七七命座6：施放仙法·救苦度厄后，七七获得4层洞玄；除七七外的队伍中自己的当前场上角色造成星超导反应伤害时，将消耗1层洞玄，提升造成的伤害，提升值相当于七七攻击力的600%。洞玄至多持续12秒。",
            en: "Qiqi C6: After using Adeptus Art: Preserver of Fortune, Qiqi gains 4 stacks of Glimpse of Mystery. When your current active character (other than Qiqi) deals Stellar-Conduct DMG, 1 stack is consumed, and DMG dealt is increased by 600% of Qiqi's ATK. Glimpse of Mystery lasts up to 12s."
        )),
        from: BuffFrom::Character(CharacterName::Qiqi),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "qiqi_atk",
            title: locale!(
                zh_cn: "七七攻击力",
                en: "Qiqi ATK"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let qiqi_atk = match *b {
            BuffConfig::QiqiC6 { qiqi_atk } => qiqi_atk,
            _ => 0.0
        };
        Box::new(BuffQiqiC6 { qiqi_atk })
    }
}
