// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::weapon::weapons::prelude::*;

pub struct BeyondTheChrysalisEffect {
    pub rate1: f64,
    pub rate2: f64,
}

impl<A: Attribute> WeaponEffect<A> for BeyondTheChrysalisEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 装备者每次施放元素战技或元素爆发时，将按照顺序依次获得「忠忱之风」「叛弃之风」
        // 「丰获之风」三种效果中的一种，装备者退场时移除效果并重置顺序。三种效果互斥且
        // 各自持续 10 秒，故以两个「应用比例」配置项分别近似「忠忱之风」与「叛弃之风」
        // 的平均覆盖率（0~1，默认 0.0）。
        if self.rate1 > 0.0 {
            // 忠忱之风：装备者的暴击伤害提升
            attribute.set_value_to(
                AttributeName::CriticalDamageBase,
                "蝶变被动",
                (0.4 + 0.16 * refine) * self.rate1,
            );
        }

        if self.rate2 > 0.0 {
            // 叛弃之风：装备者造成的星扩散反应伤害提升
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "蝶变被动",
                (0.27 + 0.09 * refine) * self.rate2,
            );
        }

        // 丰获之风为恢复元素能量效果，不参与伤害计算，故不实现。
    }
}

pub struct BeyondTheChrysalis;

impl WeaponTrait for BeyondTheChrysalis {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::BeyondTheChrysalis,
        internal_name: "Sword_Samosvist",
        weapon_type: WeaponType::Sword,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalDamage96),
        weapon_base: WeaponBaseATKFamily::ATK674,
        star: 5,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "装备者每次施放元素战技或元素爆发时，将按照以下顺序，依次获得以下三种效果中的一种：<br>忠忱之风：装备者的暴击伤害提升 <span style=\"color: #409EFF;\">56%-72%-88%-104%-120%</span> ，持续10秒；<br>叛弃之风：装备者造成的星扩散反应伤害提升 <span style=\"color: #409EFF;\">36%-45%-54%-63%-72%</span> ，持续10秒；<br>丰获之风：为装备者恢复 <span style=\"color: #409EFF;\">5-5.5-6-6.5-7</span> 点元素能量，每4秒至多通过这种方式恢复 <span style=\"color: #409EFF;\">5-5.5-6-6.5-7</span> 点元素能量。<br>装备者退场时，将移除上述效果，并重置其顺序。",
            en: "Each time the equipping character uses their Elemental Skill or Elemental Burst, they gain one of the following three effects in sequence:<br>Winds of Devotion: Increases the equipping character's CRIT DMG by <span style=\"color: #409EFF;\">56%-72%-88%-104%-120%</span> for 10s;<br>Winds of Defiance: Increases Stellar Swirl reaction DMG dealt by the equipping character by <span style=\"color: #409EFF;\">36%-45%-54%-63%-72%</span> for 10s; and<br>Winds of Plenty: Regenerates <span style=\"color: #409EFF;\">5-5.5-6-6.5-7</span> Elemental Energy for the equipping character. Up to <span style=\"color: #409EFF;\">5-5.5-6-6.5-7</span> Elemental Energy can be regenerated in this way every 4s.<br>The aforementioned effects are removed and the sequence is reset when the equipping character leaves the field."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "蝶变",
            en: "Beyond the Chrysalis"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "rate1",
            title: locale!(zh_cn: "「忠忱之风」应用比例", en: "\"Winds of Devotion\" Ratio"),
            config: ItemConfig::RATE01_TYPE,
        },
        ItemConfig {
            name: "rate2",
            title: locale!(zh_cn: "「叛弃之风」应用比例", en: "\"Winds of Defiance\" Ratio"),
            config: ItemConfig::RATE01_TYPE,
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (rate1, rate2) = match *config {
            WeaponConfig::BeyondTheChrysalis { rate1, rate2 } => (rate1, rate2),
            _ => (0.0, 0.0),
        };

        Some(Box::new(BeyondTheChrysalisEffect {
            rate1,
            rate2,
        }))
    }
}
