// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::weapon::weapons::prelude::*;

pub struct SilverLightEffect {
    pub stack: f64,
}

impl<A: Attribute> WeaponEffect<A> for SilverLightEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 施放元素战技后的 12 秒内元素精通提升，至多叠加 2 层，每层持续时间独立计算，
        // 以「被动等效层数」近似其平均层数。
        attribute.set_value_to(AttributeName::ElementalMastery, "银釭被动", (39.0 + 13.0 * refine) * self.stack);
    }
}

pub struct SilverLight;

impl WeaponTrait for SilverLight {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::SilverLight,
        internal_name: "Sword_Fajian",
        weapon_type: WeaponType::Sword,
        weapon_sub_stat: Some(WeaponSubStatFamily::ATK90),
        weapon_base: WeaponBaseATKFamily::ATK510,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "施放元素战技后的12秒内，元素精通提升 <span style=\"color: #409EFF;\">52-65-78-91-104</span> 点。该效果至多叠加2层，每层持续时间独立计算。",
            en: "Increases Elemental Mastery by <span style=\"color: #409EFF;\">52-65-78-91-104</span> for 12s after Elemental Skill use. Max 2 stacks, and each stack's duration is independent of the others."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "银釭",
            en: "Silver Light"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "stack",
            title: ItemConfig::DEFAULT_STACK_TITLE,
            config: ItemConfigType::Float { min: 0.0, max: 2.0, default: 2.0 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let stack = match *config {
            WeaponConfig::SilverLight { stack } => stack,
            _ => 0.0,
        };

        Some(Box::new(SilverLightEffect {
            stack,
        }))
    }
}
