// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::weapon::weapons::prelude::*;

pub struct WhitelakeFrostfeatherEffect {
    pub stack: f64,
    pub full_rate: f64,
}

impl<A: Attribute> WeaponEffect<A> for WhitelakeFrostfeatherEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 「湖色的哀告」：元素战技命中敌人后攻击力提升，至多叠加3层。
        if self.stack > 0.0 {
            attribute.add_atk_percentage("白湖冬羽被动", (0.06 + 0.02 * refine) * self.stack);
        }

        // 持有3层时，装备者造成的星烁反应伤害的暴击伤害提升。
        // 以「满层比例」配置项近似处于3层的时间占比。
        if self.full_rate > 0.0 {
            attribute.set_value_to_t(AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::CriticalDamage,
                ReactionType::StellarConduct,
            )), "白湖冬羽被动", (0.35 + 0.15 * refine) * self.full_rate);
            attribute.set_value_to_t(AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::CriticalDamage,
                ReactionType::StellarSwirl,
            )), "白湖冬羽被动", (0.35 + 0.15 * refine) * self.full_rate);
        }

        // 恢复元素能量的效果不参与伤害计算，故不实现。
    }
}

pub struct WhitelakeFrostfeather;

impl WeaponTrait for WhitelakeFrostfeather {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::WhitelakeFrostfeather,
        internal_name: "Sword_Swanlake",
        weapon_type: WeaponType::Sword,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalRate48),
        weapon_base: WeaponBaseATKFamily::ATK674,
        star: 5,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "装备者的元素战技命中敌人时，获得「湖色的哀告」：攻击力提升 <span style=\"color: #409EFF;\">8%-10%-12%-14%-16%</span> ，持续8秒，至多叠加3层，每0.1秒至多触发一次，每层持续时间独立计算；持有3层时，装备者造成的星烁反应伤害的暴击伤害提升 <span style=\"color: #409EFF;\">50%-65%-80%-95%-110%</span> ，且触发星烁反应或造成星烁反应伤害时，还会使装备者恢复 <span style=\"color: #409EFF;\">4-4.5-5-5.5-6</span> 点元素能量。上述恢复元素能量的效果每3.5秒至多触发一次。装备者处于队伍后台时，依然能触发上述效果。",
            en: "When the equipping character hits an opponent with their Elemental Skill, they gain \"Lake-Hued Lament\": ATK increases by <span style=\"color: #409EFF;\">8%-10%-12%-14%-16%</span> for 8s. This effect can trigger once every 0.1s. Max 3 stacks, and each stack's duration is independent. At 3 stacks, the CRIT DMG of any Stellar Glimmer reaction DMG caused by the equipping character is increased by <span style=\"color: #409EFF;\">50%-65%-80%-95%-110%</span>, and triggering Stellar Glimmer reactions or Stellar Glimmer reaction DMG will also restore <span style=\"color: #409EFF;\">4-4.5-5-5.5-6</span> Elemental Energy to the character. This Energy recovery effect can trigger once every 3.5s. Can be triggered even when the equipping character is off-field."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "白湖冬羽",
            en: "Whitelake Frostfeather"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "stack",
            title: ItemConfig::DEFAULT_STACK_TITLE,
            config: ItemConfigType::Float { min: 0.0, max: 3.0, default: 3.0 },
        },
        ItemConfig {
            name: "full_rate",
            title: locale!(zh_cn: "满层比例", en: "Full Stack Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 1.0 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (stack, full_rate) = match *config {
            WeaponConfig::WhitelakeFrostfeather { stack, full_rate } => (stack, full_rate),
            _ => (0.0, 0.0),
        };

        Some(Box::new(WhitelakeFrostfeatherEffect {
            stack,
            full_rate,
        }))
    }
}
