// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::weapon::weapons::prelude::*;

pub struct BreezeborneRefrainEffect {
    pub rate: f64,
}

impl<A: Attribute> WeaponEffect<A> for BreezeborneRefrainEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 元素充能效率提升。
        attribute.set_value_to(AttributeName::Recharge, "柔风游弦被动", 0.15 + 0.05 * refine);

        // 「蛇信的死毒」：使队伍中附近的所有角色造成的星烁反应伤害提升（星烁反应包含星超导与
        // 星扩散）。「纯净者的圣咏」叠至 3 层后转为「蛇信的死毒」（持续 12 秒，期间无法再次获得
        // 「纯净者的圣咏」），该状态存在层数循环，故以「覆盖率」配置项近似其生效时间占比
        // （0~1，默认 1.0 表示全程覆盖）。
        if self.rate > 0.0 {
            let bonus = (0.18 + 0.06 * refine) * self.rate;
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarConduct,
                )),
                "柔风游弦被动",
                bonus,
            );
            attribute.set_value_to_s(
                CharacterSelector::select_all(attribute),
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "柔风游弦被动",
                bonus,
            );
        }
    }
}

pub struct BreezeborneRefrain;

impl WeaponTrait for BreezeborneRefrain {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::BreezeborneRefrain,
        internal_name: "Bow_Windtalker",
        weapon_type: WeaponType::Bow,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalRate60),
        weapon_base: WeaponBaseATKFamily::ATK510,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "元素充能效率提升 <span style=\"color: #409EFF;\">20%-25%-30%-35%-40%</span> 。装备者的元素战技或元素爆发命中敌人时，获得一层「纯净者的圣咏」，该效果至多叠加3层，每0.03秒至多获得一层。叠加至3层时，将清除所有「纯净者的圣咏」，获得「蛇信的死毒」：使队伍中附近的所有角色造成的星烁反应伤害提升 <span style=\"color: #409EFF;\">24%-30%-36%-42%-48%</span> ，持续12秒，期间无法再次获得「纯净者的圣咏」。装备者处于队伍后台时，依然能触发上述效果。",
            en: "Increases Energy Recharge by <span style=\"color: #409EFF;\">20%-25%-30%-35%-40%</span>. When the equipping character hits the opponent with their Elemental Skill or Elemental Burst, they gain a stack of \"Hymn of the Pure.\" This effect can trigger once every 0.03s, max 3 stacks, and at 3 stacks, all instances of \"Hymn of the Pure\" are cleared to give the equipping character \"Thus Lied the Viper\" instead. This grants nearby party characters a <span style=\"color: #409EFF;\">24%-30%-36%-42%-48%</span> Stellar Glimmer reaction DMG boost for 12s, during which no stacks of \"Hymn of the Pure\" can be obtained. The aforementioned effects can still trigger even when the equipping character is not on the field."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "柔风游弦",
            en: "Breezeborne Refrain"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "rate",
            title: locale!(zh_cn: "「蛇信的死毒」覆盖率", en: "\"Thus Lied the Viper\" Uptime Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 1.0 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let rate = match *config {
            WeaponConfig::BreezeborneRefrain { rate } => rate,
            _ => 0.0,
        };

        Some(Box::new(BreezeborneRefrainEffect {
            rate,
        }))
    }
}
