// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::weapon::weapons::prelude::*;

pub struct JadeVistaEffect {
    pub same_count: usize,
    pub diff_count: usize,
}

impl<A: Attribute> WeaponEffect<A> for JadeVistaEffect {
    fn apply(&self, data: &WeaponCommonData, attribute: &mut A) {
        let refine = data.refine as f64;

        // 除装备者外，队伍中每有一名同元素角色：装备者的元素精通提升；
        // 每有一名不同元素角色：装备者的攻击力提升。
        // 上述两种效果总共至多叠加3层，元素类型相同的效果优先生效。
        let same = self.same_count.min(3);
        let diff = self.diff_count.min(3 - same);

        if same > 0 {
            attribute.set_value_by(AttributeName::ElementalMastery, "悬黎千钧被动", (48.0 + 16.0 * refine) * same as f64);
        }
        if diff > 0 {
            attribute.add_atk_percentage("悬黎千钧被动", (0.08 + 0.04 * refine) * diff as f64);
        }
    }
}

pub struct JadeVista;

impl WeaponTrait for JadeVista {
    const META_DATA: WeaponStaticData = WeaponStaticData {
        name: WeaponName::JadeVista,
        internal_name: "Bow_ShatteredMirror",
        weapon_type: WeaponType::Bow,
        weapon_sub_stat: Some(WeaponSubStatFamily::CriticalRate60),
        weapon_base: WeaponBaseATKFamily::ATK510,
        star: 4,
        #[cfg(not(target_family = "wasm"))]
        effect: Some(crate::common::i18n::locale!(
            zh_cn: "除装备者外，队伍中每有一名角色：元素类型与装备者相同：装备者的元素精通提升 <span style=\"color: #409EFF;\">64-80-96-112-128</span> 点；元素类型与装备者不同：装备者的攻击力提升 <span style=\"color: #409EFF;\">12%-15%-18%-21%-24%</span> 。上述两种效果总共至多叠加3层，元素类型相同的效果优先生效。",
            en: "For every party member other than the equipping character: · Who is of the same Elemental Type as the equipper: The equipping character's Elemental Mastery is increased by <span style=\"color: #409EFF;\">64-80-96-112-128</span>; · Who is not of the same Elemental Type as the equipper: The equipping character's ATK increases by <span style=\"color: #409EFF;\">12%-15%-18%-21%-24%</span>. The two effects described above can stack up to 3 times in total, with Elemental Mastery buffs applied first."
        )),
        #[cfg(not(target_family = "wasm"))]
        name_locale: crate::common::i18n::locale!(
            zh_cn: "悬黎千钧",
            en: "Jade Vista"
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "same_count",
            title: locale!(zh_cn: "同元素角色数", en: "Same Element Count"),
            config: ItemConfigType::Int { min: 0, max: 3, default: 1 },
        },
        ItemConfig {
            name: "diff_count",
            title: locale!(zh_cn: "不同元素角色数", en: "Diff Element Count"),
            config: ItemConfigType::Int { min: 0, max: 3, default: 2 },
        },
    ]);

    fn get_effect<A: Attribute>(character: &CharacterCommonData, config: &WeaponConfig) -> Option<Box<dyn WeaponEffect<A>>> {
        let (same_count, diff_count) = match *config {
            WeaponConfig::JadeVista { same_count, diff_count } => (same_count, diff_count),
            _ => (0, 0),
        };

        Some(Box::new(JadeVistaEffect {
            same_count,
            diff_count,
        }))
    }
}
