// Generated by GitHub Copilot (DeepSeek V4 Flash)
use crate::target_functions::target_functions::prelude::*;
use crate::character::characters::AetherCryo;

pub struct AetherCryoDefaultTargetFunction;

impl TargetFunctionMetaTrait for AetherCryoDefaultTargetFunction {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: TargetFunctionMeta = TargetFunctionMeta {
        name: TargetFunctionName::AetherCryoDefault,
        name_locale: locale!(
            zh_cn: "空-冰-旅行者",
            en: "Aether-Cryo-Traveller"
        ),
        description: locale!(
            zh_cn: "旅行者空-冰爆发每轮总伤害",
            en: "Traveller Aether-Cryo Burst DMG per Round"
        ),
        tags: "输出",
        four: TargetFunctionFor::SomeWho(CharacterName::AetherCryo),
        image: TargetFunctionMetaImage::Avatar
    };

    fn create(_character: &CharacterCommonData, _weapon: &WeaponCommonData, _config: &TargetFunctionConfig) -> Box<dyn TargetFunction> {
        Box::new(AetherCryoDefaultTargetFunction)
    }
}

impl TargetFunction for AetherCryoDefaultTargetFunction {
    fn get_target_function_opt_config(&self) -> TargetFunctionOptConfig {
        TargetFunctionOptConfig {
            atk_fixed: 0.2,
            atk_percentage: 0.6,
            hp_fixed: 0.0,
            hp_percentage: 0.0,
            def_fixed: 0.0,
            def_percentage: 0.0,
            recharge: 0.0,
            elemental_mastery: 0.2,
            critical: 1.0,
            critical_damage: 1.0,
            healing_bonus: 0.0,
            bonus_electro: 0.0,
            bonus_pyro: 0.0,
            bonus_hydro: 0.0,
            bonus_anemo: 0.0,
            bonus_cryo: 0.0,
            bonus_geo: 0.0,
            bonus_dendro: 0.0,
            bonus_physical: 0.0,
            sand_main_stats: vec![
                StatName::ATKPercentage,
            ],
            goblet_main_stats: vec![
                StatName::ATKPercentage,
            ],
            head_main_stats: vec![
                StatName::CriticalRate,
                StatName::CriticalDamage,
                StatName::ATKPercentage,
            ],
            set_names: Some(vec![
                ArtifactSetName::HeartOfTheFurnace,
                ArtifactSetName::GildedDreams,
            ]),
            very_critical_set_names: Some(vec![
                ArtifactSetName::DisenchantmentInDeepShadow,
                ArtifactSetName::ScarletProof,
            ]),
            normal_threshold: TargetFunctionOptConfig::DEFAULT_NORMAL_THRESHOLD,
            critical_threshold: TargetFunctionOptConfig::DEFAULT_CRITICAL_THRESHOLD,
            very_critical_threshold: TargetFunctionOptConfig::DEFAULT_VERY_CRITICAL_THRESHOLD,
        }
    }

    fn get_default_artifact_config(&self, _team_config: &TeamQuantization) -> ArtifactEffectConfig {
        Default::default()
    }

    fn target(&self, attribute: &TargetFunctionAttributeType, character: &Character<TargetFunctionAttributeType>, _weapon: &Weapon<TargetFunctionAttributeType>, _artifacts: &[&Artifact], enemy: &Enemy) -> f64 {
        // 寒辉满层（8层）、栗烈寒星总是在场，命座2冰晶命中视为触发（未触发星烁→60精通）
        let config = CharacterSkillConfig::AetherCryo { frostglow_stacks: 8, frostpierce_star_on_field: true, c2_ice_crystal_hit: true, c2_stellar_triggered: false };

        let mut attribute_c = (*attribute).clone();
        AetherCryo::change_attribute::<TargetFunctionAttributeType>(&mut attribute_c, &character.common_data, &config);
        let solved = attribute_c.solve();
        let context = DamageContext { character_common_data: &character.common_data, attribute: &solved, enemy };

        type Ty = <AetherCryo as CharacterTrait>::DamageEnumType;

        let dmg = |s: Ty| -> f64 {
            AetherCryo::damage::<SimpleDamageBuilder>(&context, s, &config, None).normal.expectation
        };

        // 爆发输出：元素爆发总伤害（Q_TOTAL）+ 一次强化重击（重击·冰凝）总伤害（P4T）
        dmg(Ty::Q_TOTAL) + dmg(Ty::P4T)
    }
}
