// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::target_functions::target_functions::prelude::*;
use crate::character::characters::Lohen;

pub struct LohenDefaultTargetFunction;

impl TargetFunctionMetaTrait for LohenDefaultTargetFunction {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: TargetFunctionMeta = TargetFunctionMeta {
        name: TargetFunctionName::LohenDefault,
        name_locale: locale!(
            zh_cn: "洛恩-「恣锐锋镞」",
            en: "Lohen-Sharpened Arrowhead"
        ),
        description: locale!(
            zh_cn: "洛恩一轮输出总伤害",
            en: "Lohen Total Damage Output per Round"
        ),
        tags: "输出",
        four: TargetFunctionFor::SomeWho(CharacterName::Lohen),
        image: TargetFunctionMetaImage::Avatar
    };

    fn create(_character: &CharacterCommonData, _weapon: &WeaponCommonData, _config: &TargetFunctionConfig) -> Box<dyn TargetFunction> {
        Box::new(LohenDefaultTargetFunction)
    }
}

impl TargetFunction for LohenDefaultTargetFunction {
    fn get_target_function_opt_config(&self) -> TargetFunctionOptConfig {
        TargetFunctionOptConfig {
            atk_fixed: 0.2,
            atk_percentage: 0.6,
            hp_fixed: 0.0,
            hp_percentage: 0.0,
            def_fixed: 0.0,
            def_percentage: 0.0,
            recharge: 0.0,
            elemental_mastery: 0.0,
            critical: 1.0,
            critical_damage: 1.0,
            healing_bonus: 0.0,
            bonus_electro: 0.0,
            bonus_pyro: 0.0,
            bonus_hydro: 0.0,
            bonus_anemo: 0.0,
            bonus_cryo: 1.0,
            bonus_geo: 0.0,
            bonus_dendro: 0.0,
            bonus_physical: 0.0,
            sand_main_stats: vec![
                StatName::ATKPercentage,
            ],
            goblet_main_stats: vec![
                StatName::CryoBonus,
                StatName::ATKPercentage,
            ],
            head_main_stats: vec![
                StatName::CriticalRate,
                StatName::CriticalDamage,
                StatName::ATKPercentage,
            ],
            set_names: Some(vec![
                ArtifactSetName::GladiatorsFinale,
                ArtifactSetName::BlizzardStrayer,
                ArtifactSetName::VermillionHereafter,
                ArtifactSetName::MarechausseeHunter,
                ArtifactSetName::FinaleOfTheDeepGalleries,
            ]),
            very_critical_set_names: Some(vec![
                ArtifactSetName::ADayCarvedFromRisingWinds,
                ArtifactSetName::ShimenawasReminiscence,
            ]),
            normal_threshold: TargetFunctionOptConfig::DEFAULT_NORMAL_THRESHOLD,
            critical_threshold: TargetFunctionOptConfig::DEFAULT_CRITICAL_THRESHOLD,
            very_critical_threshold: TargetFunctionOptConfig::DEFAULT_VERY_CRITICAL_THRESHOLD,
        }
    }

    fn get_default_artifact_config(&self, _team_config: &TeamQuantization) -> ArtifactEffectConfig {
        Default::default()
    }

    fn target(&self, attribute: &TargetFunctionAttributeType, character: &Character<TargetFunctionAttributeType>, _weapon: &Weapon<TargetFunctionAttributeType>, _artifacts: &[&Artifact], enemy: &Enemy) -> f64 {
        let config1 = CharacterSkillConfig::Lohen { in_masterstroke: true, evilsbane_blade: false };
        let config2 = CharacterSkillConfig::Lohen { in_masterstroke: true, evilsbane_blade: true };

        let context1 = {
            let mut attribute_temp = (*attribute).clone();
            Lohen::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config1);
            DamageContext { character_common_data: &character.common_data, attribute: &attribute_temp.solve(), enemy }
        };
        let context2 = {
            let mut attribute_temp = (*attribute).clone();
            Lohen::change_attribute::<TargetFunctionAttributeType>(&mut attribute_temp, &character.common_data, &config2);
            DamageContext { character_common_data: &character.common_data, attribute: &attribute_temp.solve(), enemy }
        };

        type Ty = <Lohen as CharacterTrait>::DamageEnumType;

        // 辅助函数：计算一套 E 普攻的总伤害（E1 E2 E3T E4 E51 E52）
        let e_combo = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            Lohen::damage::<SimpleDamageBuilder>(context, Ty::E1, config, None).normal.expectation
                + Lohen::damage::<SimpleDamageBuilder>(context, Ty::E2, config, None).normal.expectation
                + Lohen::damage::<SimpleDamageBuilder>(context, Ty::E3T, config, None).normal.expectation
                + Lohen::damage::<SimpleDamageBuilder>(context, Ty::E4, config, None).normal.expectation
                + Lohen::damage::<SimpleDamageBuilder>(context, Ty::E51, config, None).normal.expectation
                + Lohen::damage::<SimpleDamageBuilder>(context, Ty::E52, config, None).normal.expectation
        };

        let eg_dmg = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            Lohen::damage::<SimpleDamageBuilder>(context, Ty::EG, config, None).normal.expectation
        };

        let c2a_dmg = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            Lohen::damage::<SimpleDamageBuilder>(context, Ty::C2A, config, None).normal.expectation
        };

        let q_dmg = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            Lohen::damage::<SimpleDamageBuilder>(context, Ty::Q, config, None).normal.expectation
        };

        let constellation = character.common_data.constellation;

        // 辅助函数：E combo + C2A + EG，顺序不影响总伤害
        let e_c2a_eg_combo = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
            e_combo(context, config) + c2a_dmg(context, config) + eg_dmg(context, config)
        };

        if constellation >= 6 {
            // 六命以上：Q (EG E1 C2A E2 E3T E4 E51 E52 EG E1 C2A E2 E3T E4 E51 E52 EG) ×2
            // = Q + (EG + e_combo + C2A + EG + e_combo + C2A + EG) ×2
            // = Q + (EG + (e_combo + C2A + EG) ×2) ×2
            // 第一次 Q 及前使用 config1，此后使用 config2
            let e_full_combo = |context: &DamageContext<'_, TargetFunctionAttributeResultType>, config: &CharacterSkillConfig| -> f64 {
                eg_dmg(context, config) + e_c2a_eg_combo(context, config) * 2.0
            };

            q_dmg(&context1, &config1) + e_full_combo(&context2, &config2) * 2.0
        } else if constellation >= 4 {
            // 四命以上：Q (E1 C2A E2 E3T E4 E51 E52 EG) ×4
            // = Q + e_c2a_eg_combo ×4
            // 第一次 Q 及前使用 config1，此后使用 config2
            q_dmg(&context1, &config1) + e_c2a_eg_combo(&context2, &config2) * 4.0
        } else {
            // 基础循环：三次 (E1 E2 E3T E4 E51 E52 EG C2A) 循环最后追加一次 (E1 E2 E3T E4 E51 E52 Q)
            // 第一次 EG 及前使用 config1，第一次 C2A 及后使用 config2
            // 第一轮：E1-E52 用 config1，EG 用 config1，C2A 用 config2
            let first_cycle = e_combo(&context1, &config1) + eg_dmg(&context1, &config1) + c2a_dmg(&context2, &config2);

            // 后续两轮全部用 config2
            let later_cycles = e_c2a_eg_combo(&context2, &config2) * 2.0;

            // 最后追加：E1 E2 E3T E4 E51 E52 Q 全部用 config2
            let final_combo = e_combo(&context2, &config2) + q_dmg(&context2, &config2);

            first_cycle + later_cycles + final_combo
        }
    }
}
