// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::buffs::buffs::prelude::*;
use crate::character::characters::nicole::NICOLE_SKILL;

pub struct BuffNicoleE {
    pub level_e: usize,
    pub atk: f64,
}

impl<A: Attribute> Buff<A> for BuffNicoleE {
    fn change_attribute(&self, attribute: &mut A) {
        let ratio = NICOLE_SKILL.e_grace_ratio[self.level_e - 1];
        let max = NICOLE_SKILL.e_grace_max[self.level_e - 1];

        let atk_bonus = (self.atk * ratio).min(max);

        attribute.set_value_to_t(
            AttributeType::Panel(AttributeName::ATKFixed),
            "尼可E技能",
            atk_bonus,
        );
    }
}

impl BuffMeta for BuffNicoleE {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::NicoleE,
        name_locale: locale!(
            zh_cn: "尼可-「虚己之赐」",
            en: "Nicole-Grace of Kenosis"
        ),
        image: BuffImage::Avatar(CharacterName::Nicole),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "尼可E技能：为队伍中附近的所有角色赋予「虚己之赐」效果，基于尼可的攻击力提升攻击力。",
            en: "Nicole Skill E: Bestows the Grace of Kenosis effect on all nearby party members, increasing their ATK based on Nicole's ATK."
        )),
        from: BuffFrom::Character(CharacterName::Nicole),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "level_e",
            title: locale!(
                zh_cn: "技能等级",
                en: "Skill Level"
            ),
            config: ItemConfigType::Int { min: 1, max: 15, default: 10 }
        },
        ItemConfig {
            name: "atk",
            title: locale!(
                zh_cn: "尼可攻击力",
                en: "Nicole's ATK"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (level_e, atk) = match *b {
            BuffConfig::NicoleE { level_e, atk } => (level_e, atk),
            _ => (10, 0.0)
        };
        Box::new(BuffNicoleE { level_e, atk })
    }
}


pub struct BuffNicoleGuidance {
    pub has_guidance: bool,
}

impl<A: Attribute> Buff<A> for BuffNicoleGuidance {
    fn change_attribute(&self, attribute: &mut A) {
        if self.has_guidance {
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::ATKFixed),
                "尼可圣祝之引",
                300.0,
            );
        }
    }
}

impl BuffMeta for BuffNicoleGuidance {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::NicoleGuidance,
        name_locale: locale!(
            zh_cn: "尼可-「圣祝之引」",
            en: "Nicole-Guidance of Theosis"
        ),
        image: BuffImage::Avatar(CharacterName::Nicole),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "尼可天赋1/天赋2：「虚己之赐」升变为「圣祝之引」，额外提升300点攻击力。\n解锁固有天赋「分有」并满足其中观测条件后，或解锁固有天赋「慕善」后，虚己之赐将升变为圣祝之引。",
            en: "Nicole Talent 1/Talent 2: Grace of Kenosis is upgraded to Guidance of Theosis, increasing ATK by an additional 300.\nAfter unlocking the Passive Talent \"Methexis\" and meeting the Observation conditions, or unlocking the Passive Talent \"Philokalia,\" Grace of Kenosis will be upgraded to Guidance of Theosis."
        )),
        from: BuffFrom::Character(CharacterName::Nicole),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "has_guidance",
            title: locale!(
                zh_cn: "拥有圣祝之引",
                en: "Has Guidance of Theosis"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let has_guidance = match *b {
            BuffConfig::NicoleGuidance { has_guidance } => has_guidance,
            _ => false
        };
        Box::new(BuffNicoleGuidance { has_guidance })
    }
}


pub struct BuffNicoleC2 {
    pub has_c2: bool,
    pub element: Element,
}

impl<A: Attribute> Buff<A> for BuffNicoleC2 {
    fn change_attribute(&self, attribute: &mut A) {
        if self.has_c2 {
            // C2：虚己之赐额外提升300点攻击力（不计入加成上限）
            attribute.set_value_to_t(
                AttributeType::Panel(AttributeName::ATKFixed),
                "尼可命座2",
                300.0,
            );

            // C2：圣祝之引依据角色元素类型降低对应元素抗性25%
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_element(
                    AttributeVariableType::ResMinus,
                    self.element,
                )),
                "尼可命座2",
                0.25,
            );
        }
    }
}

impl BuffMeta for BuffNicoleC2 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::NicoleC2,
        name_locale: locale!(
            zh_cn: "尼可-「我要教导你，指引你应走的路」",
            en: "Nicole-\"I Will Guide You and Show You the Path You Should Tread\""
        ),
        image: BuffImage::Avatar(CharacterName::Nicole),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "尼可命座2：「虚己之赐」额外提升300点攻击力（不计入加成上限）；「圣祝之引」依据角色元素类型，使附近敌人的对应元素抗性降低25%。",
            en: "Nicole C2: Grace of Kenosis increases ATK by an additional 300 (does not count toward the ATK Bonus limit); Guidance of Theosis decreases nearby opponents' Elemental RES against the corresponding character's Elemental Type by 25%."
        )),
        from: BuffFrom::Character(CharacterName::Nicole),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "has_c2",
            title: locale!(
                zh_cn: "命座2",
                en: "C2"
            ),
            config: ItemConfigType::Bool { default: false }
        },
        ItemConfig {
            name: "element",
            title: locale!(
                zh_cn: "角色元素类型",
                en: "Character's Element"
            ),
            config: ItemConfigType::Element8 { default: Element::Pyro }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (has_c2, element) = match *b {
            BuffConfig::NicoleC2 { has_c2, element } => (has_c2, element),
            _ => (false, Element::Pyro)
        };
        Box::new(BuffNicoleC2 { has_c2, element })
    }
}


pub struct BuffNicoleC4 {
    pub atk: f64,
}

impl<A: Attribute> Buff<A> for BuffNicoleC4 {
    fn change_attribute(&self, attribute: &mut A) {
        let atk = self.atk;

        for skill in [
            SkillType::NormalAttack,
            SkillType::ChargedAttack,
            SkillType::PlungingAttackInAction,
            SkillType::PlungingAttackOnGround,
            SkillType::ElementalSkill,
            SkillType::ElementalBurst,
        ]
        .into_iter()
        {
            attribute.set_value_to_t(
                AttributeType::Invisible(InvisibleAttributeType::new_skill(
                    AttributeVariableType::BaseDamage,
                    skill,
                )),
                "尼可命座4",
                atk * 0.7,
            );
        }
    }
}

impl BuffMeta for BuffNicoleC4 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::NicoleC4,
        name_locale: locale!(
            zh_cn: "尼可-「向左或向右，无论你行往何方」",
            en: "Nicole-\"Whether Left or Right, No Matter Which Way You Turn\""
        ),
        image: BuffImage::Avatar(CharacterName::Nicole),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "尼可命座4：拥有「先导之佑」的角色的普通攻击、重击、下落攻击、元素战技与元素爆发造成的伤害提升，提升值相当于尼可攻击力的70%。",
            en: "Nicole C4: The Normal Attack, Charged Attack, Plunging Attack, Elemental Skill, and Elemental Burst DMG of characters with Pathfinder's Blessing is increased by 70% of Nicole's ATK."
        )),
        from: BuffFrom::Character(CharacterName::Nicole),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "atk",
            title: locale!(
                zh_cn: "尼可攻击力",
                en: "Nicole's ATK"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let atk = match *b {
            BuffConfig::NicoleC4 { atk } => atk,
            _ => 0.0
        };
        Box::new(BuffNicoleC4 { atk })
    }
}


pub struct BuffNicoleC6 {
}

impl<A: Attribute> Buff<A> for BuffNicoleC6 {
    fn change_attribute(&self, attribute: &mut A) {
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_any(
                AttributeVariableType::DefPenetration,
            )),
            "尼可命座6",
            0.4,
        );
    }
}

impl BuffMeta for BuffNicoleC6 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::NicoleC6,
        name_locale: locale!(
            zh_cn: "尼可-「这便是正确的道路，莫要彷徨」",
            en: "Nicole-\"This Is the Path, Walk It Without Delay\""
        ),
        image: BuffImage::Avatar(CharacterName::Nicole),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "尼可命座6：拥有「圣祝之引」的角色造成的伤害将无视敌人40%的防御力。",
            en: "Nicole C6: DMG dealt by characters with Guidance of Theosis will ignore 40% of opponents' DEF."
        )),
        from: BuffFrom::Character(CharacterName::Nicole),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        Box::new(BuffNicoleC6 {})
    }
}
