// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct PruneSkillType {
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    pub e_dmg: [f64; 15],
    pub e_dmg_convert: [f64; 15],

    pub q_dmg: [f64; 15],
    pub q_dmg_bell: [f64; 15],

    pub p1_dmg: f64,
    pub c4_dmg: f64,
}

pub const PRUNE_SKILL: PruneSkillType = PruneSkillType {
    // Normal Attack: Badaboom! Hexbuster Hammer
    a_dmg1: [0.4862, 0.5227, 0.5591, 0.6078, 0.6442, 0.6807, 0.7293, 0.7779, 0.8266, 0.8752, 0.9238, 0.9724, 1.0332, 1.094, 1.1547],
    a_dmg2: [0.4828, 0.519, 0.5552, 0.6035, 0.6397, 0.6759, 0.7242, 0.7725, 0.8208, 0.8691, 0.9173, 0.9656, 1.026, 1.0863, 1.1467],
    a_dmg3: [0.6798, 0.7308, 0.7817, 0.8497, 0.9007, 0.9517, 1.0197, 1.0876, 1.1556, 1.2236, 1.2916, 1.3595, 1.4445, 1.5295, 1.6144],
    z_dmg: [1.3352, 1.4353, 1.5355, 1.669, 1.7691, 1.8693, 2.0028, 2.1363, 2.2698, 2.4034, 2.5369, 2.6704, 2.8373, 3.0042, 3.1711],
    x_dmg1: [0.5683, 0.6145, 0.6608, 0.7269, 0.7731, 0.826, 0.8987, 0.9714, 1.0441, 1.1234, 1.2027, 1.282, 1.3612, 1.4405, 1.5198],
    x_dmg2: [1.1363, 1.2288, 1.3213, 1.4535, 1.5459, 1.6516, 1.797, 1.9423, 2.0877, 2.2462, 2.4048, 2.5634, 2.7219, 2.8805, 3.039],
    x_dmg3: [1.4193, 1.5349, 1.6504, 1.8154, 1.931, 2.063, 2.2445, 2.4261, 2.6076, 2.8057, 3.0037, 3.2018, 3.3998, 3.5979, 3.7959],

    // Elemental Skill: Ring-A-Ding-Ding! Hexhunter Chime
    e_dmg: [1.6744, 1.8, 1.9256, 2.093, 2.2186, 2.3442, 2.5116, 2.679, 2.8465, 3.0139, 3.1814, 3.3488, 3.5581, 3.7674, 3.9767],
    e_dmg_convert: [2.0456, 2.199, 2.3524, 2.557, 2.7104, 2.8638, 3.0684, 3.273, 3.4775, 3.6821, 3.8866, 4.0912, 4.3469, 4.6026, 4.8583],

    // Elemental Burst: The Bell Tolls! The Hunt is On!
    q_dmg: [0.9696, 1.0423, 1.115, 1.212, 1.2847, 1.3574, 1.4544, 1.5514, 1.6483, 1.7453, 1.8422, 1.9392, 2.0604, 2.1816, 2.3028],
    q_dmg_bell: [0.7044, 0.7572, 0.8101, 0.8805, 0.9333, 0.9862, 1.0566, 1.127, 1.1975, 1.2679, 1.3384, 1.4088, 1.4969, 1.5849, 1.673],

    p1_dmg: 1.5,
    c4_dmg: 0.8,
};

pub const PRUNE_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Prune,
    internal_name: "Prune",
    element: Element::Anemo,
    hp: [811, 2085, 2691, 4031, 4461, 5132, 5706, 6376, 6807, 7477, 7907, 8578, 9008, 9679, 10348],
    atk: [19, 48, 61, 92, 102, 117, 130, 146, 155, 171, 180, 196, 206, 221, 277],
    def: [49, 125, 161, 242, 267, 308, 342, 382, 408, 448, 474, 514, 540, 580, 620],
    sub_stat: CharacterSubStatFamily::ATK240,
    weapon_type: WeaponType::Catalyst,
    star: 4,
    skill_name1: locale!(
        zh_cn: "隆咚咚·破魔之锤",
        en: "Badaboom! Hexbuster Hammer",
    ),
    skill_name2: locale!(
        zh_cn: "叮铃铃·猎魔之音",
        en: "Ring-A-Ding-Ding! Hexhunter Chime",
    ),
    skill_name3: locale!(
        zh_cn: "铃鸣·狩魔之刻",
        en: "The Bell Tolls! The Hunt is On!",
    ),
    name_locale: locale!(
        zh_cn: "布伦妮",
        en: "Prune",
    )
};

pub struct PruneEffect {
    pub hexerei_secret_rite: bool,
    pub elemental_absorption: Option<Element>,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for PruneEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P4: Hexerei: Secret Rite - Prune ATK +60% when Hexerei character with Tolling Rally triggers reaction
        if self.hexerei_secret_rite {
            attribute.add_atk_percentage("布伦妮天赋3", 0.6);
        }
    }
}

damage_enum!(
    PruneDamageEnum
    A1
    A2
    A3
    Z
    X1
    X2
    X3
    E
    EC
    Q
    QB
    P1
    C4E
    C4Q
);

impl PruneDamageEnum {
    pub fn get_element(&self, elemental_absorption: Option<Element>) -> Element {
        use PruneDamageEnum::*;
        match *self {
            A1 | A2 | A3 | Z | X1 | X2 | X3 | E | Q | QB => Element::Anemo,
            EC | P1 | C4E | C4Q => elemental_absorption.unwrap_or(Element::Anemo),
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use PruneDamageEnum::*;
        match *self {
            A1 | A2 | A3 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E | EC | C4E => SkillType::ElementalSkill,
            Q | QB | P1 | C4Q => SkillType::ElementalBurst,
        }
    }
}

pub struct Prune;

impl CharacterTrait for Prune {
    const STATIC_DATA: CharacterStaticData = PRUNE_STATIC_DATA;
    type SkillType = PruneSkillType;
    const SKILL: Self::SkillType = PRUNE_SKILL;
    type DamageEnumType = PruneDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = Some(
        &[CharacterTag::Hexerei]
    );

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            PruneDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            PruneDamageEnum
            E locale!(zh_cn: "叮铃铃·猎魔之音伤害", en: "Ring-A-Ding-Ding! Hexhunter Chime DMG")
            EC locale!(zh_cn: "咚锵锵·裁魔之惩伤害", en: "Clang Clang! Witch-tribution Comes! DMG")
            C4E locale!(zh_cn: "命座4弹射伤害-元素战技", en: "C4 Ricochet DMG-Elemental Skill")
        ),
        skill3: skill_map!(
            PruneDamageEnum
            Q locale!(zh_cn: "技能伤害", en: "Skill DMG")
            QB locale!(zh_cn: "诱巫饵铃伤害", en: "Witchlure Bell DMG")
            P1 locale!(zh_cn: "狩灾誓锤伤害", en: "Banehunter Oathhammer DMG")
            C4Q locale!(zh_cn: "命座4弹射伤害-元素爆发", en: "C4 Ricochet DMG-Elemental Burst")
        )
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::HEXEREI_SECRET_RITE_GLOBAL(false, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "elemental_absorption",
            title: locale!(
                zh_cn: "元素转化",
                en: "Elemental Absorption"
            ),
            config: ItemConfigType::ElementOptional {
                elements: &[Element::Pyro, Element::Hydro, Element::Electro, Element::Cryo],
                default: None,
            }
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "tolling_rally",
            title: locale!(
                zh_cn: "「振铃鼓舞」效果",
                en: "Tolling Rally effect"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "swirl_trigger",
            title: locale!(
                zh_cn: "当前场上角色触发扩散反应",
                en: "On-field character triggers Swirl"
            ),
            config: ItemConfigType::Bool { default: false }
        },
        ItemConfig {
            name: "hunt_the_witch_stacks",
            title: locale!(
                zh_cn: "「寻猎魔女」层数",
                en: "Hunt the Witch stacks"
            ),
            config: ItemConfigType::Int { min: 0, max: 6, default: 6 }
        },
        ItemConfig {
            name: "c6_atk",
            title: locale!(
                zh_cn: "命座6攻击力加成",
                en: "C6 ATK Bonus"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (hexerei_secret_rite, elemental_absorption) = match &common_data.config {
            CharacterConfig::Prune { hexerei_secret_rite, elemental_absorption } => (*hexerei_secret_rite, *elemental_absorption),
            _ => (false, None),
        };

        let (tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk) = match *skill_config {
            CharacterSkillConfig::Prune { tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk } => (tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk),
            _ => (false, false, 0, false)
        };

        // P2: Tolling Synchronicity - other party members gain DMG bonus based on Prune's ATK > 2000
        if tolling_rally && common_data.has_talent2 {
            attribute.add_edge_s1to1(
                CharacterSelector::select_all_except_self(attribute),
                AttributeType::Panel(AttributeName::ATK),
                AttributeType::Invisible(InvisibleAttributeType::new_any(AttributeVariableType::Bonus)),
                Arc::new(move |atk: f64, _| ((atk - 2000.0) * 0.00025).max(0.0).min(0.5)),
                "布伦妮天赋2",
                EdgePriority::Invisible,
            );
        }

        // P4: If Swirl triggered, on-field character additionally gains +30% ATK
        if hexerei_secret_rite && swirl_trigger {
            attribute.add_edge_s1ton(
                CharacterSelector::select_onfield(attribute),
                AttributeType::Panel(AttributeName::ATKBase),
                AttributeType::Panel(AttributeName::ATKPercentage),
                Arc::new(move |base: f64, _| base * 0.3),
                "布伦妮天赋3",
                EdgePriority::Base,
            );
        }

        // C2: Hunt the Witch - Prune ATK increases
        if common_data.constellation >= 2 && hunt_the_witch_stacks > 0 {
            let c2_atk_bonus = 0.1 + hunt_the_witch_stacks as f64 * 0.05; // base 10% + 5% per stack, max 40%
            attribute.add_atk_percentage("布伦妮命座2", c2_atk_bonus);
        }

        // C6: After Tolling Rally reaction trigger, Prune and active chars gain 350 ATK
        if common_data.constellation >= 6 && c6_atk && tolling_rally {
            attribute.set_value_by(AttributeName::ATKFixed, "布伦妮命座6", 350.0);
            attribute.set_value_by_s(
                CharacterSelector::select_onfield_except_self(attribute),
                AttributeType::Panel(AttributeName::ATKFixed),
                "布伦妮命座6",
                350.0,
            );
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: PruneDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (hexerei_secret_rite, elemental_absorption) = match &context.character_common_data.config {
            CharacterConfig::Prune { hexerei_secret_rite, elemental_absorption } => (*hexerei_secret_rite, *elemental_absorption),
            _ => (false, None),
        };

        let (tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk) = match *config {
            CharacterSkillConfig::Prune { tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk } => (tolling_rally, swirl_trigger, hunt_the_witch_stacks, c6_atk),
            _ => (false, false, 0, false)
        };

        use PruneDamageEnum::*;
        let mut builder = D::new();

        // P1, C4E and C4Q are only available when the converted hammer exists
        if (s == P1 || s == C4E || s == C4Q) && elemental_absorption == None {
            return builder.none();
        }

        // P1 only available with talent1
        if s == P1 && !context.character_common_data.has_talent1 {
            return builder.none();
        }

        // C4 only available with constellation >= 4
        if (s == C4E || s == C4Q) && context.character_common_data.constellation < 4 {
            return builder.none();
        }

        let ratio = match s {
            A1 => PRUNE_SKILL.a_dmg1[s1],
            A2 => PRUNE_SKILL.a_dmg2[s1],
            A3 => PRUNE_SKILL.a_dmg3[s1],
            Z => PRUNE_SKILL.z_dmg[s1],
            X1 => PRUNE_SKILL.x_dmg1[s1],
            X2 => PRUNE_SKILL.x_dmg2[s1],
            X3 => PRUNE_SKILL.x_dmg3[s1],
            E => PRUNE_SKILL.e_dmg[s2],
            EC => PRUNE_SKILL.e_dmg_convert[s2],
            Q => PRUNE_SKILL.q_dmg[s3],
            QB => PRUNE_SKILL.q_dmg_bell[s3],
            P1 => PRUNE_SKILL.p1_dmg,
            C4E | C4Q => PRUNE_SKILL.c4_dmg,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        builder.damage(
            &context.attribute,
            &context.enemy,
            s.get_element(elemental_absorption),
            s.get_skill_type(),
            context.character_common_data.level,
            fumo,
        )
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (hexerei_secret_rite, elemental_absorption) = match *config {
            CharacterConfig::Prune { hexerei_secret_rite, elemental_absorption } => (hexerei_secret_rite, elemental_absorption),
            _ => (false, None),
        };
        Some(Box::new(PruneEffect {
            hexerei_secret_rite,
            elemental_absorption,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
