// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::character::characters::prelude::*;

pub struct VesnaSkillType {
    // Normal Attack: 巡风剑舞
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15], // 三段伤害（共 2 次，单次倍率）
    pub a_dmg4: [f64; 15],
    pub a_dmg5: [f64; 15],
    pub a_dmg6: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 操典·制胜有道
    pub e_dmg: [f64; 15],           // 技能伤害
    pub e_sword1: [f64; 15],        // 翔风剑一阶伤害
    pub e_sword2: [f64; 15],        // 翔风剑二阶伤害
    pub e_spirit2: [f64; 15],       // 翔风剑二阶灵剑伤害
    pub e_spirit3: [f64; 15],       // 翔风剑三阶灵剑伤害（单次，共 4 次）
    pub e_spirit3_final: [f64; 15], // 翔风剑三阶灵剑最终段伤害
    pub e_plume: [f64; 15],         // 风翎伤害

    // Elemental Burst: 致礼·献予女皇陛下
    pub q_spirit: [f64; 15], // 灵剑伤害

    // 天赋1·仪典·春之行列
    pub p1_stack_bonus: f64, // 每层「整肃」使灵剑伤害提升 (0.10 = 10%)
    pub p1_max_stacks: f64,  // 「整肃」最大层数 (6)

    // 天赋2·理典·冬之凯风
    pub p2_atk_per_cryo_anemo: f64, // 每位冰/风元素角色提升攻击力 (0.06 = 6%)
    pub p2_em_per_other: f64,       // 每位其他元素角色提升元素精通 (25)

    // 天赋3·星耀祝礼·散华序饰
    pub p3_base_per_100_atk: f64, // 每 100 点攻击力提升星扩散反应基础伤害 (0.007 = 0.7%)
    pub p3_base_max: f64,         // 该方式最大提升 (0.14 = 14%)

    // 命座1·送冬的华宴
    pub c1_stellar_bonus: f64, // 「巡风列装」模式下星扩散反应伤害提升 (0.20 = 20%)

    // 命座2·迎春的轮舞
    pub c2_atk_bonus: f64, // 拥有最大层数「整肃」时攻击力提升 (0.40 = 40%)

    // 命座4·先代的荣膺
    pub c4_p2_multiplier: f64, // 天赋2 攻击力/元素精通提升效果倍率 (3.0)

    // 命座6·不移的赤忱
    pub c6_transpose_atk: f64,  // 翔风剑·变移伤害攻击力倍率 (1.5 = 150%)
    pub c6_spirit_atk: f64,     // 翔风剑·变移召唤灵剑伤害攻击力倍率 (2.0 = 200%)
    pub c6_elevate: f64,        // 星扩散反应伤害擢升 (0.20 = 20%)
}

pub const VESNA_SKILL: VesnaSkillType = VesnaSkillType {
    // Normal Attack: 巡风剑舞
    a_dmg1: [0.4042, 0.4371, 0.47, 0.517, 0.5499, 0.5875, 0.6392, 0.6909, 0.7426, 0.799, 0.8554, 0.9118, 0.9682, 1.0246, 1.081],
    a_dmg2: [0.4868, 0.5264, 0.566, 0.6226, 0.6622, 0.7075, 0.7698, 0.832, 0.8943, 0.9622, 1.0301, 1.098, 1.166, 1.2339, 1.3018],
    a_dmg3: [0.2808, 0.3036, 0.3265, 0.3591, 0.382, 0.4081, 0.444, 0.48, 0.5159, 0.5551, 0.5942, 0.6334, 0.6726, 0.7118, 0.7509],
    a_dmg4: [0.5917, 0.6398, 0.688, 0.7568, 0.805, 0.86, 0.9357, 1.0114, 1.087, 1.1696, 1.2522, 1.3347, 1.4173, 1.4998, 1.5824],
    a_dmg5: [0.6244, 0.6752, 0.726, 0.7986, 0.8494, 0.9075, 0.9874, 1.0672, 1.1471, 1.2342, 1.3213, 1.4084, 1.4956, 1.5827, 1.6698],
    a_dmg6: [0.7224, 0.7812, 0.84, 0.924, 0.9828, 1.05, 1.1424, 1.2348, 1.3272, 1.428, 1.5288, 1.6296, 1.7304, 1.8312, 1.932],
    z_dmg: [1.3304, 1.4387, 1.547, 1.7017, 1.81, 1.9338, 2.1039, 2.2741, 2.4443, 2.6299, 2.8155, 3.0012, 3.1868, 3.3725, 3.5581],
    x_dmg1: [0.6393, 0.6914, 0.7434, 0.8177, 0.8698, 0.9293, 1.011, 1.0928, 1.1746, 1.2638, 1.353, 1.4422, 1.5314, 1.6206, 1.7098],
    x_dmg2: [1.2784, 1.3824, 1.4865, 1.6351, 1.7392, 1.8581, 2.0216, 2.1851, 2.3486, 2.527, 2.7054, 2.8838, 3.0622, 3.2405, 3.4189],
    x_dmg3: [1.5968, 1.7267, 1.8567, 2.0424, 2.1723, 2.3209, 2.5251, 2.7293, 2.9336, 3.1564, 3.3792, 3.602, 3.8248, 4.0476, 4.2704],

    // Elemental Skill: 操典·制胜有道
    e_dmg: [0.40, 0.43, 0.46, 0.50, 0.53, 0.56, 0.60, 0.64, 0.68, 0.72, 0.76, 0.80, 0.85, 0.90, 0.95],
    e_sword1: [0.40, 0.43, 0.46, 0.50, 0.53, 0.56, 0.60, 0.64, 0.68, 0.72, 0.76, 0.80, 0.85, 0.90, 0.95],
    e_sword2: [0.60, 0.645, 0.69, 0.75, 0.795, 0.84, 0.90, 0.96, 1.02, 1.08, 1.14, 1.20, 1.275, 1.35, 1.425],
    e_spirit2: [1.12, 1.204, 1.288, 1.40, 1.484, 1.568, 1.68, 1.792, 1.904, 2.016, 2.128, 2.24, 2.38, 2.52, 2.66],
    e_spirit3: [0.448, 0.4816, 0.5152, 0.56, 0.5936, 0.6272, 0.672, 0.7168, 0.7616, 0.8064, 0.8512, 0.896, 0.952, 1.008, 1.064],
    e_spirit3_final: [1.568, 1.6856, 1.8032, 1.96, 2.0776, 2.1952, 2.352, 2.5088, 2.6656, 2.8224, 2.9792, 3.136, 3.332, 3.528, 3.724],
    e_plume: [0.104, 0.1118, 0.1196, 0.13, 0.1378, 0.1456, 0.156, 0.1664, 0.1768, 0.1872, 0.1976, 0.208, 0.221, 0.234, 0.247],

    // Elemental Burst: 致礼·献予女皇陛下
    q_spirit: [2.632, 2.8294, 3.0268, 3.29, 3.4874, 3.6848, 3.948, 4.2112, 4.4744, 4.7376, 5.0008, 5.264, 5.593, 5.922, 6.251],

    // 天赋1·仪典·春之行列
    p1_stack_bonus: 0.10,
    p1_max_stacks: 6.0,

    // 天赋2·理典·冬之凯风
    p2_atk_per_cryo_anemo: 0.06,
    p2_em_per_other: 25.0,

    // 天赋3·星耀祝礼·散华序饰
    p3_base_per_100_atk: 0.007,
    p3_base_max: 0.14,

    // 命座1·送冬的华宴
    c1_stellar_bonus: 0.20,

    // 命座2·迎春的轮舞
    c2_atk_bonus: 0.40,

    // 命座4·先代的荣膺
    c4_p2_multiplier: 3.0,

    // 命座6·不移的赤忱
    c6_transpose_atk: 1.5,
    c6_spirit_atk: 2.0,
    c6_elevate: 0.20,
};

pub const VESNA_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::Vesna,
    internal_name: "Vesna",
    element: Element::Anemo,
    hp: [1032, 2678, 3563, 5332, 5961, 6858, 7697, 8603, 9232, 10147, 10776, 11701, 12330, 13262, 14205],
    atk: [28, 71, 95, 142, 159, 183, 205, 230, 246, 271, 288, 312, 329, 354, 434],
    def: [57, 147, 196, 294, 328, 378, 424, 474, 508, 559, 593, 644, 679, 730, 782],
    sub_stat: CharacterSubStatFamily::CriticalRate192,
    weapon_type: WeaponType::Sword,
    star: 5,
    skill_name1: locale!(
        zh_cn: "巡风剑舞",
        en: "Vila Blade Dance",
    ),
    skill_name2: locale!(
        zh_cn: "操典·制胜有道",
        en: "The Art of Victory",
    ),
    skill_name3: locale!(
        zh_cn: "致礼·献予女皇陛下",
        en: "For the Tsaritsa!",
    ),
    name_locale: locale!(
        zh_cn: "薇斯纳",
        en: "Vesna",
    ),
};

pub struct VesnaEffect {
    pub stellar_glimmer_state: StellarGlimmerState,
    pub cryo_anemo_count: usize,
    pub other_count: usize,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for VesnaEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋2·理典·冬之凯风：[辉映·星扩散] 依据队伍中角色的元素类型，薇斯纳获得对应效果。
        // ·每有一位冰元素或风元素角色：攻击力提升 6%；
        // ·每有一位不为上述元素类型的角色：元素精通提升 25 点。
        // 命座4「先代的荣膺」使上述提升效果变为原本的三倍。
        // 该天赋效果以「辉映·星扩散」为限定条件，需处于辉映·星扩散状态时才生效。
        if self.common_data.has_talent2 && self.stellar_glimmer_state.is_stellar_swirl() {
            let multiplier = if self.common_data.constellation >= 4 {
                VESNA_SKILL.c4_p2_multiplier
            } else {
                1.0
            };

            let atk_bonus = self.cryo_anemo_count as f64 * VESNA_SKILL.p2_atk_per_cryo_anemo * multiplier;
            if atk_bonus > 0.0 {
                attribute.add_atk_percentage("薇斯纳天赋2", atk_bonus);
            }

            let em_bonus = self.other_count as f64 * VESNA_SKILL.p2_em_per_other * multiplier;
            if em_bonus > 0.0 {
                attribute.set_value_by(AttributeName::ElementalMastery, "薇斯纳天赋2", em_bonus);
            }
        }

        // 天赋3·星耀祝礼·散华序饰：基于薇斯纳的攻击力，提升队伍中角色造成的星扩散反应的基础伤害，
        // 每 100 点攻击力提升 0.7%，至多提升 14%。（天赋3 始终生效，不受辉映状态限制）
        attribute.add_edge_s1to1(
            CharacterSelector::select_all(attribute),
            AttributeType::Panel(AttributeName::ATK),
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeBase,
                ReactionType::StellarSwirl,
            )),
            Arc::new(|atk: f64, _| (atk / 100.0 * VESNA_SKILL.p3_base_per_100_atk).min(VESNA_SKILL.p3_base_max)),
            "薇斯纳天赋3",
            EdgePriority::Invisible,
        );

        // 命座6·不移的赤忱：薇斯纳造成的星扩散反应伤害擢升 20%
        if self.common_data.constellation >= 6 {
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ElevativeElevate,
                    ReactionType::StellarSwirl,
                )),
                "薇斯纳命座6",
                VESNA_SKILL.c6_elevate,
            );
        }
    }
}

damage_enum!(
    VesnaDamageEnum
    A1          // 一段伤害
    A2          // 二段伤害
    A31         // 三段伤害-1
    A32         // 三段伤害-2
    A4          // 四段伤害
    A5          // 五段伤害
    A6          // 六段伤害
    Z           // 重击伤害
    X1          // 下坠期间伤害
    X2          // 低空坠地冲击伤害
    X3          // 高空坠地冲击伤害
    E           // 元素战技伤害（操典·制胜有道）
    E_SWORD1    // 翔风剑一阶伤害
    E_SWORD2    // 翔风剑二阶伤害
    E_SPIRIT2   // 翔风剑二阶灵剑伤害（视为星扩散反应伤害的灵剑伤害）
    E_SPIRIT3   // 翔风剑三阶灵剑伤害（单次，共 4 次）
    E_SPIRIT3_TOTAL // 翔风剑三阶灵剑总伤害（×4）
    E_SPIRIT3_FINAL // 翔风剑三阶灵剑最终段伤害
    E_PLUME     // 风翎伤害（「巡风列装」模式下普通攻击/重击/下落攻击唤出）
    Q_SPIRIT    // 元素爆发灵剑伤害（视为星扩散反应伤害的灵剑伤害）
    C6A         // 命座6「翔风剑·变移」伤害（普通攻击触发）
    C6A_SPIRIT  // 命座6「翔风剑·变移」灵剑伤害（普通攻击触发）
    C6E         // 命座6「翔风剑·变移」伤害（元素战技触发）
    C6E_SPIRIT  // 命座6「翔风剑·变移」灵剑伤害（元素战技触发）
);

impl VesnaDamageEnum {
    /// 普通攻击、重击与下落攻击在「巡风列装」模式下转为造成风元素伤害。
    pub fn get_element(&self, in_armed_for_action: bool) -> Element {
        use VesnaDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | A5 | A6 | Z | X1 | X2 | X3 => {
                if in_armed_for_action {
                    Element::Anemo
                } else {
                    Element::Physical
                }
            }
            _ => Element::Anemo,
        }
    }

    pub fn get_skill_type(&self) -> SkillType {
        use VesnaDamageEnum::*;
        match *self {
            A1 | A2 | A31 | A32 | A4 | A5 | A6 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E | E_SWORD1 | E_SWORD2 | E_SPIRIT2 | E_SPIRIT3 | E_SPIRIT3_TOTAL | E_SPIRIT3_FINAL => SkillType::ElementalSkill,
            // 风翎为「巡风列装」模式下唤出的协同攻击，倍率取自元素战技，按元素战技伤害类型计算
            // （与七七「寒病鬼差协同攻击」、雷电将军「协同攻击伤害」的处理一致）
            E_PLUME => SkillType::ElementalSkill,
            Q_SPIRIT => SkillType::ElementalBurst,
            // 命座6「翔风剑·变移」可由普通攻击或元素战技触发，分别判定
            C6A | C6A_SPIRIT => SkillType::NormalAttack,
            C6E | C6E_SPIRIT => SkillType::ElementalSkill,
        }
    }

    /// 灵剑造成的伤害：处于「辉映·星扩散」状态时转为造成视为星扩散反应伤害的风元素伤害。
    pub fn get_elevative_type(&self, stellar_glimmer_state: StellarGlimmerState) -> Option<ElevativeReaction> {
        use VesnaDamageEnum::*;
        match *self {
            E_SPIRIT2 | E_SPIRIT3 | E_SPIRIT3_TOTAL | E_SPIRIT3_FINAL | Q_SPIRIT | C6A_SPIRIT | C6E_SPIRIT => {
                if stellar_glimmer_state.is_stellar_swirl() {
                    Some(ElevativeReaction::StellarSwirlAnemo)
                } else {
                    None
                }
            }
            _ => None,
        }
    }
}

pub struct Vesna;

impl CharacterTrait for Vesna {
    const STATIC_DATA: CharacterStaticData = VESNA_STATIC_DATA;
    type SkillType = VesnaSkillType;
    const SKILL: Self::SkillType = VESNA_SKILL;
    type DamageEnumType = VesnaDamageEnum;
    type RoleEnum = ();

    const DEFAULT_TAGS: Option<&'static [CharacterTag]> = None;

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            VesnaDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A31 hit_n_dmg!(3, 1)
            A32 hit_n_dmg!(3, 2)
            A4 hit_n_dmg!(4)
            A5 hit_n_dmg!(5)
            A6 hit_n_dmg!(6)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
            C6A locale!(zh_cn: "命座6「翔风剑·变移」伤害", en: "C6 \"Windborne Sword: Transpose\" DMG")
            C6A_SPIRIT locale!(zh_cn: "命座6「翔风剑·变移」灵剑伤害", en: "C6 \"Windborne Sword: Transpose\" Spirit Blade DMG")
        ),
        skill2: skill_map!(
            VesnaDamageEnum
            E locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E_SWORD1 locale!(zh_cn: "翔风剑一阶伤害", en: "Windborne Sword Lv. 1 DMG")
            E_SWORD2 locale!(zh_cn: "翔风剑二阶伤害", en: "Windborne Sword Lv. 2 DMG")
            E_SPIRIT2 locale!(zh_cn: "翔风剑二阶灵剑伤害", en: "Windborne Sword Lv. 2 Spirit Blade DMG")
            E_SPIRIT3 locale!(zh_cn: "翔风剑三阶灵剑伤害（单次）", en: "Windborne Sword Lv. 3 Spirit Blade DMG (per hit)")
            E_SPIRIT3_TOTAL locale!(zh_cn: "翔风剑三阶灵剑总伤害", en: "Windborne Sword Lv. 3 Spirit Blade Total DMG")
            E_SPIRIT3_FINAL locale!(zh_cn: "翔风剑三阶灵剑最终段伤害", en: "Windborne Sword Lv. 3 Spirit Blade Final Hit DMG")
            E_PLUME locale!(zh_cn: "风翎伤害", en: "Wind Pinion DMG")
            C6E locale!(zh_cn: "命座6「翔风剑·变移」伤害", en: "C6 \"Windborne Sword: Transpose\" DMG")
            C6E_SPIRIT locale!(zh_cn: "命座6「翔风剑·变移」灵剑伤害", en: "C6 \"Windborne Sword: Transpose\" Spirit Blade DMG")
        ),
        skill3: skill_map!(
            VesnaDamageEnum
            Q_SPIRIT locale!(zh_cn: "灵剑伤害", en: "Spirit Blade DMG")
        ),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::STELLAR_GLIMMER_STATE(StellarGlimmerState::None, ItemConfig::PRIORITY_CHARACTER),
        ItemConfig {
            name: "cryo_anemo_count",
            title: locale!(
                zh_cn: "队伍中冰/风元素角色数量（含薇斯纳）",
                en: "Count of Cryo/Anemo Characters in the Team (including Vesna)"
            ),
            config: ItemConfigType::Int { min: 1, max: 4, default: 1 }
        },
        ItemConfig {
            name: "other_count",
            title: locale!(
                zh_cn: "队伍中其他元素角色数量",
                en: "Count of Other-Element Characters in the Team"
            ),
            config: ItemConfigType::Int { min: 0, max: 3, default: 0 }
        },
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "in_armed_for_action",
            title: locale!(
                zh_cn: "处于「巡风列装」模式（普通攻击/重击/下落攻击转为风元素伤害）",
                en: "In Armed for Action Mode (Normal/Charged/Plunging Attacks become Anemo DMG)"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "disciplinary_stacks",
            title: locale!(
                zh_cn: "「整肃」层数（施放翔风剑/元素爆发后获得，至多6层，每层使灵剑伤害提升10%；命座2 满层时攻击力提升40%）",
                en: "Disciplinary Action Stacks (gained after Windborne Sword/Burst, max 6, +10% Spirit Blade DMG per stack; C2 grants +40% ATK at max stacks)"
            ),
            config: ItemConfigType::Int { min: 0, max: 6, default: 1 }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let (in_armed_for_action, disciplinary_stacks) = match *skill_config {
            CharacterSkillConfig::Vesna { in_armed_for_action, disciplinary_stacks } => (in_armed_for_action, disciplinary_stacks),
            _ => (false, 0),
        };

        // 命座1·送冬的华宴：「巡风列装」模式下，薇斯纳造成的星扩散反应伤害提升 20%
        if common_data.constellation >= 1 && in_armed_for_action {
            attribute.set_value_by_t(
                AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                    AttributeVariableType::ReactionEnhance,
                    ReactionType::StellarSwirl,
                )),
                "薇斯纳命座1",
                VESNA_SKILL.c1_stellar_bonus,
            );
        }

        // 命座2·迎春的轮舞：拥有最大层数的「整肃」时，薇斯纳的攻击力提升 40%
        // （需要解锁突破天赋1「仪典·春之行列」；进入「巡风列装」时即获得最大层数）
        if common_data.constellation >= 2
            && common_data.has_talent1
            && disciplinary_stacks >= VESNA_SKILL.p1_max_stacks as usize
        {
            attribute.add_atk_percentage("薇斯纳命座2", VESNA_SKILL.c2_atk_bonus);
        }
    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: VesnaDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let stellar_glimmer_state = match &context.character_common_data.config {
            CharacterConfig::Vesna { stellar_glimmer_state, .. } => *stellar_glimmer_state,
            _ => StellarGlimmerState::None,
        };

        let (in_armed_for_action, disciplinary_stacks) = match *config {
            CharacterSkillConfig::Vesna { in_armed_for_action, disciplinary_stacks } => (in_armed_for_action, disciplinary_stacks),
            _ => (false, 0),
        };

        use VesnaDamageEnum::*;
        let mut builder = D::new();

        // 风翎：仅在「巡风列装」模式下唤出
        if s == E_PLUME && !in_armed_for_action {
            return builder.none();
        }
        // 命座6「翔风剑·变移」：需要解锁命座6
        if matches!(s, C6A | C6A_SPIRIT | C6E | C6E_SPIRIT) && context.character_common_data.constellation < 6 {
            return builder.none();
        }

        // 天赋1·仪典·春之行列：拥有「整肃」时，薇斯纳召唤的灵剑造成原本 100% + 层数 * 10% 的伤害
        let spirit_multiplier = if context.character_common_data.has_talent1 {
            1.0 + (disciplinary_stacks.min(VESNA_SKILL.p1_max_stacks as usize) as f64) * VESNA_SKILL.p1_stack_bonus
        } else {
            1.0
        };

        let ratio = match s {
            A1 => VESNA_SKILL.a_dmg1[s1],
            A2 => VESNA_SKILL.a_dmg2[s1],
            A31 | A32 => VESNA_SKILL.a_dmg3[s1],
            A4 => VESNA_SKILL.a_dmg4[s1],
            A5 => VESNA_SKILL.a_dmg5[s1],
            A6 => VESNA_SKILL.a_dmg6[s1],
            Z => VESNA_SKILL.z_dmg[s1],
            X1 => VESNA_SKILL.x_dmg1[s1],
            X2 => VESNA_SKILL.x_dmg2[s1],
            X3 => VESNA_SKILL.x_dmg3[s1],
            E => VESNA_SKILL.e_dmg[s2],
            E_SWORD1 => VESNA_SKILL.e_sword1[s2],
            E_SWORD2 => VESNA_SKILL.e_sword2[s2],
            E_SPIRIT2 => VESNA_SKILL.e_spirit2[s2] * spirit_multiplier,
            E_SPIRIT3 => VESNA_SKILL.e_spirit3[s2] * spirit_multiplier,
            E_SPIRIT3_TOTAL => VESNA_SKILL.e_spirit3[s2] * 4.0 * spirit_multiplier,
            E_SPIRIT3_FINAL => VESNA_SKILL.e_spirit3_final[s2] * spirit_multiplier,
            E_PLUME => VESNA_SKILL.e_plume[s2],
            Q_SPIRIT => VESNA_SKILL.q_spirit[s3] * spirit_multiplier,
            C6A | C6E => VESNA_SKILL.c6_transpose_atk,
            C6A_SPIRIT | C6E_SPIRIT => VESNA_SKILL.c6_spirit_atk * spirit_multiplier,
        };

        builder.add_atk_ratio("技能倍率", ratio);

        if let Some(elevative_type) = s.get_elevative_type(stellar_glimmer_state) {
            builder.elevative(
                &context.attribute,
                &context.enemy,
                s.get_element(in_armed_for_action),
                elevative_type,
                SkillType::Elevative,
                context.character_common_data.level,
                fumo,
            )
        } else {
            builder.damage(
                &context.attribute,
                &context.enemy,
                s.get_element(in_armed_for_action),
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            )
        }
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let (stellar_glimmer_state, cryo_anemo_count, other_count) = match *config {
            CharacterConfig::Vesna { stellar_glimmer_state, cryo_anemo_count, other_count } => {
                (stellar_glimmer_state, cryo_anemo_count, other_count)
            }
            _ => (StellarGlimmerState::None, 1, 0),
        };
        Some(Box::new(VesnaEffect {
            stellar_glimmer_state,
            cryo_anemo_count,
            other_count,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
