// Generated by GitHub Copilot (DeepSeek V4 Pro)
use crate::character::characters::prelude::*;

pub struct YumemizukiMizukiSkillType {
    // Normal Attack: 梦我梦心
    pub a_dmg1: [f64; 15],
    pub a_dmg2: [f64; 15],
    pub a_dmg3: [f64; 15],
    pub z_dmg: [f64; 15],
    pub x_dmg1: [f64; 15],
    pub x_dmg2: [f64; 15],
    pub x_dmg3: [f64; 15],

    // Elemental Skill: 秋沙歌枕巡礼
    pub e_dmg1: [f64; 15],    // 技能伤害
    pub e_dmg2: [f64; 15],    // 持续攻击伤害
    pub e_bonus: [f64; 15],   // 每点精通提升扩散伤害百分比

    // Elemental Burst: 安乐秘汤疗法
    pub q_dmg1: [f64; 15],    // 技能伤害
    pub q_dmg2: [f64; 15],    // 梦念冲击波伤害
    pub q_heal: [f64; 15],    // 拾取点心回复生命值（精通倍率）
    pub q_heal_fixed: [f64; 15], // 拾取点心回复生命值（固定值）

    // 天赋3·廓然梦生
    pub p3_em_share: f64,       // 队伍精通提升比例 (0.1 = 10%)
    pub p3_dmg_em_ratio: f64,   // 下次周期伤害提升精通比例 (10.0 = 1000%)

    // C1: 宿雾若水遥
    pub c1_swirl_bonus: f64,  // 扩散伤害提升精通比例 (11.0 = 1100%)
    pub c1_extra_atk: f64,    // 额外攻击精通比例 (10.0 = 1000%)

    // C2: 缠忆君影梦相见
    pub c2_bonus_per_em: f64, // 每点精通提供元素伤害加成 (0.0004 = 0.04%)
    pub c2_res_minus: f64,    // 减抗比例 (0.2 = 20%)

    // C4: 泉轻流花暖
    pub c4_energy: f64,       // 能量恢复 (5.0)
    pub c4_heal_em: f64,      // 额外治疗精通比例 (2.66 = 266%)

    // C6: 慕念萦心间
    pub c6_crit_rate_base: f64,    // 固定暴击率 (0.3 = 30%)
    pub c6_crit_dmg_base: f64,     // 固定暴击伤害 (1.0 = 100%)
    pub c6_em_threshold: f64,      // 精通阈值 (500.0)
    pub c6_crit_rate_per_em: f64,  // 每点精通暴击率 (0.0004 = 0.04%)
    pub c6_crit_dmg_per_em: f64,   // 每点精通暴击伤害 (0.0016 = 0.16%)
    pub c6_crit_rate_max: f64,     // 暴击率上限 (0.2 = 20%)
    pub c6_crit_dmg_max: f64,      // 暴击伤害上限 (0.8 = 80%)
}

pub const YUMEMIZUKI_MIZUKI_SKILL: YumemizukiMizukiSkillType = YumemizukiMizukiSkillType {
    // Normal Attack: 梦我梦心
    a_dmg1: [0.522768, 0.561976, 0.601183, 0.65346, 0.692668, 0.731875, 0.784152, 0.836429, 0.888706, 0.940982, 0.993259, 1.045536, 1.110882, 1.176228, 1.241574],
    a_dmg2: [0.469144, 0.50433, 0.539516, 0.58643, 0.621616, 0.656802, 0.703716, 0.75063, 0.797545, 0.844459, 0.891374, 0.938288, 0.996931, 1.055574, 1.114217],
    a_dmg3: [0.713688, 0.767215, 0.820741, 0.89211, 0.945637, 0.999163, 1.070532, 1.141901, 1.21327, 1.284638, 1.356007, 1.427376, 1.516587, 1.605798, 1.695009],
    z_dmg: [1.3, 1.3975, 1.495, 1.625, 1.7225, 1.82, 1.95, 2.08, 2.21, 2.34, 2.47, 2.6, 2.7625, 2.925, 3.0875],
    x_dmg1: [0.568288, 0.614544, 0.6608, 0.72688, 0.773136, 0.826, 0.898688, 0.971376, 1.044064, 1.12336, 1.202656, 1.281952, 1.361248, 1.440544, 1.51984],
    x_dmg2: [1.136335, 1.228828, 1.32132, 1.453452, 1.545944, 1.65165, 1.796995, 1.94234, 2.087686, 2.246244, 2.404802, 2.563361, 2.721919, 2.880478, 3.039036],
    x_dmg3: [1.419344, 1.534872, 1.6504, 1.81544, 1.930968, 2.063, 2.244544, 2.426088, 2.607632, 2.80568, 3.003728, 3.201776, 3.399824, 3.597872, 3.79592],

    // Elemental Skill: 秋沙歌枕巡礼
    e_dmg1: [0.57744, 0.620748, 0.664056, 0.7218, 0.765108, 0.808416, 0.86616, 0.923904, 0.981648, 1.039392, 1.097136, 1.15488, 1.22706, 1.29924, 1.37142],
    e_dmg2: [0.44912, 0.482804, 0.516488, 0.5614, 0.595084, 0.628768, 0.67368, 0.718592, 0.763504, 0.808416, 0.853328, 0.89824, 0.95438, 1.01052, 1.06666],
    e_bonus: [0.0018, 0.0021, 0.0024, 0.0027, 0.003, 0.0033, 0.0036, 0.0039, 0.0042, 0.0045, 0.0048, 0.0051, 0.0054, 0.0057, 0.006],

    // Elemental Burst: 安乐秘汤疗法
    q_dmg1: [0.9408, 1.01136, 1.08192, 1.176, 1.24656, 1.31712, 1.4112, 1.50528, 1.59936, 1.69344, 1.78752, 1.8816, 1.9992, 2.1168, 2.2344],
    q_dmg2: [0.7056, 0.75852, 0.81144, 0.882, 0.93492, 0.98784, 1.0584, 1.12896, 1.19952, 1.27008, 1.34064, 1.4112, 1.4994, 1.5876, 1.6758],
    q_heal: [1.3056, 1.40352, 1.50144, 1.632, 1.72992, 1.82784, 1.9584, 2.08896, 2.21952, 2.35008, 2.48064, 2.6112, 2.7744, 2.9376, 3.1008],
    q_heal_fixed: [314.57, 346.03137, 380.11453, 416.81946, 456.14618, 498.09467, 542.6649, 589.857, 639.67084, 692.10645, 747.1639, 804.843, 865.144, 928.0668, 993.61127],

    // 天赋3·廓然梦生
    p3_em_share: 0.1,
    p3_dmg_em_ratio: 10.0,

    // C1: 宿雾若水遥
    c1_swirl_bonus: 11.0,
    c1_extra_atk: 10.0,

    // C2: 缠忆君影梦相见
    c2_bonus_per_em: 0.0004,
    c2_res_minus: 0.2,

    // C4: 泉轻流花暖
    c4_energy: 5.0,
    c4_heal_em: 2.66,

    // C6: 慕念萦心间
    c6_crit_rate_base: 0.3,
    c6_crit_dmg_base: 1.0,
    c6_em_threshold: 500.0,
    c6_crit_rate_per_em: 0.0004,
    c6_crit_dmg_per_em: 0.0016,
    c6_crit_rate_max: 0.2,
    c6_crit_dmg_max: 0.8,
};

pub const YUMEMIZUKI_MIZUKI_STATIC_DATA: CharacterStaticData = CharacterStaticData {
    name: CharacterName::YumemizukiMizuki,
    internal_name: "YumemizukiMizuki",
    name_locale: locale!(
        zh_cn: "梦见月瑞希",
        en: "Yumemizuki Mizuki"
    ),
    element: Element::Anemo,
    hp: [991, 2572, 3422, 5120, 5724, 6586, 7391, 8262, 8866, 9744, 10348, 11236, 11840, 12736, 13641],
    atk: [17, 43, 58, 87, 97, 111, 125, 140, 150, 165, 175, 190, 200, 215, 264],
    def: [59, 153, 203, 304, 340, 391, 439, 491, 527, 579, 615, 668, 704, 757, 811],
    sub_stat: CharacterSubStatFamily::ElementalMastery115,
    weapon_type: WeaponType::Catalyst,
    star: 5,
    skill_name1: locale!(
        zh_cn: "梦我梦心",
        en: "Pure Heart, Pure Dreams"
    ),
    skill_name2: locale!(
        zh_cn: "秋沙歌枕巡礼",
        en: "Aisa Utamakura Pilgrimage"
    ),
    skill_name3: locale!(
        zh_cn: "安乐秘汤疗法",
        en: "Anraku Secret Spring Therapy"
    ),
};

pub struct YumemizukiMizukiEffect {
    pub talent2_rate: f64,
    pub common_data: CharacterCommonData,
}

impl<A: Attribute> ChangeAttribute<A> for YumemizukiMizukiEffect {
    fn change_attribute(&self, attribute: &mut A) {
        // P2: 昼想夜梦 — 队伍中附近其他角色火/水/冰/雷攻击命中时，瑞希元素精通+100
        if self.common_data.has_talent2 {
            let em_bonus = self.talent2_rate * 100.0;
            attribute.set_value_to(AttributeName::ElementalMastery, "梦见月瑞希天赋2", em_bonus);
        }
    }
}

damage_enum!(
    YumemizukiMizukiDamageEnum
    A1
    A2
    A3
    Z
    X1
    X2
    X3
    E1
    E2
    Q1
    Q2
    QHeal
    C1E
    C4Heal
);

impl YumemizukiMizukiDamageEnum {
    pub fn get_skill_type(&self) -> SkillType {
        use YumemizukiMizukiDamageEnum::*;
        match *self {
            A1 | A2 | A3 => SkillType::NormalAttack,
            Z => SkillType::ChargedAttack,
            X1 => SkillType::PlungingAttackInAction,
            X2 | X3 => SkillType::PlungingAttackOnGround,
            E1 | E2 | C1E => SkillType::ElementalSkill,
            Q1 | Q2 | QHeal | C4Heal => SkillType::ElementalBurst,
        }
    }
}

pub struct YumemizukiMizuki;

impl CharacterTrait for YumemizukiMizuki {
    const STATIC_DATA: CharacterStaticData = YUMEMIZUKI_MIZUKI_STATIC_DATA;
    type SkillType = YumemizukiMizukiSkillType;
    const SKILL: Self::SkillType = YUMEMIZUKI_MIZUKI_SKILL;
    type DamageEnumType = YumemizukiMizukiDamageEnum;
    type RoleEnum = ();

    #[cfg(not(target_family = "wasm"))]
    const SKILL_MAP: CharacterSkillMap = CharacterSkillMap {
        skill1: skill_map!(
            YumemizukiMizukiDamageEnum
            A1 hit_n_dmg!(1)
            A2 hit_n_dmg!(2)
            A3 hit_n_dmg!(3)
            Z charged_dmg!()
            X1 plunging_dmg!(1)
            X2 plunging_dmg!(2)
            X3 plunging_dmg!(3)
        ),
        skill2: skill_map!(
            YumemizukiMizukiDamageEnum
            E1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            E2 locale!(zh_cn: "持续攻击伤害", en: "Continuous Attack DMG")
            C1E locale!(zh_cn: "命座1「二十三夜待」额外攻击", en: "C1 \"Twenty-Three Nights' Awaiting\" Extra Attack")
        ),
        skill3: skill_map!(
            YumemizukiMizukiDamageEnum
            Q1 locale!(zh_cn: "技能伤害", en: "Skill DMG")
            Q2 locale!(zh_cn: "梦念冲击波伤害", en: "Munen Shockwave DMG")
            QHeal locale!(zh_cn: "拾取点心回复生命值", en: "Snack Pick-Up HP Regeneration")
            C4Heal locale!(zh_cn: "命座4「泉轻流花暖」额外治疗", en: "C4 \"Buds Warm Lucid Springs\" Extra Healing")
        ),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_DATA: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "talent2_rate",
            title: locale!(
                zh_cn: "天赋「昼想夜梦」覆盖率",
                en: "Talent 2 Coverage"
            ),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 0.0 }
        }
    ]);

    #[cfg(not(target_family = "wasm"))]
    const CONFIG_SKILL: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "in_dreamdrifter",
            title: locale!(
                zh_cn: "处于梦浮状态",
                en: "In Dreamdrifter state"
            ),
            config: ItemConfigType::Bool { default: true }
        },
        ItemConfig {
            name: "p3_boost_active",
            title: locale!(
                zh_cn: "天赋3「廓然梦生」增伤生效",
                en: "\"Vast Be the Dream\" DMG boost active"
            ),
            config: ItemConfigType::Bool { default: true }
        },
    ]);

    fn change_attribute<A: Attribute>(attribute: &mut A, common_data: &CharacterCommonData, skill_config: &CharacterSkillConfig) {
        let talent2_rate = match &common_data.config {
            CharacterConfig::YumemizukiMizuki { talent2_rate } => *talent2_rate,
            _ => 0.0,
        };

        let (in_dreamdrifter, p3_boost_active) = match *skill_config {
            CharacterSkillConfig::YumemizukiMizuki { in_dreamdrifter, p3_boost_active } =>
                (in_dreamdrifter, p3_boost_active),
            _ => (false, false),
        };

        let _ = (talent2_rate, p3_boost_active);

        if in_dreamdrifter {
            // C6: 慕念萦心间 — 基于元素精通超过500的部分，提升瑞希自身的暴击率和暴击伤害
            if common_data.constellation >= 6 {
                attribute.add_edge_t1(
                    AttributeType::Panel(AttributeName::ElementalMastery),
                    AttributeType::Panel(AttributeName::CriticalBase),
                    Arc::new(move |em: f64, _| {
                        ((em - YUMEMIZUKI_MIZUKI_SKILL.c6_em_threshold).max(0.0) * YUMEMIZUKI_MIZUKI_SKILL.c6_crit_rate_per_em)
                            .min(YUMEMIZUKI_MIZUKI_SKILL.c6_crit_rate_max)
                    }),
                    "梦见月瑞希命座6",
                    EdgePriority::Common,
                );
                attribute.add_edge_t1(
                    AttributeType::Panel(AttributeName::ElementalMastery),
                    AttributeType::Panel(AttributeName::CriticalDamageBase),
                    Arc::new(move |em: f64, _| {
                        ((em - YUMEMIZUKI_MIZUKI_SKILL.c6_em_threshold).max(0.0) * YUMEMIZUKI_MIZUKI_SKILL.c6_crit_dmg_per_em)
                            .min(YUMEMIZUKI_MIZUKI_SKILL.c6_crit_dmg_max)
                    }),
                    "梦见月瑞希命座6",
                    EdgePriority::Common,
                );
            }
    
            // 天赋3·廓然梦生：队伍中附近角色的元素精通提升，提升值相当于梦见月瑞希自己的元素精通的10%
            attribute.add_edge_s1to1(
                CharacterSelector::select_self(attribute),
                AttributeType::Panel(AttributeName::ElementalMastery),
                AttributeType::Panel(AttributeName::ElementalMastery),
                Arc::new(move |em: f64, _| em * YUMEMIZUKI_MIZUKI_SKILL.p3_em_share),
                "梦见月瑞希天赋3",
                EdgePriority::Common,
            );
    
            // C2: 缠忆君影梦相见 — 附近敌人的火/水/冰/雷/风元素抗性降低20%
            if common_data.constellation >= 2 {
                let res = YUMEMIZUKI_MIZUKI_SKILL.c2_res_minus;
                for element in [Element::Pyro, Element::Hydro, Element::Cryo, Element::Electro, Element::Anemo].iter() {
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_element(AttributeVariableType::ResMinus, *element)),
                        "梦见月瑞希命座2",
                        res,
                    );
                }
            }
    
            // C6: 慕念萦心间 — 扩散反应可以暴击，暴击率固定30%、暴击伤害固定100%
            if common_data.constellation >= 6 {
                let swirl_reactions = [
                    ReactionType::PyroSwirl,
                    ReactionType::HydroSwirl,
                    ReactionType::ElectroSwirl,
                    ReactionType::CryoSwirl,
                ];
                for &reaction in &swirl_reactions {
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_reaction(AttributeVariableType::CriticalRate, reaction)),
                        "梦见月瑞希命座6",
                        YUMEMIZUKI_MIZUKI_SKILL.c6_crit_rate_base,
                    );
                    attribute.set_value_to_s(
                        CharacterSelector::select_all(attribute),
                        AttributeType::Invisible(InvisibleAttributeType::new_reaction(AttributeVariableType::CriticalDamage, reaction)),
                        "梦见月瑞希命座6",
                        YUMEMIZUKI_MIZUKI_SKILL.c6_crit_dmg_base,
                    );
                }
            }
        }

    }

    fn damage_internal<D: DamageBuilder>(context: &DamageContext<'_, D::AttributeType>, s: usize, config: &CharacterSkillConfig, fumo: Option<Element>) -> D::Result {
        let s: YumemizukiMizukiDamageEnum = num::FromPrimitive::from_usize(s).unwrap();
        let (s1, s2, s3) = context.character_common_data.get_3_skill();

        let (in_dreamdrifter, p3_boost_active) = match *config {
            CharacterSkillConfig::YumemizukiMizuki { in_dreamdrifter, p3_boost_active } =>
                (in_dreamdrifter, p3_boost_active),
            _ => (false, false),
        };

        use YumemizukiMizukiDamageEnum::*;
        let mut builder = D::new();

        // 命座1「二十三夜待」额外攻击：需要命座1且梦浮状态
        if s == C1E {
            if context.character_common_data.constellation < 1 || !in_dreamdrifter {
                return builder.none();
            }
            builder.add_em_ratio("梦见月瑞希命座1", YUMEMIZUKI_MIZUKI_SKILL.c1_extra_atk);
            return builder.damage(
                &context.attribute,
                &context.enemy,
                Element::Anemo,
                s.get_skill_type(),
                context.character_common_data.level,
                fumo,
            );
        }

        // 元素爆发治疗
        if s == QHeal {
            let rate = YUMEMIZUKI_MIZUKI_SKILL.q_heal[s3];
            let fixed = YUMEMIZUKI_MIZUKI_SKILL.q_heal_fixed[s3];

            builder.add_em_ratio("技能倍率", rate);
            builder.add_extra_damage("技能倍率", fixed);

            return builder.heal(&context.attribute);
        }

        // 命座4「泉轻流花暖」额外治疗：需要命座4且梦浮状态
        if s == C4Heal {
            if context.character_common_data.constellation < 4 || !in_dreamdrifter {
                return builder.none();
            }
            builder.add_em_ratio("梦见月瑞希命座4", YUMEMIZUKI_MIZUKI_SKILL.c4_heal_em);
            return builder.heal(&context.attribute);
        }

        let rate = match s {
            A1 => YUMEMIZUKI_MIZUKI_SKILL.a_dmg1[s1],
            A2 => YUMEMIZUKI_MIZUKI_SKILL.a_dmg2[s1],
            A3 => YUMEMIZUKI_MIZUKI_SKILL.a_dmg3[s1],
            Z => YUMEMIZUKI_MIZUKI_SKILL.z_dmg[s1],
            X1 => YUMEMIZUKI_MIZUKI_SKILL.x_dmg1[s1],
            X2 => YUMEMIZUKI_MIZUKI_SKILL.x_dmg2[s1],
            X3 => YUMEMIZUKI_MIZUKI_SKILL.x_dmg3[s1],
            E1 => YUMEMIZUKI_MIZUKI_SKILL.e_dmg1[s2],
            E2 => YUMEMIZUKI_MIZUKI_SKILL.e_dmg2[s2],
            Q1 => YUMEMIZUKI_MIZUKI_SKILL.q_dmg1[s3],
            Q2 => YUMEMIZUKI_MIZUKI_SKILL.q_dmg2[s3],
            _ => 0.0,
        };

        builder.add_atk_ratio("技能倍率", rate);

        // 天赋3·廓然梦生：扩散触发后下一次周期性风伤提升1000%精通
        if s == E2 && in_dreamdrifter && p3_boost_active {
            let em = context.attribute.get_em_all();
            builder.add_extra_damage("梦见月瑞希天赋3", em * YUMEMIZUKI_MIZUKI_SKILL.p3_dmg_em_ratio);
        }

        builder.damage(
            &context.attribute,
            &context.enemy,
            Element::Anemo,
            s.get_skill_type(),
            context.character_common_data.level,
            fumo,
        )
    }

    fn new_effect<A: Attribute>(common_data: &CharacterCommonData, config: &CharacterConfig) -> Option<Box<dyn ChangeAttribute<A>>> {
        let talent2_rate = match *config {
            CharacterConfig::YumemizukiMizuki { talent2_rate } => talent2_rate,
            _ => 0.0,
        };
        Some(Box::new(YumemizukiMizukiEffect {
            talent2_rate,
            common_data: common_data.clone(),
        }))
    }

    fn get_target_function_by_role(role_index: usize, _team: &TeamQuantization, _c: &CharacterCommonData, _w: &WeaponCommonData) -> Box<dyn TargetFunction> {
        unimplemented!()
    }
}
