// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::buffs::buffs::prelude::*;

pub struct BuffBreezeborneRefrain {
    pub refine: usize,
    pub rate: f64,
}

impl<A: Attribute> Buff<A> for BuffBreezeborneRefrain {
    fn change_attribute(&self, attribute: &mut A) {
        let refine = self.refine as f64;

        // 「蛇信的死毒」：使队伍中附近的所有角色造成的星烁反应伤害提升（星烁反应包含星超导与
        // 星扩散）。该状态存在层数循环，故以「覆盖率」配置项近似其生效时间占比。
        let bonus = (0.18 + 0.06 * refine) * self.rate;

        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarConduct,
            )),
            "柔风游弦被动",
            bonus,
        );
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ReactionEnhance,
                ReactionType::StellarSwirl,
            )),
            "柔风游弦被动",
            bonus,
        );
    }
}

impl BuffMeta for BuffBreezeborneRefrain {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::BreezeborneRefrain,
        name_locale: locale!(
            zh_cn: "柔风游弦-「蛇信的死毒」",
            en: "Breezeborne Refrain-Thus Lied the Viper"
        ),
        image: BuffImage::Weapon(WeaponName::BreezeborneRefrain),
        genre: BuffGenre::Weapon,
        description: Some(locale!(
            zh_cn: "装备者的元素战技或元素爆发命中敌人时，获得一层「纯净者的圣咏」，该效果至多叠加3层，每0.03秒至多获得一层。叠加至3层时，将清除所有「纯净者的圣咏」，获得「蛇信的死毒」：使队伍中附近的所有角色造成的星烁反应伤害提升 <span style=\"color: #409EFF;\">24%-30%-36%-42%-48%</span> ，持续12秒，期间无法再次获得「纯净者的圣咏」。装备者处于队伍后台时，依然能触发上述效果。",
            en: "When the equipping character hits the opponent with their Elemental Skill or Elemental Burst, they gain a stack of \"Hymn of the Pure.\" This effect can trigger once every 0.03s, max 3 stacks, and at 3 stacks, all instances of \"Hymn of the Pure\" are cleared to give the equipping character \"Thus Lied the Viper\" instead. This grants nearby party characters a <span style=\"color: #409EFF;\">24%-30%-36%-42%-48%</span> Stellar Glimmer reaction DMG boost for 12s, during which no stacks of \"Hymn of the Pure\" can be obtained. The aforementioned effects can still trigger even when the equipping character is not on the field."
        )),
        from: BuffFrom::Weapon(WeaponName::BreezeborneRefrain)
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig::REFINE,
        ItemConfig {
            name: "rate",
            title: locale!(zh_cn: "「蛇信的死毒」覆盖率", en: "\"Thus Lied the Viper\" Uptime Ratio"),
            config: ItemConfigType::Float { min: 0.0, max: 1.0, default: 1.0 },
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let (refine, rate) = match *b {
            BuffConfig::BreezeborneRefrain { refine, rate } => (refine, rate),
            _ => (1, 0.0)
        };

        Box::new(BuffBreezeborneRefrain {
            refine,
            rate,
        })
    }
}
