// Generated by GitHub Copilot (DeepSeek V4.1 Flash)
use crate::buffs::buffs::prelude::*;
use crate::character::characters::vesna::VESNA_SKILL;

pub struct BuffVesnaP3 {
    pub atk: f64,
}

impl<A: Attribute> Buff<A> for BuffVesnaP3 {
    fn change_attribute(&self, attribute: &mut A) {
        // 天赋3·星耀祝礼·散华序饰：基于薇斯纳的攻击力，提升当前角色造成的星扩散反应的基础伤害，
        // 每 100 点攻击力提升 0.7%，至多提升 14%。
        // 该效果默认不可叠加，使用 set_value_to_t 以避免重复累计。
        attribute.set_value_to_t(
            AttributeType::Invisible(InvisibleAttributeType::new_reaction(
                AttributeVariableType::ElevativeBase,
                ReactionType::StellarSwirl,
            )),
            "薇斯纳天赋3",
            (self.atk / 100.0 * VESNA_SKILL.p3_base_per_100_atk).min(VESNA_SKILL.p3_base_max),
        );
    }
}

impl BuffMeta for BuffVesnaP3 {
    #[cfg(not(target_family = "wasm"))]
    const META_DATA: BuffMetaData = BuffMetaData {
        name: BuffName::VesnaP3,
        name_locale: locale!(
            zh_cn: "薇斯纳-「星耀祝礼·散华序饰」",
            en: "Vesna-Stellar Jubilee: Splendid Prelude"
        ),
        image: BuffImage::Avatar(CharacterName::Vesna),
        genre: BuffGenre::Character,
        description: Some(locale!(
            zh_cn: "薇斯纳天赋3：队伍中的角色触发冰元素扩散反应时，将转为触发星扩散反应，且基于薇斯纳的攻击力，提升队伍中角色造成的星扩散反应的基础伤害：每100点攻击力都将提升0.7%星扩散反应的基础伤害，至多通过这种方式提升14%伤害。",
            en: "Vesna Talent 3: When party members trigger Cryo Swirl, it will be changed to a Stellar Swirl reaction, and party members' Base DMG for the Stellar Swirl will be increased based on Vesna's ATK. Every 100 ATK she has increases the Base Stellar Swirl DMG by 0.7%. The maximum DMG increase that can be gained this way is 14%."
        )),
        from: BuffFrom::Character(CharacterName::Vesna),
    };

    #[cfg(not(target_family = "wasm"))]
    const CONFIG: Option<&'static [ItemConfig]> = Some(&[
        ItemConfig {
            name: "atk",
            title: locale!(
                zh_cn: "攻击力",
                en: "ATK"
            ),
            config: ItemConfigType::FloatInput { default: 0.0 }
        },
    ]);

    fn create<A: Attribute>(b: &BuffConfig) -> Box<dyn Buff<A>> {
        let atk = match *b {
            BuffConfig::VesnaP3 { atk } => atk,
            _ => 0.0
        };
        Box::new(BuffVesnaP3 {
            atk,
        })
    }
}
